cdc/owner.go
cdc/schema/storage.go

When the `StartTs` of a changefeed is smaller than any none-system table DDL, we should have a right way to calculate `global resolved ts` and `global checkpoint ts`
- The `global resolved ts` can use the `ddl resolved ts` value
- Set the `global checkpoint ts` to the local checkpoint cache stored in `ChangeFeedInfo`
Tests 
- Unit test

owner: fix checkpoint ts calculate in owner

---

cmd/client.go
cmd/ctrl.go

In the current design, all CDC metadata is stored in etcd, we should provide some method for users to query the required information.
NOTE this pr doesn't expose any API using HTTP, gRPC or some other way. We will consider exposing these APIs when the `CDC SQL management design` in TiDB is ready.
Add a `ctrl` subcommand, can be used as following:
```
➜  ./bin/cdc ctrl --cmd=query-cf-list
[{"id":"a2339fed-d360-4726-bd42-f2f0c08daa44"}]
➜  ./bin/cdc ctrl --cmd=query-capture-list
[{"id":"3feb1b3b-9010-4043-a573-68e4c150d59c"}]
➜  ./bin/cdc ctrl --cmd=query-cf-info --changefeed-id=a2339fed-d360-4726-bd42-f2f0c08daa44
{"sink-uri":"root@tcp(127.0.0.1:3306)/test","opts":{},"create-time":"2019-12-10T11:37:29.7099354+08:00","start-ts":413125585561190400,"target-ts":0}
➜  ./bin/cdc ctrl …
```

cmd: add ctrl command to encapsulate some etcd query

---

.gitignore
cdc/capture.go
cdc/kv/client.go
cdc/kv/etcd.go
cdc/owner.go
cdc/owner_operator.go
cdc/puller/puller.go
cdc/roles/storage/etcd.go
cdc/scheduler.go
cdc/sink/mysql.go
cdc/txn/txn.go

using `errors.Trace()` to trace most of errors in CDC

*: Trace error

---

cdc/model/txn.go
cdc/processor.go
cdc/processor_test.go

We've introduced a new struct because we can't tell a normal txn and a resolved one using only `model.RawTxn`.
Add a `IsResolved` field to `model.RawTxn` so that we don't have to introduce a new struct.
Tests 
- Unit test

Add a IsResolved field for RawTxn so that we can reuse it for a fake resolved txn

---

cdc/entry/mounter.go
cdc/entry/mounter_test.go
cdc/processor.go
cdc/processor_test.go

`model.Txn` is so small that we don't need to avoid copying the return value.
Return value for model.Txn.
Tests 
- Unit test

Return value for model.Txn

---

cdc/owner.go

A processor starts a table replication from `StartTs`, which is first set by the owner.
The `StartTs` should consider both the `StartTs` of the changefeed and the `CheckpointTs` of the changefeed.
~Use max(`StartTs`, `CheckpointTs`) as `StartTs` in the `ProcessTableInfo`~
Use `detail.GetCheckpointTs()` as `StartTs` in the `ProcessTableInfo`
Tests 
- Unit test

owner: fix startTs in processor table info dispatched from owner

---

cdc/capture.go
cdc/capture_info.go
cdc/cdc_test.go
cdc/http_handler.go
cdc/http_status.go
cdc/http_status_test.go
cdc/kv/etcd.go
cdc/owner.go
cdc/roles/manager.go
cdc/roles/manager_test.go
cdc/roles/mock_manager.go
cmd/ctrl.go

Add owner resign support and add a way for users to query which capture is the owner.
- add `ResignOwner` function in the `Manager` interface
- add a `is-owner` field in the result of `./cdc ctrl --cmd=query-capture-list`, just for test at present
- add an HTTP api to resign owner from a capture
- unit test entrance is removed by accident, put it back
Tests 
- Unit test

support resign owner, add is-owner field in capture list result

---

cdc/owner.go
cdc/owner_test.go

We have already used the name `ChangeFeedInfo` for the parts of infomation about a change feed that's going to be saved in `etcd`.
It's confusing if we have both `ChangeFeedInfo` and `changeFeedInfo`.
Simply use `changeFeed`.
Some other minor changes: fix a typo in `flushChangeFeedInfos` and preallocate the map.
Tests 
- Unit test

Refactor, changeFeedInfo -> changeFeed

---

cdc/processor.go

When there's no more incoming txns and the number of pending txns doesn't reach the limit, the txns are not flushed.
Flush pending txns when the buffers are empty
Tests 
- Unit test

Flush pending txns when the buffers are empty

---

tests/_utils/cleanup_process
tests/multi_capture/run.sh
tests/simple/run.sh
tests/split_region/run.sh

In each integration test case, we should wait for the cdc gotest server daemon exits (which will ensure all coverage data is flushed into the disk),  before we stash the coverage file.
Add a process aliveness checker in the integration test script.
Tests 
- Unit test

tests: wait cdc server exits in integration test

---

cdc/kv/client.go
cdc/kv/metrics.go
cdc/metrics_processor.go
cdc/owner.go
cdc/processor.go
cdc/processor_test.go

1, Adjust and add some metrics.
2, Fix goroutine leak by not close sorter
3, Fix diffProcessTableInfos assume tables is sorted by id.
4, Fix deadlock while successive drop tables.
drop two table at upstream: drop table t1; drop table t2;
ts1 = the timestamp of "drop table t1"
ts2 = the timestamp of "drop table t2"
the flowing step may happen:
a. gloableResolveTS = t1, checkpointTS of processor = ts (after execute
drop table t1)
b. processor update resolveTS = t2;
c. owner update gloableResolveTS = t2;
d. processor update checkpointTS = t2(in memory).
e. owner remove table t1 in etcd.
f. processor learn t1 removed and update the in memory checkpointTS as
the one in etch which is t1.
g. processor will never forward checkpointTS and owner wait checkpointTS
of processor to be t2 for execute …

Fix deadlock while successive drop tables

---

cdc/filter.go
cdc/filter_test.go
cdc/owner.go
cdc/owner_operator.go
cdc/owner_test.go
cdc/processor.go
cdc/sink/mysql.go
cdc/sink/mysql_test.go

Ignored or not, a "success" message was logged for each DDL passed to `sink.Emit`.
We need to separate the ignored and those that were actually executed.
Move txn filtering out of `mysqlSink`, the callers should filter the txns and decide what to do if the whole txn is ignored.
Tests 
- Unit test

Move txn filtering out of mysqlSink

---

cdc/capture.go
cdc/processor.go
cdc/scheduler.go
cdc/scheduler_test.go
cdc/server.go

This PR makes capture acts like a resource manager by the following two changes:
- capture doesn't exit when meeting a processor error
- capture waits for all processors exit during system shutdown
more resources management will be added later, such as the changefeed pause/resume
Still use the callback way for the interactions between capture and processors, we may refactor it later.
Tests 
- Unit test

wait all processors exit in capture

---

cdc/puller/metrics.go
cdc/puller/puller.go

When fine tuning performance, it would be helpful to know the statistics of the txns resolved in one go.
Add a metric.
Tests 
- Unit test

Add a metric to track the number of txns resolved in one go

---

cdc/model/changefeed.go
cdc/owner.go

The `loadChangeFeeds` method is too complex.
Simplify the method by extracting functions.
The algorithm is actually quite simple:
1. For existing change feeds, try to set the last updated time and mark some as unavailable
1. Create new change feeds for non-exist change feeds and register them into owner
1. Distribute tables among available processors
Tests 
- Unit test

Refactor, extract functions to simplify loadChangeFeeds

---

cdc/processor.go
cdc/puller/buffer.go
cdc/puller/buffer_test.go

TiCDC sync is too slow.
make the buffer larger in processor and puller, lead to push revolved ts faster.
At least 10x better performance.
Tests 
- Unit test

processor: make the buffer larger in processor and puller to improve performance

---

tests/dailytest/case.go

test: merge new binlog test 
Tests 
- Unit test

test: merge new binlog test 

---

cdc/owner_operator.go
cdc/processor.go
cdc/sink/mysql.go
cdc/sink/mysql_test.go
cdc/sink/sink.go

`model.Txn`s are executed one by one in `mysqlSink`.
Try to execute DML SQLs concurrently.
Tests 
- Unit test

Split DMLs into independent groups, execute them concurrently

---

cdc/sink/mysql_test.go

The test assumed that the splitted groups are in order, which is not true because it's generated from a `map`.
Select the expected database and table by inspecting the first table in each group.
Tests 
- Unit test

Fix TestShouldSplitByTable

---

cdc/owner.go

All capture IDs are collected into a slice before they are deleted from the map.
In Go, it's OK to delete from a map while iterating over it. ([ref](https://github.com/golang/go/issues/9926#issuecomment-74988212))
Delete while iterating.
Tests 
- Unit test

Delete from map directly

---

cdc/http_status.go

We only store `CaptureID` in etcd, it is hard to match CDC server with a capture
Add `id` and `pid` in the status HTTP API
Tests 
- Unit test

Add capture ID and process pid in status API

---

cdc/capture.go
cdc/kv/etcd.go
cdc/kv/etcd_test.go
cdc/model/owner.go
cdc/model/owner_test.go
cdc/owner.go
cdc/server.go
cmd/server.go
pkg/util/log.go
pkg/util/log_test.go

Add clean strategy for `SubChangefeedInfo` when a processor is down and table rebalance at the same time.
When the owner marks a processor down, clean both `CaptureInfo` and all `SubChangeFeedInfo` belongs to the capture, and rebalance tables when marking processor down.
One exception, if the owner cleans the processor `SubChangeFeedInfo` and it crashes before table rebalance, some tables replication information is missing. In this scenario, the global `CheckpointTs` will not be forwarded until another owner is elected. In order to keep state management simple, we tend to add some recover mechanism in the owner's logic for this scenario, which will be solved in another PR.
Tests 
- Unit test

owner rebalance tables when marking processor down

---

cdc/owner.go

Currently when a capture becomes owner, it always scans all changefeeds, and re-assign each table to be replicated.
Filter tables already in replication state in all processors, don't re-assign them.
Tests 
- Unit test

fix table management when owner starts up

---

cdc/processor.go

Fix a potential panic of `send on closed channel`, which is caused by the branch of a select that is chosen could be non-deterministic (except for the `default` branch).
Close the channel p.executedTxns where we use it as sender
Tests 
- Unit test

close channel p.executedTxns where we use it as sender

---

cdc/entry/mounter_test.go
cdc/processor.go
cdc/schema/storage.go
cdc/schema/storage_test.go

The implicit column part of schema is never used. In fact it's not even used in binlog now.
Remove unused code.
Tests 
- Unit test

Remove unused code copied from binlog

---

cdc/entry/mounter.go
cdc/schema/storage.go
cdc/schema/storage_test.go

A `TableName` is looked up and unpacked, and then recreated outside.
Return the `TableName` direclty.
Tests 
- Unit test

Refactor, get table name directly

---

cdc/owner.go

There are too many "update changefeed" messages in the log when debugging.
Only emit the log when the changefeed is indeed updated.
Tests 
- Manual test
I ran `test.sh --debug` and check that the message is only printed when the fake txns forward the global resolved ts.

Only emit log when the changefeed is indeed updated

---

cdc/entry/mounter.go
cdc/entry/mounter_test.go

don't build delete dml when set index key
Tests 
- Unit test

mounter: don't build delete dml when set index key

---

cdc/model/changefeed.go
cdc/model/changefeed_test.go
cmd/cdc.toml
cmd/client.go
cmd/cmd_test.go

A command line interface is needed to test filter rules.
1. Add a `config` option for `cdc cli` to read configurations like `filter-rules` from a file
1. Fix a bug
Tests 
- Unit test
- Manual test
Change `run.sh` to specify a config file and observe that tables are filtered according to the configuration.

Add support for `cdc cli` to read filter configs from file

---

cdc/http_handler.go
cdc/http_status.go
cdc/kv/etcd.go
cdc/kv/etcd_test.go
cdc/model/changefeed.go
cdc/model/errors.go
cdc/model/owner.go
cdc/owner.go
cdc/owner_test.go
cdc/processor.go
cdc/roles/storage/etcd.go
cdc/scheduler.go
cdc/scheduler_test.go

We have no management to a running changefeed, such as pause replication, resume replication or remove this changefeed from a CDC cluster.
- Treat changefeed as resource both in owner and processor, so if a DDL executed to downstream with failure, we don't exit the whole owner, but only pause the changefeed replication.
- Introduce the `AdminJob` concept, which can be processed by the owner only. We can use this feature by HTTP API now.
- In both `Stop` and `Remove` job, we release all the TiKV gRPC connections and stop the replication. The difference between these two jobs is the `Stop` job will preserve the `Changefeed` information, so we can resume the replication of this changefeed
Tests 
- Unit test

support changefeed stop/pause/remove operation

---

cdc/model/changefeed.go
cmd/debug.go

We have region fully coverage check in the TiKV client, so we should use precise tableID in table puller. Just make the debug cmd works.
fetch tableID from upstream
Tests 
- Unit test

set puller with precise tableIDs in debug cmd

---

go.mod
go.sum

kvproto has merged the cdc protocol and deletes the old `cdc` branch. We should update kvproto version in go.mod (to fix failure in make check: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/cdc_ghpr_check/detail/cdc_ghpr_check/662/pipeline)
~Also update tidb related dependencies to the latest. unfortunately found encode/decode compatible  issue, will upgrade other dependencies later. ref: https://github.com/pingcap/tidb/blob/master/docs/design/2018-07-19-row-format.md~
Tests 
- Unit test

update kvproto dep version

---

cdc/kv/etcd.go
cdc/kv/etcd_test.go
cdc/model/changefeed.go
cdc/model/changefeed_test.go
cdc/model/owner.go
cdc/owner.go
cdc/owner_test.go
cdc/processor.go
cdc/processor_test.go
cdc/roles/storage/etcd.go
cdc/roles/storage/etcd_test.go
cdc/scheduler.go
cdc/scheduler_test.go
cmd/client.go
cmd/ctrl.go

uniform terminology:
we name XXXStatus to the struct which includes the variable changed continually.
we name XXXInfo to the struct which includes config or environment info changed occasionally.

uniform terminology about changefeed

---

cdc/owner.go
cdc/owner_test.go

When a changefeed is stopped or removed, the `OwnerDDLHandler` of this changefeed is not released.
Close the `OwnerDDLHandler` before the `changeFeed` is removed from owner memory.
Tests 
- Unit test

owner: release ddl puller when a changefeed is stopped

---

ticdc.json

some labels are not taken into consideration in some metrics.
- Change default datasource from `default Prometheus` to `cdc-server`
- Add some necessary sum by.
Tests 
before change:
after change:

update dashboard, add some sum query

---

cdc/entry/kv_entry.go
cdc/puller/puller.go
tests/util/db.go

when upstream execute an adding column DDL, the DDL job state will follow `none` -> `delete-only` -> `write only` -> `done`.
When the column is `write only`, `TiDB` may write some value into this column. But CDC will receive ddl job after the job is `done`. So when CDC can't find the column info.
When the column is `write only`, it's not public yet, so the value inserted in this column must be default value.
Just ignore the `write only` column
Tests 
- Unit test

bug fix: ignore the column which is in `write only` status

---

cdc/capture.go
cdc/kv/client.go
cdc/kv/matcher.go
cdc/kv/matcher_test.go
cdc/processor.go
tests/dailytest/case.go

kvclient may be output a row which value is null
When two changes of the same key get received, the previous one may be overridden after the second prewrite.
Use "startTs + key" instead of "key" alone as the key of the state map.
Tests 
- Unit test

bug fix: kvclient may be output a row which value is null

---

Makefile
cdc/capture.go
cdc/capture_info.go
cdc/capture_info_test.go
cdc/owner.go
cdc/roles/manager.go
cdc/scheduler.go
cdc/scheduler_test.go
go.mod
go.sum

etcd has an auto compaction mechanism, we have some etcd key watch with revision. If error happens and retries from a compacted key revision, the error "mvcc: required revision has been compacted" will be returned from etcd API.
- add necessary retry on the `mvcc.ErrCompacted`
- remove revision if we can watch without rev
- add failpoint in unit  test
Tests 
- Unit test

retry when etcd watch meets mvcc.ErrCompacted

---

cdc/capture.go
cdc/owner.go
cdc/scheduler.go
go.mod

Some watch operation may meet the `mvcc.ErrCompacted` which is a retriable error, but we should have a rate limit for such retry.
use golang native rate limit
Tests 
- Unit test

add rate limit in some watch operation retry

---

cdc/capture.go
cdc/owner.go
cdc/processor.go
cdc/scheduler.go

Some time interval variables have significant effect to replication performance. We should have more clear way to manage them.
move these variables to a constant group in the file where they belong. (Easy for benchmark, of course some of the polling mechanism will be refined in the future)
Tests 
- Unit test

move some time interval constant variables

---

cdc/kv/client.go
cdc/kv/testing.go
cdc/model/kv.go
cdc/processor.go
cdc/puller/buffer.go
cdc/puller/buffer_test.go
cdc/puller/puller.go
cdc/puller/txn_test.go

1. `RawKVEntry` is an alias of `RegionFeedValue`
1. `ResolvedSpan` contains exactly the same information as `RegionFeedCheckpoint`
1. `KvOrResolved` is just a disguised `RegionFeedEvent`
This PR aims to simplify the code by merging these structs.
Only one of the dupcalited structs is kept for each twin structs.
We no longer need to create a new struct and copy each field from the old one.
Tests 
- Unit test

*: Merge similar structs

---

cmd/cdc.toml

The `ignore-txn-commit-ts` will be recognized as sub-item of `[[filter-rules.do-tables]]` in original sample config.
move `ignore-txn-commit-ts` to a proper place
Tests 
- No code

fix toml in sample config

---

cdc/kv/etcd.go
cdc/kv/etcd_test.go
cdc/model/errors.go
cdc/model/owner.go
cdc/model/owner_test.go
cdc/owner.go
cdc/owner_test.go
cdc/processor.go
cdc/processor_test.go
cdc/roles/storage/etcd.go
cdc/roles/storage/etcd_test.go
cdc/scheduler.go
cdc/scheduler_test.go

reduce the probability of write conflicts about `TaskStatus`
split `TaskStatus` into `TaskStatus` and `TaskPosition`
The processor write ResolvedTS and CheckpointTs into `TaskPosition`, and rarely write `TaskStatus`,
so we can reduce the probability of write conflicts about `TaskStatus`
Tests 
- Unit test

etcd: split TaskStatus into two structs

---

cdc/kv/client.go
cdc/kv/metrics.go
cdc/metrics.go
cdc/processor.go
cdc/processor_test.go
cdc/puller/buffer.go
cdc/puller/metrics.go
cdc/puller/puller.go
cdc/scheduler.go
cdc/sink/metrics.go
cdc/sink/mysql.go
pkg/util/ctx.go
pkg/util/ctx_test.go
ticdc.json

We need to monitor the data replication qps in data link, especially for each event channel 
- Add more metrics to monitor data replication speed
- Update relative grafana template config
Tests 
- Unit test

add more metrics for tracing data replication link

---

cdc/puller/entry_group.go
cdc/puller/entry_group_test.go
cdc/puller/puller.go

The original `EntryMap` implement is not very efficient, there exists too many unnecessary map iteration because not all KV entries in the `EntryMap` need to be retrieved each time.
Add a simple `EntryGroup` struct, including an entry map and a sorted ts slice. We can retrieve entries via the sorted ts slice more efficient
Tests 
- Unit test
before: CollectRawTxns: 88.52% **map operation: 64.76%**
after: CollectRawTxns: CollectRawTxns: 11.16%, **EntryGroup operation: 0.84%**

puller: use a more efficient EntryGroup

---

cdc/owner.go
cdc/processor.go
tests/util/db.go

If we flush on each `resolved` event, the bulks being synced would be too small.
Don't flush on `resolved` events, record the last resolved ts received and forward it only after flushing.
Tests 
- Unit test

processor: Do not flush on resolved event

---

cdc/owner.go
cdc/owner_operator.go
cdc/owner_test.go
cdc/processor.go
cdc/sink/mysql.go
cmd/client.go
tests/run.sh

fix #277 fix  #270 
- add dry-run for mysql sink
- a quick fix for slow handle in process txn caused by sleep and doing nothing.
Tests 
- Unit test
- No code
Code changes
Side effects

Add dry run opt and quick fix for slow handle txn

---

cdc/owner_operator.go
cdc/processor.go
cdc/puller/buffer.go
cdc/puller/buffer_test.go
cdc/puller/mock_puller.go
cdc/puller/puller.go
cmd/debug.go
go.mod
go.sum

fix #271 
Add a limit memory buffer for kv event, consume the kv event
ASAP, once reach limited memory buffer will pull.Run will return error
and processor.Run will fail.
Tests 
- Unit test
temporarily change the default mem buffer value to a low value and will reach the `ErrReachLimit` case. 
```
107 [2020/02/24 19:20:29.829 +08:00] [INFO] [capture.go:117] ["stop to run processor"] ["changefeed id"=5ccf8990-2145-4baf-8286-2d07fb6d2de3] [error="reach limit"] [errorVerbose="reach limit\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.2    0190809092503-95897b64e011/errors.go:174\ngithub.com/pingcap/errors.Trace\n\tgithub.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/juju_adaptor.go:15\ngithub.com/pingca …
```

Add mem buffer for kv event.

---

cdc/kv/client.go

The default gRPC window size is 64K, we can use a large value to increase the throughput.
ref: https://www.jianshu.com/p/48ad37e8b4ed
change `InitialWindowSize` and `InitialConnWindowSize` to 1GB
Tests 
- Unit test
throughput increased by approximately 40%
before:
after:

kv-client: add grpc window size config

---

cdc/puller/span_frontier.go

A quick fix for #282 
- firstly we can adjust the tree synchronously when we delete an element
- secondly comparing with `fast` insert way and `non-fast` insert way, found the `non-fast` insert way costs less CPU from flamegraph
| operation way       | puller.(*spanFrontier).insert | interval.(*Tree).Delete | interval.(*Tree).Insert | interval.(*Tree).AdjustRanges |
| ------------------- | ----------------------------- | ----------------------- | ----------------------- | ----------------------------- |
| fast insert way     | 17.17%                        | 4.50%                   | 0.96%                   | 9.42%                         |
| non fast insert way | 11.61%                        | 6.15%                   | 2.98%                   | -                             |
The …

span frontier adjust tree node synchronously

---

cdc/filter.go
cdc/owner.go
cdc/owner_operator.go
cdc/owner_test.go
cdc/processor.go
cdc/processor_test.go
cdc/roles/storage/etcd.go
cdc/scheduler.go
cdc/sink/mysql.go
cdc/sink/mysql_test.go
cdc/sink/sink.go

handle row-based changed event in processor
* processor receives globalResolvedTS and sends to sink, but not to block row changed event
* every `tableInfo` holds a mounter

processor: handle row-based changed event in processor, part three

---

cdc/kv/client.go
cdc/kv/client_test.go

Add a gRPC conn array to manage multiple gRPC connections. On the one hand, we can bypass the 1024 conn limit in TiKV temporarily. On the other hand, after the new implementation of EventFeed API we still need connection array for higher throughput.
Add a struct to keep connections, and use connections in a round-robin way.
Tests 
- Unit test

kv-client: add gRPC conn array

---

cdc/entry/mounter.go
cdc/owner.go
cdc/owner_operator.go
cdc/sink/mysql.go

QA found a bug that CDC couldn't replicate `CREATE TABLE` when the schema name is not all lowercase.
The root cause is TiDB stores the `CREATE TABLE` DDL history with a lowercase schema name.
Find the correct schema name from the `SchemaStorage` when we mount a DDL
Tests 
- Unit test

Fix lowercase schema name in ddl mounter

---

cdc/capture.go
cdc/kv/etcd.go
cdc/kv/etcd_test.go
cdc/model/processor.go
cdc/owner.go
cdc/owner_test.go
cdc/processor.go
cdc/scheduler.go
cmd/ctrl.go

The owner periodically checks the task status and marks the processor down if the task is not updated in time.  When a processor is marked down, the task associated with it is rebalanced to other processors.
As issue #269 says, when there is something wrong with the upstream(TiDB/TiKV) or network, the processor receives no more data to update the task status, the processor will be marked as down which is a false positive.
The PR introduces a session for each processor that keeps alive with a lease. Each processor is assigned an ID which constructs a key registered in the Etcd. When a processor stops, the lease expires, and the key will be deleted. The owner keeps watching on the key， and when a key is found deleted, the processor is marked as down.
* The session for capture is only used …

Reduce the RTO by watching the liveness of processors

---

cdc/entry/schema_builder.go

when we add a table with start-ts, we can't guarantee that `start-ts` is less than `checkpointts`,  `DoGC` function of `schema builder` will panic
Tests 
- Unit test

bug fix: panic about schema builder

---

cdc/roles/manager.go

Etcd uses 1s as the election timeout by default, this proves
the TTL could be a few seconds in the LAN environment. To speed
up the election of the owner, we reduce the session TTL to 5s.
Reduce 1ManagerSessionTTLSeconds` from 60 to 5
Tests 
- Unit test

manager: use a less TTL value

---

cdc/processor.go
cdc/scheduler.go
cdc/sink/mysql.go
cdc/sink/sink.go
tests/run.sh

sink prints too much logs in each exec DML loop
- remove log for each time that MySQL sink executes DMLs, instead of a periodically print status
Tests 
- Unit test

sink: refine mysql log, remove redundant SQL count log

---

cdc/model/owner.go
cdc/owner.go
cdc/processor.go

panic in storagebuilder sometimes
The information exchange between owner and processor is dependent on `TaskPositions` and `TaskStatus`.
`TaskStatus` is updated by the owner mainly, `TaskPositions` is updated by processors.
When the owner adds a table to the processor, the owner will update `TaskStatus`.  When the processor finds the change of `TaskStatus`, the processor will start table puller and update `TaskPositions`.
If the `TaskStatus` is already updated, but `TablePostitions` is still not updated by the processor, the owner may ignore the checkpointTS of the newest table.
Tests 
- Unit test

bug fix: panic in storagebuilder sometimes

---

cdc/scheduler.go

set changedfeed id into sink options mistakenly

bug fix: set changedfeed id into sink options mistakenly

---

Makefile

Fail to run test for go 1.14
https://github.com/pingcap/ticdc/issues/305
A workaround that setting `GOVERSION114=1` before running test for go 1.14
Tests 
```bash
GOVERSION114=1 make test
```

Makefile: fix running test for go 1.14

---

cdc/sink/mysql.go

Fix https://github.com/pingcap/ticdc/issues/320
the schema `test` may not exist in downstream, we can omit schema name in MySQL DSN
Tests 
- Unit test

sink/mysql: remove default schema in mysql dsn

---

cdc/entry/mounter.go
cdc/owner.go
cdc/owner_operator.go
cdc/processor.go
pkg/util/span.go

When TiDB need execute a Add Index DDL, TiDB will put the DDL Job into `DDLJobAddIdxList`, but not `DDLJobList`, so ddl puller should listen both `DDLJobList` and `DDLJobAddIdxList`.
fixed #369
Tests 
- Unit test
I will replenish integration tests in next PR

puller: fix listen add index ddl

---

cdc/task.go

When a task is dispatched before a change feed status is created, a newfound task can not be parsed.
When a change feed status is not created, use a default value.
Tests 
- Unit test

task: fix to parse task when the status is not created

---

cdc/entry/mounter.go
cdc/entry/schema_builder.go
cdc/entry/schema_storage.go
cdc/model/errors.go
cdc/processor.go

we maintain an undo ddl job queue in schema builder, if all of the schema storage loaded a DDL job, we can remove this job from the undo queue.
The ddl jobs will be removed if the ts of ddl is smaller or equal than checkpoint TS. but there may be an unapplied job which ts is equal with checkpoint TS. we remove it by mistake.
fixed #373 #372 #355 
Tests 
- Unit test

bug fix: fix schema builder may remove unapplied DDL job

---

cdc/capture.go

print the log message after a processor is created

capture: print log after the processor being started

---

cdc/owner.go
cdc/processor.go
cdc/sink/black_hole.go

the `blackhole` sink returns immediately after `Run`, besides the `resolved ts` is not handled very well.
- wait for context done in `Run`
- refine some error handler
- use the same resolved logic in MySQL sink
Tests 
- Unit test

sink: fix Run in black hole sink

---

cdc/puller/entry_sorter.go
cdc/puller/puller.go
cdc/sink/mqProducer/kafka.go
kafka_consumer/main.go

Fix #384 
One general principle of using Go channels is that we should only close a channel in a sender goroutine if the sender is the only sender of the channel.
So we close the `resolvedCh` belongs to a sorter in the sender goroutine.
Tests 
- Unit test

puller: fix sorter may panic because of bad usage of chan

---

cdc/kv/client.go

Fix #387 
- Add retry to gRPC stream client getter
- To deal with the store permanently down scenario, try to relocate the active store, so retry the mainloop of `dispatchRequest` when getting stream client failed.
Tests 
- Unit test

Add retry to gRPC stream client getter

---

cdc/entry/mounter.go
cdc/processor.go
cdc/puller/buffer.go
cdc/puller/entry_sorter.go
cdc/puller/puller.go
cdc/sink/mq.go
ticdc.json

As we have an unlimited buffer between puller and TiKV, we could increase channel buffer size as large as possible.
Tests 
- Unit test

increase chan size, fix grafana template

---

scripts/jenkins_ci/integration_test_common.groovy

Add `availability` into the Jenkins integration test

ci: add availability into the jenkins test

---

go.mod
pkg/util/region_range_lock.go
pkg/util/region_range_lock_test.go

This PR adds a util named RegionRangeLock, which is a simple range and can also maintains minimal checkpointTs by range and identify stale acquire-lock operation by checking the version of the region's epoch.
This PR is part of https://github.com/pingcap/ticdc/pull/385 , which supports region merge.
Added new util RegionRangeLock.
Tests 
- Unit test
Code changes
Side effects
- No.

util: Add RegionRangeLock

---

cdc/changefeed.go

Fix #414
This may happen as following
- The CDC-A(owner) processes a `drop table` DDL, where the table originally locates at CDC-B.
- Before CDC-A writes new `taskStatus` into etcd, the CDC-B crashes, capture watcher in CDC-A finds it, and delete the `taskStatus` of CDC-B
- `c.taskStatus[captureID]` is nil and panic.
We could just ignore it and in the next round there will be no more `taskStatus` for CDC-B
Tests 
- Unit test

fix restore table panic

---

cdc/puller/metrics.go
cdc/puller/puller.go

We have metric label generation in some hot path in puller.
pre allocate prometheus labels to reduce cpu consume
Tests 
- Unit test

pre allocate prometheus labels to reduce cpu consume

---

cdc/kv/client.go
cdc/kv/matcher.go
cdc/kv/matcher_test.go

commit log may come before prewrite log, if the incremental scan has not finished.
use a cache to store the unmatched commit log before initialized
Tests 
- Unit test

kv-client: support p-c out of order before initialized

---

cdc/owner.go
cdc/task.go
cdc/task_test.go
go.mod

Closes #409 
Add failpoint for the task watcher and the capture watcher
Add failpoint to trigger an ErrCompacted error
**Notice that the unit test for the capture watcher is not added, because the whole test file has been commented out.**
Tests 
- Unit test

unittest: add failpoint for watchers

---

cdc/kv/client.go

This PR tries to print some log when the channel to a region's worker cannot be sent or received for too long time.
But actually I'm not sure the performance overhead to create the timer.
This PR tries to print some log when the channel to a region's worker cannot be sent or received for too long time.
Tests 
- Manual test
Example:
```
[2020/04/03 10:35:07.812 +00:00] [WARN] [client.go:1062] ["region not receiving event from tikv for too long time"] [regionID=8] [span="{\"Start\":\"bURETEpvYkxp/3N0AAAAAAAA+QAAAAAAAABs\",\"End\":\"bURETEpvYkxp/3N0AAAAAAAA+QAAAAAAAABt\"}"] [duration=5m0s]
[2020/04/03 10:35:07.815 +00:00] [WARN] [client.go:1062] ["region not receiving event from tikv for too long time"] [regionID=8] [span="{\"Start\":\"bURETEpvYkFk/2RJZHhMaXN0/wAAAAAAAAAA9wAAAAAAAABs\",\"End\ …
```

kv/client: Print log when region worker channel is stuck

---

cdc/kv/client.go

In the incremental scan procedure, TiKV may send commit event without a corresponding prewrite event. 
We can just ignore this commit event, but don't check whether the committed log with same `start-ts` and `key` is really received, because the check may cost too much memory to store `start-ts`-`key` pair of all committed events.
Tests 
- Unit test

kv-client: ignore commit log without prewrite before initialized

---

cdc/entry/mounter.go
cdc/kv/matcher.go

ignore prewrite event if value is empty
Tests 
- Unit test

kv client: ignore prewrite event if value is empty

---

cdc/kv/client.go

region information is not recorded correctly when `regions not completely left cover span` error happens
record the region meta
Tests 
- Unit test

kv-client: use correct region in log

---

cdc/sink/mysql.go
scripts/jenkins_ci/integration_test_common.groovy
tests/sink_retry/conf/diff_config.toml
tests/sink_retry/conf/workload
tests/sink_retry/run.sh

We have no retry mechanism in MySQL sink, as our DML SQLs in MySQL sink are reentrant, we can simply retry on errors.
retry when transaction execution meets error in MySQL sink
Tests 
- Unit test

sink: add retry mechanism for dml execution

---

cdc/metrics_processor.go
cdc/puller/puller.go
cdc/sink/black_hole.go
ticdc.json

some metrics are outdated
- remove unused metrics
- add new added metrics in grafana template
- use `checkpoint-ts` as the initialized value of `puller resolved-ts`, which is used for monitor only.
Tests 
- Unit test

refine some prometheus metrics, update grafana template

---

cdc/entry/mounter.go
cdc/entry/schema_storage.go
cdc/entry/schema_storage_test.go

When we have workload in upstream and kill CDC server, the server doesn't exit immediately but hangs.
```
goroutine 549 [select]:
github.com/cenkalti/backoff.RetryNotify(0xc00131ac20, 0x23d3c20, 0xc007ab1600, 0x0, 0x0, 0x0)
github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:60 +0x1e6
github.com/cenkalti/backoff.Retry(...)
github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:24
github.com/pingcap/ticdc/pkg/retry.Run(0x989680, 0x19, 0xc00131ac78, 0xc00279b1a9, 0xa)
github.com/pingcap/ticdc@/pkg/retry/retry.go:30 +0xb8
github.com/pingcap/ticdc/cdc/entry.(*SchemaStorage).GetSnapshot(0xc0014425c0, 0x5c5c9dbee50066b, 0x20, 0xc00279b1a9, 0xa)
github.com/pingcap/ticdc@/cdc/entry/schema_storage.go:579 +0x81
github.com/pingcap/ticdc/cdc/entry.(*mounterImpl).unmarshalAndMountRowChanged(0xc0 …
```

schema: fix snapshot getter blocks too long when cdc exits

---

cdc/kv/client.go
cdc/sink/mysql.go

`ScanRegions` API of PD may return incorrect information in some extreme cases, it is better to retry more than returns an error in kv client
increase the upper limit of retry count
Tests 
- Unit test

kv-client: increase upper limit of retry count.

---

cdc/kv/client.go
cdc/kv/client_test.go
cdc/kv/testing.go
cdc/owner.go
cdc/owner_operator.go
cdc/processor.go
cdc/puller/puller.go
scripts/jenkins_ci/integration_test_common.groovy
tests/_utils/stop_tidb_cluster
tests/resolve_lock/config.toml
tests/resolve_lock/diff_config.toml
tests/resolve_lock/main.go
tests/resolve_lock/run.sh
tests/util/config.go

support resolve lock for ticdc
Tests 
- Unit test

kvclient: support resolve lock for ticdc

---

cdc/roles/storage/etcd.go

Fix https://github.com/pingcap/ticdc/issues/443
`TaskStatus` may be deleted during owner update task status.
Tests 
- Unit test

fix owner panic when update task status failed

---

cdc/entry/schema_storage.go
cdc/owner.go
cmd/client.go

recount ineligible table set when start the changefeed
Tests 
- Unit test

schema: recount ineligible table set when start the changefeed

---

cdc/changefeed.go
cdc/entry/mounter.go
cdc/entry/schema_storage.go
cdc/entry/schema_storage_test.go
cdc/owner.go
cdc/puller/mock_puller.go
cmd/client.go

* fix the issue about getting the wrong schema snap when start changefeed
* add a `PrintStatus` function for `schema snap` to make debug easier, and print the status of schema snap when some error happened.
Tests 
- Unit test

owner: fix the issue about getting the wrong schema snap when start changefeed

---

cdc/capture.go
cdc/kv/client.go
cdc/owner.go
cdc/processor.go
cdc/server.go

Reduce unnecessary operations when start a event feed
Tests 
- Unit test

kvclient: Reduce unnecessary operations when start a event feed

---

cdc/kv/client.go
cdc/sink/mqProducer/kafka.go

in a region merge test, found a lot of CPU is consumed by `runtime.siftdownTimer`.
We should close ticker when the routine that ticker is running in exits. 
before:
after:
Tests 
- Unit test

close ticker to fix ticker resource leak

---

cdc/model/changefeed.go
cdc/model/mounter.go
cdc/model/sink.go
cdc/processor.go
cdc/puller/entry_sorter.go
cdc/puller/entry_sorter_test.go
cdc/puller/file_sorter.go
cdc/puller/sorter.go
cmd/client.go
scripts/jenkins_ci/integration_test_common.groovy
tests/file_sort/conf/diff_config.toml
tests/file_sort/conf/workload
tests/file_sort/run.sh

This is the first part of https://github.com/pingcap/ticdc/issues/466, add a file sort mechanism, a changefeed can use either memory sorter or file sorter
- add two kinds of sort engine, memory and file
- define a new interface `EventSorter` in puller, so we don't need to change original replication model.
- file sorter has an `input` cache channel, it reads from `input` channel and flushes events to file until they are all mounted. 
- implement a simple double cache, one is used to sort with files, the other one is used to cache unsorted data to file.
Tests 
- Unit test

Support file sort in puller

---

cdc/puller/file_sorter.go

If there are no events in an unsorted file, file sorter creates a new sorted file name but doesn't create the sorted file
Just don't create a new sorted file name if there is no event at all
Tests 
- Unit test

puller: fix cache file name but no sorted file created in file sorter

---

cdc/owner.go

Fix #485 
NOTE: there still exists another problem, with the following time sequence. I will fix this problem in another PR
```
capture-1 crashes -> 
owner doesn't finish `removeCapture` before it is evicted ->
another capture becomes owner, but the new owner doesn't aware of the existence of capture-1
```
- `loadChangeFeeds` once before `watchCapture`
- separate `balanceTables` from `loadChangeFeeds`
Tests 
- Unit test

owner: fix task status not deleted when capture is crashed

---

cdc/puller/file_sorter.go

`lastSortedFile` is not correctly assigned
Use correct assignment logic.
Tests 
- Unit test

fix last sorted file assignment in file sorter

---

cdc/sink/mysql.go

When MySQL sink executes DDL failed and retries, user doesn't know what is happening from log
- Add log for DDL failure before next retry
- make DDL executing context cancelable 
Tests 
- Unit test

sink: add log when executing DDL failed during retry

---

cdc/kv/client.go

This PR fixes some bugs that the kv client didn't handle TiKV reconnecting correctly.
Bug 1:
1. In `dispatchRequests`, it sends a request to a region, and the region info is added to the `pendingRegions` map.
2. Due to some reason like unstable network or TiKV crash, it failed to send the request, and tries to send it again.
3. It adds the new pending region info to the `pendingRegions` map with a new requestID, and tries to re-establish the stream.
4. The `receiveFromStream` goroutine noticed the stream is broken, and closes all pending regions on this stream. In this case, the new pending region info will be regarded as a dead request and will be closed. However, the `dispatchRequests` goroutine is just trying to reconnect and send a new request to that region.
5.1 If the reconnecting …

kv/client: Fix incorrect behaviors when reconnecting the stream

---

cdc/kv/client.go
cdc/sink/mq.go
pkg/util/region_range_lock.go

This PR tries to reduce the amount of logs printed by kv/client.
It's possible that this change makes it harder to investigate when a CDC server runs under INFO log level meets problem.
Tests 
- No code

kv/client: Reduce some logs

---

cdc/entry/codec.go
cdc/entry/mounter.go
cdc/server.go
cdc/sink/mysql.go
cdc/sink/sink.go
cmd/server.go
kafka_consumer/main.go
pkg/util/ctx.go

support to config time zone
Tests 
- Unit test

*: support to config time zone

---

cdc/entry/mounter.go

mounter: skip put index event in unmarshalIndexKVEntry

---

Makefile
cdc/owner.go
scripts/jenkins_ci/integration_test_common.groovy
tests/availability/capture.sh
tests/availability/owner.sh

Fix a but that task information may be not totally cleanup, and blocks the replication.
When a new owner `throne`, it firstly cleans up existing stale task information. Because the new owner does not know the events occurs before, like processor deletion, it always tries to check task status to find stale task information. As for stale task information, there are three kinds of resource.
- capture info, which has a 3s session TTL
`/tidb/cdc/capture/b64e38d7-1f11-441a-ab64-3fd11838c77d`
- task status
`/tidb/cdc/task/status/b64e38d7-1f11-441a-ab64-3fd11838c77d/27ce907f-4cb7-4775-a11e-8be6a34e9c91`
- task position
`/tidb/cdc/task/position/b64e38d7-1f11-441a-ab64-3fd11838c77d/27ce907f-4cb7-4775-a11e-8be6a34e9c91`
If task status is deleted, but task position is stale, the `cleanUpStaleTasks` …

owner: fix stale tasks cleanup

---

cdc/sink/mysql.go

currently cdc always logs a warning log when executing DDL
only log warning when err is not nil
Tests 
- Unit test

sink: remove verbose log if DDL execution is successful

---

cdc/server.go
cdc/sink/mysql.go
cmd/server.go
pkg/util/tz.go

If the environment `TZ` is not set , the value of `time.Local.String()` is `Local`, 
when we try to connect to mysql using `Local` timezone, we will get an error: `Error 1298: Unknown or incorrect time zone: 'Local'`
Tests 
- Unit test

*: fix wrong timezone when env `TZ` is not set

---

cdc/puller/file_sorter.go
tests/file_sort/conf/workload
tests/file_sort/run.sh

Fix several bugs in file sorter
- unsorted files can't be removed before sorted files are generated.
- file sorter only outputs resolved ts event when a round of sort finishes, which does not meet our requirement. As the data accumulated before this resolved ts may cause OOM 
- Remove unsorted files together with the sorted files
- As events are sorted, we can output a resolved ts event periodically, we output auto resolved ts event after sending every 1000 rows now.
- use more data in file sort integration test
Tests 
- Unit test

file-sorter: fix unsorted files gc, add auto resolved ts output

---

cmd/client.go

make create changefeed command easier to use
- support both `y` and `Y` when choosing to ignore eligible tables
- refine some message
Tests 
- Unit test

cmd: refine create changefeed message

---

cdc/sink/mq.go
cdc/sink/mqProducer/kafka.go

fix a bug about advancing checkpointTs mistakenly
Tests 
- Unit test

kafka sink: fix a bug about advancing checkpointTs mistakenly

---

cdc/metrics_processor.go
cdc/processor.go
cdc/sink/metrics.go
cdc/sink/mysql.go
metrics/alertmanager/ticdc.rules.yml
metrics/grafana/ticdc.json

We need more metrics and alerts.
1. add memory usage > 10GiB alerts.
2. add 3 time usage alerts for 3 parts:
- sorter sort
- sorter merge
- mounter mount
3. add alert for tikv resolved ts not updated for 1m.
4. add alerts for processor exits with errrors and mysql execution errors.
5. add two panels mysql execution errors count and processor exits with errrors counts into `ticdc.json`.
Tests 
- No code

Add metrics and alerts

---

cdc/owner.go
tests/availability/capture.sh
tests/availability/owner.sh
tests/availability/processor.sh
tests/availability/run.sh

Fix bug found in https://github.com/pingcap/ticdc/issues/530
TODO: there exists another bug, if owner has cleaned up task status (either in `removeCapture` or in `cleanUpStaleTasks`),  but the owner crashes before the orphan tables are dispatched, the orphan tables will be ignored. Will solve it in another PR.
- clean up stale task each time before watch capture event starts
- re-balance tables when cleaning up stale tasks
Tests 
- Unit test

owner: fix cleanup tasks in some corner case

---

.github/pull_request_template.md
README.md
tests/_utils/run_cdc_server

coverage file could be overwritten in a test case that starts more than one captures, add `pid` to coverage file to distinguish them.
- add pid in cdc server coverage file
- update document link in readme
- add coverage report of integration test from coveralls.io
Tests 
- Unit test

*: add pid in cdc server coverage file

---

cdc/capture.go
cdc/owner.go
cdc/server.go
tests/availability/owner.sh

Fix https://github.com/pingcap/ticdc/issues/523
- remove the panic mechanism in capture, just return the `Suicide` error when etcd session is done.
- make `campaignOwnerLoop` as a background routine, in most failure cases (including err compacted, `s.capture.Campaign` failed, owner Run failed), we don't return error directly, just run another campaign loop
Tests 
- Unit test
- Fix owner may not run the main work loop because some errors are not handled correctly.

owner: fix resouce cleanup when an owner exits

---

cdc/kv/client.go
cdc/kv/client_test.go

This PR tries to fix the issue about reconnecting TiKV may make CDC stuck for a while, and added some debug logs for investigation.
Tests 
- Unit test
- Fix the issue that reconnecting to TiKV may cause CDC stuck for a while

client: Fix the issue that TiKV reconnecting may make CDC stuck for a while

---

cdc/owner.go
tests/_utils/run_cdc_server

Fix https://github.com/pingcap/ticdc/issues/544
- Should filter task status belonging to active capture.
- Also fix a variable name in test script, as `_` will be interpreted as a part of bash variable
Tests 
- Unit test

owner: only dispatch stale task status during clean up

---

cdc/task.go

in a test happens to find following bug
```
[2020/05/08 23:07:59.271 +08:00] [INFO] [processor.go:144] ["start processor with startts"] [startts=0]
[2020/05/08 23:07:59.272 +08:00] [INFO] [store.go:68] ["new store"] [path="tikv://localhost:2379?disableGC=true"]
[2020/05/08 23:07:59.272 +08:00] [INFO] [client.go:141] ["[pd] create pd client with endpoints"] [pd-address="[localhost:2379]"]
[2020/05/08 23:07:59.278 +08:00] [INFO] [base_client.go:226] ["[pd] update member urls"] [old-urls="[http://localhost:2379]"] [new-urls="[http://127.0.0.1:2379]"]
[2020/05/08 23:07:59.278 +08:00] [INFO] [base_client.go:242] ["[pd] switch leader"] [new-leader=http://127.0.0.1:2379] [old-leader=]
[2020/05/08 23:07:59.279 +08:00] [INFO] [base_client.go:92] ["[pd] init cluster id"] …
```

task: use start-ts if changefeed status doesn't exist

---

cdc/processor.go

processor can be stopped by the admin command, which should not update info and log error. Fix #543
- add a flag to record whether the processor is stopped.
- treat `model.ErrAdminStopProcessor` when processor exits.
Tests 
- Unit test

processor: refine log output when stopped by admin command

---

cdc/sink/mqProducer/kafka.go

kafka sink: fix data race in kafka sink

---

pkg/notify/notify.go
pkg/notify/notify_test.go

The `receiverCh` is not closed from the sender routine.
```
➜  GO111MODULE=on go test -check.f TestContinusStop
panic: send on closed channel
goroutine 3445 [running]:
github.com/pingcap/ticdc/pkg/notify.signalNonBlocking(0xc000b510e0)
/home/tidb/code/ticdc/pkg/notify/notify.go:29 +0x35
github.com/pingcap/ticdc/pkg/notify.(*Notifier).NewReceiver.func1(0xc000b3b720, 0xc000b510e0)
/home/tidb/code/ticdc/pkg/notify/notify.go:55 +0x5c
created by github.com/pingcap/ticdc/pkg/notify.(*Notifier).NewReceiver
/home/tidb/code/ticdc/pkg/notify/notify.go:53 +0x30b
exit status 2
FAIL    github.com/pingcap/ticdc/pkg/notify     0.126s
```
This error also happens in integration test: https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/cdc_ghpr_kafka_integration_test/runs/216/ …

notify: fix data race and send on close chan in receiveCh

---

cdc/capture.go
cdc/server.go
cdc/sink/mysql.go
cmd/client.go
cmd/client_capture.go
cmd/client_changefeed.go
cmd/client_meta.go
cmd/client_processor.go
cmd/client_tso.go
cmd/util.go
tests/_utils/start_tidb_cluster
tests/cli/run.sh

Add dial timeout and verify sink connection when creating changefeed.
Cc https://github.com/pingcap/ticdc/issues/542
Tests 
- Add client dial timeout
- Verify sink connection when creating changefeed

cmd: add dial timeout and verify sink connection status

---

cdc/sink/mysql.go

Fix bug in https://github.com/pingcap/ticdc/issues/573
send to channel in select mode, with `ctx.Done()` check
Tests 
- Unit test

sink: when context is done, send to chan will be block

---

cdc/owner.go
cdc/processor.go
cdc/server.go
cmd/client.go
cmd/server.go
go.mod
go.sum
pkg/util/check.go
pkg/util/check_test.go
tests/resolve_lock/main.go

Add version check when starting CDC server and CDC client. It impls #542 task 9.
It also passes context to PD client and may help #562 .
Fix https://github.com/pingcap/ticdc/issues/564
Tests 
- Unit test
Code changes
- Support validate cluster version

*: check cluster version

---

cdc/metrics_processor.go
cdc/processor.go
cdc/puller/puller.go
metrics/grafana/ticdc.json

refine some metrics
- processor output chan size should not contain `table` label
- pre allocate labels
Tests 
- Unit test
<!-- bugfixes or new feature need a release note, must in the form of a list, such as

metrics: some metrics optimization

---

cdc/changefeed.go
cdc/entry/schema_storage.go
cdc/kv/etcd.go
cdc/kv/etcd_test.go
cdc/model/capture.go
cdc/model/owner.go
cdc/model/owner_test.go
cdc/owner.go
cdc/processor.go
cdc/roles/storage/etcd.go
cdc/roles/storage/etcd_test.go
pkg/notify/notify_test.go
tests/_utils/run_cdc_server
tests/_utils/start_tidb_cluster
tests/availability/owner.sh
tests/cyclic_ab/conf/diff_config.toml
tests/resolve_lock/main.go

- Unify the variable types of tableID
- Deprecated the table lock and using undo list(Operation in TaskStatus) to maintain table migration
- support to add or remove more than one tables in one tick
Tests 
- Unit test

*: a new table migration mechanism

---

cdc/processor.go

optimization for https://github.com/pingcap/ticdc/issues/571
- Emit RowChangedEvents in batch
- cache RowChangedEvent and flush them when reaching batch limit or receiving a ResolvedEvent
Tests 
- Unit test

process sorted RowChangedEvent in batch to increase throughput

---

cmd/client.go
cmd/client_capture.go
cmd/client_changefeed.go
cmd/client_meta.go
cmd/client_processor.go
cmd/client_tso.go
cmd/root.go
cmd/server.go
cmd/util.go

Prevent ongoing requests being canceled by deadline exceeded.
Tests 

cmd: prevent ongoing requests being canceled by deadline exceeded

---

cdc/puller/entry_sorter_test.go

test case is not registered in `check` in puller module
add `check.TestingT(t)
Tests 
- Unit test

tests: enable unit test in puller module

---

cdc/sink/mqProducer/kafka.go

Fix https://github.com/pingcap/ticdc/issues/576, also close `sarama.SyncProducer` and `sarama.AsyncProducer` before Kafka sink is destroyed.
- make `Close` of `kafkaSaramaProducer` reentrant
- use `Close` to release resource
Tests 
- Unit test

sink: refine close in kafka sink

---

cdc/changefeed.go
cdc/model/changefeed.go
cdc/owner.go
cdc/processor.go
cdc/sink/dispatcher/interface.go
cdc/sink/mq.go
cdc/sink/mysql.go
cdc/sink/sink.go
cmd/changefeed.toml
cmd/client_changefeed.go
cmd/cmd_test.go
cmd/util.go
kafka_consumer/main.go
pkg/config/config.go
pkg/config/cyclic.go
pkg/config/filter.go
pkg/config/mounter.go
pkg/config/sink.go
pkg/cyclic/replication.go
pkg/filter/filter.go
pkg/filter/filter_test.go

config: reduce the structure of config file
Tests 
- Unit test

config: reduce the structure of config file

---

cmd/client.go
cmd/root.go
cmd/server.go

fix #542 (8)
Tests 
- Unit test

cli: log some critical information to stdout but not log file

---

cdc/kv/client.go

advance the max receive msg size of GRPC
Tests 
- Unit test

kvclient: advance the max receive msg size of GRPC

---

cdc/kv/etcd.go
cdc/kv/etcd_test.go
cdc/owner.go
cmd/client_changefeed.go

fix #541 #542.(3)
ignore and warn the invalid admin jobs.
if users remove the changefeed, the owner will delete the changefeed info immediately and set 24h TTL to the changefeed status.
the CDC CLI will report a warning to tall users the changefeed has been deleted.
```
./cdc cli changefeed remove --changefeed-id 04dac05c-484d-49e2-8163-1cca0d7f2
./cdc cli changefeed query --changefeed-id 04dac05c-484d-49e2-8163-1cca0d7f2fb5
[2020/06/01 09:07:24.984 +00:00] [WARN] [client_changefeed.go:149] ["this changefeed has been deleted, the residual meta data will be completely deleted within 24 hours."]
{
"info": null,
"status": {
"resolved-ts": 417071719969980417,
"checkpoint-ts": 417071719707836417,
"admin-job-type": 3
},
"count": 0,
"task-status": []
} …
```

owner: ignore the invalid admin jobs

---

Dockerfile

timezone info is not shipped in `alpine` container, so the CDC will fail to start if `timezone` is configured.
add `tzdata` package
Tests 
- Manually test, build docker image from new Dockerfile
- Need to republish v4.0.x docker images.

Add timezone data in Dockerfile

---

cdc/sink/mq.go
cdc/sink/mysql.go
cmd/server.go

- Currently cdc servers logs version info (a.k.a welcome information `"Welcome to Change Data Capture (CDC)"`) to stdout, and other logs log to `cdc.log` by default.
- Fix https://github.com/pingcap/ticdc/issues/575
- Fix statistics is not print periodically in some cases.
- Default log to stdout in cdc server
- Log welcome information after log handler is initialized
Tests 

*: refine cdc server log and sink statistics log

---

pkg/util/tz.go
pkg/util/tz_test.go

Fix #619 
- if `region` information from zone file is `zoneinfo`, use the last element of zone file only.
- use `path/filepath` to instead `path`
Tests 
- Unit test

util: fix local timezone parse error

---

cdc/processor.go
cdc/sink/mysql.go

close the sink and release the db connect after processor is stoped and changefeed is closed
Tests 
- Unit test
fix the issue about the db content leak

sink: close the sink and release the db connect

---

pkg/util/check.go
pkg/util/check_test.go

PD uses version in git describe format which has a string `-[0-9]+-g[0-9a-f]{8,}`. It breaks semver comparison.
Remove the string `-[0-9]+-g[0-9a-f]{8,}`
Tests 
- Unit test
- Fix check version in git describe format.

pkg/util: fix check version in git describe format

---

tests/file_sort/conf/workload
tests/file_sort/run.sh

`file_sort` test often runs timeout now.
- Decrease data size
-  Increase wait time
Tests 

Decrease data size and increase wait time in file sort test

---

cdc/capture.go
cdc/model/changefeed.go
cdc/model/changefeed_test.go
cdc/owner.go
pkg/filter/filter.go

This is a part of https://github.com/pingcap/ticdc/issues/629, make cdc server can be compatible with changefeed created by cdc cli version (4.0.0-rc to 4.0.0) (no panic from old style changefeedinfo)
- Fill in default changefeed info if needed
Tests 
- start cdc server with this PR
- create a cdc changefeed with cdc cli v4.0.0
- the changefeed can run normally

Add some backward compatibility to cdc cli

---

cdc/changefeed.go
cdc/sink/mysql.go
tests/_utils/start_tidb_cluster
tests/autorandom/conf/diff_config.toml
tests/autorandom/data/test.sql
tests/autorandom/run.sh
tests/cli/run.sh

When syncing data from tidb to tidb, if the primary key is AutoRandom, insert operations will fail because by default the db session to the sink does not allow writing to the AutoRandom key.
Adding code to set the session veriable allow_auto_random_explicit_insert to true when creating a mysqlSink.
Tests 

Enable support for AutoRandom in tidb sink

---

tests/_utils/run_cdc_server
tests/_utils/start_tidb_cluster
tests/file_sort/run.sh

For now, we use info level to run CI, it is not enough for debugging some CI failure like #644.
This PR set level to debug by default. 
Tests 
- No release note.

tests: turn log level to debug

---

cdc/model/mounter.go
cdc/processor.go

Fix #644 
Found two bugs:
~1. sinkEmittedResolvedTs and real emitted row changed events
- each sorter sends row changed events to the output channel of a processor.
- but resolved ts of each table is updated asynchronously, which means if the resolved ts of a table is updated, some row changed events before this resolved ts may be not consumed by processor yet.~ as `processor.output` chan is sequence, when resolved ts event is fetched, row changed events must have been consumed.
2. processor local resolved ts calculation and mark table (Then why the cyclic test often meets this bug makes sense )
- processor receives and emits row changed events of mark table, but mark table is not maintained in processor table list, and when calculating processor local resolved ts, the mark table is not …

Fix crts maybe less than emit resolved ts in processor

---

cdc/owner.go
cmd/client_meta.go
tests/_utils/run_cdc_cli
tests/cli/run.sh

Add a command to delete CDC GC TTL, the item 13 in #542 .
Tests 
- Add a command to delete CDC GC TTL

cmd: add a command to delete CDC GC TTL

---

tests/_utils/stop_tidb_cluster

kill the process to avoid port occupancy issues
Tests 

test: kill the process to avoid port occupancy issues

---

tests/cyclic_ab/run.sh
tests/cyclic_abc/run.sh
tests/cyclic_loopback/run.sh

Row changed events could be duplicated in CDC, so the number of DML events is nondeterministic 
Remove the event count check in test.
Tests 

remove events count check in cyclic test

---

cdc/sink/mysql.go
tests/resolve_lock/run.sh

support config tidb txn mode in mysql sink, and use `optimistic` as default mode. ref: https://github.com/pingcap/ticdc/issues/668
Pass this parameter from `sink-uri` (If user use MySQL dsn as sink-uri, this parameter is passed from dsn parameter)
Tests 
- Support config tidb txn mode in MySQL sink, and use optimistic as default

sink: support config tidb txn mode in mysql sink

---

cmd/client_changefeed.go
cmd/server.go
tests/cli/run.sh

Fix https://github.com/pingcap/ticdc/issues/673
Note this `tz` is only used in sink uri verification, the timezone
used in changefeed is determined by the `timezone` paramter passed
to `cdc server`
read timezone from `TZ` env or `--tz` parameter
Tests 

Support tz parameter when creating changefeed

---

cdc/kv/client.go
cdc/kv/client_test.go
cdc/server.go
cmd/client.go
pkg/util/check.go
pkg/util/check_test.go

Check TiKV version before making EventFeed RPC in order to mitigate compatibility issues.
Cc  #663 
Tests 
- Unit test
Side effects
- No release note.

kv,util: check TiKV version before event feed and refine version check

---

cdc/model/sink.go
kafka_consumer/main.go

Kafka consumer used in integration test reuses the MySQL sink of TiCDC, MySQL sink groups transaction by `start-ts` of row changed events, but `start-ts` is not contained in TiCDC open protocol.
Just hack to set `start-ts` equals to `commit-ts` of row changed events emitted from Kafka consumer. (We don't change TiCDC open protocol in this PR)
Tests 

Fix start-ts in row changed event emitted from kafka consumer

---

cdc/changefeed.go
cdc/processor.go
pkg/config/config.go
pkg/scheduler/interface.go
pkg/scheduler/table_number.go
pkg/scheduler/table_number_test.go

support to balance subtasks to new captures ,fix #638
- Adjust the default value of `Scheduler.PollingTime` to `-1`
- If `Scheduler.PollingTime` is less than 0, the rebanlance process will not be call by time trigger.
Tests 
- Unit test
- support to balance subtasks to new captures

support to balance subtasks to new captures

---

pkg/cyclic/mark.go
tests/cli/run.sh

Fix the error when creating mark table with invalid characters.
```
fail to create mark table repl_mark_test_dm_meta_sg-test_syncer_checkpoint: 
Error 1064: You have an error in your SQL syntax; 
check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 62 near "-test_syncer_checkpoint
```
Should quote schema and table
Tests 

pkg: quote schema.table to avoid error in SQL syntax

---

cdc/server.go
cdc/sink/mysql.go

Fix goroutine hangs when executing dmls with error
```
goroutine 446 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0xc005850730)
runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc005850728)
sync/waitgroup.go:130 +0x64
github.com/pingcap/ticdc/cdc/sink.(*mysqlSinkWorker).waitAllTxnsExecuted(...)
github.com/pingcap/ticdc/cdc/sink/mysql.go:499
github.com/pingcap/ticdc/cdc/sink.(*mysqlSinkWorker).waitAndClose(...)
github.com/pingcap/ticdc/cdc/sink/mysql.go:503
github.com/pingcap/ticdc/cdc/sink.concurrentExec(0x2a97bc0, 0xc000d14840, 0xc0058506c0, 0x10, 0x100, 0xc00575dda0, 0x0, 0xffffffffffffffff)
github.com/pingcap/ticdc/cdc/sink/mysql.go:476 +0x601
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).concurrentExec(0xc000d6e7c0, 0x2a97bc0, 0xc000d14840, 0xc0058506c0, 0x0, 0x0) …
```

sink: fix wait group is not updated when exec with error

---

cdc/changefeed.go
cdc/entry/mounter.go
cdc/model/changefeed.go
cdc/model/sink.go
cdc/owner.go
cdc/sink/mysql.go
cmd/client_changefeed.go
cmd/util.go
pkg/cyclic/filter.go
pkg/cyclic/filter_test.go
pkg/cyclic/mark/mark.go
pkg/cyclic/mark/mark_test.go
pkg/cyclic/replication.go
pkg/cyclic/replication_test.go
pkg/filter/filter.go
pkg/filter/filter_test.go
pkg/quotes/quotes.go
tests/cli/run.sh
tests/cyclic_ab/conf/only_test_simple.toml
tests/cyclic_ab/run.sh

This PR tries to:
- Fix #679 CDC stops replication due to ineligible tables are not ignored.
- Fix #678 If mark table not in allow list, create cyclic changefeed will fail
Tests 
- Unit test
Code changes
Side effects
- Fix the issue that fail to create cyclic changefeed if mark table not in allow list.
- Fix the issue that cyclic changefeed does works if there are some ineligible tables.

*: fix cyclic replication issues with filter and ineligible tables

---

cdc/changefeed.go
cdc/http_handler.go
cdc/http_status.go
cdc/owner.go

*: fix typo of rebalance

---

cdc/processor.go

In some tests we find after changefeed is stopped via admin API, processor maybe not fully exit, and some kv client blocks at `stream.Recv`.
After some investigation we find processor doesn't cancel ddl puller when `p.stop()` is called.
Cancel ddl puller when in processor stop.
Tests 
- Fix processor does not fully exit when changefeed is stopped via admin API.

processor: fix processor doesn't fully exit after `p.stop` is called

---

cdc/model/changefeed_test.go
cmd/cmd_test.go
pkg/config/filter.go
pkg/filter/filter.go
pkg/filter/filter_test.go

replace ddl-white-list with ddl-allow-list
replace ddl-white-list with ddl-allow-list
Tests 
- Unit test
Side effects
- If running changefed has been configured with `ddl-white-list`, this configuration will be lost after TiCDC upgrade
- `ddl-white-list` in the old changefeed config file must be replaced with `ddl-allow-list`

*: replace ddl-white-list with ddl-allow-list

---

cdc/model/changefeed.go
cdc/model/errors.go
cdc/model/owner.go
cdc/owner.go
cdc/processor.go
tests/changefeed_auto_stop/conf/diff_config.toml
tests/changefeed_auto_stop/conf/workload
tests/changefeed_auto_stop/run.sh

This is part of https://github.com/pingcap/ticdc/issues/664, and tries to release resource if one processor of a changefeed meets error
- If a processor exits with error, upload the error message to `task position`.
- If owner finds error in `task position`, stop the changefeed via admin job. 
Tests 
- Stop changefeed automatically if one of processor exits

Stop changefeed automatically if one of processor exits

---

cdc/sink/mysql.go

minor performance optimization
use string operator `+` instead of `fmt.Spritnf`
In fact TiDB has schema/table name size limit of 64 (https://github.com/pingcap/parser/blob/master/mysql/const.go#L71-L74), and in most cases, table name tends to be shorter.
simple benchmark
```
package main
import (
"fmt"
"strings"
"testing"
)
func BenchmarkBuild(b *testing.B) {
funcs := []struct {
name string
f    func(table string)
}{
{
"fmt.Sprintf", func(table string) {
var builder strings.Builder
builder.WriteString(fmt.Sprintf("DELETE FROM %s WHERE", table))
},
}, {
"builder", func(table string) {
var builder strings.Builder
builder.WriteString("DELETE FROM ")
builder.WriteString(table)
builder.WriteString(" WHERE")
},
}, {
"operator", func(table string) {
var builder strings.Builder …
```

Remove fmt.Sprintf when assembling SQLs

---

cdc/sink/metrics.go
cdc/sink/mysql.go
cdc/sink/mysql_test.go
metrics/grafana/ticdc.json

Solve https://github.com/pingcap/ticdc/issues/685
- Add bucket size to monitor SQL distribution in each MySQL sink worker.
- Add detect conflict duration metric to monitor wait time for each txn due to conflict.
Tests 
- Unit test

mysql-sink: add more performance related metrics

---

cdc/sink/mq.go
cdc/sink/mqProducer/kafka.go
cdc/sink/mqProducer/kafka_test.go
tests/simple/run.sh

Support user to configure `kafka-client-id` in sink-uri
Extract `kafka-client-id` from sink-uri and pass it to KafkaConfig
Tests 
- Unit test
- Support to configure `kafka-client-id` in the mq sink-uri

sink: support to configure kafka-client-id in mq sink-uri

---

cmd/client_changefeed.go
go.mod
go.sum
tests/cli/run.sh

This is the first part of https://github.com/pingcap/ticdc/issues/560
Add a `changefeed update` command in cdc cli
Tests 
- Unit test

cmd: support update changefeed config, in non-online way

---

cdc/sink/codec/canal_test.go
cdc/sink/codec/json_test.go

#709 and fix some tiny bugs which are ignored for this issue.
```go
package main
import (
`reflect`
)
type A struct{}
func (a *A) Foo() {
println("Foo")
}
func main() {
a := &A{}
println(reflect.TypeOf(a).NumMethod()) // 1
a_ := A{}
println(reflect.TypeOf(a_).NumMethod()) // 0
}
```
- Unit test

fix some tiny bugs in canal test cases

---

cdc/http_handler.go
cdc/http_status.go
cdc/model/changefeed.go
cdc/owner.go
cmd/client.go
cmd/client_changefeed.go
cmd/util.go
tests/cli/run.sh

- Fix bug that a paused changefeed can't be removed. item-5 in https://github.com/pingcap/ticdc/issues/542
- Add a `--simple` option in changefeed query command, and output the most common used replication status to users, with more user-friendly output format. part of item-11 in https://github.com/pingcap/ticdc/issues/542
- Make state transition of a changefeed more clearly.
- Expand the feed state, to `normal`, `stopped`, `removed` and `failed`
- `failed` is an internal state, only exists when the owner creates chagnefeed meets error, in this case, the changefeed can't be resumed, users can re-create a new changefeed.
- `normal`, `stopped`, `removed` are published to users, and these states can be transformed as follows. 
| state in column title -> state in row | normal | paused | …

Refine some state transition when handling admin job

---

cmd/client.go
pkg/util/log.go

cdc cli forces to use `warn` log level, when some operation blocks, we need verbose logs for debug.
- Add log-level option to cli command, default use warn
- Enable sarama logger when log level less than `info`
Tests 

Add log-level to cli command, replace sarama logger

---

cdc/http_handler.go
cmd/client.go
cmd/client_changefeed.go
cmd/client_processor.go

Fix item-12 in https://github.com/pingcap/ticdc/issues/542
- Add a summary filed in changefeed list
- Accepts a shorthand letter for some variable name, including `c` is short for `changefeed-id`, `p` is short for `capture-id
Sample output
```
➜  ./cdc cli changefeed list
[
{
"id": "4e24dde6-53c1-40b6-badf-63620e4940dc",
"summary": {
"state": "normal",
"tso": 417886179132964865,
"checkpoint": "2020-07-07 16:07:44.881",
"error": null
}
},
{
"id": "8f0bd661-e3ab-4e25-a8eb-d835c0348a58",
"summary": {
"state": "stopped",
"tso": 417885338318929921,
"checkpoint": "2020-07-07 15:14:17.430",
"error": null
}
}
]
```
Tests 
- Unit test

Add changefeed summary in list command, add some shortcut

---

cdc/sink/mqProducer/kafka.go

Since the values of `Producer.Flush.Frequency`, `Producer.Flush.Bytes` and `Producer.Flush.Messages` are 0, sarama always flushes message as-fast-as-possible 
https://github.com/Shopify/sarama/blob/5933302b8bc4b51c43f1bc2531146d59dc88a91d/produce_set.go#L258-L259
In most cases `Producer.Flush.MaxMessages` will be not used. Besides we can control message size via `Producer.MaxMessageBytes` (https://github.com/Shopify/sarama/blob/master/produce_set.go#L230-L250)
Remove this config
Tests 

remove incorrect kafka parameter

---

cdc/kv/client.go
cdc/processor.go

Some context canceled error should not be logged as error. After this PR the exit log of cdc server looks cleaner.
- change log in gRPC stream recv
- change log in processor update info
Tests 

Remove some unnecessary error log

---

go.mod
go.sum

Fix panic in unit test with go >= 1.14. ref: https://github.com/etcd-io/bbolt/pull/201
```
fatal error: checkptr: unsafe pointer conversion
goroutine 124 [running]:
runtime.throw(0x1dee7a4, 0x23)
/home/tidb/.gvm/gos/go1.14.4/src/runtime/panic.go:1116 +0x72 fp=0xc0001c97a0 sp=0xc0001c9770 pc=0x4678e2
runtime.checkptrAlignment(0xc000116a90, 0x1cd75c0, 0x1)
/home/tidb/.gvm/gos/go1.14.4/src/runtime/checkptr.go:20 +0xc9 fp=0xc0001c97d0 sp=0xc0001c97a0 pc=0x438b99
go.etcd.io/bbolt.(*Bucket).write(0xc0001c9948, 0x0, 0x0, 0x0)
/home/tidb/.gvm/pkgsets/go1.14.4/global/pkg/mod/go.etcd.io/bbolt@v1.3.3/bucket.go:624 +0x15c fp=0xc0001c9838 sp=0xc0001c97d0 pc=0x161b4dc
go.etcd.io/bbolt.(*Bucket).CreateBucket(0xc0001280f8, 0x2c836b0, 0x7, 0x7, 0xc0001c9ba8, 0x16d7096, 0xc000156748) …
```

upgrade go.etcd.io/etcd to fix panic in unit test with go1.14

---

cmd/client_changefeed.go

statistics command will panic if changefeed doesn't exist #767 
Handle the not-exist error.

Fix statistics command panic

---

cdc/sink/mysql.go
pkg/cyclic/mark/mark.go
pkg/cyclic/replication.go
tests/_utils/check_contains
tests/cyclic_ab/run.sh

Add start_timestamp column to mark table to facilitate debugging.
Tests 
Code changes
Side effects
- **Breaking backward compatibility**
- Add start_timestamp column to mark table to facilitate debugging.

cyclic: add start_timestamp to mark tables

---

cdc/puller/file_sorter.go
tests/file_sort/conf/diff_config.toml
tests/file_sort/run.sh

Fix bug found in https://github.com/pingcap/ticdc/issues/754
Use `CRTs-1` as fake resolved ts, where `CRTs` is commit ts of a real event. The root cause is sorted events could have the same commit ts, use `CRTs-1` as resolved ts is safe and eliminates this problem.
Tests 
- Unit test

file-sorter: fix fake resolved ts event breaks CRTs restraint

---

tests/multi_source/main.go

Fix a fatal met in test: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/1748/pipeline
```
[2020-07-28T09:34:15.592Z] [2020/07/28 17:34:15.247 +08:00] [FATAL] [main.go:183] ["unexpected error when executing sql"] [error="Error 1049: database doesn't exist"] [stack="github.com/pingcap/log.Fatal
/go/pkg/mod/github.com/pingcap/log@v0.0.0-20200511115504-543df19646ad/global.go:59
main.dml
/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/tests/multi_source/main.go:183
main.runDDLTest.func2
/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/tests/multi_source/main.go:87"]
```
Ignore this error in test client
Tests 
- Unit test
- Integration …

Fix dml with database not found error in test

---

cdc/sink/mysql.go

The `allow_auto_random_explicit_insert` option detect in TiCDC fails after https://github.com/pingcap/tidb/pull/18896 merged, because 
```
mysql> show global variables like 'allow_auto_random_explicit_insert';
+-----------------------------------+-------+
| Variable_name                     | Value |
+-----------------------------------+-------+
| allow_auto_random_explicit_insert | off   |
+-----------------------------------+-------+
1 row in set (0.01 sec)
mysql> show session variables like 'allow_auto_random_explicit_insert';
+-----------------------------------+-------+
| Variable_name                     | Value |
+-----------------------------------+-------+
| allow_auto_random_explicit_insert | 0     |
+-----------------------------------+-------+
1 row in set (0.01 sec)
```
To …

Fix auto random enable detect

---

cdc/kv/client.go
cdc/kv/store_op.go

Querying CurrentVersion too frequently when resolving lock. #790 
CurrentVersion is now cached and is updated regularly by a separate goroutine.
Tests 
Code changes

perf: optimize get tso frequency

---

cdc/kv/client.go
cdc/puller/puller.go
cdc/sink/black_hole.go
cdc/sink/common/common.go
cdc/sink/metrics.go
cdc/sink/mq.go
cdc/sink/mysql.go
cdc/sink/mysql_test.go
cdc/sink/sink.go
cdc/sink/statistics.go
metrics/grafana/ticdc.json
pkg/regionspan/span.go

* Add a metrics about pending flush rows.
* Add a metrics about MySQL sink txn execution duration.
* Pretty print Span.
Tests 
Side effects
* No release note

cdc: add metrics about pending rows and txn execution duration

---

cdc/sink/mysql.go
tests/sink_hang/conf/diff_config.toml
tests/sink_hang/run.sh

In a test when TiDB cluster is abnormal, ticdc executes DMLs with some errors, but one of goroutine is hang up and blocks the whole sink
```
goroutine 1560236 [IO wait, 205 minutes]:
internal/poll.runtime_pollWait(0x7fa0f1b689c8, 0x72, 0xffffffffffffffff)
runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc010079618, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc010079600, 0xc0113cc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc010079600, 0xc0113cc000, 0x1000, 0x1000, 0xc0254cad80, 0xc010079600, 0xc010079618)
net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00ddea000, 0xc0113cc000, 0x1000, 0x1000, …
```

Fix mysql sink may be blocked by network io wait

---

Makefile
scripts/fix_lib_zstd.sh

- Fix CI warning `cdc.test: Symbol 'stderr' causes overflow in R_X86_64_PC32 relocation`
- Fix build failure with some GCC version, such as with `gcc version 9.3.0 (on Ubuntu 20.04.1 LTS)·
```
/home/apple/.gvm/gos/go1.14.6/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /home/apple/.gvm/pkgsets/go1.14.6/global/pkg/mod/github.com/valyala/gozstd@v1.7.0/libzstd_linux_amd64.a(zdict.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a PDE object; recompile with -fPIE
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```
NOTE: this fix can be removed after we upgrade https://github.com/apache/pulsar-client-go to latest version
Compile `libzstd.a` based on https://github.com/valyala/gozstd#faq …

Fix compatibility of libzstd with different gcc version

---

cdc/changefeed.go
cdc/kv/etcd.go
cdc/owner.go
cdc/processor.go
scripts/jenkins_ci/integration_test_common.groovy

We can update processor local checkpoint ts more frequently.
However based on test, if no DDL is executed, processor checkpoint ts doesn't affect replication latency.
- Fix task status is always flushed in processor, as the new modified revision is not updated correctly.
- Use notify mechanism to trigger the checkpoint flush of a processor, but still keep a 200ms duration restriction.
- Refine some function names
Tests 
- Unit test

Remove checkpoint ts tick and refine task status updater in processor

---

cdc/changefeed.go
cdc/processor.go
cdc/sink/mysql.go
tests/kill_owner_with_ddl/conf/diff_config.toml
tests/kill_owner_with_ddl/run.sh

Fix the bug found in https://github.com/pingcap/ticdc/issues/838
For the case-1:
- task position could be updated after processor is stopped.
For the case-2:
- Owner exits before a DDL is executed, and checkpoint ts of all processors have reached DDL FinishedTs
- When owner restarts, the resolved ts equals to the unfinished DDL and the replication state is not correctly updated to `ChangeFeedWaitToExecDDL`
- The global checkpoint ts will be forwarded, and this DDL will be lost.
- check whether processor is stopped before flushing task position, to fix case-1
- change the condition to `minResolvedTs >= c.ddlJobHistory[0].BinlogInfo.FinishedTS` to fix case-2
Tests 
- Unit test

fix DDL may be lost if owner exits

---

cmd/client_changefeed.go
cmd/util.go
pkg/security/credential.go
tests/cyclic_abc/run.sh

Fix `changefeed list` and `changefeed query` do not work when TLS is enabled.
Tests 
- Fix `changefeed list` and `changefeed query` do not work when TLS is enabled.

cmd: fix cmd TLS usage

---

cdc/entry/mounter.go
cdc/model/schema_storage.go
cdc/sink/mysql.go
cdc/sink/mysql_test.go

Implement https://github.com/pingcap/ticdc/issues/807
1. pass `SchemaStorage` from processor
2. pass table info in each RowChangedEvent
3. pass a stable coumn name list in each RowChangedEvent
Tests 
- Unit test
- Add a batch replace way to optimize download write throughput in MySQL sink.

Use batch replace in mysql sink to increase performance

---

cdc/sink/mysql.go
tests/sink_hang/run.sh

Fix case-3 in https://github.com/pingcap/ticdc/issues/838
The transactions are sent to two sink workers, we must ensure the sink worker with `MySQLSinkHangLongTime` injected is executed before the sink worker with `MySQLSinkExecDMLError` injected returns.
Add a delay in sink worker before injected `MySQLSinkExecDMLError` returns.
Tests 
- Unit test

fix unstable test in sink hang

---

pkg/scheduler/table_number.go
pkg/scheduler/table_number_test.go

When the table count is exactly an integral multiple of capture numbers, the table number based scheduler doesn't make an absolutely even scheduling
such as 4 tables, 2 captures, the scheduling result should be 2, 2
Use float64 to calculate table tableNumberLimiter
Tests 
- Unit test

minor optimization for table number scheduler

---

cdc/http_handler.go
cdc/kv/etcd.go
cdc/kv/etcd_test.go
cdc/model/owner.go
cdc/owner.go
cmd/client.go
cmd/client_changefeed.go
cmd/util.go
tests/cli/run.sh

Fix https://github.com/pingcap/ticdc/issues/858
- add a force option in cdc cli changefeed remove, if `--force` is provided, remove the remaining task position after the changefeed is fully stopped, or if the changefeed is already removed or finished, clear the remaining task position.
- refuse to create a changefeed, if changefeedInfo or job status is remaining in PD
Tests 
- Unit test

support force remove a changefeed, check removed/finished changefeed when creating

---

tests/gc_safepoint/run.sh

fix gc safepoint name, still use query etcd way for gc safepoint, because I found `pd-ctl` doesn't work well in CI. (doesn't known why, the request will be blocked)
use correct gc safepoint key name
Tests 
- Unit test

fix service gc safepoint key name

---

cdc/owner.go
tests/gc_safepoint/run.sh

TiCDC updates service gc safepoint too frequent now, nearly every 10ms
```
[2020/08/23 22:12:43.902 +08:00] [INFO] [grpc_service.go:796] ["update service GC safe point"] [service-id=ticdc] [expire-at=1598278363] [safepoint=418956433904893954]
[2020/08/23 22:12:43.917 +08:00] [INFO] [grpc_service.go:796] ["update service GC safe point"] [service-id=ticdc] [expire-at=1598278363] [safepoint=418956433904893954]
[2020/08/23 22:12:43.927 +08:00] [INFO] [grpc_service.go:796] ["update service GC safe point"] [service-id=ticdc] [expire-at=1598278363] [safepoint=418956433904893954]
[2020/08/23 22:12:43.934 +08:00] [INFO] [grpc_service.go:796] ["update service GC safe point"] [service-id=ticdc] [expire-at=1598278363] [safepoint=418956433904893954]
```
increase gc safepoint update internal to 2s, it …

owner: increase gc safepoint update frequency to 2s

---

tests/_utils/start_tidb_cluster_impl

TiDB implements `clustered index` in 5.0, ref: https://github.com/pingcap/tidb/pull/17044, TiCDC is not compatible with clustered index now
Note: this change will be reverted after TiCDC supports clustered index
Set `@@global.tidb_enable_clustered_index=0` when starting TiDB in integration test
Tests 
- Unit test

tests: disable clustered index in integration test

---

cdc/http_handler.go
cdc/http_status_test.go

Some http API can be served by CDC owner only, fix https://github.com/pingcap/ticdc/issues/891
Return immediately when meeting non leader error
Tests 
- Unit test

api: return immediately when meeting non leader error

---

tests/_utils/start_tidb_cluster_impl
tests/_utils/start_tls_tidb_cluster_impl

#901 only disables clustered index in upstream tidb
Disable clustered index in all TiDBs in integration test
Tests 
- Unit test

tests: disable clustered index in all tidb in integration test

---

cdc/kv/client.go

Fix event entry wrong usage during code refactor
Use correct cacheEntry
Tests 
- Unit test

kv-client: fix entry variable wrong usage

---

cdc/capture.go
cdc/kv/etcd.go
cdc/kv/etcd_test.go
cdc/kv/metrics.go
cdc/owner.go
cdc/owner_test.go
cdc/processor.go
cdc/server.go
cdc/task_test.go
cmd/client.go
cmd/server.go
metrics/grafana/ticdc.json
pkg/etcd/client.go
pkg/etcd/client_test.go

Currently, we use a watch mechanism to update processor/changefeed checkpoint, the update frequency could be 20+/s, which may be too frequent in most scenarios.
Add parameters in cdc server to control owner/processor flush checkpoint interval
Before, with 200ms interval and 500ms interval
After resolved ts check, processor flush interval=100ms, owner flush interval=200ms. **But this has a bug, if both checkpoint ts and resolved ts are not forwarded and new table is dispatched to this processor, replication will be blocked!**. We should fix this.
Current status
Tests 
- Unit test
- Support to control the write frequency of checkpoint flush from cdc server parameter

*/: add pd write frequency control from cdc server parameter

---

cdc/sink/mysql.go
go.mod
go.sum

tidb/parser reverts a change with rfc error, upgrade deps to latest release-4.0. DNM after tidb-tools release-4.0 is updated
upgrade go module
Tests 
- Unit test

go mod: upgrade tidb/parser to latest release-4.0

---

cdc/changefeed.go
cdc/model/owner.go
cdc/processor.go

The following logs are too many when a table is dispatched to processor
```
[2020/09/14 16:25:52.338 +08:00] [INFO] [changefeed.go:746] ["some operation is still unapplied"] [captureID=158cb6fd-e023-4e90-862f-d5af82324a37] [appliedTs=419449261358317578] [status="{\"tables\":{\"45\":{\"start-ts\":419449209232556033,\"mark-table-id\":0},\"47\":{\"start-ts\":419449260481183754,\"mark-table-id\":0},\"49\":{\"start-ts\":419449261358317578,\"mark-table-id\":0}},\"operation\":{\"49\":{\"delete\":false,\"boundary_ts\":419449261358317578,\"done\":false}},\"admin-job-type\":0}"]
```
```
[2020/09/14 17:40:38.656 +08:00] [INFO] [owner.go:306] ["ignore known table"] [tid=49] [table=test.t3] [ts=419450436785274881]
```
- For the `some operation is still unapplied` log, we can extract all logged …

dispatcher: refine table operation log, add status field in table operation

---

cdc/sink/mysql.go
cdc/sink/mysql_test.go
cdc/sink/sink.go

In MySQL sink, insert is translated to REPLACE SQL, update is translated to DELETE + REPLACE SQL
When old value feature is enabled, we can distinguish whether a SQL is update or insert, so we can translate insert to INSERT SQL and update to UPDATE SQL to increase executing performance.
But in some cases, `update` and `insert` is not reentrant, we also need the `safe-mode` mechanism to force write data.
Besides, the more convenient `safe-mode` switch will be implemented in another PR.
- Introduce a new `safe-mode` option in MySQL sink
- The SQL translator behavior, when the old value feature is enabled, is as follows
|                  | insert  | update           |
| ---------------- | ------- | ---------------- |
| in safe mode     | REPLACE | DELETE + REPLACE |
| not in safe mode | …

sink/mysql: support translated to insert SQL if old value enabled

---

cdc/sink/producer/kafka/kafka.go

- There is a possibility that Kafka producer might panic when it is being closed.
- Handle the closure of error channel properly.
Tests 

fix: Kafka producer error handling

---

cdc/model/sink.go
cdc/sink/codec/avro.go
integration/framework/avro_kafka_docker_env.go
integration/framework/docker_compose_op.go
integration/framework/sql_helper.go

- Avro cannot issue correct delete event due to change in the usage of Column and PreColumn in RowChangedEvent.
- Integration test framework could not correctly detect failure to delete.
- Add `HandleKeyColumns` method to `RowChangedEvent` to ease future refactoring.
- Fix Avro deletion.
- Fix integration framework.
Tests 
Code changes

fix: Avro cannot delete

---

cdc/puller/puller.go

delete metrics when close the puller
Tests 
- Unit test

metrics: delete metrics when close the puller

---

cdc/sink/codec/canal.go
cdc/sink/codec/canal_test.go

1. Repeated Canal messages caused by not resetting the state.
2. Panics on deletes caused by nil Columns pointer.
3. Sending empty messages when there's no new data.
4. Defective buffer resizing logic.
1. Reset the packet after building the message. 
2. Check whether Column and PreColumn pointers are nil.
3. Check whether a message is empty.
4. Shrink the packet buffer appropriately.
Tests 
- Integration test **(Pending)**

sink: fix Canal sink bugs

---

cdc/changefeed.go
cdc/kv/etcd.go
cdc/kv/etcd_test.go
cdc/processor.go

Some debug logs are too noisy, remove some debug logs that don't carry more debug information.
- In the `checkUpdateTs` function, the `prevMinCheckpointTs` and `prevMinResolvedTs` are initialized with `targetTs`, so the first time check is always logged, we can remove this log.
- The processor always performs an etcd write operation when `flushTaskPosition` is called and has one line log. The `PutTaskPosition` operation can be optimized to `PutTaskPositionOnChange` operation, which means the processor only writes to etcd when the value of task position is changed (or etcd doesn't have the initialized key value). After this optimization etcd write ops in `flushTaskPosition` decreases from 30 to 2. 
Tests 
- Unit test

changefeed: simplify debug log, put task position only value changes

---

cmd/client.go
cmd/util.go

In a user test, an `Em space` is added after pd addr, which leads the wrong recognization of pd address.
Such as
```
./cdc cli changefeed create --pd=http://127.0.0.1:2379　--sink-uri="mysql://127.0.0.1:3306/"
```
the pd addr will be recognized as
```
http://127.0.0.1:2379　--sink-uri="mysql://127.0.0.1:3306/
```
- Add better error message when meeting pd connect failure
- Correct log level in log util init function.
Tests 
- Unit test

cmd: add pd addr in pd connect failed error message

---

metrics/alertmanager/ticdc.rules.yml

mounter unmarshal alert is too sensitive. It keeps firing while checkpoint ts lag is small.
Tests 
- No release note.

metrics: reduce mounter alerts

---

cdc/processor.go
cdc/sink/mysql.go
cdc/sink/producer/kafka/kafka.go
tests/processor_resolved_ts_fallback/conf/diff_config.toml
tests/processor_resolved_ts_fallback/run.sh

Fix #981 
The global resolved ts could be fallback when a table is rebalanced, so
we should use the local resolved ts of a processor instead of the
received global resolved ts, which is similar to the logic in following codes
https://github.com/pingcap/ticdc/blob/b901c90678bbcce66ae7568a54dcbd137eaded7d/cdc/processor.go#L689-L696
Use the local resolved ts of a processor instead of the received global resolved ts to check the rule that CRTs is larger than `resolved ts`
Tests 
- Unit test

processor: fix incorrect fatal detect in processor

---

cdc/model/sink.go

fix json name typo
use unified key name between json and toml key. `TableName` is not persistent in etcd, so this is a compatible fix
Tests 
- Unit test

model: fix json name typo

---

scripts/jenkins_ci/integration_test_common.groovy

jenkins recommand file size for stash/restore is 5-100MB
> There's not a hard stash size limit, but between 5-100 MB you should probably consider alternatives. Name of a stash. Should be a simple identifier akin to a job name.
Use fileserver to transfer third_party binaries
Tests 
- Unit test

scripts/ci: use fileserver to transfer third_party binaries

---

tests/row_format/data/step1.sql
tests/row_format/data/step2.sql
tests/row_format/data/step3.sql
tests/row_format/data/step4.sql
tests/row_format/run.sh

After global level variable is changed, the existing session doesn't reload this variable.
Re-create a new tidb session after variable `tidb_row_format_version` value is changed.
Tests 
- Unit test

tests: fix session variable is not reload in row format case

---

Makefile

integration test build binary doesn't contain ldflags, which leads to some constant variable missing, such as `RELEASE_VERSION`
pass ldflags in integration test build
Tests 
- Unit test

makefile: pass ldflags in integration test build

---

cdc/processor.go

After investigating the https://github.com/pingcap/ticdc/issues/993, found key `/tidb/cdc/task/status/<capture-id>/<changefeed-id>` is always updated when processor calls `flushTaskStatusAndPosition`
This bug happens since v4.0.5
The fix is straightforward, check `newModRevision` returned by `AtomicPutTaskStatus`, `newModRevision=0` means status is not updated, we don't update the mod revision cache.
Tests 
- Unit test
- Fix a bug that processor always flushes task status to the etcd because of incorrect mod revision cache.

processor: fix task status is always flushed because of incorrect mod revision cache

---

cdc/changefeed.go

Fix https://github.com/pingcap/ticdc/issues/1016
Add a flag to prevent duplicated syncpoint persistent
Tests 
- Unit test

changefeed: record only once if both ticker and ddl trigger syncpoint

---

cdc/sink/mysql.go

Duplicated syncpoint could happen in following scenarios
- ticker and ddl trigger at the same time
- ddl trigger happens first, and in the next round ticker happens
- owner records by ticker once, but crashes, another owner meets the same syncpoint
For each changefeed and primary_ts pair, keep the first secondary_ts is enough, so change the syncpoint SQL to `insert ignore` pattern.
Tests 
- Unit test

sink: ignore duplicated syncpoint

---

cdc/sink/mysql.go

If replication normally with mysql sink, there could be no log for a long time, which is curious.
Add periodic statistics status log in MySQL sink
Tests 
- Unit test

sink/mysql: fix statistics print status missing in MySQL sink

---

cdc/sink/mysql.go
cdc/sink/mysql_test.go
kafka_consumer/main.go

In some Cloud MySQL service, only timezone SYSTEM and CST is available, we need to allow user to pass a string represented timezone
- cdc server keeps using the `timezone` parameter that is configured in `cdc server` command.
- The `time_zone` query string in sink DSN will be determined by the `time-zone` parameter in sink uri and cdc server's timezone. The decision sequence is as follows:
1. if `time-zone` is provided in sink uri, but value is empty, the downstream sink DSN will not contain any `time_zone` parameter.
2. if `time-zone` is provided in sink uri with any value, the downstream sink DSN will contain the same value in `time_zone`
3. if `time-zone` is not provided in sink uri, query context for timezone and use timezone string value in DSN.
Tests 
- Unit test …

sink/mysql: support to pass a timezone dsn parameter

---

cdc/changefeed.go
cdc/kv/client.go
cdc/owner.go
cdc/processor.go
cdc/server.go
pkg/notify/notify.go
pkg/util/ctx.go

fix 6 goroutine leaks in TiCDC fix #1025
a goroutine leak in tidb client is found by this test pingcap/tidb#20654
before this PR:
after this PR:
- Fix many goroutine leaks.

*: fix many goroutine leak

---

.github/workflows/check_and_build.yml

Try to fix lint CI in github action. ref: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
detail error logs: https://github.com/pingcap/ticdc/commit/da768202b97ecdbdeccf42fc076ae2bc4ceaf217/checks/1410676409/logs
```
2020-11-17T07:33:08.7069919Z Finding needed golangci-lint version...
2020-11-17T07:33:08.7071210Z Setup go stable version spec 1
2020-11-17T07:33:08.7235182Z ##[error]Unable to process command '::set-env name=GOROOT::/opt/hostedtoolcache/go/1.15.4/x64' successfully.
2020-11-17T07:33:08.7264613Z ##[error]The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: …
```

ci/action: upgrade golangci-lint-action to v2

---

kafka_consumer/main.go

kafka_consumer: fix wrong timezone when 'TZ' env is not set and downstream is mysql
Improve robustness.
[*: fix wrong timezone when env `TZ` is not set #512](https://github.com/pingcap/ticdc/pull/512) fix wrong timezone in cdc, but *kafka_consumer* demo still have this problem, see [kafka_consumer wrong timezone when no parameter ‘--timezone’ and env ‘TZ’ is not set #1082](https://github.com/pingcap/ticdc/issues/1082).
This pr load local timezone by calling util.GetTimezone instead of use time.Local
Tests 
```shell
./kafka_consumer --upstream-uri="kafka://127.0.0.1:9092/cdc-test?kafka-version=2.4.0&partition-num=6&max-message-bytes=67108864&replication-factor=1" --downstream-uri="mysql://root:123456@127.0.0.1:3306/"
```
> …

kafka_consumer: fix wrong timezone when 'TZ' env is not set and downstream is mysql

---

cdc/owner.go
cdc/processor.go
pkg/util/ctx.go
pkg/util/ctx_test.go

[#1102](https://github.com/pingcap/ticdc/issues/1102)
Return an **error** for `util.KVStorageFromCtx`, and add some unit test functions in `ctx_text.go`.
Tests 
- Unit test
Code changes
Side effects

*:some helper functions add error return value and add some unit tests in ctx_test.go

---

cdc/kv/client.go
cdc/kv/client_test.go
cdc/kv/testing.go
cdc/model/kv.go
cdc/owner_operator.go
cdc/processor.go
cdc/puller/puller.go
cdc/puller/puller_test.go
pkg/util/ctx_test.go

Add unit tests for cdc/puller/puller.go
- Extract kv client into a new interface `CDCKVClient`
- Add a simple injected mock puller, which can be injected with `RegionFeedEvent`
Tests 
- Unit test

tests: add unit tests for cdc/puller/puller.go

---

Makefile

Fix `./scripts/add-leaktest.sh: 29: ./scripts/add-leaktest.sh: goimports: not found`
install `golang.org/x/tools/cmd/goimports` before running add-leaktest.sh
Tests 
- Unit test

Makefile: fix goimports not found in leak test check

---

cdc/sink/mysql.go
cdc/sink/mysql_test.go
pkg/cyclic/replication.go
pkg/cyclic/replication_test.go

Add unit tests for MySQL sink
- Fix a bug that cyclic replication doesn't relax SQL mode.
- use sql mock to test MySQL sink
Tests 
- Unit test

tests: add unit tests for mysql sink

---

cdc/owner.go
cdc/owner_test.go

Fix https://github.com/pingcap/ticdc/issues/1158
- TiCDC should clean the metadata of a changefeed as thoroughly as possible when removing a changefeed, but it is still possible to leave redundant metadata.
- Owner should choose whether to filter metadata when using it or clean up redundant data regularly, this PR chooses the second way.
Owner clean up the stale tasks at the beginning of each run round.
Tests 
- Unit test
- Fix a bug that outdated metadata could cause the newly created changefeed abnormal.

owner: fix owner doesn't clean up stale tasks

---

cdc/model/owner.go
cdc/processor.go

Fix https://github.com/pingcap/ticdc/issues/1188. This is a hotfix for current codebase, we should process with the `Dirty` field of task status carefully.
change flush check condition
Tests 
- Unit test
- hack puller `p.tsTracker.Frontier()` to force no forward to simulate long time incremental scan.
- watch the task status key version in etcd doesn't change.

processor: fix task status flushed too many before table is initialized

---

tests/common_1/run.sh
tests/ddl_reentrant/run.sh

https://github.com/pingcap/tidb/pull/21533 disables multi schema change feature by default, which leads to some tests failure caused by `ERROR 8200 (HY000) at line 12: Unsupported multi schema change`
Turn on the `tidb_enable_change_multi_schema` switch in tests where multi schema change happens
Note cherry-pick just wants to keep the test code same as far as possible
Tests 
- Unit test

tests: turn on the tidb_enable_change_multi_schema switch in some tests

---

cdc/kv/client.go

In an internal test, TiCDC can't recover from a TiKV crash or recovery.
We meet endless following errors after killing a TiKV, where `store=172.16.4.197:21160` is the killed TiKV server.
```
[2020/12/10 17:05:01.000 +08:00] [WARN] [client.go:723] ["get grpc stream client failed"] [regionID=11544] [requestID=7814] [storeID=7] [error="[CDC:ErrTiKVEventFeed]rpc error: code = Canceled desc = grpc: the client connection is closing"]
[2020/12/10 17:05:01.000 +08:00] [INFO] [region_cache.go:600] ["mark store's regions need be refill"] [store=172.16.4.197:21160]
[2020/12/10 17:05:01.000 +08:00] [INFO] [region_cache.go:414] ["invalidate current region, because others failed on same store"] [region=12557] [store=172.16.4.197:21160]
[2020/12/10 17:05:01.000 +08:00] [INFO] [client.go:656] ["cannot …
```

kv/client: fix gRPC connection pool, don't close conn when meeting error

---

go.mod
go.sum

update tidb dependence for release-4.0
Tests 
- Unit test

*: update tidb dependence for release-4.0

---

cdc/owner.go
cdc/processor.go
tests/processor_stop_delay/conf/diff_config.toml
tests/processor_stop_delay/run.sh

Fix https://github.com/pingcap/ticdc/issues/1211
Root cause: There exists race condition when CDC owner creates a new changefeed (which will assign new task status) and a stale processor stops (which is responsible for replicating the same changefeed). The latest task status written by owner could be deleted by a stale processor.
This PR changes the update of `task status` to a linearizable way, which means a paused/removed task status can be deleted, but cannot be put.
TODO: We should summary the schedule model of CDC owner and processor to make it works in a provable automaton.
Tests 
- Unit test
- Fix a bug that some tables' row change could be lost when the network between CDC and PD has jitter, and there exist changefeed resume operation at the same time.

owner: wait all task metadata cleaned before creating new changefeed

---

cdc/capture.go
cdc/owner_test.go
cdc/processor.go
cdc/server.go

Using the global singleton for pd client and tikv client, and fix pd client freeze
The modification of this PR bypasses the bug about pd client freeze by using a global singleton for pd client
Tests 
- Unit test
- Fix the bug of possible TiCDC server freeze

*: Using the global singleton for pd client and tikv client, and fix pd client freeze

---

cdc/capture.go
tests/capture_session_done_during_task/conf/diff_config.toml
tests/capture_session_done_during_task/run.sh

Fix https://github.com/pingcap/ticdc/issues/1170
If a capture's etcd session is disconnected, it should suicide and recover asap. However we have a selection of two channels, one is checking `etcd session done` and the other one is `handle task event`.
When an error happens after handling one task event, check whether the etcd session is already invalid, if it is disconnected, just ignore the error and suicide and recover the capture internal, instead of the process level exit.
Tests 
- Unit test
- Fix a bug that CDC could exit unexpected when etcd session is disconnected

cpature: fix session done is not considered during handling task event

---

cdc/owner.go

Fix for a memory accumulated issue in owner
https://github.com/pingcap/ticdc/blob/eed57c94491fd140f0a8a0528acc574bc542bb0b/cdc/owner.go#L1024-L1039
The output channel consume speed (which relays on how often L1035 can be run) may be much slower than the etcd key update frequency, which will lead to data accumulated in etcd watch client
Ignore position update event if output channel is full, it is safe enough as the owner has a builtin ticker to trigger `o.run`
**NOTE: this is a release-4.0 quick fix, I will update master/release-5.0 and add test cases later**
Tests 
- Unit test
- Manual test (add detailed scripts or steps below)  (**Have tested in an internal test cluster**)
- setup a ticdc cluster, create one or more changefeeds
- running cdc for 10mins, get memory …

owner: fix memory accumulated when owner consume etcd update slow

---

cdc/kv/client.go
cdc/kv/client_test.go
cdc/model/kv.go
cdc/model/kv_test.go

Add more unit tests in kv client
- Fix a minor bug that `requestID` increased twice each time when creating a new `eventFeedSession`
- Add test cases covering event error handling
- Add test cases covering KV event processing
Tests 
- Unit test

tests: add more unit tests in kv client

---

cdc/capture.go
cdc/capture_test.go
cdc/processor.go
pkg/etcd/client.go
pkg/etcd/client_test.go

Fix https://github.com/pingcap/ticdc/issues/1234
This is part 1 of #1234 
Tests 
- Unit test
- Fix a bug that cdc server could exit unexpected when meeting ErrTaskStatusNotExists and the capture session is disconnected at the same time.

capture: fix incorrect session aliveness detection

---

scripts/jenkins_ci/integration_test_common.groovy
tests/clustered_index/run.sh

Nightly tiflash will meet following error in the integration test
```
[FATAL] [server.rs:683] ["failed to start node: Grpc(RpcFailure(RpcStatus { status: 2-UNKNOWN, details: Some(\"version should compatible with version  5.0.0-alpha, got 4.1.0-rc-43-g54f66c524\") }))"]
```
- Change default branch in CI to `release-5.0-rc` for TiDB/TiKV/PD/TiFlash
- Enable specific tiflash branch in CI
`master` branch and `release-4.0` branch will be picked manually
Tests 
- Unit test

CI: enable specific tiflash branch in CI

---

scripts/jenkins_ci/integration_test_common.groovy

tiflash download url is not the same as TiDB/PD/TiKV
- Support both configure `make integration_test tiflash=release-5.0-rc`
- And `release_test__tiflash_commit` parameter in release test
Tests 
- Unit test

CI: fix tiflash parameter

---

cdc/owner.go
cdc/owner_test.go

Fix https://github.com/pingcap/ticdc/issues/1268, since #1268 has been merged into `release-4.0` before `4.0.10` is released, this PR needs to be shipped in `4.0.10` too.
No release since this is a bug fix in non-release version
Add a flag to record whether capture information is initialized in owner.
Tests 
- Unit test

owner: fix cleanup stale tasks before capture info is constructed

---

cdc/sink/mysql.go
cdc/sink/mysql_test.go

Fix bug in #1261 & #1275
- Rollback txn if txn execute with failure, to fix #1275 
- Add readTimeout/writeTimeout/timeout parameter in all MySQL dsns to fix #1261 
- Fix another bug that resource is not cleared if get db connection with error
- Add unit test cases to verify the three bug fixes.
Besides, this PR doesn't introduce any timeout context to control database operation, since at current stage, TiCDC doesn't need to have an accurate running time limit for database operation.
Tests 
- Unit test
- add `read-timeout`, `write-timeout` and `timeout` in sink uri parameters 
- Fix a bug that MySQL connection is not recycled when some transactions executed with failure.
- Fix …

sink/mysql: rollback txn to recycle db conn, refine timeout param in db conn

---

cdc/changefeed.go
cdc/owner.go
tests/changefeed_error/run.sh

- Owner DDL error messages are not visible to the user.
- Add error details to the AdminJob.
Tests 
- Expose owner DDL errors messages to the user

owner: add error message for owner ddl errors

---

scripts/jenkins_ci/integration_test_common.groovy

refine ci script to make downloading logs easier
Tests 

ci: refine ci script to make downloading logs easier

---

cdc/sink/codec/json.go
cdc/sink/codec/json_test.go
cdc/sink/mq_test.go
cdc/sink/producer/pulsar/producer.go

- Lack of unit tests for the open protocol parameters `max-message-bytes` and `max-batch-size`.
- Added unit tests for `max-message-bytes` and `max-batch-size`.
Tests 
- Unit test
Code changes

sink: Encoder configuration unit tests

---

tests/run.sh

Reduce disk usage in the integration test, since after https://github.com/tikv/tikv/pull/9497 the minimum TiKV reverse space will be 5G in CI environment
cleanup test binaries and data, preserve logs before each case starts
Tests 
- Unit test

tests: cleanup binaries and cluster data before each run

---

cdc/processor.go

fix race when exit the processor
```
==================
WARNING: DATA RACE
Write at 0x00c0007ee118 by goroutine 286:
github.com/pingcap/ticdc/cdc.runProcessor.func1()
/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/processor.go:1213 +0x8df
Previous read at 0x00c0007ee118 by goroutine 266:
encoding/json.ptrEncoder.encode()
/usr/local/go/src/reflect/value.go:1065 +0x131
encoding/json.ptrEncoder.encode-fm()
/usr/local/go/src/encoding/json/encode.go:805 +0x7b
encoding/json.structEncoder.encode()
/usr/local/go/src/encoding/json/encode.go:664 +0x40d
encoding/json.structEncoder.encode-fm()
/usr/local/go/src/encoding/json/encode.go:635 +0xa0
encoding/json.ptrEncoder.encode()
/usr/local/go/src/encoding/json/encode.go:810 +0xfc …
```

processor: fix race when exit the processor

---

metrics/grafana/ticdc.json

Many users(come from DBaaS、operator、tiup) monitor multiple TiDB clusters in one Grafana, this PR make Grafana dashboards support multiple clusters and not affect single cluster usage. Cluster variable is hidden by default.
- add a tidb_cluster label in all expr
- add cluster variable in Grafana templating
How it Works:
load it to your Grafana :))
Single Cluster:
No change
Multiple Cluster:
Construct a label that can uniquely identify the cluster. in tidb_operator, you can use {namespace}-{cluster_name} as your {tidb_cluster} variable.
add this configuration to your prometheus config
```
relabel_configs:
- source_labels:
- namespace
- name
separator: "-"
target_label: tidb_cluster
```
Tests 
- No code
Side effects
- No effects
- https://github.com/pingcap/tidb/pull/22503
- …

metrics: grafana dashboards support multiple cluster

---

metrics/grafana/ticdc.json

The latest version of tidb-operator will use the instance name as the cluster label. The previous expression uses the cluster label got the value of the tidb_cluster variable. It will cause Grafana can not to display the data.
Tests 
- No code
Side effects
- No effects

metrics: use tidb_cluster label get variable values

---

go.mod
go.sum

Fix build failure in darwin/freebsd, related to https://github.com/shirou/gopsutil/issues/853, https://github.com/shirou/gopsutil/pull/958. `master` branch is ok
```
[2021-01-30T03:02:49.692Z] + make build
[2021-01-30T03:02:49.692Z] CGO_ENABLED=0 GO111MODULE=on go build  -trimpath  -ldflags '-X "github.com/pingcap/ticdc/pkg/version.ReleaseVersion=v4.0.11" -X "github.com/pingcap/ticdc/pkg/version.BuildTS=2021-01-30 03:02:49" -X "github.com/pingcap/ticdc/pkg/version.GitHash=f9ecdb2b448419d0770b44c579ef96c9d58bcac7" -X "github.com/pingcap/ticdc/pkg/version.GitBranch=heads/refs/tags/v4.0.11" -X "github.com/pingcap/ticdc/pkg/version.GoVersion=go version go1.13.4 darwin/amd64"' -o bin/cdc ./main.go
[2021-01-30T03:03:46.787Z] # github.com/shirou/gopsutil/disk
[2021-01-30T03:03:46.787Z] …
```

go mod: add indirect version of shirou/gopsutil to fix freebsd build

---

.github/workflows/check_and_build.yml

Add CI job for building TiCDC on both Ubuntu and macOS.
Tests 
- Unit test

ci: build on both ubuntu and macOS

---

cdc/sink/statistics.go

related to #1392 
Statistics is **changefeed independent**, it works more like a sink keepalive sign.
If TiCDC supports to replicate thousands of changefeeds in the future, the statistic way should be optimized. But currently, it is all right to keep the periodic statistics
Increase sink statistics interval to `10 minutes`, which will not be logged too much.
Tests 
- Unit test

sink: increase statistics interval

---

cdc/sink/manager.go

fix the memory leak in sink manager, this bug is import by #1247 , fix #1398
https://github.com/pingcap/ticdc/blob/6febbae2ec0425fcad6ad74a0644ec595ccc0189/cdc/sink/manager.go#L149
- The blue squares represent the space referenced by `t.buffer`
- The yellow squares represent space that has been discarded by the `t.buffer`
- All squares that are not white hold a reference of `RowChangeEvnet`
The yellow squares is unreachable but can't be GC, because the `b.buffer` reference the `array` and the `array` include the yellow squares, the GO GC can't reclaim this space.
Tests 
- Unit test

fix the memory leak in sink manager (#1401)

---

cdc/owner.go

If owner transfers, the metric `ticdc_owner_checkpoint_ts_lag` is still kept in the old owner, it is safe to remove them since new owner will maintain these metrics.
If we don't remove the outdated metric, we will see two values for the same metric, where the `max` operator will give an unexpected result in Grafana
cleanup checkpoint lag metric when owner exits
Tests 
- Unit test

owner: cleanup checkpoint lag metric when owner exits

---

cdc/sink/manager.go

fix the memory leak in sink manager, this bug is import by #1247 
https://github.com/pingcap/ticdc/blob/6febbae2ec0425fcad6ad74a0644ec595ccc0189/cdc/sink/manager.go#L149
- The blue squares represent the space referenced by `t.buffer`
- The yellow squares represent space that has been discarded by the `t.buffer`
- All squares that are not white hold a reference of `RowChangeEvnet`
The yellow squares is unreachable but can't be GC, because the `b.buffer` reference the `array` and the `array` include the yellow squares, the GO GC can't reclaim this space.
Tests 
- Unit test

sink: fix the memory leak in sink manager

---

cdc/sink/mysql.go
cdc/sink/mysql_test.go

Fix #1406 
Create receiver when creating the MySQL sink, it doesn't affect the normal workflow of MySQL sink.
Tests 
- Unit test

sink/mysql: fix confused error log when creating new changefeed

---

Makefile
scripts/fix_lib_zstd.sh

- add a makefile command: `build-failpoint`, which can help us to build a binary with failpoint-enabled
- refine `fix_lib_zstd.sh`: change the source code of pulsar client to make sure `github.com/valyala/gozstd` will never be built
Tests 
- No code

make: add build-failpoint command and fix failpoint build

---

cdc/kv/client.go
cdc/kv/client_test.go
cdc/puller/puller.go
cdc/puller/puller_test.go

Fix duplicated DDL output from puller.
DDL puller watches two region range, [mDDLJobListl, mDDLJobListm) and [mDDLJobAddIdxListl, mDDLJobAddIdxListm), two ranges belong to the same region. If we filter region-uncover event in puller, we will get duplicated DDL events.
In most cases, regions should not be overlapped, such as each table owns one or more independent regions. However DDL update subscription is a particular case.
There is no bug exposed to user, so we don't need to update release note.
Filter key overflow region in kv-client before sending to the puller. The CPU cost for checking region coverage is almost same between checking in kv-client and in puller, while check in kv-client can save some time for event entry processing and channel send operation.
Tests 
- Unit test
- …

kv-client: filter key overflow region before sending to puller

---

errors.toml
pkg/errors/errors.go
pkg/etcd/client.go
pkg/orchestrator/etcd_worker.go
pkg/orchestrator/etcd_worker_test.go
pkg/orchestrator/jsonstate/json_reactor_state_test.go
testing_utils/cdc_state_checker/cdc_monitor.go

some features and bugfix for etcd worker:
- make sure the pending patches will be committed when reactor returns an ErrReactorFinished
- support update the same key multiple times in one tick
- add a beautiful debug info when commit an etcd txn
- exit the main loop when etcd session is done
Tests 
- Unit test

etcd worker: some features and bugfix for etcd worker

---

cdc/sink/common/common.go
pkg/pipeline/pipeline.go
pkg/pipeline/pipeline_test.go
scripts/jenkins_ci/integration_test_common.groovy

- fix panic message could be ignore when pipeline is exiting and a node is in panic.
Tests 
- Unit test

pipeline: fix panic message could be ignore when pipeline is exiting

---

.github/workflows/check_and_build.yml
.github/workflows/integration.yml

`make check` failed with go1.16, ref: https://github.com/pingcap/ticdc/runs/1961364142
another fix related to #1444
change to specific go version in github action, if using the `^x.y.z` way, github action will use a newer go version comparing to `x.y.z` if possible.
Tests 
- Unit test

github-action: use specific go version

---

cdc/kv/client.go
cdc/kv/client_test.go
cdc/kv/client_v2.go
cdc/kv/region_worker.go
cdc/kv/resolvedts_heap.go
cdc/kv/resolvedts_heap_test.go
pkg/regionspan/span.go
pkg/regionspan/span_test.go

part 2 of #1393, please review this PR after #1397 is merged
- Add a heap to manage region resolved ts, so we don't need to iterate each region every time, and this can reduce lock contention for region state.
- Use a channel to pass resolved ts update event, so resolved ts update will not block event processing
Tests 
- Unit test

kv-client: add resolved ts heap for quick resolve lock

---

Makefile
cdc/capture.go
cdc/capture_test.go
cdc/http_status.go
cdc/metrics.go
cdc/owner.go
cdc/processor.go
cdc/processor/pipeline/sink.go
cdc/processor/pipeline/sink_test.go
cdc/processor/pipeline/table.go
cdc/processor/processor.go
cdc/processor_test.go
cdc/server.go
cdc/sink/mysql.go
cdc/task_test.go
pkg/config/config.go
pkg/orchestrator/etcd_worker.go
tests/capture_session_done_during_task/run.sh
tests/changefeed_auto_stop/run.sh
tests/cli/run.sh
tests/cyclic_ab/run.sh
tests/cyclic_abc/run.sh
tests/ddl_puller_lag/run.sh
tests/processor_panic/run.sh
tests/processor_stop_delay/run.sh

cherry-pick #1187 to release-4.0
- switch on the new processor
- add a flag `config.NewReplicaImpl` to enable the new processor
- this is the last pr in refactor processor
- fix a bug in the sink node of the table pipeline

processor: switch on the new processor, refactor processor part five (#1187)

---

cdc/kv/region_worker.go
cdc/kv/region_worker_test.go

part 3 of #1393, please review this PR after #1426 is merged
- In write less, read more scenario, `sync.Map` is faster than RWMutex and Mutex. Note this is concluded from some benchmarks, such as https://github.com/golang/go/issues/17973, https://www.jianshu.com/p/cffffa914381, but maybe not quite suitable for our scene, we need more tests for this point, the most important thing here is to simulate the real world workload.
- Separate into multiple `sync.Map` can accelerate map access
- Use multiple `sync.Map`s for regionFeedState get/put operation.
- The bucket size of `sync.Map` pool is determined by cpu number, min threshold, and max threshold
Tests 
- Unit test

kv-client: use multiple sync.Map to reduce lock contention

---

cdc/kv/client.go
cdc/kv/client_bench_test.go
cdc/kv/client_mock_test.go
cdc/kv/client_test.go

Benchmark for kv client. part of #1393. This PR is based on #1439
Besides we observed the performance of clientv1 decreases when CPU cores increase, while the clientv2 behaves better, this is as expected, which is described in #1439
TODO: currently kv client test still uses the deprecated `mocktikv` module, and the region management is not efficient in mocktikv, if we test with more than 100k regions, the current test framework can't behavior normally. In the future we need to refactor better test framework for kv client with the help of `unistore`. There is still a long way to go.
```
➜  go test -test.bench="BenchmarkResolvedTs" -v client_bench_test.go client_mock_test.go $(find . -name \*.go|grep -v test.go)
goos: linux
goarch: amd64
BenchmarkResolvedTsClientV1 …
```

kv-client: add benchmark for kv client

---

cdc/kv/client.go
cdc/kv/client_test.go
cdc/kv/client_v2.go
cdc/kv/region_worker.go

Part fix #1457 
The root cause is `onRegionFail` of a single region could be called concurrently and more than once. This PR fixed a bug in client v2 (not in client v1)
- After this fix, there exists an unresolved scenario, where a region failed and region id changed, which means stale region state information could be remained in states management (Both happens in client v2 and client v1)
- #1457 still needs investigation, since client v1 can also panic
Use the stopped property to prevent duplicated call of `onRegionFail`
Tests 
- Unit test

kv-client: fix reentrant onRegionFail causes duplicated range unlock

---

cdc/sink/cdclog/utils.go

Signed-off-by: disksing <i@disksing.com>
There is linter warning about 'capture variable in loop'.
Use correct variable in goroutine.
Tests 
- Unit test

cdclog: fix lint warning

---

cmd/client_changefeed.go
cmd/cmd_test.go
cmd/util.go

Add check described in https://github.com/pingcap/ticdc/issues/1150, TODO list item 1
- The check is enabled when
- create a new changefeed, comparing `start-ts` with current tso.
- or resume a changefeed, comparing changefeed `checkpoint-ts` with current tso.
- The threshold is **1 day**
Tests 
- Unit test
- Add double confirm when creating or resuming changefeed with `start-ts` or `checkpoint-ts` 1 day before current ts.

cmd: check changefeed start-ts when creating or resuming

---

cdc/entry/mounter.go

before https://github.com/pingcap/tidb/pull/23092, the Datum of a BLOB/TEXT column is bytes type.
after https://github.com/pingcap/tidb/pull/23092, the Datum of a BLOB/TEXT column is string type.
so we need to convert string to bytes to keep compatibility 
Tests 
- Unit test

mounter: fix a compatibility issue after tidb#23092

---

cdc/kv/client.go
cdc/kv/client_test.go

Fix bug described in https://github.com/pingcap/ticdc/issues/1457, for kv client V1
The error case is as follows
1. kv client establishes two regions request, naming region-1, region-2, they
belong to the same TiKV store.
2. The region-1 is firstly established, yet region-2 has some delay after its
region state is inserted into `pendingRegions`
3. At this time the TiKV store crashes and `stream.Recv` returns error. In the
defer function of `receiveFromStream`, all pending regions will be cleaned
up, which means the region lock will be unlocked once for these regions.
4. In step-2, the region-2 continues to run, it can't get store stream which
has been deleted in step-3, so it will create new stream but fails because
of unstable TiKV store, at this point, the kv client should handle with …

kv/client: fix panic caused by reentrant unlock pending region

---

cdc/kv/client.go
pkg/regionspan/region_range_lock.go
pkg/regionspan/region_range_lock_test.go

Fix region lock blocked if the kv client has been canceled and some of the regions are not unlocked.
Add context cancel check in region range lock
Tests 
- Unit test
- Fix lock range may block when context is cancelled in kv client

kv/client: fix lock range may block when context is cancelled

---

cdc/processor.go
tests/changefeed_auto_stop/run.sh
tests/processor_stop_delay_2/conf/diff_config.toml
tests/processor_stop_delay_2/run.sh

fix #1546, this bug is only exist in old processor
Tests 
- Unit test
- processor: fix the bug of untimely release of resources when stopping a processor

processor: fix a concurrency issues and goroutine leak when processor stopped

---

cdc/metrics_owner.go
cdc/owner.go
metrics/grafana/ticdc.json

part 2 of https://github.com/pingcap/ticdc/issues/1533
Add table count in metric, with labels of `changefeed-id`, `capture-addr` and `type`
Tests 
- Unit test

metrics: add owner in memory table count metrics

---

metrics/grafana/ticdc.json

Previously we added some metrics for old value in tikv.
Add panels for those metrics.
Tests 
- metrics/grafana: add more panels for old value

metrics/grafana: add more panels for old value

---

cdc/puller/sorter/heap_sorter.go
cdc/puller/sorter/merger.go
cdc/puller/sorter/merger_test.go
cdc/puller/sorter/sorter_test.go
cdc/puller/sorter/unified_sorter.go
errors.toml
pkg/errors/errors.go

- Unified Sorter recycles temp files prematurely, causing file corruption.
- Added a mechanism to cancel asynchronous IO operations.
Tests 
- Unit test
Side effects

sorter: fix Unified Sorter resource release

---

cdc/kv/client.go
cdc/kv/client_test.go

Fix ErrNoPendingRegion found in test
This error is caused by the following scenario
1. Two regions, naming region-1 and region-2, they belong to the same TiKV store
2. Region-1 is handled, and creates a new TiKV stream
3. Region-2 is dispatched, and in old logic, it will be inserted into `pendingRegions` first.
4. `stream.Recv` meets error, and the whole regions belonged to this store will be re-established. The pending region will be cleaned up, region-2 included
5. The step-3 continues, finds no TiKV stream, which has been deleted in step-4, it creates a new one and establishes request for region-2
6. New event of region-2 is received, but region-2 is no longer in `pendingRegions`
The root cause is the map of `pending regions` are shared in two goroutines and the access boundary is not …

kv/client: fix ErrNoPendingRegion because of shared map operation

---

cdc/kv/client.go
cdc/processor.go
cdc/puller/puller.go
cdc/puller/sorter/unified_sorter.go

Avoiding OOM problems
block sorter output channel when a table's resolved ts is far greater than checkpoint ts to avoid existing too many events in the buffer.
Tests 
- Unit test
- Support a flow controler to avoid cdc server OOM

processor: flow control for controlling sorter output speed

---

cmd/client_changefeed.go
tests/cli/run.sh

Fix a new bug introduced by #1554
- `--pd` parameter should be ignored
- other unsupported parameter doesn't panic, log a warnning
Tests 
- Unit test

cmd: fix pd parameter in update config

---

cdc/kv/client.go
cdc/kv/client_test.go
cdc/kv/client_v2.go
cdc/kv/region_worker.go

Fix bug-1.3 in #1633
This is also another bug that can trigger `"received an event but neither pending region nor running region was found`
```
➜  go test -count=1 -v --tags leak -check.f TestStreamRecvWithErrorIOEOF
=== RUN   Test
[2021/04/12 11:18:38.114 +08:00] [INFO] [client.go:355] ["get clusterID"] [id=1]
[2021/04/12 11:18:38.116 +08:00] [INFO] [region_range_lock.go:218] ["range locked"] [lockID=1] [regionID=3] [startKey=61] [endKey=62] [checkpointTs=100]
[2021/04/12 11:18:38.116 +08:00] [INFO] [client.go:776] ["creating new stream to store to send request"] [regionID=3] [requestID=2] [storeID=1] [addr=127.0.0.1:36297]
[2021/04/12 11:18:38.119 +08:00] [INFO] [client.go:822] ["start new request"] [request="{\"header\":{\"cluster_id\":1},\"region_id\":3,\"checkpoint_ts\":100,\"start_ke …
```

kv/client: fix the error handling for io.EOF may miss region reconnect

---

pkg/pipeline/pipeline_test.go

Fix unstable unit test found in https://github.com/pingcap/ticdc/issues/1501#issuecomment-812846556
```
[2021-04-02T16:20:07.344Z] [2021/04/03 00:17:07.593 +08:00] [ERROR] [pipeline.go:96] ["found error when running the node"] [name="error node"] [error="error node throw an error, index: 3"] [errorVerbose="error node throw an error, index: 3\ngithub.com/pingcap/ticdc/pkg/pipeline.(*errorNode).Receive\n\t/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/pkg/pipeline/pipeline_test.go:197\ngithub.com/pingcap/ticdc/pkg/pipeline.(*nodeRunner).run\n\t/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/pkg/pipeline/runner.go:60\ngithub.com/pingcap/ticdc/pkg/pipeline.(*Pipeline).driveRunner\n\t/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/gith …
```

pipeline: fix unstable unit test

---

cdc/kv/client.go
cdc/kv/client_test.go
cdc/kv/client_v2.go

See https://github.com/pingcap/ticdc/pull/1569
See https://github.com/pingcap/ticdc/pull/1569
Tests 
- Unit test
- Fix replication may be interrupted because of region operation conflict in kv client

kvclient: port no pending region fix to master branch

---

cdc/sink/mysql.go
cdc/sink/mysql_test.go

Fix #1585 
- Set session variable `explicit_defaults_for_timestamp` to `ON` in MySQL sink, which will keep the same behavior between upstream TiDB and downstream MySQL 5.7.
- Note only set this session variable when the value `explicit_defaults_for_timestamp`  in downstream is `OFF`, because in TiDB variable `explicit_defaults_for_timestamp` is readonly.
Tests 
- Unit test
- Set session variable `explicit_defaults_for_timestamp` to `ON` to make downstream MySQL5.7 keeps the same behavior with upstream TiDB.

sink/mysql: explicit_defaults_for_timestamp compatibility with mysql

---

cmd/client_changefeed.go

#1622 
do not panic if parse config file get error, just return it
Tests 
- No code
Code changes
Side effects
No release note

fix panic issue in update changefeed config.

---

cdc/sink/simple_mysql_tester.go

The old value test in github action often fails because of the following error:
```
[2021/04/14 03:56:12.480 +00:00] [ERROR] [processor.go:145] ["run processor failed"] [changefeed=b3f67eb2-de83-4984-8576-8e7358a7e4a5] [capture-id=4abeb2ce-d9e5-42d7-924c-1827b959d847] [capture=capturer1:8300] [error="Error 1062: Duplicate entry '158' for key 'PRIMARY'"] [errorVerbose="Error 1062: Duplicate entry '158' for key 'PRIMARY'
github.com/pingcap/errors.AddStack
github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/errors.go:174
github.com/pingcap/errors.Trace
github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/juju_adaptor.go:15
github.com/pingcap/ticdc/cdc/sink.(*simpleMySQLSink).executeRowChangedEvents
github.com/pingcap/ticdc/cdc/sink/simple_mysql_tester.go:150 …
```

github/action: insert/update SQL could meet duplicated entry error

---

cdc/puller/sorter/backend_pool.go
cdc/puller/sorter/heap_sorter.go
cdc/puller/sorter/merger.go
cdc/puller/sorter/sorter_test.go
cdc/puller/sorter/unified_sorter.go
errors.toml
metrics/grafana/ticdc.json
pkg/errors/errors.go

- Unified Sorter might return an unhelpful error `ErrWorkerPoolHandleCancelled` for some IO errors.
- Some error handling code might cause data race.
- Filter the `ErrWorkerPoolHandleCancelled` error.
- Add appropriate synchronization to avoid races.
- Add unit test cases for these fixes.
Tests 
- Unit test
- Fix Unified Sorter returning unhelpful error messages & other misc. fixes.

sorter: fix Unified Sorter error handling & add more unit test cases

---

cdc/kv/client_test.go

Fix a test failure in https://github.com/pingcap/ticdc/issues/1501#issuecomment-820027078
Note release-5.0 should be cherry-picked manually.
The cause is that when the mock TiKV server starts up for the second time, it could cost some time before it is available and kv client will try to request for more than one time.
Tests 
- Unit test

kv/client: fix unstable unit test, where request id is not accurate

---

cdc/kv/client_test.go

Fix unstable unit test
```
[2021-04-21T06:27:22.638Z] [2021/04/21 14:26:58.418 +08:00] [ERROR] [client_v2.go:81] ["received an event but neither pending region nor running region was found"] [regionID=3] [requestID=61] [addr=127.0.0.1:15936] [stack="github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).sendRegionChangeEventV2\n\t/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/ticdc/cdc/kv/client_v2.go:81\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).receiveFromStreamV2\n\t/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/ticdc/cdc/kv/client_v2.go:274\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).dispatchRequest.func1\n\t/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:815\ngolan …
```

tests: fix mock server sends event before kv client is ready

---

Makefile

Fix version number on macOS.
Tests 
```
git tag v5.0.2
git checkout -b refs/tags/v5.0.2
make
```

Makefile: fix incorrect version number on macOS

---

cmd/util.go

Tests 
- Unit test
- No code
Code changes
Side effects

cmd: fix wrong usage in cdc server cli flag, --cert-allowed-cn

---

cdc/sink/codec/avro.go
cdc/sink/codec/avro_test.go
cdc/sink/mq.go
docker-compose-avro.yml
integration/integration.go
integration/tests/case_date_time.go

- https://asktug.com/t/topic/69408/4
- Restore timezone information in Avro encoder.
Tests 
- Unit test
- Fix time zone lost in Avro output.

sink: fix avro timezone

---

cdc/kv/client.go
cdc/kv/client_test.go
cdc/kv/client_v2.go
cdc/kv/region_worker.go
cdc/kv/resolvedts_heap.go
cdc/kv/resolvedts_heap_test.go

- Fix a potential deadlock when a reconnect is performed
- Fix un initialized regions are not reconnected.
note release-5.0 should be picked manually.
- Reuse the `resolvedTsManager` to manage the time of last event in each un-initialized region, rename `resolvedTsManager` to `regionTsManager`
- Separate the reconnect check of un-initialized regions from the lock resolver routine to reduce lock contention.
Tests 
- Unit test

kv/client: fix force reconnect in client v2

---

cdc/http_status.go
cdc/http_status_test.go
go.sum

- Lack of a convenient way to control failpoints at runtime.
- Added an http API endpoint as `/fail/`
Tests 
- Unit test
Code changes
- Aadd http handler for failpoint

http_server: add http handler for failpoint

---

cdc/processor/pipeline/cyclic_mark_test.go
cdc/processor/pipeline/puller.go
cdc/processor/pipeline/sink.go
cdc/processor/pipeline/sink_test.go
cdc/processor/pipeline/table.go

all context of std lib should be named as `context`
all context of cdc package should be named as `cdcContext`
this pr modified the code in `ticdc/cdc/processor/pipeline` package.
Tests 
- Unit test

context: uniform the import naming of context, part 1

---

cdc/sink/common/flow_control.go
cdc/sink/common/flow_control_test.go

- Fix release-4.0 deadlock caused by flow-control when the sorter's input channel has been blocked.
```
goroutine 2776 [select, 363 minutes]:
github.com/pingcap/ticdc/cdc.(*oldProcessor).runFlowControl.func1(0xc0895d7918, 0x2189526)
github.com/pingcap/ticdc@/cdc/processor.go:990 +0x1d8
github.com/pingcap/ticdc/cdc/sink/common.(*TableMemoryQuota).ConsumeWithBlocking(0xc096495da0, 0x13, 0xc0895d7c20, 0x0, 0x0)
github.com/pingcap/ticdc@/cdc/sink/common/flow_control.go:77 +0xfc
github.com/pingcap/ticdc/cdc/sink/common.(*TableFlowController).Consume(0xc096495dd0, 0x5e5a0ae09d400ea, 0x13, 0xc0895d7c20, 0x0, 0x0)
github.com/pingcap/ticdc@/cdc/sink/common/flow_control.go:174 +0x8a
github.com/pingcap/ticdc/cdc.(*oldProcessor).runFlowControl(0xc0026606c0, 0x2f71160, 0xc095bf2440, 0x34, …
```

*: fix flow control deadlock (release-4.0)

---

cdc/kv/client.go
cdc/puller/sorter/merger.go
cmd/client_changefeed.go

#1765  
#1762 
#1761 
Appropriate log output is added(#1765) and redundant log output is removed(#1761 #1762).
Tests 
1.For #1765 , the out put now is as below: 
```
$ cdc cli changefeed query -c ttl-test-12
>
[2021/05/14 11:47:30.324 +08:00] [ERROR] [client_changefeed.go:218] ["This changefeed does not exist"] [changefeed=ttl-test-12]
Error: [CDC:ErrChangeFeedNotExists]changefeed not exists, key: /tidb/cdc/job/ttl-test-12
Usage:
cdc cli changefeed query [flags]
Flags:
-c, --changefeed-id string   Replication task (changefeed) ID
-h, --help                   help for query
-s, --simple                 Output simplified replication status
Global Flags:
--ca string          CA certificate path for TLS connection
--cert string …
```

*:refine log output

---

cdc/model/changefeed.go
cdc/model/changefeed_test.go
cdc/processor/state_test.go
cmd/client_changefeed.go
tests/unified_sorter/run.sh

Hide `--sort-dir` in changefeed command
- Hide `--sort-dir` in changefeed command
- Set `SortDir` to `` `json:"-"` `` in changefeed, so the `changefeed query` won't print any `sort-dir` which may confuse user. Note only set it to an ignore field is **backward compatibility**
Tests 
- Unit test

cmd: hide --sort-dir in changefeed command. (deprecated warning exists)

---

cdc/model/reactor_state.go
cdc/model/reactor_state_test.go
errors.toml
pkg/errors/errors.go
pkg/etcd/etcdkey.go
pkg/orchestrator/reactor_state_tester.go

a reactor state implement in model package, and I will remove the state implement in processor package in next pr.
the reactor state implements in model package and processor pacakge are roughly the same
it's order to let processor and owner use the same reactor state
FYI: what is recator state and how it works? see: https://github.com/pingcap/ticdc/blob/master/pkg/orchestrator/doc.go
Tests 
- Unit test

new_owner: let processor and owner use the same reactor state

---

pkg/orchestrator/etcd_worker.go
pkg/orchestrator/etcd_worker_bank_test.go
pkg/orchestrator/reactor_state_tester.go

- Fix a bug that etcd worker lost data
- a etcd worker bank test
the etcd worker have two steps when it's starting:
1. read entire data snapshot and apply it to the reactor state
2. start to watch the data change log from etcd and apply logs to the reacator state
the data lost between step 1 and step 2 because the start reversion of the watch is not set
Tests 
- Unit test

etcd_worker: fix a bug that etcd worker maybe lost data at starting

---

cdc/changefeed.go
cdc/changefeed_test.go

The resolved TS and checkpoint TS of a change feed is stopped, but no error reported
We can check the owner log, and find logs like this:
```
[2021/04/25 21:39:48.899 +08:00] [WARN] [changefeed.go:561] ["the target capture is not exist, sent the table to orphanTables"] [job="{\"From\":\"b51b0e86-373c-49a2-a7c4-42c98fde4e5e\",\"To\":\"5ec78795-88ea-43b3-803b-229a3ededc3b\",\"TableID\":694,\"TableReplicaInfo\":{\"start-ts\":424504976445538305,\"mark-table-id\":0},\"Status\":1}"]
[2021/04/25 21:39:48.899 +08:00] [WARN] [changefeed.go:561] ["the target capture is not exist, sent the table to orphanTables"] [job="{\"From\":\"b51b0e86-373c-49a2-a7c4-42c98fde4e5e\",\"To\":\"5ec78795-88ea-43b3-803b-229a3ededc3b\",\"TableID\":1103,\"TableReplicaInfo\":{\"start-ts\":424504976445538305,\"mark-table-i …
```

owner: fix a bug which lead to replication stopped and no error report

---

tests/_utils/start_tidb_cluster_impl
tests/processor_panic/main.go

Fix the following error in CI when starting TiFlash
```
[2021/05/25 15:48:39.592 +08:00] [ERROR] [<unknown>] ["Application: DB::Exception: Illegal arguments: can not use DTFile to store snapshot data when the storage engine is not DeltaTree, [engine=1] [snapshot method=file1]"] [thread_id=1]
```
- Use DeltaTree storage engine
- Besides descrease the data set size of one integration test, which is often timeout in integration test
Tests 
- Unit test

tests: fix tiflash storage engine in integration test

---

cdc/changefeed.go

[TiCDC FAQ](https://docs.pingcap.com/tidb/stable/troubleshoot-ticdc#when-the-downstream-of-a-changefeed-is-a-database-similar-to-mysql-and-ticdc-executes-a-time-consuming-ddl-statement-all-other-changefeeds-are-blocked-how-should-i-handle-the-issue) describes we can use the following way to find the `start-ts` of a DDL when we want to skip it.
> Search for the apply job field in the TiCDC log and confirm the StartTs of the DDL statement.
However the `apply job` log doesn't print `start-ts` of the DDL job.
- Log start-ts in the `apply job` log.
- Besides we can also update document, to instruct user to find the correct `start-ts` of a DDL job by TiDB DDL history.
Tests 
- Unit test

changefeed: log start-ts when applying ddl job

---

cdc/kv/client.go
cdc/kv/client_test.go
cdc/kv/client_v2.go

Fix a bug in kv client v2 that committed events are not counted in event ts manager
- Always send ts update notification to event ts manager when region receives any event and it is not initialized.
- Remove a failpoint in test case, and we can update global variable directly.
Tests 
- Unit test

kv/client: fix time is not updated when receiving committed event

---

cdc/owner.go
cdc/owner_test.go
errors.toml
pkg/errors/errors.go

TiKV GC safe point will be blocked indefinitely due to TiCDC changefeed checkpoint stagnation.
Set a threshold Y: Regardless of the status of the changefeed, TiCDC is allowed to block TiKV GC safe time for Y hours at most.
The threshold Y is set in the config/config.go file as a variable named gc-TTL and the default value is 84000 seconds (24 hours).
Tests 
- Unit test
step1: set  `defaultServerConfig.gcTTL = 20` in /pkg/config.go 
step2: add ` log.Warn("try to update gcSafePoint", zap.Time("gcSafePoint", oracle.GetTimeFromTS(gcSafePoint)))`  below line 802 in cdc/owner.go to print log info
step3: In a shell window type `tiup playground` to deploy a tidb cluster.
step4: Move to ticdc directory, and type `./bin/cdc server` to to start the …

owner: Modified the update strategy of gcSafePoint (#1731)

---

cdc/puller/sorter/heap_sorter.go

ref: #1853
~Since the access of `h.heap` is not concurrent, we can use the same `slice`~
The heap will be used in an async pool. We choose a conservative initialize size for sort heap slice.
- the heap is flushed every 100ms or accumulated data size execeeds `1GB`?
Tests 
- Unit test
- Reduce memory malloc in sort heap to avoid too much CPU overhead.

sorter: reduce memory malloc to avoid too much CPU overhead

---

Makefile
cdc/metrics_processor.go
cdc/processor.go
cdc/processor/pipeline/metrics.go
cdc/processor/pipeline/sink.go
cdc/processor/pipeline/sink_test.go
cdc/processor/pipeline/sorter.go
cdc/processor/pipeline/table.go
cdc/sink/common/flow_control.go
cdc/sink/common/flow_control_test.go
cmd/server_test.go
errors.toml
pkg/config/config.go
pkg/config/config_test.go
pkg/errors/errors.go
pkg/pipeline/pipeline.go

#1680 
1. sink flow control for old processor
2. sink flow control for new processor
Tests 
- Unit test
Side effects
- Support sink flow control to reduce OOM

*: port sink flow control for old processor & new processor to release-5.0

---

cdc/puller/sorter/sorter_test.go

- `TestSorterIOError` times out often.
- Reduces the size of the test data
Tests 
- Unit test

sorter: fix unstable unit tests

---

cdc/kv/client_test.go
cdc/kv/region_worker.go
errors.toml
pkg/errors/errors.go

Fix `region_worker` does not exit when TiKV store disconnect happens and region worker is set to exit manually. Unit test will be added later. Fix https://github.com/pingcap/ticdc/issues/1905 and #1904
The `eventHandler` should return a non-nil error when region worker is notified to exit, which will terminate other routines under the same `errgroup` to exit
Tests 
- Unit test

kv/client: fix region worker exited error

---

cdc/capture/capture.go
cdc/owner/changefeed.go
cdc/owner/changefeed_test.go
cdc/owner/ddl_puller.go
cdc/owner/ddl_puller_test.go
cdc/owner/gc_manager.go
cdc/owner/owner.go
cdc/owner/owner_test.go

a capture implement, the capture manages and runs the owner and processor
the capture starts and runs the owner and processor, restart the owner and processor when they throw an error
the unit test of capture is a unit test framework for the hole capture(including the owner and the processor), the framework is WIP.
Tests 
- Unit test

new_owner: a capture implement, the capture manages and runs the owner and processor

---

cdc/owner/feed_state_manager.go
cdc/owner/feed_state_manager_test.go

fix a changefeed can not removed when the changefeed status is not exist
Tests 
- Unit test

owner: fix a changefeed can not removed when the changefeed status is not exist

---

cdc/kv/client.go
cdc/kv/client_test.go
cdc/kv/client_v2.go
cdc/kv/metrics.go
cdc/kv/region_worker.go
cdc/kv/token_region.go
cdc/kv/token_region_test.go
tests/move_table/conf/workload

cherry-pick #1899 into release-5.0
cherry-pick #1899 into release-5.0
Tests 
- Unit test
- Add concurrency limit to the region incremental scan in kv client.

kv/client: add incremental scan region count limit

---

cdc/model/reactor_state.go
cdc/model/reactor_state_test.go
cdc/owner/changefeed.go
cdc/owner/changefeed_test.go
cdc/owner/owner.go
cdc/processor/manager.go
cdc/processor/processor.go
cdc/processor/processor_test.go
pkg/orchestrator/etcd_worker.go
pkg/orchestrator/etcd_worker_bank_test.go
pkg/orchestrator/etcd_worker_test.go
pkg/orchestrator/interfaces.go
pkg/orchestrator/reactor_state_tester.go
testing_utils/cdc_state_checker/state.go

fix `etcdserver: too many operations in txn request`:
before this PR, all operations of etcd key in a tick is committed as one txn, and the operations are generated by multiple changefeeds.
after this PR, the operations of one changefeed will be committed as one txn, and all operations of etcd key in a tick will be committed as more than one txn.
Tests 
- Unit test

owner: fix etcd error too many operations in txn request

---

cdc/kv/region_worker.go
pkg/workerpool/pool_impl.go

- TiCDC can OOM frequently on machines with memory less than 16GB.
- Decreased the channel sizes in two places.
Tests 
- Unit test
- Manual test 
Side effects
- Reduce unnecessary memory consumption

*: reduce memory consumption by reducing channel sizes

---

cdc/puller/sorter/backend_pool.go
cdc/puller/sorter/backend_pool_test.go

- When `/proc/meminfo` fails to open, TiCDC will panic because of inappropriate error handling. This usually happens when the OS does not allow TiCDC any more file descriptors.
- Fixed error handling when reading system memory pressure.
Tests 
- Unit test
- Fix panic when TiCDC fails to read `/proc/meminfo`

sorter: fix panic when getting memory pressure fails

---

cdc/kv/client.go
cdc/kv/client_test.go
cdc/kv/client_v2.go
cdc/puller/frontier/frontier_test.go

A workaround fix for #1576 
Since the region can merge and split at any given time, we have found one possible scenario that can cause panic in #1576, as following
- A, B, C, D, E are region range key.
- In the first line each range represents a region range, such as [A, B) represents range from A to B.
- The second line represents the resolved-ts maintained in puller frontier.
```
1. 
[A, B) [B, C) [C, D) [D, E)
20     20     10     20
2. [B, C) [C, D) merged into [B, D). But [B, D) does not forward, because of split to [B, C) and [C, D) immediately
[A, B) [B, D) [D, E)
20     10     20
3. [B, D) split to [B, C) and [C, D). [B, C) does not forward, because of merge into [A, B) immediately
[A, B) [B, C) [C, D) [D, E)
20     10     10     20
4.  Bump, here we meet resolved ts fall back, …
```

kv/client: send resovled ts in advance when region is locked

---

cdc/kv/etcd.go
cdc/kv/etcd_test.go
cdc/model/changefeed.go
cdc/model/changefeed_test.go
cmd/client_changefeed.go
errors.toml
pkg/errors/errors.go

fix `changefeed-id need to be limit max length` #1709
add a limit check
Tests 
- Unit test
Code changes
- Add changfeed-id limit check

cli: fix changefeed-id need to be limit max length 

---

cdc/puller/puller.go

This is an addition fix after #2038 
In #2038, kv client tries to send `resolved ts` to puller after a region information is loaded from PD and dispatched in kv client. However, in extreme scenario, `BatchLoadRegionsWithKeyRange` could still miss some regions of intermediate states. 
In the #2038 scenario, the fallen back resolved doesn't make any sense, because the `resovled-ts` in puller only guarantees **no late data**, but doesn't guarantee **no repeated data**. We have the same behavior in kv client when processing the resovled ts fallen back from TiKV, ref: https://github.com/pingcap/ticdc/blob/43c40f9d368a5f85beaf05080c3f11135648faa5/cdc/kv/client.go#L1473-L1480
- late data: It is **the first time** that a row changed event is received, and its `commit-ts` is smaller than …

puller: ignore fallen back resolved ts

---

cdc/processor/pipeline/mounter.go
cdc/processor/pipeline/mounter_test.go
cdc/processor/pipeline/sorter.go
cdc/processor/pipeline/table.go

- If DDL puller is behind, mounter could block the entire tablePipeline, causing deadlocks together with TiKV concurrency control or other components.
- Events waiting to be mounted are buffered in a Deque, which has no explicit size limit (the flowController ensures there will be no OOM).
Tests 
- Unit test
- Manual test (WIP)
Side effects

table_pipeline: Fix blocking entire pipeline when DDL puller is lagging behind

---

cdc/processor/processor.go

- The processor cancels tables one by one, meaning that the next table is not cancelled until the first table has fully exited. This causes risks of deadlocking.
- Cancel them all at once.
Tests 
- Unit test

processor: cancel all tables all at once

---

README.md

close https://github.com/pingcap/ticdc/issues/2082
Use the correct file.
Tests 
- No code
Code changes
None
Side effects
None
None

readme: Update the expired docker-compose startup command

---

cdc/puller/sorter/sorter_test.go
cdc/puller/sorter/unified_sorter.go

- Cancelling Unified Sorter's `Run` does not cancel `AddEntry`. This can cause unexpected channel congestion.
- Added close detection in `AddEntry`.
Tests 
- Unit test
Side effects

sorter: add close check to AddEntry

---

cdc/kv/client_test.go

- Some unit test cases can deadlock the testing framework when panics are not handled properly.
- Makes sure that WaitGroups are marked done when panicking.
Tests 
- Unit test

kv_client: fix unit tests deadlocked when panicking

---

errors.toml
pkg/errors/errors.go

fix CDC:ErrGCTTLExceeded error message has " %!d(MISSING) " #2080
fix the error msg
Tests 

error: fix wrong error message of ErrGCTTLExceeded

---

cmd/client.go

Inaccurate error message for PD address #1893
as the title said

cli: make error message compatible with pd flag name when PD address  unreachable 

---

cmd/client.go

close https://github.com/pingcap/ticdc/issues/1893
make error message compatible with pd flag name.
Tests 
None
Code changes
None
Side effects
None

cli: make error message compatible with pd flag name

---

cdc/kv/client.go
cdc/kv/client_test.go

Keep using kv client v1 in 5.0 release, only enable it in 5.1 release
turn off switch
Tests 
- Unit test

kv/client: keep using kv client v1 in 5.0

---

tools/check/check-tidy.sh

None
Only diff go.sum, otherwise there will be a lot of diff information after modifying the other codes.
Tests 
- No code
Code changes
None
Side effects
None

tools: only diff the go.mod and go.sum

---

README.md

fix readme Go version Go >= 1.16. we update to go 1.6.4 https://github.com/pingcap/ticdc/pull/1818, but ticdc is no longer compatible with go version >= 1.13 after  #2109
Tests 
- No code

doc: change readme support Go version to Go >= 1.16

---

cdc/capture.go
cdc/capture/capture.go
cdc/owner_test.go
cdc/server.go
cmd/server_test.go
pkg/config/config.go
pkg/config/config_test.go

This is part of #1540, close #2148
Add `capture-session-ttl` in server config
Tests 
- Unit test
- Add `capture-session-ttl` in cdc server config

config: cherry-pick capture-session-ttl config into release-4.0

---

pkg/pipeline/message.go

Reduce tick message in-use objects.
Cc: https://github.com/pingcap/ticdc/issues/2212
Tests 
```release-note
None
```

pipeline: reduce tick message in-use objects

---

errors.toml
pkg/errors/errors.go
pkg/orchestrator/etcd_txn.go
pkg/orchestrator/etcd_worker.go
pkg/orchestrator/etcd_worker_bank_test.go
pkg/orchestrator/etcd_worker_big_txn_test.go
pkg/orchestrator/etcd_worker_test.go
pkg/orchestrator/reactor_state_tester.go
tests/processor_stop_delay_2/run.sh

- A native Etcd transactions can only hold up to 128 operations. Even if the parameter can be adjusted, it would cause performance degradation in the whole Etcd cluster.
- We need Etcd transactions to make sure that the owner knows, at every instance, which tables are taken into consideration when each capture calculates its own checkpoint-ts, to prevent data loss.
- Emulate transactions in EtcdWorker with a prewrite-commit protocol.
Tests 
- Unit test
Side effects

etcd_worker: big txn

---

cdc/kv/region_worker.go
cdc/kv/resolvedts_heap.go
cdc/kv/resolvedts_heap_test.go

Fix #2188
Introduce a penalty mechanism
- If TiCDC keeps receiving unchanged resolved-ts, increase the penalty. 
- If TiCDC receives a new resolved ts, reset the penalty to zero
- Only resolve ts if the penalty is larger than threshold
Tests 
- Unit test
- Don't resolve lock immediately after a region is initialized.

kv/client: don't resolve lock immediately after a region is initialized

---

pkg/retry/retry_with_opt.go

fix `sleep*3` overflowed in `getBackoffInMs`, detected by Test DoCornerCases fails https://github.com/pingcap/ticdc/issues/2273
Tests 
- Unit test
Code changes
Side effects

pkg: fix retry getBackoffInMs panic when sleep overflowed

---

cdc/sink/manager.go
cdc/sink/manager_test.go

- There is an unsynchronized access to a shared map, which can cause runtime panic.
- Lock it.
Tests 
- Unit test
- Fix minor runtime panic risk

sink: fix concurrent map access in sink manager

---

cdc/entry/codec.go
cdc/entry/mounter.go
cdc/entry/mounter_test.go
cdc/model/mounter.go
cdc/model/schema_storage.go
cdc/processor.go
cdc/processor/pipeline/puller.go
cdc/processor/pipeline/sink.go
cdc/processor/pipeline/sink_test.go
pkg/regionspan/span.go
pkg/regionspan/span_test.go

ref: https://github.com/pingcap/ticdc/issues/2301
ticdc  always pull the old value internally.
Because our `new collation` feature needs the `old value` to work properly. However, some users will not use old value, but may use new collation, so it needs to be configured by the user. (Users don't even know if they have new collation on)
To simplify this configuration and to make it easier for the user, we decided to:
1. always use old value **internally.**
2. the data output to the user needs to be in the correct format (without the old value configuration on, the old value cannot be output)
Tests 
- Unit test
Code changes
None
Side effects
- Need to cherry-pick to the …

puller,mounter,processor: always pull the old value internally

---

pkg/filter/filter.go

ref: https://github.com/pingcap/ticdc/pull/2218
Pick some code from the original PR.
Tests 
- No code
Code changes
None
Side effects
None

filter: refine comments and function visibility

---

pkg/cmd/context/context.go
pkg/cmd/factory/factory.go
pkg/cmd/factory/factory_impl.go
pkg/cmd/util/helper.go
pkg/cmd/util/helper_test.go

part of https://github.com/pingcap/ticdc/issues/2168
cc: https://github.com/pingcap/ticdc/issues/2199
split from https://github.com/pingcap/ticdc/pull/2262
add client construction factory abstraction.
1. abstract the client constructor code that we originally put in the cli initialization
2. abstract the interface and have a struct (subsequently used as the cli's global flags binding) implement it, var _ ClientGetter = &ClientFlags{}, so that in effect the constructor implementation becomes the global flags of our original cli.
3. Putting our original global context into a new package
Tests 
None
Code changes
Side effects
None
None
/cc @amyangfei  @overvenus

refactor(cli): add client construction factory abstraction

---

pkg/pipeline/pipeline.go

Save CPU by skipping stack backtrace.
Skips stack backtrace.
Tests 
- Unit test
```release-note
None
```

pipeline: skip stack backtrace in hot path

---

cdc/processor/processor.go
pkg/pipeline/pipeline.go

Remove two unnecessary error logs:
```
[2021/08/02 22:03:33.331 +08:00] [ERROR] [pipeline.go:99] ["found error when running the node"] [name=sink] [error="[CDC:ErrTableProcessorStoppedSafely]table processor stopped safely"] [errorVerbose="[CDC:ErrTableProcessorStoppedSafely]table processor stopped safely\ngithub.com/pingcap/errors.AddStack\n\t/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\t/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/normalize.go:156\ngithub.com/pingcap/ticdc/cdc/processor/pipeline.(*sinkNode).flushSink.func1\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/cdc/processor/pipeline/sink.go:116\ngith …
```

processor: cleanup some unnecessary error logs

---

Makefile
pkg/version/check_test.go

- The next release version in TiCDC is `5.2.0`
- When creating a new changefeed with master cdc, we met `[2021/08/05 15:58:48.191 +08:00] [WARN] [client_changefeed.go:275] ["The TiCDC cluster is built from an older version, disabling old value by default."] [version=5.0.0-master]`
Change default release version to `5.2.0-master` when built from master
Tests 
- Unit test
```release-note
None
```

makefile: bump release version to 5.2.0-master when built from master

---

cdc/kv/client.go
cdc/kv/client_v2.go

In kv client, gRPC stream read or send error is retriable, use warn log when these scenarios happen
Use warn log when meet gRPC stream error
Tests 
- Unit test
```release-note
None
```

kv/client: change some error log to warn log

---

cdc/server.go
cmd/client.go

When the first pd in pd list is down, client and server command run faild .
Close https://github.com/pingcap/ticdc/issues/2502
Version check will check all pds in pd list provided by the command, not just the first one
Tests 
- Unit test
- No code
Code changes
Side effects
```release-note
None
```

client,server:check all pd versions

---

cdc/http_router.go
cdc/http_status_test.go

Fix some pprof requests (`/debug/pprof/xxx`) return 404
```
➜  curl http://172.16.6.135:8301/debug/pprof/goroutine\?debug=1
404 page not found%
```
Should match path `/debug/pprof/:any` and handled by `pprof.Index`
Tests 
- Unit test
```release-note
None
```

http: enable all sub paths matching in pprof

---

cdc/capture.go
cdc/capture/capture.go
cdc/capture_test.go
cdc/kv/client.go
cdc/kv/client_bench_test.go
cdc/kv/client_test.go
cdc/kv/grpc_pool.go
cdc/kv/grpc_pool_impl.go
cdc/kv/grpc_pool_impl_test.go
cdc/kv/metrics.go
cdc/kv/testing.go
cdc/owner.go
cdc/owner/ddl_puller.go
cdc/owner_operator.go
cdc/owner_test.go
cdc/processor.go
cdc/processor/pipeline/puller.go
cdc/processor/processor.go
cdc/puller/puller.go
cdc/puller/puller_test.go
pkg/context/context.go

Add global gRPC connection pool in cdc server.
- The gRPC pool is shared by all kv clients in a `capture`, the pool is created before a `capture` starts running and destroyed after a `capture` suicides or exits.
- The gPRC pool maintains a bucket of gPRC connections for each TiKV store, the bucket is increased in a lazy way.
- The gPRC pool provides a builtin recycle method, which is used to collect idle connections periodically.
Tests 
- Unit test
```release-note
Add a global gRPC connection pool and share gRPC connections among kv clients.
```

kv/client: add global grpc connection pool

---

cdc/kv/grpc_pool_impl.go

- Improper error handling in grpc pool can cause nil pointer dereference.
- No need to close connection if `Dial` has returned error.
Tests 
- Unit test
```release-note
None
```

kvclient: Fix grpc pool error handling

---

cdc/owner/changefeed.go
cdc/owner/schema.go
tests/ddl_reentrant/run.sh

Close #2603 
- Fixed the timestamp with which to read TiKV snapshot for schema.
- Improved integration test case `ddl_reentrant` so that similar bugs will not be reintroduced in the future.
Tests 
```release-note
Fixed a bug in DDL handling when the owner restarts.
```

owner: fix schema snapshot read from TiKV

---

cdc/sink/codec/json.go
cdc/sink/codec/json_test.go
cdc/sink/mq_test.go

Fix the open protocol part of #2612 
Note we still need to confirm what is the right behavior in protocol canal, canal-json, avro, maxwell for empty row change.
Ignore empty row change events in open protocol
Tests 
- Unit test
```release-note
Fix open protocol, don't output an empty value when there is no change in one transaction. 
```

sink/mq: fix empty value in open protocol

---

cdc/puller/frontier/heap_test.go

https://github.com/pingcap/ticdc/issues/2614
Tests 
- Unit test
Code changes
Side effects
```release-note
None
```

test: fix TestRemoveNode timeout

---

cdc/owner/changefeed.go
cdc/owner/changefeed_test.go

- The scheduler is called prematurely with a schema snapshot state earlier than expected.  Consider the scenario where a table `tbl1` is dropped at `ts` and the changefeed starts at `ts`. By design, the DDL puller will be starting from `ts` and the owner's schema cache will have been initialized to the TiKV snapshot at `ts - 1`. The owner will discover the existence of `tbl1` on the first tick and schedules it immediately. Soon after, when the `drop table tbl1` DDL job has been received, the owner would immediately remove it. This is a violation of expectation by the scheduler, which expects tables to be added in batches, and, before the previous batch has been successfully dispatched, no other batches should be scheduled. This violation has caused an integer underflow, hence #2625 
close …

owner: fix scheduling tables too early

---

cdc/owner/gc_manager.go
cdc/owner/gc_manager_test.go
cdc/owner/schema.go
tests/gc_safepoint/run.sh

- Since #2626 GC safepoint should be calculated from `checkpointTs - 1` instead of `checkpointTs`.
- Subtract one from GC safepoint.
Tests 
- Unit test
Code changes
Side effects
```release-note
None
```

owner: fix gc safepoint larger by one

---

cdc/async_sink.go
cdc/async_sink_test.go
cdc/changefeed.go
cdc/owner.go
cdc/owner_test.go
tests/changefeed_error/run.sh
tests/cyclic_abc/run.sh
tests/ddl_async/conf/block_cf_config.toml
tests/ddl_async/conf/diff_config.toml
tests/ddl_async/conf/normal_cf_config.toml
tests/ddl_async/data/prepare.sql
tests/ddl_async/run.sh
tests/ddl_reentrant/run.sh

close #2295 
Backport async sink to old owner and old changefeed.
Tests 
- Unit test
Code changes
Side effects
```release-note
This PR make the old owner handle DDL in Async mode.
```

async_sink: backport async sink to 5.0-branch old owner

---

cdc/model/mounter.go
cdc/processor/pipeline/cyclic_mark.go
cdc/processor/pipeline/cyclic_mark_test.go
cdc/processor/pipeline/sink.go

part of https://github.com/pingcap/ticdc/issues/2632
clean up useless WaitPrepare call.
The mounter will ensure the row is ready to use.
Tests 
- Unit test
Code changes
None
Side effects
None
```release-note
None
```

sink: clean up useless WaitPrepare call

---

cdc/capture/capture.go
cdc/kv/client.go

Note: TiCDC in the following tests includes https://github.com/pingcap/ticdc/pull/2214.  
Tested with following changes
```diff
diff --git a/cdc/puller/sorter/unified_sorter.go b/cdc/puller/sorter/unified_sorter.go
index 9cd9c898..6e033429 100644
--- a/cdc/puller/sorter/unified_sorter.go
+++ b/cdc/puller/sorter/unified_sorter.go
@@ -197,9 +197,9 @@ func (s *UnifiedSorter) Run(ctx context.Context) error {
}
})
-       errg.Go(func() error {
-               return printError(runMerger(subctx, numConcurrentHeaps, heapSorterCollectCh, s.outputCh, ioCancelFunc))
-       })
+       // errg.Go(func() error {
+       //      return printError(runMerger(subctx, numConcurrentHeaps, heapSorterCollectCh, s.outputCh, ioCancelFunc))
+       // })
errg.Go(func() error {
captureAddr := …
```

kv: reduce gRPC window size to avoid OOM

---

cdc/processor/pipeline/sink.go
cdc/processor/pipeline/sink_test.go
cdc/processor/pipeline/table.go
cdc/processor/processor.go
pkg/pipeline/message.go

Fix a data inconsistency issue caused by conflict write from two captures, it was a remaining bug after #2417
- The table status of a pipeline should not set to stopped until the underlying sink is closed.
- Remove unused `StoppedTs` parameter in pipeline command.
Tests 
- Unit test
```release-note
Fix a bug that multiple processors could write the same table when this table is re-scheduling
```

pipeline: set table status to stopped after sink is closed

---

cdc/kv/client.go
cdc/kv/metrics.go
cdc/kv/region_worker.go
cdc/kv/token_region.go
cdc/processor/pipeline/puller.go
metrics/grafana/ticdc.json

Add three more metrics in kv client.
- Metric `KV client scanning regions` using `ticdc_kvclient_region_token` will help us to distinguish whether there is incremental scan ongoing.
- Metric `Active stream count of each gRPC connection` using `ticdc_kvclient_grpc_stream_count` will help us to find gRPC stream distribution among all TiKV stores.
- Add event type ("received" and "dropped") in metric `Event size percentile` to help us know how many events are dropped.
Tests 
- Unit test
```release-note
None
```

metrics: add more metrics about kv client and gRPC stream

---

tests/gc_safepoint/run.sh

close #2653 
record start_safepoint before check_safepoint_forward
Tests 
Code changes
Side effects
None
None
```release-note
None
```

tests: fix unstable integration_test gc_safepoint

---

tests/_utils/stop_tidb_cluster

kill cdc server first to avoid too much noise in cdc logs, such as, which will benefit for debugging when case runs failed.
```
[2021/09/16 13:51:54.150 +08:00] [INFO] [client.go:377] ["establish stream to store failed, retry later"] [addr=127.0.0.1:20162] [error="[CDC:ErrTiKVEventFeed]rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:20162: connect: connection refused\": rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:20162: connect: connection refused\""] [errorVerbose="[CDC:ErrTiKVEventFeed]rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:20162: connect: connection refused\": rpc error: code = …
```

tests: fix stop sequence of test binaries

---

pkg/leakutil/leak_helper.go
pkg/leakutil/leak_helper_test.go

Extract leak helper func to a new pkg to avoid the circle deps in pkg/util
Extract leak helper func to a new pkg, avoid adding other unnecessary deps.
Tests 
- Unit test
Code changes
Add leakutil.SetUpLeakTest() to ignore some common unexpected stack top functions
```release-note
Extract leak helper func to a new pkg to avoid the circle deps in pkg/util
```

test(pkg/leakutil): extract leak helper func to a new pkg

---

pkg/cyclic/filter_test.go
pkg/cyclic/main_test.go
pkg/cyclic/mark/main_test.go
pkg/cyclic/mark/mark_test.go
pkg/cyclic/replication_test.go

migrate test-infra to testify for pkg/cyclic pkg,  close #2869  close #2870
2. migrate leak test from leaktest to goleak
Tests 
- Unit test
```release-note
migrate test-infra to testify for pkg/cyclic pkg
```

test(pkg/cyclic): migrate test-infra to testify for pkg/cyclic pkg

---

pkg/flags/main_test.go
pkg/flags/urls_test.go

migrate test-infra to testify for pkg/flags pkg, close  #2935 
2. migrate leak test from leaktest to goleak
Tests 
- Unit test
```release-note
`None`.
```

perf(pkg/flags): migrate test-infra to testify for pkg/flags pkg

---

pkg/httputil/httputil_test.go
pkg/httputil/main_test.go

migrate test-infra to testify for pkg/httputil pkg, close  #2933
2. migrate leak test from leaktest to goleak
Tests 
- Unit test
```release-note
None
```

test(pkg/httputil): migrate test-infra to testify for pkg/httputil pkg

---

pkg/pipeline/main_test.go
pkg/pipeline/pipeline_test.go

close #2954
2. migrate leak-test from testleak to goleak
Tests 
- Unit test
Code changes
- None
Side effects
- None
```release-note
None.
```

test(pkg/pipeline): migrate test-infra to testify for pkg/pipeline pkg

---

cdc/entry/schema_storage.go

Verbose some critical logs. 
Tests 
- Unit test
```release-note
None
```

schema_storage: verbose DDL log

---

cdc/redo/manager.go
cdc/redo/manager_test.go
pkg/applier/redo.go
pkg/applier/redo_test.go
pkg/cmd/redo/apply.go
pkg/cmd/redo/meta.go
pkg/cmd/redo/redo.go
pkg/cmd/util/changefeed.toml
pkg/config/config.go
pkg/config/config_test.go
pkg/config/consistent.go
tests/consistent_replicate_local/conf/changefeed.toml
tests/consistent_replicate_local/run.sh
tests/consistent_replicate_s3/conf/changefeed.toml
tests/consistent_replicate_s3/run.sh

Update some redo log related configuration, according to GA document.
- Use `storage`, instead of `storage` and `s3-uri`, keep the same backend storage style with br. Ref: https://docs.pingcap.com/tidb/stable/backup-and-restore-storages#external-storages
- Change `dir` to `tmp-dir` in `cdc redo apply` and `cdc redo meta` commands.
- Change default consistent level to `none`
Tests 
- Unit test
```release-note
None
```

ticdc/redolog: refine configuration in redo log

---

pkg/applier/redo_test.go

Close #3185 
MySQL sink can return error either in `sql.Open()` or `db.PingContext()`
`fail to open MySQL connection: [CDC:ErrMySQLConnectionError]dial tcp 127.0.0.1:37853: connect: connection refused: dial tcp 127.0.0.1:37853: connect: connection refused`
or 
`[CDC:ErrMySQLConnectionError]Open database connection failed: dial tcp 127.0.0.1:37390: connect: connection refused`
Use `CDC:ErrMySQLConnectionError` to match both of these two errors.
Tests 
- Unit test
```release-note
None
```

tests: fix MySQL error that redo applier may meet

---

cdc/entry/schema_storage.go

Signed-off-by: sdojjy <sdojjy@qq.com>
In TiCDC DBInfo is ready only data, to reduce memory, we can use DBInfo.Copy() method to shallow copy DBInfo
replace DBInfo.Clone() with DBInfo.Copy()
Tests 
- Unit test
Code changes
Side effects
```release-note
None
```

schema storage shallow copy DBInfo

---

pkg/p2p/server_wrapper_test.go

```
[2021-11-03T03:03:49.175Z] [2021/11/03 11:01:57.701 +08:00] [INFO] [server_wrapper_test.go:49] ["error received"] [error="rpc error: code = Canceled desc = context canceled"]
[2021-11-03T03:03:49.175Z] --- FAIL: TestServerWrapperDelayed (0.13s)
[2021-11-03T03:03:49.175Z]     server_wrapper_test.go:185: FAIL:	OnNewMessage(*p2p.MessagePacket)
[2021-11-03T03:03:49.175Z]         		at: [server_wrapper_test.go:165]
[2021-11-03T03:03:49.175Z]     server_wrapper_test.go:185: FAIL: 0 out of 1 expectation(s) were met.
[2021-11-03T03:03:49.175Z]         	The code you are testing needs to make 1 more call(s).
[2021-11-03T03:03:49.175Z]         	at: [server_wrapper_test.go:185]
[2021-11-03T03:03:49.175Z] FAIL
```
- This test case should be considered passed only if it does not panic, because we …

p2p: fix unstable test TestServerWrapperDelayed

---

kafka_consumer/Dockerfile

part of https://github.com/pingcap/ticdc/issues/2199
remove useless kafka_consumer Dockerfile. We have reduced a root folder.
It is still using 1.13 of golang, which I believe is not used anywhere.
If you still want to keep it, I can move it to the right place.
Tests 
- No code
Code changes
None
Side effects
None
None
```release-note
None
```

kafka_consumer: remove useless kafka_consumer Dockerfile

---

cdc/kv/region_worker.go

Close #3288
Fix a region loss case, we can reproduce as following steps
1. Create a TiDB cluster with 5 TiKV nodes, create a table with 4TB data(or 100K regions)
2. Setup a TiCDC cluster to replicate table in step-1
3. Use TiUP to restart all these TiKVs without transferring leader region, by ` tiup cluster restart <cluster-name> -R tikv` command for example.
4. Observe the replication stucks even all regions are initialized. (Both cached regions and scanning regions are zero)
By comparing the initialized regions in TiCDC and all regions by querying `select region_id from information_schema.tikv_region_status where db_name = 'xx' and table_name = 'yy'` from TiDB, we can observe some regions are lost.
By querying the lost region id in TiCDC log, we found the region disconnected without …

kv/client: fix region loss in single region handler

---

dm/tests/ha_cases2/run.sh

fix unstable case [here](https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/434/pipeline/)
run command with retry
reason see [this](https://github.com/pingcap/dm/pull/2225#issuecomment-951583877)
Tests 
- No code
```release-note
`None`.
```

dm-test: fix unstable case

---

cdc/processor/processor.go

Close #3411
The error channel created in processor will be used in sink, sink manager and redo log manager. It is not safe to close a channel from channel receiver (ref: https://go101.org/article/channel-closing.html).
We don't close this error channel and let runtime GC to recycle it.
Tests 
- Unit test
```release-note
None
```

ticdc/processor: don't close error channel in receiver

---

cdc/sink/mq.go
cdc/sink/mq_test.go
cdc/sink/producer/kafka/kafka.go
cdc/sink/producer/kafka/kafka_test.go

close #3337
This is part work of making Kafka GA. Contain the following:
* Refine the logic of creating topic
* Make some variable become a field of the `Config`, which would be helpful if we would support one producer per topic in the future since this group producer parameters together.
* Bugfix
* If `auto-create-topic` disable by the user, the partition count will not be checked.
* before create the topic, make sure broker's `message.max.bytes` not less than `max-message-bytes`
Tests 
- Unit test
Code changes
Side effects
- Breaking …

cdc/sink: adjust kafka initialization logic

---

cdc/processor/pipeline/sorter.go
cdc/sorter/unified/merger.go
cdc/sorter/unified/sorter_test.go
cdc/sorter/unified/unified_sorter.go
pkg/cmd/server/server.go

None
trivial refactor for unified sorter.
rename some structures and methods to make happy.
Tests 
- No code
Code changes
Side effects
None
None
```release-note
None
```

sorter: rename some structures and methods to make revive happy

---

pkg/orchestrator/reactor_state.go

Log capture info when remote capture is offline, which makes debug more easily
Log capture info when remote capture is offline
Tests 
- Unit test
- `TestGlobalStateUpdate` has covered the change already.
```release-note
None
```

ticdc/reactor: log capture info when remote capture is offline

---

cdc/scheduler/util/table_set.go
cdc/scheduler/util/table_set_test.go

- The scheduler needs a convenient way to update the table records.
- The scheduler needs to know which tables are removed when a capture goes offline, for better observability.
- Implemented `func (s *TableSet) UpdateTableRecord(record *TableRecord) (successful bool)`
- Added return value for `func (s *TableSet) RemoveTableRecordByCaptureID(captureID model.CaptureID) []*TableRecord`.
- Minor adjustment of unit test cases.
Tests 
- Unit test
Code changes
```release-note
None
```

cdc/scheduler_v2: refine TableSet for scheduler

---

cdc/owner/changefeed.go
cdc/processor/pipeline/table.go
cdc/sink/manager.go
cdc/sink/table_sink.go

Revert #3029 and #2617 temporary for resolving #3503.
Cc https://github.com/pingcap/ticdc/issues/3545
Tests 
See #3503
```release-note
None
```

processor,sink(cdc): let sink report resolved ts and do not skip buffer sink flush

---

Makefile

part of https://github.com/pingcap/ticdc/issues/3569
separate statistics for unit tests and integration tests.
Tests 
- No code
Code changes
None
Side effects
None
```release-note
None
```

test(ticdc): separate statistics for unit tests and integration tests

---

tests/ddl_reentrant/run.sh

- Testing DDL reentrant from `start-ts` cannot reveal common problems with DDL handling.
- Tests DDL reentrant from `finish-ts`.
Tests 
```release-note
None
```

cdc/tests: adjust ddl_reentrant test case

---

cdc/owner/async_sink_test.go
cdc/processor/pipeline/sink.go
cdc/processor/pipeline/sink_test.go
cdc/processor/pipeline/table.go
cdc/sink/black_hole.go
cdc/sink/buffer_sink.go
cdc/sink/cdclog/file.go
cdc/sink/cdclog/s3.go
cdc/sink/manager.go
cdc/sink/manager_test.go
cdc/sink/mq.go
cdc/sink/mq_test.go
cdc/sink/mysql.go
cdc/sink/mysql_test.go
cdc/sink/simple_mysql_tester.go
cdc/sink/sink.go
cdc/sink/table_sink.go
cmd/kafka-consumer/main.go
pkg/applier/redo.go

To fix the bug of #3503 , we should manage table checkpoint per table in the sink, this is PR is a part of the fix. In this PR, only change the interface method, no real logic is changed.
add table ID to Sink interface, below functions will be changed,
```
type Sink interface {
FlushRowChangedEvents(ctx context.Context, tableID model.TableID, resolvedTs uint64) (uint64, error)
Barrier(ctx context.Context, tableID model.TableID) error
}
```
Tests 
- Unit test
Code changes
Side effects
```release-note
`None`.
```

cdc/sink: Refine sink interface

---

cdc/sink/codec/avro.go
cdc/sink/codec/avro_test.go

Closes #3624
When inserting valid JSON into a column of the `json` type this happens:
```
panic: interface conversion: interface {} is string, not json.BinaryJSON
goroutine 1228 [running]:
github.com/pingcap/ticdc/cdc/sink/codec.columnToAvroNativeData(0xc003f93bc0, 0xc000e14cb0, 0xc0027471c8, 0x2, 0xc00197a1a8, 0xd, 0x0, 0x0)
github.com/pingcap/ticdc/cdc/sink/codec/avro.go:479 +0x19c5
github.com/pingcap/ticdc/cdc/sink/codec.rowToAvroNativeData(0xc00274e1f0, 0x2, 0x2, 0xc000e14cb0, 0x4, 0xc002747190, 0xc, 0x37)
github.com/pingcap/ticdc/cdc/sink/codec/avro.go:274 +0xa8
github.com/pingcap/ticdc/cdc/sink/codec.avroEncode(0xc003f93bf0, 0xc0026817c0, 0x5f5736086ec0002, 0xc00274e1f0, 0x2, 0x2, 0xc000e14cb0, 0xc0044ef560, 0xc0044ef570, 0x3a071e8) …
```

Fix handling of JSON columns

---

dm/dm/master/workerrpc/rawgrpc.go

`// Deprecated: use WithConnectParams instead. Will be supported throughout 1.x.` and the client has using `grpc.WithConnectParams`, the `grpc.WithBackoffMaxDelay` is duplicate.
Tests 
- No need to add tests
```release-note
None
```

chore(dm): grpc.WithBackoffMaxDelay has been deprecated

---

tests/integration_tests/row_format/data/step3.sql

add unsigned type to `row format` integration test, to cover more cases.
add unsigned for int / real table.
Tests 
- No code
Code changes
Side effects
```release-note
`None`.
```

cdc/integration: Add unsigned test to row format

---

cdc/entry/mounter.go
cdc/entry/mounter_test.go

close  #3793
Fix default value  unsupported bug cause by amend feature of tidb, related to issue #3793
Amend feature of TiDB:
As for add column DDL, if a DDL occur between a trx, the trx will not redo but commit the old schema data directly, which will cause TiCDC use new schema to parse old schema data.
After call "getDefaultOrZeroValue", we need to call "formatColVal" to format data from the tidb type to go supported sql type
Tests 
- Unit test
Start 2 transactions:
1. Transaction 1:
```
Create table test_column(id int primary key);
Insert Into test_column values(1);
begin;
Insert Into test_column values(2);
// hold the trx untill Transaction 2 commit DDL
commit;
```
- Transaction 2:
```
alter table test_column add …
```

mounter(ticdc): fix mounter add default value type unsupported

---

.github/ISSUE_TEMPLATE/flaking-test.yml
.github/ISSUE_TEMPLATE/question.yml
.github/workflows/assign_bugs_questions_project.yaml
.github/workflows/dm_binlog_999999.yaml
.github/workflows/dm_chaos.yaml
.github/workflows/dm_upstream_switch.yaml
.github/workflows/upgrade_dm_via_tiup.yaml

Some remaining `pingcap/ticdc`, finished the remaining problem-2 in https://github.com/pingcap/tiflow/issues/3749
**The DM github action tests are verified in #3966.**
These files were introduced from `v5.3.0`, so cherry pick to `release-5.3` is enough.
replace `pingcap/ticdc` with `pingcap/tiflow` in files from `.github` dir
Tests 
- Unit test
```release-note
None
```

github: replace pingcap/ticdc with pingcap/tiflow in workflow

---

cdc/owner/scheduler.go
cdc/owner/scheduler_test.go
cdc/processor/agent.go
cdc/processor/agent_test.go
dm/tests/README.md
pkg/p2p/client.go
pkg/p2p/client_test.go

**This is a bug fix on unreleased code.**
Close #3972 
- This error should not be directly reported to the user since it may not represent an actual failure.
- Do not report ErrPeerMessageClientClosed
Tests 
- Unit test
```release-note
None
```

owner, processor(cdc): fix reporting ErrPeerMessageClientClosed to user erroneously

---

dm/dm/worker/config.go
dm/dm/worker/dm-worker.toml
dm/dm/worker/relay.go
dm/dm/worker/server.go
dm/dm/worker/source_worker.go
dm/dm/worker/source_worker_test.go
dm/dm/worker/task_checker_test.go
dm/tests/dmctl_basic/conf/get_worker1.toml
dm/tests/dmctl_basic/conf/get_worker2.toml
dm/tests/print_status/conf/dm-worker1.toml
dm/tests/print_status/run.sh

Support different worker has different path to store relay log
as title
Tests 
Code changes
Side effects
```release-note
DM-worker can specify a path to store its relay log
```

worker(dm): worker has higher priority to config relay dir

---

cdc/owner/ddl_puller.go
cdc/owner/ddl_puller_test.go
dm/tests/shardddl4/run.sh

- To help diagnosing replication stagnation, we need to be notified of owner's DDL puller being stuck.
- Added a warning if owner's DDL puller lags behind for over 30 seconds.
Tests 
- Unit test
Side effects
```release-note
None
```

owner(cdc): add a warning for owner DDL puller being stuck

---

dm/tests/shardddl4/run.sh

Reverts pingcap/tiflow#4031
close https://github.com/pingcap/tiflow/issues/4029, because https://github.com/pingcap/tidb-tools/pull/576 has been merged
```release-note
None
```

Revert "test(dm): fix unexpected sync-diff temporarily"

---

cdc/sink/codec/craft.go
cdc/sink/codec/craft_test.go
cdc/sink/codec/json.go
cdc/sink/codec/json_test.go
cdc/sink/producer/kafka/config.go
cdc/sink/producer/kafka/kafka.go
cdc/sink/producer/kafka/kafka_test.go
go.mod
pkg/config/sink.go
pkg/kafka/cluster_admin_client_mock_impl.go

close #4041
set Kafka producer's default `max-message-bytes` to 10M, and use the minimum value among sink-uri's `max-message-bytes`, broker's `message.max.bytes`, topic's `max.message.bytes` to initialize the producer.
* set the default value of `max-message-bytes` to 10M
* use the min value of the 3 mentioned above to initialize the producer.
Tests 
- Unit test
Code changes
Side effects
```release-note
Set `max-message-bytes` default to 10M, and use the min value with topic and broker to initialize the producer.
```

sink(ticdc): set max-message-bytes default to 10m

---

cdc/sink/codec/craft.go
cdc/sink/codec/craft_test.go
cdc/sink/codec/json.go
cdc/sink/codec/json_test.go
cdc/sink/mq.go
cdc/sink/mq_test.go
cdc/sink/producer/kafka/kafka.go
cdc/sink/producer/kafka/kafka_test.go

when initializing the encoder, make sure `max-message-bytes` in the `opts`, and set identical to producer's configuration.
Tests 
- Unit test
Code changes
Side effects
```release-note
`None`.
```

codec(cdc): fix encoder `max-message-bytes`

---

cdc/processor/pipeline/sink.go
cdc/processor/pipeline/sink_test.go
cdc/sink/table_sink.go
pkg/pipeline/test.go

Issue Number: close #4055
The code changed is simple and the reason is described in comments.	
Tests 
- Unit test
Code changes
Side effects
```release-note
Fix a bug that can cause changefeed stuck due to a deadlock occurs.
```

sink (ticdc): fix a deadlock due to checkpointTs fall back in sinkNode

---

cdc/kv/client.go
cdc/kv/client_test.go
cdc/kv/region_worker.go

Issue Number: close #4006 
Tests 
- Unit test
```release-note
Reduce "EventFeed retry rate limited" logs
```

kv(ticdc): reduce eventfeed rate limited log

---

cdc/capture/http_errors.go
cdc/capture/http_handler.go
tests/integration_tests/http_api/util/test_case.py

Issue Number: close #3840 
Return an error when the processor info not exists.
Tests 
Code changes
Side effects
```release-note
Fix the bug that http API panic when the processor info we want to get is not exist. 
```

http_api (ticdc): fix http api 'get processor' panic.

---

cdc/entry/schema_storage.go

Issue Number: close #4066 
add DDL job debug log before being skip 
```release-note
`None`.
```

DDL(ticdc): add more online DDL debug log

---

tests/integration_tests/default_value/config.toml
tests/integration_tests/default_value/diff_config.toml
tests/integration_tests/default_value/main.go
tests/integration_tests/default_value/run.sh

Issue Number: close #4223 
Tests 
```release-note
`None`.
```

test(cdc): Add defaultvalue integration test

---

Makefile

Issue Number: close #4302 
Add `-parallel` param to goveralls to accelerate the generation of coverage report. 
Tests 
- Unit test
```release-note
None
```

test(ticdc): Accelerating the generation of goveralls coverage report

---

dm/dm/worker/source_worker.go
dm/tests/metrics/run.sh

Issue Number: close #4281
as title
Tests 
Code changes
Side effects
```release-note
Fix a bug that upstream metrics won't update if no query-status
```

source_worker(dm): peroidically update source metrics background

---

pkg/p2p/client_test.go
pkg/p2p/mock_grpc_client.go

Issue Number: ref #3825 
- Made `mockSendMessageClient` thread-safe.
Tests 
- Unit test
```release-note
None
```

tests(cdc): fix data race in TestMessageClientBasics

---

deployments/ticdc/docker/integration-test.Dockerfile
scripts/canal/docker/Dockerfile

Issue Number: close https://github.com/pingcap/tiflow/issues/4433
use mysql 2022 rpm GPG key.
Tests 
- No code
Code changes
None
Side effects
None
```release-note
None
```

test(ticdc): use mysql 2022 rpm GPG key

---

dm/syncer/dml_worker.go
dm/tests/shardddl1/run.sh

Issue Number: close #4317
- when update job split into multiple dmls(delete + replace), len(dmls)>len(jobs), we should determine the error dml is generated from which job
- - when in multipleRows mode, we combine multiple jobs into one dml, if dml execute failed, we cannot determine which job it is 
so simply use the first job when meet error and `len(jobs)!=len(dmls)`, which not affect other feature.
Tests 
- Unit test
- No code
Code changes
Side effects
- Need to …

bugfix: fix update statement execute error in safemode cause dm-worker panic

---

cdc/sink/mysql.go
cdc/sink/mysql_test.go

Issue Number: close #4501
Remove duplicated sqls.
Tests 
- Unit test
```release-note
Fix a bug that MySQL sink will generate duplicated replace SQL if `batch-replace-enable` is disabled.
```

sink(ticdc): fix duplicated replace when batch-replace is disabled

---

cdc/entry/mounter.go
cdc/entry/mounter_test.go
tests/integration_tests/default_value/config.toml
tests/integration_tests/default_value/diff_config.toml
tests/integration_tests/default_value/main.go
tests/integration_tests/default_value/run.sh
tests/integration_tests/multi_source/diff_config.toml

This is a manual pr merge(https://github.com/pingcap/tiflow/pull/3846 https://github.com/pingcap/tiflow/pull/4224 https://github.com/pingcap/tiflow/pull/3930)
Issue Number: close https://github.com/pingcap/tiflow/issues/3793 https://github.com/pingcap/tiflow/issues/4223 https://github.com/pingcap/tiflow/issues/3929 https://github.com/pingcap/tiflow/issues/3918
Tests 
- Unit test
```release-note
Support more data types with default value attribute, and fix potential data inconsistency caused by default value logic
```

Fix unsupported data type issue caused by default value filling logic 

---

cdc/sink/codec/avro.go
cdc/sink/codec/canal.go
cdc/sink/codec/canal_flat.go
cdc/sink/codec/canal_flat_test.go
cdc/sink/codec/craft.go
cdc/sink/codec/interface.go
cdc/sink/codec/json.go
cdc/sink/codec/maxwell.go
cdc/sink/mq.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/4423
Remove useless AppendResolvedEvent API.
Most protocols don't implement it, and its original purpose was to ensure the order of dml and ddl. But now buffersink already guarantees it. So we can remove it.
Tests 
- Unit test
Code changes
Side effects
None
None
```release-note
None
```

ticdc(sink): remove useless AppendResolvedEvent

---

dm/loader/util.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/4287
When use DM as a library, sometimes etcd client is not valid thus we should support nil etcd client
Tests 
- pass original tests
Code changes
Side effects
```release-note
`None`.
```

loader(dm): skip feature for nil etcd client

---

cdc/sink/black_hole.go
cdc/sink/buffer_sink_test.go
cdc/sink/mq.go
cdc/sink/mysql.go
cdc/sink/mysql_test.go
cdc/sink/producer/kafka/kafka.go
cdc/sink/sink.go
cdc/sink/statistics.go

Issue Number: close #4607
Remove `opt` from `statistics`.
We should avoid pass `opts` along the call chain, it's implicit and hard to reason about.
Tests 
- No code
Code changes
Side effects
```release-note
`None`.
```

cdc/sink: decouple opt out of statistics

---

cdc/entry/mounter.go

Issue Number: close https://github.com/pingcap/tiflow/issues/4582
The original part of the logic was to find the handle column of the delete event when pkishandle. But now the TiCDC puller node pulls the old value by default, so we don't need to do this anymore.
Tests 
Code changes
None
Side effects
None
None
```release-note
None
```

ticdc(mounter): remove unnecessary delete event decode logic

---

tests/integration_tests/default_value/main.go

close  #4600
Issue Number: close #4600 
temporary ignore `Error 1105` for default_value integration test
Tests 
- Unit test
- No code
Code changes
Side effects
```release-note
`None`.
```

integration(ticdc): temporary ignore `Error 1105` for default_value integration test

---

dm/pkg/schema/tracker.go
dm/pkg/schema/tracker_test.go
dm/tests/downstream_diff_index/data/db1.increment.sql
dm/tests/downstream_diff_index/data/db1.prepare.sql
dm/tests/downstream_diff_index/run.sh

Issue Number: close #4637
found that MockTableInfo will always use default charset and collation, BuildTableInfoFromAST is better
Tests 
- Unit test
Code changes
Side effects
```release-note
Fix a bug that long varchar will report error of "Column length too big..."
```

tracker(dm): respect CHARSET when build TableInfo

---

cdc/sink/codec/avro.go
cdc/sink/codec/avro_test.go
cdc/sink/codec/canal.go
cdc/sink/codec/canal_flat.go
cdc/sink/codec/canal_flat_test.go
cdc/sink/codec/canal_test.go
cdc/sink/codec/codec_test.go
cdc/sink/codec/craft.go
cdc/sink/codec/craft_test.go
cdc/sink/codec/interface.go
cdc/sink/codec/json.go
cdc/sink/codec/json_test.go
cdc/sink/codec/maxwell.go
cdc/sink/codec/maxwell_test.go
cdc/sink/mq.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/4423
remove useless op return value of AppendRowChangedEvent.
1. we do not need to return it when we append the msg to the buf.
2. the flushToProducer func never receive EncoderNeedSyncWrite op.
Tests 
- Unit test
Code changes
Side effects
None
None
```release-note
None
```

sink(ticdc): remove useless op return value of AppendRowChangedEvent

---

cdc/entry/mounter.go
cdc/entry/mounter_test.go
tests/integration_tests/default_value/config.toml
tests/integration_tests/default_value/diff_config.toml
tests/integration_tests/default_value/main.go
tests/integration_tests/default_value/run.sh
tests/integration_tests/multi_source/diff_config.toml

This is a manual pr merge(https://github.com/pingcap/tiflow/pull/3846 https://github.com/pingcap/tiflow/pull/4224 https://github.com/pingcap/tiflow/pull/3930)
Issue Number: close https://github.com/pingcap/tiflow/issues/3793 https://github.com/pingcap/tiflow/issues/4223 https://github.com/pingcap/tiflow/issues/3929 https://github.com/pingcap/tiflow/issues/3918
```release-note
Support more data types with default value attribute, and fix potential data inconsistency caused by default value logic
```

Fix data inconsistency caused by default value

---

cdc/http_test.go
cdc/sorter/unified/file_backend.go
cdc/sorter/unified/file_backend_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/3206
Tests 
Code changes
None
Side effects
None
None
```release-note
None
```

sorter(ticdc): fix the issue of using wrong values for writeCount and dataSize

---

cdc/sink/codec/avro.go
cdc/sink/codec/canal.go
cdc/sink/codec/canal_flat.go
cdc/sink/codec/craft.go
cdc/sink/codec/interface.go
cdc/sink/codec/json.go
cdc/sink/codec/json_test.go
cdc/sink/codec/maxwell.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/4423
remove useless MixedBuild and Reset funcs. We have removed the cdc log, so this is completely useless code.
Tests 
- Unit test
Code changes
Side effects
None
None
```release-note
None
```

sink/codec(ticdc): remove useless MixedBuild and Reset funcs

---

cdc/sink/producer/kafka/kafka.go
cdc/sink/producer/kafka/kafka_test.go
pkg/kafka/cluster_admin_client.go
pkg/kafka/cluster_admin_client_mock_impl.go
pkg/kafka/config.go

Issue Number: close #4660
port `ClusterAdminClientMockImpl` from master, with all necessary changes to test code 
Tests 
- No code
Code changes
Side effects
```release-note
`None`.
```

cdc/kafka: remove skip-auto-create failpoint in kafka test

---

metrics/grafana/ticdc.json

Signed-off-by: just1900 <legendj228@gmail.com>
K8s community and organizations are increasingly deploying multiple Kubernetes clusters to improve availability, isolation and scalability. Since TiDB Operator have support [deploying tidb across-kubernetes](https://docs.pingcap.com/tidb-in-kubernetes/dev/deploy-tidb-cluster-across-multiple-kubernetes), this PR will address the multi-k8s issue without affecting existing single-cluster use case.
Issue Number: close #4665
What's Changed:
* add a k8s_cluster label in all expr
* add k8s_cluster variable in Grafana templating
How it works:
* For users with single-k8s, nothing need to be changed, just use it as before.
* For users with multi-k8s:
* first add `kubernetes` label to identify k8s cluster in your prometheus' `external_labels`.
* set …

metrics: support multi-k8s in grafana dashboards

---

tests/integration_tests/cyclic_ab/conf/diff_config.toml

Fix sync_diff_inspector compatible error for  cyclic.ab,
```
["failed to initialize diff process"] [error="from upstream: please make sure the filter is correct.: the target has no table to be compared. source-table is ``test`.`ineligible``"] [errorVerbose="the target has no table to be compared. source-table is ``test`.`ineligible`
```
Issue Number: close #4715
filter out ineligible tables
```release-note
`None`.
```

integration(test): fix sync_diff_inspector compatible error

---

tests/integration_tests/clustered_index/run.sh

Issue Number: close #4727 
Remove integration test clustered_index temporarily since kafka test fail
```release-note
`None`.
```

test(ticdc): skip kafka test for integration test clustered_index temporarily

---

pkg/p2p/client.go
pkg/p2p/client_test.go
pkg/p2p/internal/send_chan.go
pkg/p2p/internal/send_chan_test.go
pkg/p2p/server_client_integration_test.go

Issue Number: ref [microcosm#211](https://github.com/hanfei1991/microcosm/issues/211)
- Make it safe for multiple goroutines to send to the same message topic.
Tests 
- Unit test
```release-note
None
```

pkg/p2p(cdc,dataflow): Make it safe to write to the same topic concurrently

---

dm/pkg/schema/tracker_test.go
dm/syncer/error.go
go.mod
go.sum
pkg/errorutil/ignore.go

Issue Number: close #4812
update TiDB to support new syntax
Tests 
- Unit test
```release-note
`None`.
```

dep(dm): update tidb

---

dm/dm/master/shardddl/optimist_test.go

Issue Number: ref #4159 
- execute test serially
Tests 
- Unit test
```release-note
`None`.
```

unit_test: fix concurrency test cause etcd race

---

dm/dm/ctl/master/operate_schema.go
dm/dm/ctl/master/source_table_schema.go
dm/syncer/schema.go
dm/tests/shardddl1/run.sh

Issue Number: close #4547 
change default value of operate-schema --sync to true
Tests 
- Unit test
- No code
Code changes
Side effects
```release-note
sync schema to etcd when execute operate-schema command by default.
```

OperateSchema: change default value of operate-schema --sync to true

---

cdc/processor/pipeline/sorter.go
cdc/sorter/leveldb/leveldb.go
cdc/sorter/leveldb/message/task.go
cdc/sorter/leveldb/reader.go
cdc/sorter/leveldb/sorter.go
cdc/sorter/leveldb/sorter_test.go
cdc/sorter/leveldb/system/system.go
cdc/sorter/leveldb/system/system_test.go

Issue Number: close #4699
Needs to merge #4819 first.
StopMessage maybe lost if the total broadcast time exceeds  1s.
If sorter system actors does not close in time, systeam.closedWg is blocked.
Tests 
- Unit test
```release-note
Fix an issue that TiCDC can not exit.
```

sorter/leveldb(ticdc): fix system stop blocks forever

---

cdc/owner/changefeed_test.go
scripts/check-diff-line-width.sh

Issue Number: ref #4780 
Cc #4847
Correct line width limit.
Tests 
- No code
```release-note
None
```

scripts,owner(ticdc): correct line width limit

---

dm/pkg/checker/binlog.go
dm/pkg/checker/binlog_test.go

Issue Number: close #4959 
as title
Tests 
- Unit test
start task success with mariadb 10.1.2, there just one warning message
```
dmctl start-task tasks/task-from-mariadb.yaml
{
"result": true,
"msg": "",
"sources": [
{
"result": true,
"msg": "",
"source": "mariadb",
"worker": "worker1"
}
],
"checkResult": "fail to check synchronization configuration with type: no errors but some warnings
detail: {
"results": [
{
"id": 0,
"name": "mysql_version",
"desc": "check whether mysql version is satisfied",
"state": "warn",
"errors": [
{
"severity": "warn",
"short_error": "Migrating from MariaDB is experimentally supported. If you must use DM to migrate data from MariaDB, we suggest make your MariaDB \u003e= 10.1.2"
}
],
"extra": "address of db …
```

checker(dm): skip  check for mariadb some version

---

cdc/sink/producer/kafka/config_test.go
cdc/sink/producer/kafka/kafka_test.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/2164
migrate test-infra to testify for kafka producer.
Tests 
- Unit test
Code changes
Side effects
None
None
```release-note
None
```

sink/producer(ticdc): migrate test-infra to testify for kafka producer

---

cdc/processor/agent_test.go
pkg/p2p/client_test.go

Issue Number: close #4975 close #5012
- Loosened TestClientSendAnomalies. We accept apparent successes of sending messages after the client is closed.
- Replaced `require.Never` in `TestNoFinishOperationBeforeSyncIsReceived`, as `require.Never` will cause data races.
Tests 
- Unit test
```release-note
None
```

scheduler(cdc), tests: fix TestNoFinishOperationBeforeSyncIsReceived and TestClientSendAnomalies

---

cdc/sink/manager.go
cdc/sink/table_sink.go

Issue Number: close #5097
if flush failed, the returned checkpoint is not used by caller, so remove tableCheckpointTsMap from sink manager, it's useless.
Tests 
- Unit test
Code changes
Side effects
None
None
```release-note
`None`.
```

sink(ticdc): remove tableCheckpointTsMap from sink manager

---

cdc/sink/manager/kafka/manager.go
cdc/sink/manager/kafka/manager_test.go
cdc/sink/manager/manager.go
cdc/sink/manager/pulsar/manager.go
cdc/sink/mq.go
tests/integration_tests/multi_topics/run.sh

Issue Number: close https://github.com/pingcap/tiflow/issues/5076
make the topic manager use the correct number of partitions.
It uses the wrong number of partitions when kafka turns on auto-create configuration.
Tests 
- Unit test
Code changes
Side effects
None
None
```release-note
None
```

sink/mq(ticdc): make the topic manager use the correct number of partitions

---

cdc/sink/mq.go

Issue Number: ref #4623
#4609 removed error returned from `encoderBuilder.Build()`, so remove useless error check.
Tests 
- Unit test
```release-note
None
```

sink: remove useless error check

---

cdc/entry/mounter.go
cdc/entry/mounter_test.go
tests/integration_tests/multi_source/diff_config.toml

This is the batch cherry-pick of #3846 #3930
close issue：#3793 #3929 #3918
```release-note
Fix column default value type unsupported problem and data inconsistency issue.
```

Batch cherrypick default-value prs to release-5.2

---

cdc/processor/pipeline/sorter.go
cdc/processor/pipeline/table_actor.go
cdc/processor/pipeline/table_actor_test.go

Issue Number: close #5193 
add a `createSorter` method.
Tests 
- No code
Code changes
Side effects
```release-note
`None`.
```

processor(cdc): extract create sorter method

---

Makefile
dm/_utils/terror_gen/errors_release.txt
dm/dm/ctl/master/transfer_source.go
dm/dm/master/openapi_view.go
dm/dm/master/scheduler/scheduler.go
dm/dm/master/scheduler/scheduler_test.go
dm/dm/master/scheduler/worker.go
dm/dm/master/scheduler/worker_test.go
dm/dm/master/server.go
dm/dm/master/server_test.go
dm/dm/master/shardddl/optimist_test.go
dm/dm/worker/server_test.go
dm/errors.toml
dm/pkg/ha/bound.go
dm/pkg/ha/bound_test.go
dm/pkg/ha/doc.go
dm/pkg/ha/ops.go
dm/pkg/ha/relay.go
dm/pkg/ha/relay_test.go
dm/pkg/terror/error_list.go
dm/tests/dmctl_basic/run.sh
dm/tests/ha_cases/run.sh

Issue Number: close https://github.com/pingcap/tiflow/issues/4842
1. Support bind multi-sources for one worker
2. Support starting several relay sources on one worker.
Tests 
- Unit test
Code changes
Side effects
```release-note
support scheduler bound multi-sources for dm-workers
```

master/scheduler: support bound multi sources for dm-workers

---

dm/dm/worker/source_worker.go
dm/dm/worker/source_worker_test.go

Issue Number: close #5121
see #5121
Tests 
- Unit test
```release-note
Fix a bug that no data is return by `query-status` when upstream doesn't turn on binlog
```

worker(dm): fix no rows in SHOW MASTER STATUS will clear query-status

---

pkg/p2p/server_client_integration_test.go

Issue Number: close #5210 
- The previous workload of this test case is for `64` goroutines to use the same `MessageClient` to send messages, which can be too much for the CI's machine. The workload concurrency is reduced to `16` and the timeout is doubled.
Tests 
- Unit test
```
> go test . -test.run TestMessageClientBasicMultiTopics -test.count 1000 
ok  	github.com/pingcap/tiflow/pkg/p2p	62.062s
```
```release-note
None
```

pkg/p2p: reduce workload of TestMessageClientBasicMultiTopics

---

cdc/processor/agent_test.go
pkg/p2p/client_test.go

Issue Number: close #4975 close #5012
- Loosened TestClientSendAnomalies. We accept apparent successes of sending messages after the client is closed.
- Replaced `require.Never` in `TestNoFinishOperationBeforeSyncIsReceived`, as `require.Never` will cause data races.
Tests 
- Unit test
```release-note
None
```

scheduler(cdc), tests: fix TestNoFinishOperationBeforeSyncIsReceived and TestClientSendAnomalies (#5011)

---

cdc/owner/owner.go

Issue Number: ref #4774
- This PR is the combined cherry-pick of both #4775 and #4998
Tests 
- Unit test
- Manual test
```release-note
Fix TiCDC incorrectly display stale metrics data on dashboard.
```

owner(cdc): backport stale metrics fix to 5.4

---

dm/syncer/data_validator.go
dm/syncer/validator_checkpoint_test.go

Issue Number: close #5184 
put off initializing workers until start validator workers.
Tests 
Code changes
Side effects
```release-note
`None`
```

validator(dm): fix dmworker panic due to validator

---

cdc/sink/flowcontrol/flow_control.go
cdc/sink/flowcontrol/flow_control_test.go
cdc/sink/flowcontrol/main_test.go
cdc/sink/flowcontrol/table_memory_quota.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/5138
- make tests run and using testify
- refactor code, split file, rename fileds
Tests 
- Unit test
Code changes
Side effects
None
None
```release-note
None
```

sink/flowcontrol(ticdc): make tests run and refactor code

---

cdc/model/mounter.go
cdc/sink/mysql/txn_cache.go
cdc/sink/mysql/txn_cache_test.go
cdc/sorter/memory/entry_sorter.go
cdc/sorter/memory/entry_sorter_test.go
cdc/sorter/unified/heap.go

Issue Number: ref #5231
1. Make memory and unified sorter modules have the same sorting rules as the leveldb sorter
2. Use slices instead of maps in txnsWithTheSameCommitTs to support splitting transaction.
3. Refactor test cases to match real data, which is sorted by commitTs and startTs.
Tests 
- Unit test
Code changes
```release-note
`None`.
```

sink(ticdc): use slice in txnsWithTheSameCommitTs to support splitting transaction

---

dm/dm/config/source_config.go
dm/dm/master/bootstrap_test.go
dm/dm/master/server.go
dm/dm/master/server_test.go
dm/pkg/utils/common.go
dm/tests/all_mode/run.sh
dm/tests/case_sensitive/data/db2.prepare.sql
dm/tests/case_sensitive/run.sh

Issue Number: close #5255
OpenAPI needs automatically decides the case-sensitive from MySQL, but dmctl should keep the compatibility. So I split the two functions.
Tests 
Code changes
Side effects
```release-note
Fix DM can't replicate uppercase tables when the task has case-sensitive: false
```

master, config(dm): fix case-sensitive compatibility for dmctl

---

cdc/kv/client.go
cdc/kv/region_worker.go
cdc/model/changefeed.go
cdc/model/sink.go
cdc/owner/changefeed.go
cdc/sink/mq/mq.go
cdc/sink/mq/producer/kafka/config.go
cdc/sink/mysql/mysql.go
cdc/sink/mysql/txn_cache.go
cdc/sorter/unified/file_backend.go
cdc/sorter/unified/heap_sorter.go
cdc/sorter/unified/memory_backend.go
cdc/sorter/unified/merger.go
pkg/cyclic/filter.go
pkg/orchestrator/etcd_worker.go
pkg/p2p/client.go
scripts/check-log-style.sh

Issue Number: close #5324
related to https://github.com/pingcap/tiflow/pull/5296#discussion_r862283378
Change the zap filed regex pattern to fix some un cached log style
```diff
-grep -RnE "zap.[A-Z][a-z]+
+grep -RnE "zap.[A-Z][a-zA-Z0-9]+
```
- This change catches `zap.Int64`, `zap.ByteStrings` etc.
```diff
-(\"[0-9A-Za-z]*[-_ ][0-9A-Za-z]*\"(,|\))"
+(\"[0-9A-Za-z]*[-_ ][^\"]*\"(,|\))"
```
- This change catches `zap.Int("num of Rows", dmls.rowCount),`, `zap.Uint64("expected-num-events", r.totalEvents),` etc.
Tests 
- Unit test
Code changes
Side effects
-  **Has several zap fields change in log, but user should not relay on log contents, so it is all right to break the complexity**
```release-note
Change all variable names to camelCase in logs
```

scripts: fix un-catched pattern in check log style

---

cdc/sink/buffer_sink_test.go
cdc/sink/codec/avro_test.go
cdc/sink/codec/canal_flat_test.go
cdc/sink/codec/canal_test.go
cdc/sink/codec/codec_test.go
cdc/sink/codec/config_test.go
cdc/sink/codec/craft/codec_test.go
cdc/sink/codec/craft_test.go
cdc/sink/codec/interface_test.go
cdc/sink/codec/json_test.go
cdc/sink/codec/main_test.go
cdc/sink/codec/maxwell_test.go
cdc/sink/codec/schema_registry_test.go
cdc/sink/main_test.go
cdc/sink/mq/mq_test.go
cdc/sink/mysql/causality_test.go
cdc/sink/mysql/main_test.go
cdc/sink/mysql/txns_heap_test.go
cdc/sink/sink_manager_test.go
cdc/sink/sink_test.go

Issue Number: close #2907
Tests 
- Unit test
```release-note
`None`.
```

sink(ticdc): migrate test-infra to testify for cdc/sink 

---

cdc/capture/capture.go
cdc/kv/client.go
cdc/kv/client_bench_test.go
cdc/kv/client_test.go
cdc/puller/puller.go
cdc/puller/puller_test.go
pkg/httputil/httputil.go
pkg/pdutil/clock.go
pkg/pdutil/clock_test.go
pkg/pdutil/main_test.go
pkg/pdutil/region_label.go
pkg/pdutil/region_label_test.go
pkg/txnutil/gc/gc_manager.go
pkg/txnutil/gc/gc_manager_test.go
pkg/upstream/upstream.go
tests/integration_tests/simple/run.sh

Issue Number: close #4756 close #4762 
TiDB related issues, ref: https://github.com/pingcap/tidb/issues/33665
1. Add new pdutil pkg to support `region label`
2. Verify meta-related label rules when init `upstream`
Tests 
- Unit test
Code changes
Side effects
```release-note
`Add support for region-label to enable meta-region isolation`
```

owner(ticdc): Add support for region-label to enable meta-region isolation

---

tests/integration_tests/move_table/main.go

Issue Number: ref #5301
fix move table integration test
Tests 
- Unit test
Code changes
Side effects
```release-note
`None`.
```

test(ticdc): fix move table integration test

---

dm/pkg/schema/tracker.go
dm/pkg/schema/tracker_test.go
dm/syncer/syncer_test.go

Issue Number: ref #5334
sometimes unistore folder is abnormally big, we add task name to the folder name to know which task it belongs.
Also, clean that folder for unit tests by `Close()` 
Tests 
- Unit test
Code changes
Side effects
```release-note
`None`.
```

tracker(dm): add task name to unistore folder name

---

dm/pkg/gtid/gtid.go
dm/pkg/gtid/gtid_test.go
dm/relay/local_reader_test.go
dm/tests/incremental_mode/conf/dm-task.yaml
dm/tests/incremental_mode/conf/source1.yaml
dm/tests/incremental_mode/data/db1.prepare.sql
dm/tests/incremental_mode/data/db2.prepare.sql
dm/tests/incremental_mode/run.sh

Issue Number: close #3731 
mariadb could use 0-0-0 as empty gtid config
- support user to use uuid:0 as mysql empty gtid config
Tests 
- Manual test (mariadb)
Code changes
Side effects
```release-note
Support start an incremental task with nil MySQL GTID set.
```

syncer: support start from empty gtid config

---

cdc/processor/pipeline/sink_test.go
cdc/sink/black_hole.go
cdc/sink/mq/mq.go
cdc/sink/mysql/mysql.go
cdc/sink/mysql/mysql_test.go
cdc/sink/mysql/simple_mysql_tester.go
cdc/sink/sink.go
cdc/sink/table_sink.go
pkg/applier/redo.go

Issue Number: close https://github.com/pingcap/tiflow/issues/5425
- Rename Init to AddTable
- Rename Barrier to RemoveTable
- Remove TryEmitRowChangedEvents
- Better comments
Tests 
- No code
Code changes
Side effects
None
None
```release-note
None
```

sink(ticdc): refactor sink interface

---

.github/pull_request_template.md
README.md
README_TiCDC.md

Issue Number: ref https://github.com/pingcap/tiflow/issues/3194
- improve README.md, TiCDC currently does not support `cdc-log`
- The PR template is too complex and difficult for people to fill in, so simplify it.
Tests 
- No code
```release-note
None
```

github(both): improve README.md and simplify PR templates

---

cdc/sink/mysql/mysql.go
cdc/sink/mysql/mysql_test.go
cdc/sink/mysql/mysql_worker.go
cdc/sink/mysql/txn_cache.go
cdc/sink/mysql/txn_cache_test.go

Issue Number: close #5107
- When mysql Sink traverses the`tableMaxResolvedTs ` at this [line](https://github.com/pingcap/tiflow/blob/f3bf091a656301a59f2c98fff0ed5e49355d49e8/cdc/sink/mysql/mysql.go#L272), the map may have been concurrently modified, [which will result in an incorrect value being saved to`tableCheckpointTs `](https://github.com/pingcap/tiflow/blob/f3bf091a656301a59f2c98fff0ed5e49355d49e8/cdc/sink/mysql/mysql.go#L273).
To solve this problem, we need to: 
1. Save the resolvedTs, which are used to [search data](https://github.com/pingcap/tiflow/pull/5418/files#diff-ab73e67a0b47a3a9537743cf306c53bbf2247b8b53e8a1998ac3529e4c2d41b9R145) from txnCache, into the [flushedResolvedTsMap](https://github.com/pingcap/tiflow/pull/5418/files#diff-ab73e67a0b47a3a9537743cf306c53bbf2247b8b53e …

sink(ticdc): store checkpointTs by flushedResolvedTsMap in mysql sink

---

cdc/entry/mounter.go
cdc/entry/mounter_test.go
cdc/model/sink.go
cdc/sink/codec/avro.go
cdc/sink/codec/avro_test.go
cdc/sink/codec/schema_registry.go
tests/integration_tests/multi_changefeed/run.sh

Issue Number: ref #5338 
```release-note
None
```

sink/codec(cdc): add message size check and support schema default

---

cdc/entry/mounter.go
cdc/model/mounter.go
cdc/processor/pipeline/cyclic_mark.go
cdc/processor/pipeline/cyclic_mark_test.go
cdc/processor/pipeline/sink.go
cdc/processor/pipeline/sink_test.go
cdc/processor/pipeline/table.go
cdc/processor/pipeline/table_actor.go
cdc/processor/pipeline/table_actor_test.go
cdc/sink/black_hole.go
cdc/sink/mq/mq.go
cdc/sink/mq/mq_flush_worker.go
cdc/sink/mq/mq_flush_worker_test.go
cdc/sink/mq/mq_test.go
cdc/sink/mysql/mysql.go
cdc/sink/mysql/mysql_test.go
cdc/sink/mysql/simple_mysql_tester.go
cdc/sink/mysql/txn_cache.go
cdc/sink/mysql/txn_cache_test.go
cdc/sink/sink.go
cdc/sink/table_sink.go
cdc/sorter/leveldb/writer.go
cdc/sorter/memory/entry_sorter.go
cdc/sorter/memory/entry_sorter_test.go
cdc/sorter/unified/heap_sorter.go
cdc/sorter/unified/merger.go
cdc/sorter/unified/unified_sorter.go
cmd/kafka-consumer/main.go
pkg/applier/redo.go

Issue Number: close #5398
1. Add batch field to resolveTs
2. Added batch Resolved semantics support to Sink's `FlushRowChangedEvents` interface:
-  With `resolved.Batch == false`, TiCDC guarantees that all the Events whose commitTs is less than or equal to `resolved.Ts` are sent to Sink through `EmitRowChangedEvents`.
-  With `resolved.Batch == true`, TiCDC guarantees that all events whose commitTs is less than 'resolved.Ts' are sent to Sink.
Tests 
- Unit test
Code changes
Side effects
```release-note
`None`.
```

sink(ticdc): add batch field to resolveTs

---

tests/integration_tests/http_api/run.sh

Issue Number: close #5474 
Our CI envs still default to python2 to run tests. `http_api` requires using `requests` which brings `certifi`. Actually `certifi`'s recent releases doesn't support python2 any more.
```release-note
None
```

tests: use python3 to run http_api test to fix failed integration_tests

---

cdc/sink/mq/codec/config.go
cdc/sink/mq/codec/config_test.go
docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/cmd/cli/cli_changefeed_create.go
pkg/cmd/cli/cli_changefeed_update.go
pkg/cmd/cli/cli_changefeed_update_test.go
pkg/config/config_test_data.go
pkg/config/replica_config.go
pkg/config/sink.go

Issue Number: ref #5338 
1. `schema-registry` option should accompany  the `protocol` option under `sink` section. Otherwise, it's really unnatural.
2. support update `schema-registry` from cli and file.
```release-note
None
```

sink/codc(ticdc): fix schema-registry options in cli & config file

---

cdc/api/open.go
pkg/httputil/httputil.go

Issue Number: close #5482 
Very simple in code.
After this PR OpenAPI works normally.
```release-note
`fix openapi do not work on non-owner node`.
```

open (ticdc): fix openapi do not work on non-owner node

---

dm/syncer/syncer.go
dm/syncer/util.go
dm/tests/openapi/run.sh
dm/tests/start_task/run.sh

Issue Number: close #5471
as title
- Unit test
- No code
```release-note
fix parsing task start-time using downstream timezone problem.
```

dm: parse start-time using upstream timezone

---

.github/workflows/dataflow_engine_e2e.yaml

Issue Number: ref #5352
- Run dataflow engine e2e tests when changed code in path `dm/**`
```release-note
None
```

ci(engine,dm): enable dataflow engine e2e test in dm

---

engine/lib/worker.go
engine/lib/worker_test.go

Issue Number: close #5523 
Set the error on errCenter when call 'Exit'
- Unit test
```release-note
`None`.
```

worker[engine]: fix bug that worker impl call 'Exit', but may not return

---

engine/test/e2e/dm-job.yaml
engine/test/e2e/e2e_dm_test.go

add test of two running jobs, so we can test about metrics later
- No code
```release-note
`None`.
```

e2e(engine): test two running DM jobs

---

cdc/entry/mounter.go
cdc/kv/client.go
cdc/kv/matcher.go
cdc/kv/matcher_test.go
cdc/kv/region_worker.go
cdc/kv/region_worker_test.go
cdc/model/kv.go
cdc/model/kv_test.go

Issue Number: ref #5468
See #5477
- Unit test
```release-note
Fix data loss when upstream transaction conflicts during cdc reconnection 
```

kv(ticdc): fix data loss when upstream txn conflicts during scan (#5477)

---

engine/client/task_dispatcher.go
engine/client/task_dispatcher_test.go
engine/lib/master/worker_manager_test.go

Issue Number: close #5589 
- Abort the dispatch appropriately if `PreDispatchTask` has failed.
- Unit test
```release-note
None
```

lib/master(engine): fix PreDispatch failure handling

---

cdc/model/sink.go
cdc/model/sink_test.go
cdc/sink/mq/codec/avro.go
cdc/sink/mq/codec/avro_test.go
tests/mq_protocol_tests/cases/case_handle_key.go
tests/mq_protocol_tests/main.go

Issue Number: close #5597 
Avro shall use Handle Key as message key in case when there is no primary key, we could still try to use a not null unique key , makes downstream easy to use these events.
When there is no handle key, such as force replica situations, Avro message keys would be null. Downstream consumers need to accomodate for this. (This is already the current behavriour)
```release-note
None
```

codec(ticdc): use handlekey instead of primary key for avro

---

dm/dm/common/common.go
dm/dm/ctl/master/config.go
dm/pkg/ha/relay.go
dm/pkg/upgrade/upgrade.go
dm/pkg/upgrade/upgrade_test.go
go.mod

Issue Number: close https://github.com/pingcap/tiflow/issues/5099
Support rolling upgrade in dm. We didn't keep old dm etcd keys to avoid users deploy both old/new versions of dm-workers.
Tests 
- Unit test
Code changes
Side effects
- None
```release-note
None
```

dm/ha: rolling update support to new etcd keys

---

cdc/metrics.go
dm/dm/worker/metrics.go
engine/pkg/promutil/registry.go

Issue Number: close #5494
add flag for smooth transition, see more in  https://github.com/prometheus/client_golang/releases/tag/v1.12.2
and https://github.com/pingcap/tiflow/pull/5393#discussion_r884428789
the breaking changed metrics are not used in our code
* go_gc_heap_allocs_by_size_bytes_total -> go_gc_heap_allocs_by_size_bytes,
* go_gc_heap_frees_by_size_bytes_total -> go_gc_heap_allocs_by_size_bytes
* go_gc_pauses_seconds_total -> go_gc_pauses_seconds.
```release-note
`None`.
```

metrics(*): fix for promtheus_client breaking change

---

cdc/owner/changefeed_test.go
cdc/redo/reader/file_test.go
cdc/redo/reader/reader_test.go
cdc/redo/writer/file_test.go
cdc/redo/writer/writer_test.go
dm/pkg/storage/utils_test.go
dm/relay/meta_test.go
dm/relay/purger_helper_test.go
dm/relay/purger_test.go
dm/syncer/checkpoint_test.go
engine/pkg/etcdutils/join_test.go
engine/servermaster/etcd_test.go
engine/servermaster/server_test.go
pkg/cmd/util/helper_test.go
pkg/etcd/client_test.go
pkg/etcd/etcd_test.go
pkg/logutil/log_test.go
pkg/orchestrator/etcd_worker_test.go

Issue Number: close #5659
This pull request replaces `ioutil.TempDir` and `os.MkdirTemp` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
require.NoErrror(t, err)
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
- Unit test
- No code
No
No
```release-note
None
```

test: use `T.TempDir` to create temporary test directory

---

engine/pkg/promutil/registry.go
engine/pkg/promutil/registry_test.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/5673
Problem Summary:
Avoid embedding `Mutex` and `prometheus.Registry` in `Registry`. 
Refer to uber go style:
* https://github.com/uber-go/guide/blob/master/style.md#avoid-embedding-types-in-public-structs
* https://github.com/uber-go/guide/blob/master/style.md#zero-value-mutexes-are-valid
Make `Mutex` and `prometheus.Registry` become private normal members.
- Unit test
```release-note
None
```

promutil(engine): avoid embedding Mutex and prometheus.Registry in Registry

---

dm/syncer/checkpoint.go
dm/tests/_utils/check_process_exit
dm/tests/sequence_sharding_optimistic/run.sh
dm/tests/start_task/run.sh
dm/tests/tracker_ignored_ddl/run.sh

- integration tests
- Manual test 
test case downstream_more_column failed before this PR, and passed after this PR
```release-note
```

syncer(dm): update memory cache after FlushPointWithTableInfo

---

cdc/scheduler/internal/tp/agent.go
cdc/scheduler/internal/tp/agent_bench_test.go
cdc/scheduler/internal/tp/agent_test.go
cdc/scheduler/internal/tp/coordinator_test.go

Issue Number: close #4757 
add more unit test to cover agent implementation.
- Unit test
```release-note
`None`
```

fb/latency(cdc): add more unit test to agent 

---

cdc/owner/changefeed.go
cdc/processor/processor.go
cdc/processor/processor_test.go
cdc/scheduler/internal/tp/agent.go
cdc/scheduler/internal/tp/capture_manager.go
cdc/scheduler/internal/tp/capture_manager_test.go
cdc/scheduler/internal/tp/coordinator.go
cdc/scheduler/internal/tp/coordinator_test.go
cdc/scheduler/internal/tp/replication_manager.go
cdc/scheduler/internal/tp/replication_manager_test.go
cdc/scheduler/internal/tp/replication_set.go
cdc/scheduler/internal/tp/replication_set_test.go
cdc/scheduler/internal/tp/scheduler_balance.go
cdc/scheduler/internal/tp/scheduler_balance_test.go
cdc/scheduler/internal/tp/transport.go
cdc/scheduler/internal/tp/transport_test.go
cdc/scheduler/rexport.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/4757
Integrate two-phase scheduler and fix two bug
* Fix duplicate topic handlers panic
* Add From to messages from scheduler
* Fix missing processor epoch
* Fix missing checkpoint ts in burstBalanceTask
* Fix lost AddTable request during Commit 
- Unit test
```release-note
None
```

cdc: integrate two phase scheduler

---

cdc/processor/processor.go
cdc/scheduler/internal/tp/agent.go
cdc/scheduler/internal/tp/agent_test.go

for remove table request, check if the target exist before process the request.
- Unit test
```release-note
`None`
```

fb/latency(cdc): agent fix inconsistent state by tolerant duplicate messages.

---

cdc/api/middleware/middleware.go
cdc/api/v1/api.go
cdc/api/v2/api.go
cdc/capture/capture.go
errors.toml
pkg/cmd/cli/cli_changefeed_resume.go
pkg/errors/errors.go
pkg/etcd/etcd.go
pkg/etcd/etcd_test.go
pkg/etcd/etcdkey.go
pkg/etcd/testing.go
pkg/migrate/migrate.go
pkg/migrate/migrate_test.go
pkg/orchestrator/etcd_worker.go
pkg/orchestrator/etcd_worker_bank_test.go
pkg/orchestrator/etcd_worker_test.go
pkg/pdutil/pd_api_client.go
pkg/pdutil/pd_api_client_test.go
pkg/txnutil/gc/gc_manager.go
pkg/txnutil/gc/gc_service.go
pkg/txnutil/gc/testing.go
pkg/upstream/manager.go
pkg/upstream/manager_test.go
pkg/upstream/upstream.go
tests/integration_tests/availability/capture.sh
tests/integration_tests/availability/owner.sh
tests/integration_tests/changefeed_error/run.sh
tests/integration_tests/processor_resolved_ts_fallback/run.sh
tests/utils/cdc_state_checker/cdc_monitor.go

Issue Number: ref #5663 
1. remove /tidb/cdc gc service safe point after the migration is done
2. add upstream info
3. if server is not ready, return error
- Unit test
```release-note
`None`.
```

http&migration(ticdc): Return http error if server is not ready

---

cdc/metrics.go
cdc/scheduler/internal/tp/capture_manager.go
cdc/scheduler/internal/tp/capture_manager_test.go
cdc/scheduler/internal/tp/coordinator.go
cdc/scheduler/internal/tp/coordinator_test.go
cdc/scheduler/internal/tp/metrics.go
cdc/scheduler/internal/tp/replication_manager.go
cdc/scheduler/internal/tp/replication_manager_test.go
cdc/scheduler/internal/tp/replication_set.go
cdc/scheduler/internal/tp/replication_set_test.go
cdc/scheduler/rexport.go

Add metrics
- Unit test
```release-note
None
```

tp: add metrics

---

cdc/scheduler/internal/info_provider.go
cdc/scheduler/internal/tp/coordinator.go
cdc/scheduler/internal/tp/info_provider.go
cdc/scheduler/internal/tp/info_provider_test.go

Add info provider for two-phase scheduler.
- Unit test
```shell
curl http://${CDC_ADDR}/api/v1/changefeeds/blackhole
```
```release-note
None
```

tp: add info provider

---

cdc/model/mounter_test.go

Issue Number: close #5854
Make sure that `ts` of largerBatchResolvedTs is greater than that of normalResolvedTs.
- Unit test
```release-note
`None`.
```

tests(ticdc): fix unstable TestResolvedTs
