pingcap/tiflow

.codecov.yml
Makefile
README.md

1. add unit test coverage, use https://codecov.io/
2. add more badges
Tests 
- Unit test

Add coverage report and more badges

---

cdc/kv/client.go

fix endless retry in singleEventFeed
just remove the for loop in `singleEventFeed` and return the error if create stream fails.
handle the error outside, retry for Unavailable
also, increase max retry time, know the previous time may too quick to fail, setting 10 will fail after near 50~60 second with the Backoff strategy in the `retry` pkg wrap. 
Tests 
restart tikv, may see the relate error and recreate singleEventFeed

fix endless retry in singleEventFeed

---

Makefile
main_test.go
tests/_utils/run_cdc_server
tests/_utils/start_tidb_cluster
tests/multi_capture/conf/workload1
tests/multi_capture/conf/workload2
tests/multi_capture/run.sh
tests/simple/run.sh
tests/split_region/run.sh

Add integration test support in CI
- run integration test in CI
- collect coverage combining integration test and unit test and upload to coveralls.io
Tests 
- Unit test

support integration test in CI

---

cdc/processor_test.go
cdc/sink/mysql.go
cdc/sink/sink.go

Get Sink.Emit ready for bulk processing.
Make `Sink.Emit` accept varargs.
Tests 
- Unit test

Get Sink.Emit ready for bulk processing

---

cdc/metrics_processor.go
cdc/processor.go
cdc/puller/metrics.go
cdc/puller/puller.go

Need to add more metrics to make cdc more obersevable.
Add some new metrics:
1. The time taken to update sub change feed info.
1. The number of events received by puller.
Tests 
- Unit test

Add more metrics

---

cdc/processor.go

We didn't utilize the bulk interface of Sink.
Emit in bulk instead of saving txns one by one.
Tests 
- Unit test

Emit in bulk in syncResolved

---

ticdc.json

Add grafana dashboard ticdc.json
write it while doing #198 
we can continue to improve it later and add more metrics
Add grafana dashboard ticdc.json
some screen shot
Tests 
- No code

Add grafana dashboard ticdc.json

---

cdc/entry/mounter.go
cdc/model/txn.go
cdc/owner_operator.go
cdc/schema/storage.go
tests/cdc/cdc.go
tests/cdc/run.sh
tests/dailytest/case.go
tests/dailytest/dailytest.go
tests/run.sh
tests/util/db.go

test: switch on binlog test, part 1

---

tests/cdc/run.sh
tests/dailytest/case.go

Fix CI and close the unstable test case

test: fix ci and close the unstable test case

---

cdc/schema/storage.go

A dependency is not imported after the previous concurrent merges of #219 and #215.
Restore the import.
Tests 
- Unit test

Fix a missing import

---

cdc/entry/kv_entry_test.go
cdc/entry/mounter.go
cdc/entry/mounter_test.go
cdc/puller/mock_puller.go
cdc/schema/storage.go
cdc/schema/storage_test.go
cdc/sink/mysql.go
go.sum
tests/_utils/stop_tidb_cluster
tests/cdc/run.sh
tests/dailytest/dailytest.go

1. fix bug: mysql sink build sql query mistakenly
2. remove useless log
3. open test: open some tests
Tests 
- Unit test

test: fix bug and open tests

---

cdc/model/changefeed.go
cdc/model/changefeed_test.go

https://github.com/pingcap/tidb/pull/13757 introduces a new system schema `METRIC_SCHEMA`
Add it to system schema list
Tests 
- Unit test

Add one more TiDB system schema

---

cdc/capture.go
cdc/kv/etcd.go
cdc/kv/etcd_test.go
cdc/model/errors.go
cdc/model/owner.go
cdc/model/owner_test.go
cdc/owner.go
cdc/owner_test.go
cdc/processor.go
cdc/processor_test.go
cdc/roles/storage/etcd.go
cdc/roles/storage/etcd_test.go
cdc/scheduler.go
cdc/scheduler_test.go
cmd/ctrl.go

Uniform terminology：rename subchangefeed info to task status

rename subchangefeed info to task status

---

cdc/model/changefeed.go
cdc/model/changefeed_test.go
cdc/model/config.go
cdc/owner.go
cdc/processor.go
cmd/cdc.toml
cmd/client.go
cmd/cmd_test.go

Support ignore some txn by `CommitTs`
Add an `ignore-txn-commit-ts` parameter.
Tests 
- Unit test

Add ignore-txn-commit-ts to skip some txn

---

cdc/kv/client.go
cdc/kv/client_test.go

fix data race about checkpoint ts
Tests 
- Unit test

kvclient: fix data race about checkpoint ts

---

cdc/capture.go
cdc/filter.go
cdc/filter_test.go
cdc/model/changefeed.go
cdc/model/errors.go
cdc/model/owner.go
cdc/owner.go
cdc/owner_test.go
cdc/processor.go
cdc/processor_test.go
cdc/roles/storage/etcd.go
cdc/roles/storage/etcd_test.go
cdc/scheduler.go
cdc/scheduler_test.go
cmd/debug.go
tests/util/db.go

1. remove `Status` field in `ChangefeedInfo`
2. remove some function about `filter` of `ChangefeedInfo` and add struct `TxnFilter`
3. Adjustment the responsibility of `owner` and `changfeed`
Tests 
- Unit test

refactoring: ChangefeedInfo struct

---

cdc/processor.go

filter the job which is not synced or done
Tests 
- Unit test

bugfix: filter the job which is not synced or done

---

tests/row_format/conf/diff_config.toml
tests/row_format/data/prepare.sql
tests/row_format/run.sh

add an integration test for new row format
Tests 
- Unit test
- No code
Code changes
Side effects

test: add an integration test for new row format

---

cdc/kv/client.go
pkg/etcd/etcd.go

Some random cleanups done while read related code.
1. Change some variable names to improve readability
1. Add a missing error check
1. Reduce nested level of some code
Tests 
- Unit test

*: random cleanups

---

cdc/kv/etcd.go
cdc/kv/etcd_test.go
cdc/owner.go
cdc/owner_test.go
cdc/roles/storage/etcd.go
cdc/roles/storage/etcd_test.go

The `ChangeFeedRWriter` interface is really uglily and hard to use. This pr refactor the `ChangeFeedRWriter` interface and remove `ChangeFeedRWriter` struct
Tests 
- Unit test

etcd: refactor the ChangeFeedRWriter interface

---

tests/dailytest/db.go
tests/util/db.go

Currently we have too many diff log in integration test
As we have many rounds of diff check, set log-level to `Warn` for each round, except for the last check round, which is set log-level to `Info`
Tests 

tests: refine log level to reduce noise log

---

cdc/kv/client.go

The current kv client has several problems:
- only have limited retry for some retryable error.
- print too many noise logs if the event feed is canceled from the outer context
- not handle cancel error in some cases
- use rate limit for singleEventFeed instead of limited retry
- don't print EventFeed disconnected when meeting context.Canceled error
- exits silently when meeting context.Canceled error
Tests 
- Unit test

refine error handling in kv client

---

Dockerfile

Support to build a docker image
Add the `Dockerfile` so we can deploy cdc in the docker image.
Tests 
```
docker build .
```

build: add the Dockerfile

---

cdc/metrics_processor.go
cdc/processor.go
cdc/puller/buffer.go
cdc/puller/metrics.go
cdc/puller/puller.go
ticdc.json

we should monitor whether some buffer or channel is blocked
add metrics to monitor length of channel or buffer in replication path
Tests 
- Unit test

add metrics to chan or buffer in replication path

---

cdc/model/errors.go
cdc/model/kv.go
cdc/puller/entry_sorter.go
cdc/puller/entry_sorter_test.go
cdc/puller/mock_puller.go
cdc/puller/puller.go
tests/run.sh

support to output sorted row-based changed event
Tests 
- Unit test

puller: support to output sorted row-based changed event, part one

---

docs/design/2020-02-24-ticdc-mq-protocol-chinese-version.md

add a rfc about mq protocol in chinese

---

cdc/sink/mysql.go
cdc/sink/mysql_test.go

fix #273 
- treat uri as truely uri but compatible with the dsn
- support `worker-count` param
- set `SetMaxIdleConns`(default only 2 will cause create new connections every time)  and `SetOpenConns`
Tests 
- Unit test
Code changes

Configurable worker count

---

cdc/entry/kv_entry_test.go
cdc/entry/mounter.go
cdc/entry/mounter_test.go
cdc/entry/schema_builder.go
cdc/entry/schema_builder_test.go
cdc/entry/schema_storage.go
cdc/entry/schema_storage_test.go
cdc/filter_test.go
cdc/model/owner_test.go
cdc/model/row.go
cdc/owner.go
cdc/owner_operator.go
cdc/owner_test.go
cdc/processor.go
cdc/processor_test.go
cdc/puller/entry_sorter.go
cdc/puller/entry_sorter_test.go
cdc/puller/mock_puller_test.go
cdc/puller/puller.go
cdc/roles/storage/etcd.go
cdc/roles/storage/etcd_test.go
cdc/scheduler.go
cdc/sink/mysql.go
cdc/sink/mysql_test.go
cdc/sink/sink.go
cmd/debug.go
go.mod

fix #272 , #265 
this pr can pass the integration test now
Tests 
- Unit test
- No code
Code changes
Side effects

sink: handle row-based changed event in sink, part four

---

cmd/client.go

part of #267 
Check the changefeed `StartTs` must not be less than tikv_gc_safe_point
Tests 
- Unit test

cmd: check start ts larger than tikv_gc_safe_point

---

cdc/sink/mysql.go

We can let sink replicate data as soon as the global resolved ts is forwarded in MySQL sink.
use a channel to notify the global resolved ts forward in mysql sink, instead of a sleep way
Tests 
- Unit test

sink: use chan to notify resolved ts forward in mysql sink

---

cdc/sink/mq.go
cdc/sink/mysql.go
cdc/sink/sink.go

implement print status interface
Tests 
- Unit test

kafka sink: implement print status interface

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md

add issue template
none
Tests 
- No code

add issue template

---

CHANGELOG.md

- add changelog file
- add changelog for v4.0.0-beta.2
none
Tests 
- No code

add Changelog for v4.0.0-beta.2 release

---

scripts/jenkins_ci/cdc_ghpr_build.groovy
scripts/jenkins_ci/cdc_ghpr_check.groovy
scripts/jenkins_ci/cdc_ghpr_integration_test.groovy
scripts/jenkins_ci/cdc_ghpr_test.groovy
tools/check/check-tidy.sh

* move jenkins_ci script into the repo
* refine integration test ci script

ci: move jenkins_ci script into the repo

---

Makefile
kafka_consumer/main.go
scripts/jenkins_ci/cdc_ghpr_integration_test.groovy
scripts/jenkins_ci/cdc_ghpr_kafka_integration_test.groovy
scripts/jenkins_ci/integration_test_common.groovy
tests/_utils/run_kafka_consumer
tests/cdc/run.sh
tests/multi_capture/run.sh
tests/row_format/run.sh
tests/run.sh
tests/simple/run.sh
tests/split_region/run.sh

Tests 
- Unit test
- No code
Code changes
Side effects

ci: add kafka integration test

---

cdc/entry/schema_storage.go
cdc/owner.go
cdc/processor.go

Some log output is misleading
refine log
Tests 
- Unit test

refine log output

---

cdc/entry/schema_builder.go
cdc/kv/client.go
cdc/processor.go
cdc/roles/storage/etcd.go
cdc/sink/mq.go
cdc/sink/mysql.go
pkg/retry/retry.go
pkg/retry/retry_test.go

expose initial interval of retry function
Tests 
- Unit test

util: expose initial interval of retry function

---

cdc/capture.go
cdc/owner.go
cdc/sink/sink.go

fix block when the `run` function of `owner` returns an error
Tests 
- Unit test

fix block when the `run` function of `owner` returns an error

---

cdc/entry/schema_storage.go
cdc/model/sink.go
cdc/owner.go

fix lower case schema name
Tests 
- Unit test

bugfix: fix lower case schema name

---

cdc/sink/mq.go
cdc/sink/mqProducer/kafka.go

Tests 
- Unit test
- No code
Code changes
Side effects

config max kafka msg

---

scripts/jenkins_ci/integration_test_common.groovy

Support specify tidb/pd/tikv version in test
use example:
`/run-integration-tests tikv=release-4.0` or `/run-integration-tests tikv=pr/xxx`
Tests 

scripts: support specify tidb/pd/tikv version in test

---

cdc/processor.go
cdc/puller/entry_sorter.go
cdc/puller/metrics.go
cdc/scheduler.go
cdc/sink/metrics.go
cdc/sink/mq.go
ticdc.json

add some chan size metrics
Tests 
- Unit test

add more chan size metrics

---

cdc/puller/entry_sorter.go
ticdc.json

fix metrics in entry sorter
Tests 
- Unit test

fix entry sorter metrics

---

cdc/entry/metrics.go
cdc/entry/mounter.go
cdc/sink/black_hole.go
cdc/sink/sink.go

add metrics in mounter and blackhole sink
Tests 
- Unit test

add metrics in mounter and blackhole sink

---

cdc/kv/client.go

The replication forward will totally depend on the ResolvedTs event from
remove kv sorter
Tests 
- Unit test

kv-client: remove kv sorter

---

cdc/entry/mounter.go
cdc/model/mq.go
cdc/model/sink.go
cdc/processor.go
cdc/sink/mq.go
cdc/sink/mqProducer/kafka.go
cdc/sink/mysql.go

crop message size of kafka producer
support compression for kafka producer
Tests 
- Unit test

kafka: crop message size of kafka producer

---

cdc/kv/client.go

pre-set prometheus label values if needed in kv client
Tests 
- Unit test

kv-client: decrease metrics init cpu consume

---

cdc/entry/metrics.go
cdc/entry/mounter.go
cdc/metrics.go
cdc/owner_operator.go
cdc/processor.go
cdc/puller/buffer.go
cdc/puller/entry_sorter.go
cdc/puller/metrics.go
cdc/puller/puller.go
cdc/sink/metrics.go
cdc/sink/mq.go
pkg/util/ctx.go
ticdc.json

add more metrics
- resolved ts sent from mounter
- resolved ts sent after region spans forward
- entry sorter metrics
Tests 
- Unit test

Add more resolved ts related metrics

---

cdc/entry/mounter.go
cdc/entry/schema_storage.go
cdc/processor.go
cdc/puller/buffer.go

Tests 
- Unit test
- No code
Code changes
Side effects

mounter: decode raw row value concurrently (for test)

---

tests/_utils/start_tidb_cluster
tests/availability/owner.sh
tests/availability/run.sh

Should be merged after #425 
Add integration test script for owner HA
Closes #406

integration: add ha test for owner

---

tests/availability/capture.sh
tests/availability/run.sh

This is a PR based on #420
Add test script for capture HA test
Closes #408

ci: add capture HA test

---

cdc/changefeed.go
cdc/owner.go
cdc/processor.go
cdc/roles/storage/etcd.go
cdc/roles/storage/etcd_test.go

owner: add lock for adding table

---

cdc/owner_operator.go

Closes #442 
Check the nil value and skip if is

owner: check if the returned event is nil

---

cdc/processor.go
tests/availability/capture.sh
tests/availability/owner.sh
tests/availability/processor.sh
tests/availability/run.sh

This is a PR based on #428
Add test for stopping and resuming the processors
Closes #407

ci: add processor HA test

---

cdc/model/mounter.go
cdc/processor.go

fix the block in WaitPrepare function
Tests 
- Unit test

mounter: fix the block in WaitPrepare function

---

cdc/kv/etcd.go
cdc/model/owner.go
cmd/client.go
cmd/ctrl.go

`cdc cli processor list` is removed in #371 by accident
Add it back
Tests 
- Unit test

cmd: readd processor list command

---

cdc/entry/metrics.go
cdc/entry/mounter.go
cdc/metrics_processor.go
cdc/processor.go
cdc/puller/puller.go

Tests 
- Unit test
- No code
Code changes
Side effects

add a metrics about mount duration

---

cdc/model/mq.go
cdc/model/mq_test.go
cdc/sink/mqProducer/kafka.go
kafka_consumer/main.go

fix version and key lenght format
Tests 
- Unit test

open_protocol: fix version and key lenght format

---

scripts/jenkins_ci/integration_test_common.groovy
tests/drop_many_tables/conf/diff_config.toml
tests/drop_many_tables/data/prepare.sql
tests/drop_many_tables/run.sh

add integration test for droping more than one table in a DDL
Tests 
- Unit test

add integration test for droping more than one table in a DDL

---

cdc/sink/black_hole.go

Fix `Count` implement in blackhole sink
return `accumulated` SQL count
Tests 
- Unit test

sink: fix count in blackhole

---

scripts/jenkins_ci/integration_test_common.groovy

Update TiFlash download address.
Tests 

ci: update tiflash download address

---

metrics/grafana/ticdc.json

We need to observe the state of TiKV while running cdc.
Add TiKV metrics.
Tests 
- No code

metrics: add tikv metrics

---

cdc/changefeed.go
scripts/jenkins_ci/integration_test_common.groovy
tests/batch_add_table/conf/diff_config.toml
tests/batch_add_table/data/prepare.sql
tests/batch_add_table/data/test.sql
tests/batch_add_table/run.sh

If there are many tables in the upstream,  the process of adding tables is very slow.
Add tables in batches
Tests 
- Unit test

owner: batch add table when start a changefeed

---

cdc/changefeed.go
cdc/entry/mounter.go
cdc/processor.go
cmd/cmd_test.go
pkg/util/filter.go

1. optimize mounter decode process
2. fix a bug about balance tables
3. add a config for the number of mounter worker
Tests 
- Unit test

*: optimize mounter decode and fix some bugs

---

cdc/capture.go

When a server suicides, it doesn't cancel its sub routines.
This is a workaround, use context cancel to close all sub routines.
Tests 
- Unit test

cancel all sub routines when a server suicide

---

cmd/root.go
cmd/server.go

Close https://github.com/pingcap/ticdc/issues/501
- set log level to info
- set status binding address to 0.0.0.0:8300, instead of 127.0.0.1:8300
Tests 
- Unit test

cmd: change some default parameter

---

cmd/server.go

cmd: refine error msg when load timezone failed

cmd: refine error msg when load timezone failed

---

docker-compose.yml

Dockerfile is now located in the root.

Update dockerfile path in docker-compose.yml

---

cdc/entry/mounter.go

Fix https://github.com/pingcap/ticdc/issues/552
- allocate a chan for each codec worker in mounter 
- dispatch raw changed event randomly to codec worker. (We can do this because we don't care the sequence of kv event in mounter)
After this optimization, the most CPU consumption of codcWorker is `unmarshalAndMountRowChanged`. Besides we can increase `mounter-worker-num` to achieve liner codec performance
Tests 
- Unit test

mounter: use a chan list to avoid CPU cost with select lock

---

cdc/http_status.go

reduce status api
Tests 
- Unit test

http api: reduce status api

---

cdc/changefeed.go
cdc/kv/etcd_test.go
cdc/model/owner.go
cdc/model/owner_test.go
cdc/owner.go
cdc/processor.go
cdc/roles/storage/etcd_test.go
pkg/cyclic/replication.go
pkg/scheduler/interface.go
pkg/scheduler/table_number.go
pkg/scheduler/table_number_test.go

support to scheduler with cyclic replication
Tests 
- Unit test

scheduler: support to scheduler with cyclic replication

---

cdc/kv/client.go

avoid some atomic manipulation
Tests 
- Unit test

kvclient: avoid some atomic manipulation

---

cdc/entry/schema_storage.go
tests/common_1/conf/diff_config.toml
tests/common_1/data/test.sql
tests/common_1/run.sh

schema: support to sync view ddl

---

tests/multi_source/main.go

sleep 5 sec in test case to fix unstable ci
Tests 
- Unit test

test: sleep 5 sec in test case to fix unstable ci

---

tests/common_1/data/test.sql
tests/common_1/run.sh
tests/dailytest/case.go

refine integration test
Tests 
- Unit test

test: refine integration test, part 3

---

cdc/sink/mysql.go
cdc/sink/mysql_test.go

limit the txn size, fix the issue about txns is out of size
fix #617 
Tests 
- Unit test

sink: limit the txn size

---

tests/_utils/start_tidb_cluster

make sure the pd is started
Tests 
- Unit test

test: make sure the pd is started

---

cdc/kv/etcd.go
cdc/kv/etcd_test.go
cdc/owner.go
cdc/processor.go

Fix https://github.com/pingcap/ticdc/issues/620
Cleanup task workload at the same time when processor/owner cleanups task status/position.
Tests 
- Unit test

Add task workload cleanup

---

Dockerfile

fix the docker image lost the git hash
Tests 
- Unit test

dockerfile: fix the docker image lost the git hash

---

.codecov.yml
tests/_utils/run_cdc_cli
tests/availability/run.sh
tests/batch_add_table/run.sh
tests/cdc/run.sh
tests/cli/run.sh
tests/common_1/run.sh
tests/cyclic_ab/run.sh
tests/cyclic_loopback/run.sh
tests/ddl_sequence/run.sh
tests/drop_many_tables/run.sh
tests/file_sort/run.sh
tests/generate_column/run.sh
tests/many_pk_or_uk/run.sh
tests/multi_capture/run.sh
tests/multi_source/run.sh
tests/partition_table/run.sh
tests/resolve_lock/run.sh
tests/row_format/run.sh
tests/simple/run.sh
tests/sink_retry/run.sh
tests/split_region/run.sh
tests/tiflash/run.sh

Calculate cdc cli coverage. 
Tests 
- No release note.

tests: calculate cdc cli coverage

---

cmd/client_changefeed.go
pkg/cyclic/mark.go
tests/cyclic_ab/run.sh
tests/cyclic_loopback/run.sh

1. Base on https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html hyphen delimiter is preferred.
2. Do not create mark table for mark table. 
Tests 
As the option is not released so

cyclic: do not create mark table for mark table

---

tests/_utils/start_third_tidb_cluster
tests/_utils/stop_tidb_cluster
tests/cyclic_abc/run.sh

test: fix the failed CI

---

Makefile

remove pb files from coverage stats
filter in coverage file
Tests 
- Unit test

remove pb files from coverage stats

---

cdc/kv/client.go
cdc/kv/client_test.go
cdc/puller/frontier/frontier.go
cdc/puller/frontier/frontier_test.go
cdc/puller/frontier/heap.go
cdc/puller/frontier/heap_test.go
cdc/puller/puller.go

fix #667 
1. send resolved event when starting a single event feed
2. support to decrease ts for frontier
Tests 
- Unit test

puller: support to decrease ts for frontier

---

README.md

Fix chinese document link in README.
Tests 
- No code
Code changes
Side effects

Fix chinese document link

---

README.md
tests/README.md
tests/autorandom/run.sh
tests/batch_add_table/run.sh
tests/cdc/run.sh
tests/changefeed_auto_stop/run.sh
tests/changefeed_error/run.sh
tests/cli/run.sh
tests/common_1/run.sh
tests/ddl_sequence/run.sh
tests/drop_many_tables/run.sh
tests/file_sort/run.sh
tests/generate_column/run.sh
tests/many_pk_or_uk/run.sh
tests/multi_capture/run.sh
tests/multi_source/run.sh
tests/partition_table/run.sh
tests/resolve_lock/run.sh
tests/row_format/run.sh
tests/simple/run.sh
tests/sink_retry/run.sh
tests/split_region/run.sh
tests/tiflash/run.sh

- Add readme about how to run test in TiCDC
- Fix a bash version compatibility (because bash on MacOS doesn't support fall through syntax, ref: https://stackoverflow.com/a/14612719/1115857)
- Remove fall through, use MySQL sink as default
Tests 

Add readme in integration test

---

Makefile
tests/README.md

- Update some binary download guide for mac os.
- Add `mysql` client in test preparations
ref to problems solve part.
Tests 
- No code

Update tests guide for mac os

---

cmd/changefeed.toml
cmd/cmd_test.go

update the doc link of filter
Tests 
- No code

docs: update the doc link of filter

---

tests/changefeed_pause_resume/conf/diff_config.toml
tests/changefeed_pause_resume/run.sh

Add a test case to simulate bug found in https://github.com/pingcap/ticdc/issues/754#issuecomment-659196788
test workflow as follows
forloop:
- pause task
- do some ddls, do some dmls
- resume task
- check replication is normal
Tests 
- Unit test

Add a changefeed pause/resume test

---

cdc/sink/codec/avro.go
cdc/sink/codec/avro_test.go
cdc/sink/mq.go

Fix replicating timestamp and duration types through Kafka in Avro format.
- Fix discrepancy between Goavro and Registry.
- Re-parse duration before sending it to sink.
Tests 

Fix Avro timestamp & duration

---

cdc/processor.go

fix the wrong metric which the checkpointts is stop
Tests 
- Unit test

fix the wrong metric which the checkpointts is stop

---

cdc/entry/mounter.go

mounter: ignore the error when the index info is not found  (#777)

---

cdc/sink/mysql.go

If panic happens in MySQL sink, such as in the `prepareDMLs` function, the panic will be recovered in the `run` function of `mysqlSinkWorker`, But the counter of `txn wait group` is not correctly updated, and the sink worker routine can't exit.
```
goroutine 452 [semacquire]:
sync.runtime_Semacquire(0xc0035bd7d0)
runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc0035bd7c8)
sync/waitgroup.go:130 +0x64
github.com/pingcap/ticdc/cdc/sink.(*mysqlSinkWorker).waitAllTxnsExecuted(...)
github.com/pingcap/ticdc/cdc/sink/mysql.go:538
github.com/pingcap/ticdc/cdc/sink.(*mysqlSinkWorker).waitAndClose(...)
github.com/pingcap/ticdc/cdc/sink/mysql.go:542
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).concurrentExec(0xc0003c08c0, 0x2c36000, 0xc00007e5c0, 0xc0035cbf80, 0x0, 0x0) …
```

sink/mysql: fix wait group is not correctly updated when panic

---

Dockerfile
cdc/sink/codec/schema_registry.go
docker-compose-avro.yml
docker-compose.yml
docker/config/jdbc-sink-connector.json
scripts/avro-local-test.sh

Fix local testing facilities, especially for testing Kafka & Avro.
- Fixed bugs in docker-compose.yml
- Added scripts/avro-local-test.sh for the convenient of developers and potential users.
- **tableNameToSchemaSubject now concatenates db name and table name by "_", so as to avoid compatibility problems with older versions of Confluent Schema Registry**.
Tests 
- Manual test
- Testing facilities are changed.

Fix docker-compose.yml and add support to start local Avro testing environment

---

cdc/sink/mqProducer/kafka.go

Fix https://github.com/pingcap/ticdc/issues/798
Add check to partition number
Tests 
- Unit test

kafka: partition number can't be negative

---

cdc/http_handler.go
cdc/http_status.go
cdc/owner.go
cdc/processor.go
cdc/server.go

When sort dir does not exist, try to create it recursively
- check os.IsNotExist
- add a lock to owner access in server
Tests 
- Unit test

Support auto create sort dir in file sort mode, fix owner data race

---

cdc/sink/codec/schema_registry.go
cdc/sink/codec/schema_registry_test.go

- Compatibility issue with older versions of Confluent Schema Registry
- Retries for POST requests generate empty bodies
Tests 
- Unit test

Fix bugs in Avro implementation

---

cdc/processor.go
cdc/puller/rectifier.go
tests/changefeed_auto_stop/run.sh

fix the bug about adding table. this bug is was introduced by #771 .
add some fail-fast check
Tests 
- Unit test

fix the bug about adding table

---

pkg/filter/filter.go
pkg/filter/filter_test.go

using tidb-tools.filter to filter the system schemas
Tests 
- Unit test

filter: using tidb-tools.filter to filter the system schemas

---

cdc/metrics_processor.go
cdc/processor.go
metrics/grafana/ticdc.json

Add metric
Tests 
- No code
Code changes
Side effects

*: add metric for FlushRowChangedEvents in sinkDriver

---

cdc/entry/mounter.go
tests/common_1/data/test.sql

fix panic when a columns that are not null by default are null
Tests 
- Unit test

fix panic when a columns that are not null by default are null

---

tests/cdclog_file/run.sh
tests/cdclog_s3/run.sh

fix ci cdclog_file unstable issue.
sleep more time to wait sink finish
Tests 

cdclog: fix ci

---

Makefile

ci: fix broken CI

---

cdc/sink/producer/kafka/kafka.go

fix the bug when create a zero partition topic in kafka 
Tests 
- Unit test

sink/kafka: zero partition is not valid

---

cdc/sink/producer/kafka/kafka.go

fix get kafka partition of topic
Tests 
- Unit test

kafka: fix get kafka partition of topic

---

Dockerfile.development
docker-compose-avro.yml

- Docker build failures.
- Disabled vendoring on the production dockerfile.
- Added a separate dev dockerfile.
Tests 

fix: separate dev and prod Dockerfile 

---

.github/workflows/docker_build_test.yml

add a github action config for testing docker build
Tests 
- Unit test

test: add test for docker build

---

go.mod
go.sum

part 2 of https://github.com/pingcap/ticdc/pull/938
remove go mod replace, use latest tidb-tools
Tests 
- Unit test

go mod: update tidb-tools, remove temp replace

---

go.mod
go.sum

*: update tidb dependence

---

cdc/processor.go
tests/common_1/run.sh
tests/ddl_reentrant/run.sh

- release CI test ddl reentrant fail
- problems caused by checkpointTs = 0 
- correct version determination
- intialize checkpointTs = startTs in newProcessor
Tests 

fix: unsupported ddl test & checkpointTs = 0

---

tests/new_ci_collation/conf/changefeed.toml
tests/new_ci_collation/conf/diff_config.toml
tests/new_ci_collation/conf/tidb_config.toml
tests/new_ci_collation/data/test1.sql
tests/new_ci_collation/data/test2.sql
tests/new_ci_collation/run.sh

Add new ci collation integration test, test basic feature support
simple feature test for new ci collation
Tests 
- Unit test

tests: add new ci collation integration test

---

cdc/sink/codec/maxwell.go
cdc/sink/codec/maxwell_test.go

- Maxwell protocol outputs empty messages.
- Return nil in Build() if there's no accumulated messages.
Tests 
- Manual test 

sink: fix Maxwell empty messages

---

cdc/sink/codec/canal.go
cdc/sink/codec/canal_test.go
cdc/sink/mq.go
cmd/client_changefeed.go

- Incomplete support for old value in Canal.
- A string type encoding bug in Canal.
Tests 
- Integration test (the code for integration test is not yet suitable for merging, but it proves correctness of our implementation)
Side effects
**- Breaking backward compatibility**

sink: support canal old value & fix bug

---

pkg/pipeline/context.go
pkg/pipeline/message.go
pkg/pipeline/node.go
pkg/pipeline/pipeline.go
pkg/pipeline/pipeline_test.go
pkg/pipeline/runner.go

implement a pipeline framework for refactoring

pipeline: implement a pipeline framework

---

cmd/changefeed.toml

TiCDC supports more sink protocol now
update changefeed config template
Tests 
- Unit test

cmd: add more sink protocol config

---

cdc/kv/client.go

Resolved ts could be stopped after some regions stopped.
Fix unexpected skipping in batch resolved ts
Tests 
* Fix unexpected skipping in batch resolved ts

[release-4.0] kv: fix unexpected skipping in batch resolved ts

---

cdc/kv/client.go

Resolved ts could be stopped after some regions stopped.
Fix unexpected skipping in batch resolved ts
Tests 
* Fix unexpected skipping in batch resolved ts

kv: fix unexpected skipping in batch resolved ts

---

pkg/flags/urls_test.go
pkg/util/test_helper_test.go
pkg/version/check.go
pkg/version/check_test.go

Some packages warn `[no tests to run]`, maybe check.TestingT(t) is removed by accident in some code refactor
Ensure `check.TestingT(t)` entrypoint is added in each package.
Tests 
- Unit test

pkg: add entrypoint to some unit test

---

tests/syncpoint/run.sh

Fix https://github.com/pingcap/ticdc/issues/1050
Currently TiCDC only subscribes key value change of `DDLJobList` and `DDLJobAddIdxList` key, so we can't find a strong schema version barrier in TiCDC.
See the following timeline, before T3 the snapshot reads the old schema, after T3 the snapshot reads the new schema.
TiCDC could record a syncpoint with primary ts (T5) between T3 and T4,  and at T5, the schema in upstream is new vesrion, while the schema in downstream is old version, TiCDC will execute DDL at T4
We have two choices
- Monit more DDL metadata in TiKV, and be aware of the table info commit transaction at T3, and then skip to record syncpoint when primary ts happens in a DDL. 
- Just leave the `inaccurate` syncpoint record (Only one DDL missed compared to the upstream) and fix …

tests: fix syncpoint check in ddl

---

cdc/model/sink_test.go

Add more unit tests in cdc/model packages
This is part three, add unit tests for file cdc/model/sink.go
Tests 
- Unit test

tests: add more unit tests in cdc/model/sink.go

---

cdc/entry/schema_storage_test.go
cdc/model/schema_storage_test.go

Add more unit tests in cdc/model packages
This is part two, add unit tests for file schema_storage.go
Tests 
- Unit test

tests: add more unit tests in cdc/model/schema_storage.go

---

README.md

Job of build master has been migrated from `build_cdc_master` to `build_cdc_multi_branch`
Change badge link
Tests 
- Unit test

README: update build status badge link

---

metrics/alertmanager/ticdc.rules.yml

For now TiCDC would break TiKV hibernate regions.
Add an alert after hibernate-regions was enabled.
Tests 
- No code
* metrics: add alert for tikv hibernate regions

metrics: add alert for tikv hibernate regions

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/pull_request_template.md

Some labels in issue template are outdated
Use correct issue label
Tests 
- No code

github: update issue template

---

Makefile
cdc/entry/mounter_test.go
cdc/model/capture_test.go
cdc/model/changefeed_test.go
cdc/model/kv_test.go
cdc/model/mounter_test.go
cdc/model/owner_test.go
cdc/model/schema_storage_test.go
cdc/model/sink_test.go
cdc/model/string_test.go
cdc/owner_test.go
cdc/puller/sorter_test.go
cdc/sink/codec/json_test.go
cmd/server_test.go
pkg/util/gc_service_test.go
pkg/util/testleak/leaktest.go
scripts/add-leaktest.sh

Some unit tests missed leak test
- Add a check in `make check` to ensure leak test is added in all unit tests
- Fix some routine leak in unit tests
Tests 
- Unit test

tests: add leak test check in Makefile, complete leak tests

---

pkg/context/context_test.go

fix unstable tests
Tests 
- Unit test

context: fix unstable tests

---

tests/clustered_index/data/test.sql

add cases for clustered index
Tests 
- Unit test

test: add cases for clustered index

---

scripts/jenkins_ci/integration_test_common.groovy
tests/clustered_index/run.sh

pick https://github.com/pingcap/ticdc/pull/1242 & https://github.com/pingcap/ticdc/pull/1251 to master manually
Enable specific tiflash branch in CI
Tests 
- Unit test

CI: enable specific tiflash branch in CI

---

scripts/check-copyright.sh

- The copyright checker should not rely on the current year.
- Using regex to match copyright info.

*: fix copyright check

---

scripts/check-copyright.sh

cherry pick #1264 into release-4.0-pending

*: fix copyright check (#1264)

---

.github/pull_request_template.md

update pull request template, add metric document in check list
add metric document in check list
Tests 
- Unit test

github: update pull request template

---

cdc/owner.go
cdc/puller/sorter/backend_pool.go
cdc/puller/sorter/file_backend.go
cdc/puller/sorter/heap_sorter.go
cdc/puller/sorter/memory_backend.go
cdc/puller/sorter/merger.go
cdc/puller/sorter/metrics.go
cdc/puller/sorter/unified_sorter.go
cmd/server.go
docs/ticdc-grafana-dashboard.md
metrics/grafana/ticdc.json
scripts/check-copyright.sh

- Problems in unified sorter metrics.
- Renamed some metrics.
- Made data size stats more accurate.
- Miscellaneous changes.
Tests 
- Unit test

sorter: unified sorter metrics adjustments

---

.github/workflows/integration.yml

fix github action no space left

test: fix github action no space left

---

cdc/owner.go
cdc/puller/sorter/backend_pool.go
cdc/puller/sorter/file_backend.go
cdc/puller/sorter/heap_sorter.go
cdc/puller/sorter/memory_backend.go
cdc/puller/sorter/merger.go
cdc/puller/sorter/metrics.go
cdc/puller/sorter/unified_sorter.go
cmd/server.go
docs/ticdc-grafana-dashboard.md
metrics/grafana/ticdc.json

(cherry picked from commit d767cc7b3c5781a0c198bda1306d3fd49f75b7e3)
- Better Unified Sorter metrics.

sorter: unified sorter metrics adjustments (#1262)

---

tests/multi_changefeed/run.sh

fix unstable multi changefeed integration test cases

test: fix unstable multi changefeed integration test cases

---

README.md

add info and fix typos
Update the readme file
Tests 
- Unit test
- No code
Code changes
Side effects

README: add info and fix typos

---

cdc/kv/client.go
cdc/kv/client_test.go

Improve unit test of kv client, part of #1292
Test resolve lock logic can work normally
Tests 
- Unit test

tests: check kv client can resolve lock as expected

---

pkg/context/context.go
pkg/context/context_test.go
pkg/pipeline/context.go
pkg/pipeline/message.go
pkg/pipeline/node.go
pkg/pipeline/pipeline.go
pkg/pipeline/pipeline_test.go
pkg/pipeline/runner.go

cherry-pick #1172 to release-4.0
---
This PR is the part one of refactor processor.
refine pipeline framework
Tests 
- Unit test

pipeline: refine pipeline, refactor processor part one (#1172)

---

cdc/sink/producer/pulsar/producer.go

Signed-off-by: Xiaoguang Sun <sunxiaoguang@zhihu.com>
Fix error type in Pulsar sink
Use the correct error type in Pulsar sink
Tests 
Correct type and build
Code changes
Fix error type
Side effects
NO
NO

Fix error type in Pulsar sink

---

cdc/kv/client.go

TiCDC always interacts with region leader, every time something goes wrong, failed region will be reloaded via `BatchLoadRegionsWithKeyRange` API. So we don't need to force reload region any more.
**NOTE: current logic will always reload region information when meeting failure, in some extreme scenarios, such as TiKV region leader information is not uploaded to PD in time, the recover time with leader change will increase. This can be an optimization point.**
- `scheduleReload` is always false
- Related test cases such as change region leader, store failure etc. are already in unit tests
Tests 
- Unit test

kv-client: don't maintain need reload info for region

---

cdc/processor/processor.go
cdc/processor/processor_test.go

- add some nil pointer checks
Tests 
- Unit test
- No release note, the bug is never released

processor: fix nil pointer panic

---

metrics/grafana/ticdc.json

cherry-pick #1604 into release-5.0
Update TiKV metrics
Tests 
- Unit test

metrics: update TiKV metrics #1604

---

metrics/grafana/ticdc.json

Update TiKV metrics
Tests 
- No code

metrics: update TiKV metrics

---

cdc/kv/client.go

remove redundant log introduced by #1589, master/4.0 PR has not been merged.
remove log
Tests 
- Unit test

kv/client: remove redundant log

---

metrics/grafana/ticdc.json

Corrects TiKV CDC endpoint CPU
Tests 
- No code
- Correct TiKV CDC endpoint CPU metric in TiCDC dashboard.

metrics: correct TiKV CDC endpoint CPU

---

metrics/grafana/ticdc.json

metrics: add old value metrics

---

.github/workflows/integration.yml

At the moment, Github Action runs integration test sequentially, this is quite time-consuming.  This PR try to make different integration test jobs run in a parallel way，so that total run time can be reduced.
* Github Action Workflow file
Tests 
- No code
Code changes
Side effects
- track the effects of this change after merged into master, may cause Github Action failed frequently.
No release note

Action: make github action run in parallel

---

tests/_utils/start_tidb_cluster
tests/_utils/start_tidb_cluster_impl
tests/region_merge/conf/diff_config.toml
tests/region_merge/conf/pd_config.toml
tests/region_merge/run.sh

The continuous region merge and split test is lack in TiCDC, it is better to add one.
Add the integration test with region split and random merge support. Since the random merge is essentially random, it can help to find potential bug in TiCDC kv client (#1393).
Tests 
- Unit test

tests: add random region merge test

---

go.mod
go.sum

Upgrade tidb/parser dependency to latest release-4.0
Known bug fix
- https://github.com/pingcap/tidb/pull/24481
Upgrade tidb/parser dependency to latest release-4.0
Tests 
- Unit test

go/mod: upgrade tidb/parser to latest release-4.0

---

cdc/processor/state.go
pkg/etcd/etcdkey.go
pkg/etcd/etcdkey_test.go

Signed-off-by: Xiaoguang Sun <sunxiaoguang@zhihu.com>
Fixe a typo
Change CDCKeyTypeOnwer to CDCKeyTypeOwner
Tests 
Code compiles
Code changes
- NA
Side effects
- NA
-NA

*: fix a typo

---

.github/workflows/check_and_build.yml
.github/workflows/integration.yml
Dockerfile
Dockerfile.development
Makefile
go.mod
go.sum
tools/check/go.mod

ref: https://github.com/pingcap/ticdc/issues/1769
build ticdc with go1.16, note ticdc is still compatible with go version >= 1.13
Tests 
- Unit test

build: upgrade to go1.16.4

---

cdc/sink/common/flow_control.go
cdc/sink/common/flow_control_test.go

#1779 
#1779 
Tests 
- Unit test
- Flow Control bug fix (no released version affected)

*: fix flow control deadlock (port to master)

---

cdc/processor/doc.go

fix typo in new processor doc
No release note

docs: fix typo in design of new processor

---

README.md

We'll deprecate the TiDB Monthly Update, so I remove the link.
Tests 
- Unit test
- No code
Code changes
Side effects

README: remove the TiDB Monthly link

---

cdc/kv/etcd.go
cdc/kv/etcd_test.go
cdc/sink/cdclog/file.go
pkg/etcd/client.go
tests/processor_resolved_ts_fallback/run.sh

fix a unstable test in CI
Tests 
- Unit test

tests: fix a unstable test in CI

---

cdc/model/reactor_state.go
cdc/model/reactor_state_test.go

fix the owner panic, fix #1956
Tests 
- Unit test

owner: fix the owner panic

---

cdc/owner/owner.go

owner: fix owner ship metrics
Tests 
- Unit test

owner: fix owner ship metrics

---

errors.toml

*: fix err docs

---

cdc/http_handler.go
cdc/http_status.go
cdc/owner/owner.go
cdc/server.go

fix some nil panic when switch off the new owner
Tests 
- Unit test

owner: fix some nil panic when switch off the new owner

---

cdc/owner/owner.go
cdc/owner/owner_test.go
pkg/context/context.go

check the version of the ticdc cluster, make sure all the version of ticdc nodes is consistent
Tests 
- Unit test

owner: check the version of the ticdc cluster

---

cdc/puller/sorter/backend_pool_test.go

backend_pool_test may failed in the CI environment.
Tests 
- No code
Code changes
Side effects
No release note

puller: try to fix bad permission for backend test .

---

Makefile

None
make clean also cleanup the bin dir.
Tests 
- No code
Code changes
None
Side effects
None
None

makefile: make clean also cleanup the bin dir

---

cdc/processor/pipeline/mounter.go
cdc/processor/pipeline/mounter_test.go
cdc/processor/pipeline/sorter.go
cdc/processor/pipeline/table.go
cdc/processor/processor.go
cdc/puller/sorter/merger.go
cdc/puller/sorter/merger_test.go
cdc/puller/sorter/sorter_test.go
cdc/puller/sorter/unified_sorter.go

#1987 #2078 #2089 #2085 
- See the above PRs
Tests 
- Unit test
Side effects
- Fix potential deadlocks

*: merge new processor related deadlock fixes to 5.0 branch

---

cdc/model/changefeed.go
tests/availability/owner.sh
tests/availability/processor.sh
tests/capture_session_done_during_task/run.sh
tests/changefeed_auto_stop/run.sh
tests/changefeed_error/run.sh
tests/changefeed_finish/run.sh
tests/cli/run.sh
tests/cyclic_abc/run.sh
tests/ddl_reentrant/run.sh
tests/gc_safepoint/run.sh
tests/kafka_sink_error_resume/run.sh
tests/kill_owner_with_ddl/run.sh
tests/owner_remove_table_error/run.sh
tests/processor_err_chan/run.sh
tests/processor_stop_delay/run.sh
tests/sink_hang/run.sh
tests/syncpoint/run.sh
tests/unified_sorter_sort_dir_conflict/run.sh

fix CI for the new owner
Tests 

test: fix CI for the new owner

---

cdc/owner/schema_test.go
pkg/filter/filter.go
pkg/filter/filter_test.go
tests/capture_suicide_while_balance_table/conf/ingore_user_system_tables.toml
tests/capture_suicide_while_balance_table/run.sh.skip
tests/changefeed_reconstruct/run.sh.skip

close https://github.com/pingcap/ticdc/issues/2192
Support for synchronizing user permission-related tables.
Please see the code comments for details.
Tests 
- Unit test
Code changes
Side effects
N/A
- Support for synchronizing user permission-related tables

filter: support for synchronizing user permission-related tables

---

cdc/metrics_owner.go
cdc/model/changefeed.go
cdc/owner.go
cdc/owner/metrics.go
cdc/owner/owner.go
metrics/grafana/ticdc.json

Add metrics to monitor changefeed state #2251 
* add `changefeedStatusGauge`
* create grafana panel for changefeed state.
Tests 
- No code
Code changes
Side effects

owner, metrics: add changefeed status in metrics and grafana

---

cdc/kv/client.go
cdc/kv/metrics.go
go.mod
go.sum
metrics/grafana/ticdc.json

Add gRPC client RPC metrics.
Tests 
Side effects
```release-note
None
```

kv: add grpc client metrics

---

cdc/owner/ddl_puller.go
cdc/owner_operator.go
cdc/processor.go
cdc/processor/pipeline/puller.go
cdc/processor/processor.go
cdc/puller/puller.go
cdc/puller/puller_test.go

Follow up https://github.com/pingcap/ticdc/pull/2271
clean up unused parameter.
Tests 
- Unit test
Code changes
Side effects
None

puller: clean up unused parameter

---

.golangci.yml
cdc/changefeed.go
cdc/kv/client.go
cdc/kv/client_v2.go
cdc/kv/region_worker.go
cdc/owner.go
cdc/owner_test.go
cdc/processor/processor.go
cdc/puller/sorter/sorter_test.go
cdc/sink/codec/canal_flat.go
cdc/sink/codec/canal_flat_test.go
cdc/sink/codec/schema_registry_test.go
cdc/sink/mysql.go
cdc/sink/producer/pulsar/option.go
cdc/task.go
cdc/task_test.go
cmd/cdc/main_test.go
cmd/client_changefeed.go
cmd/util.go
pkg/httputil/httputil_test.go
pkg/orchestrator/etcd_worker.go
pkg/regionspan/region_range_lock_test.go
testing_utils/many_sorters_test/many_sorters_test.go
tests/bank/case.go
tests/dailytest/db.go
tests/dailytest/job.go
tests/dailytest/parser.go

part of https://github.com/pingcap/ticdc/issues/2162
enable unparam static check and refine codes
Tests 
- Unit test
Code changes
None
Side effects
None

*: enable unparam static check

---

.github/pull_request_template.md

update pull request template to use new release note fmt.
update pull request template
Tests 
- No code
Code changes
None
Side effects
None
None

github: update pull request template to use new release note fmt

---

.github/workflows/check_and_build.yml

cleanup duplicate lint job
cleanup duplicate lint job. They are already executed in check.
Tests 
- No code
Code changes
None
Side effects
None
```release-note
None
```

github: cleanup duplicate lint job

---

.github/workflows/check_and_build.yml
.github/workflows/integration.yml

Turn on concurrency mode to reduce the waste of resources in GitHub actions.
Turn on concurrency mode to reduce the waste of resources in GitHub actions.
See also: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
Tests 
- No code
Code changes
None
Side effects
None
```release-note
None
```

github: enable concurrency mode

---

pkg/cmd/cli/cli.go
pkg/cmd/cli/cli_capture.go
pkg/cmd/cli/cli_capture_list.go
pkg/cmd/util/helper.go
pkg/cmd/util/helper_test.go

part of #2168
cc: #2199
split from #2262
add capture cmd
Tests 
- Unit test
Code changes
None
Side effects
None
None
```release-note
None
```

cmd(refactor): add capture cmd

---

pkg/cmd/cli/cli.go
pkg/cmd/cli/cli_processor.go
pkg/cmd/cli/cli_processor_list.go
pkg/cmd/cli/cli_processor_query.go
pkg/cmd/cli/cli_tso.go
pkg/cmd/cli/cli_tso_query.go
pkg/cmd/cli/cli_unsafe.go
pkg/cmd/cli/cli_unsafe_delete_service_gc_safepoint.go
pkg/cmd/cli/cli_unsafe_reset.go
pkg/cmd/cli/cli_unsafe_show_metadata.go

part of #2168
cc: #2199
split from #2262
add cli processor cmd
Tests 
None
Code changes
None
Side effects
None
None
```release-note
None
```

cli(refactor): add cli cmds for processor, tso and unsafe

---

tests/_utils/run_cdc_server

close https://github.com/pingcap/ticdc/issues/2650
Make sure the server is really started. Check the status API.
Tests 
Code changes
None
Side effects
None
None
```release-note
None
```

test: Make sure the server is really started

---

pkg/cmd/cli/cli_changefeed.go
pkg/cmd/cli/cli_changefeed_cyclic.go
pkg/cmd/cli/cli_changefeed_cyclic_create_marktables.go
pkg/cmd/cli/cli_changefeed_helper.go
pkg/cmd/cli/cli_changefeed_list.go
pkg/cmd/cli/cli_changefeed_pause.go
pkg/cmd/cli/cli_changefeed_query.go
pkg/cmd/cli/cli_changefeed_remove.go
pkg/cmd/cli/cli_changefeed_resume.go
pkg/cmd/cli/cli_changefeed_statistics.go

split from #2482
add changefeed statistics cmd.
Tests 
Code changes
None
Side effects
None
```release-note
None
```

cli(refactor): add changefeed  cmds

---

cdc/capture/capture.go

None.
refine some comments and simplify IsOwner func.
Tests 
Code changes
None
Side effects
None
None
```release-note
None
```

capture: refine some comments and simplify IsOwner func

---

tests/region_merge/run.sh

Workaround for #2662
Use small scale to stabilize region merge test
Tests 
- Unit test
```release-note
None
```

tests: use small scale to stabilize region merge test

---

.github/workflows/assign_bugs_questions_project.yml

auto run issues assignment to project Question and Bug Reports Kanban
Tests 
- No code
Code changes
Side effects
```release-note
None
```

github workflow: add a auto assign bug github action

---

cdc/server.go
cdc/server_test.go
cdc/sink/mysql.go
pkg/config/config.go
pkg/cyclic/filter.go
tests/cyclic_abc/run.sh

#2574 
None
Tests 
- Unit test
Code changes
Side effects
```release-note
None
```

*: clean old owner related codes

---

.github/ISSUE_TEMPLATE/feature-request.md

Fix feature request label in issue template when creating new feature request
Use correct label name
Tests 
- No code
```release-note
None
```

github: fix feature request label in issue template

---

.github/ISSUE_TEMPLATE/flaking-test.md

None
fix broken templeate
Tests 
- No code
Code changes
None
Side effects
None
None
```release-note
None
```

github: fix broken templeate

---

cdc/model/owner.go
cdc/model/owner_test.go
cdc/owner/scheduler_test.go
cdc/processor/processor.go
cdc/processor/processor_test.go
pkg/scheduler/table_number_test.go

None
remove deprecated done operation.
Tests 
- Unit test
Code changes
None
Side effects
None
None
```release-note
None
```

owner: remove deprecated done operation

---

pkg/cmd/cli/cli_changefeed_update.go
pkg/cmd/cli/cli_changefeed_update_test.go

close https://github.com/pingcap/ticdc/issues/2803
ignore the global flag for changefeed update command
Tests 
- Unit test
Code changes
None
Side effects
None
```release-note
None
```

cli(fix): ignore the global flag for changefeed update command

---

cdc/kv/client.go
cdc/kv/client_test.go

This is a subtask of #2765, enable new kv client in the release-5.0 branch.
Tests 
- No code
Code changes
Side effects
```release-note
None
```

kv: enable new kv client in release-5.0 branch.

---

pkg/hash/position_inertia_test.go

migrate test-infra to testify for pkg/hash pkg, close  #2934
2. migrate leak test from leaktest to goleak
Tests 
- Unit test
```release-note
`None`.
```

test(pkg/hash): migrate test-infra to testify for pkg/hash pkg

---

docker-compose-avro.yml
docker-compose-canal.yml
docker-compose-mysql.yml

* set log-level to `info` for non `tikv` component
* alter `--sort-dir` to `--data-dir` for ticdc component.
Tests 
- No code
Code changes
Side effects
```release-note
`None`.
```

integration: update integration docker compose file.

---

pkg/config/config_test.go
pkg/config/main_test.go
pkg/config/sorter.go

migrate test-infra to testify for pkg/config pkg, close #2825 
2. migrate leak-test from testleak to goleak
Tests 
- Unit test
Code changes
- None
Side effects
- None
- None
```release-note
None
```

test(pkg/config): migrate test-infra to testify for pkg/config pkg (#2825)

---

pkg/regionspan/region_range_lock_test.go
pkg/regionspan/region_test.go
pkg/regionspan/span_test.go

migrate test-infra to testify for pkg/regionspan,  close  #2927
2. migrate leak-test from testleak to goleak
Tests 
- Unit test
```release-note
`None`.
```

test(pkg/regionspan): migrate test-infra to testify for pkg/regionspan

---

cdc/owner/changefeed.go
cdc/processor/pipeline/table.go
cdc/processor/processor.go
cdc/redo/manager.go
cdc/redo/manager_test.go
cdc/sink/manager.go
cdc/sink/manager_test.go
cdc/sink/table_sink.go
tests/consistent_replicate_local/conf/changefeed.toml
tests/consistent_replicate_local/conf/diff_config.toml
tests/consistent_replicate_local/conf/workload
tests/consistent_replicate_local/run.sh
tests/consistent_replicate_s3/conf/changefeed.toml
tests/consistent_replicate_s3/conf/diff_config.toml
tests/consistent_replicate_s3/conf/workload
tests/consistent_replicate_s3/run.sh

part of #2351 redo log based replication to implement eventually consistency
#2685 contains all of the change for the requirement, will split into small ones for review, this is one of the prs, split from the #2685, this one contains #2809,#2810,#2811,#2812,#2814 review #2809,#2810,#2811,#2812,#2814 first. Or review commit https://github.com/amyangfei/ticdc/commit/331d9bd270cada531a62b25be4cf12d5dca7ef32 directly
Also close #3117
- Add redo log manager into cdc core logic, the workflow is as follows
- Add integration tests for redo log writer and reader
Tests 
- Unit test
```release-note
None
```

redolog: add redo log into cdc core logic, add integration tests

---

dm/dm/master/config.go
dm/dm/master/config_test.go
dm/dm/master/dm-master.toml
dm/dm/master/openapi_test.go
dm/dm/master/server.go
dm/tests/dmctl_basic/conf/get_master1.toml
dm/tests/openapi/client/openapi_task_check
dm/tests/openapi/conf/dm-master1.toml
dm/tests/openapi/conf/dm-master2.toml

close https://github.com/pingcap/dm/issues/1982
and releated to https://github.com/pingcap/docs-dm/pull/812
add `[experimental-features]` in dm-master config file
Tests 
- Unit test
Code changes
Side effects
```release-note
`support config experimental feature in dm-master config file`.
```

dm/openapi: support config experimental feature

---

.github/ISSUE_TEMPLATE/dm-bug-report.yml
.github/ISSUE_TEMPLATE/flaking-test.yml
.github/ISSUE_TEMPLATE/question.yml
.github/ISSUE_TEMPLATE/ticdc-bug-report.yml

close https://github.com/pingcap/ticdc/issues/3175
add template for dm and refine other templates.
Tests 
- No code
Code changes
None
Side effects
None
None
```release-note
None
```

github: add template for dm and refine other templates

---

cdc/kv/client.go
cdc/puller/puller.go
pkg/regionspan/span.go

None
trivial fix for puller:
1. refine comments
2. remove useless field
3. refine the impl order
Tests 
- No code (Comments and useless code)
Code changes
None
Side effects
None
None
```release-note
None
```

puller,kv: trivial fix for puller

---

cdc/processor/pipeline/sink.go

None
add log when skip the empty rows.
Tests 
- No code(Only log)
Code changes
None
Side effects
None
```release-note
None
```

sink: add log when skip the empty row event

---

cdc/kv/region_worker.go
cdc/processor/pipeline/sink.go
cdc/redo/manager.go

fix some typos
Tests 
Code changes
Side effects
```release-note
None
```

*: fix some typos

---

dm/tests/dmctl_basic/conf/diff_config.toml
dm/tests/online_ddl/conf/diff_config.toml
dm/tests/print_status/conf/diff_config.toml
dm/tests/safe_mode/conf/diff_config.toml
dm/tests/sequence_safe_mode/conf/diff_config.toml
dm/tests/sequence_sharding/conf/diff_config.toml
dm/tests/sequence_sharding_optimistic/conf/diff_config.toml
dm/tests/sequence_sharding_removemeta/conf/diff_config.toml
dm/tests/sharding/conf/diff_config.toml

After https://github.com/pingcap/tidb-tools/pull/546 merged. sync-diff has breaking config change. so the dm tests need to update.
change dm test sync-diff config to adapt new config.
Tests 
Code changes
Side effects
```release-note
None
```

CI: update config for sync diff

---

dm/tests/compatibility/start.sh

in many cases `compatibility` test is failed
https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_compatibility_test/detail/dm_ghpr_compatibility_test/399/pipeline
add one matching for relay status
Tests 
- No code
Code changes
Side effects
```release-note
`None`.
```

dm/test: align CI behaviour with enable-relay

---

cdc/sink/producer/kafka/kafka.go

When try to create the topic, only check `max-message-bytes` when using the default open protocol or craft protocol.
Tests 
- Unit test
- No code
Code changes
Side effects
```release-note
None`.
```

cdc/sink: only check max-message-bytes for default protocol & craft protocol

---

cdc/capture/capture.go
cdc/processor/pipeline/system/system.go
cdc/processor/pipeline/system/system_test.go
pkg/context/context.go

it's a part of the table pipeline actor refactor.
This PR init table actor system if it is enabled
Tests 
- Unit test
- No code
Code changes
Side effects
```release-note
`None`.
```

cdc/capture: init table actor system if it is enabled

---

cdc/scheduler/scheduler_dispatcher.go
cdc/scheduler/scheduler_dispatcher_test.go

- In preparation to merge the ScheduleDispatcher, we need to clearly define the interfaces involved.
- Defined interface `ScheduleDispatcher`.
- Defined interface `ScheduleDispatcherCommunicator`.
- Implemented `mockScheduleDispatcherCommunicator` for testing.
Tests 
- No code (no unit-testable code)
Code changes
```release-note
None
```

cdc/scheduler_v2: interfaces and mocks for ScheduleDispatcher

---

docs/ci/command.md

as title
Tests 
- No code
Code changes
Side effects
```release-note
`None`.
```

docs:  update verify-ci trigger commands

---

dm/relay/relay.go

use binlog name comparison instead of string comparison.
Tests 
- I think it's apparently correct and current function is too big to test
Code changes
Side effects
```release-note
`None`.
```

relay(dm): use binlog name comparison

---

cdc/sink/codec/canal_flat.go
cdc/sink/codec/canal_flat_test.go

omit empty field in tidbExtension. 
omit empty field in tidbExtension:
1. DDL or DML event no watermark ts
2. Checkpoint event no commit ts
Tests 
- Unit test
Code changes
None
Side effects
None
None
```release-note
None
```

sink(ticdc): omit empty field in tidbExtension

---

cdc/sink/mq.go
cdc/sink/mq_test.go
cdc/sink/producer/kafka/config.go
cdc/sink/producer/kafka/config_test.go
cdc/sink/producer/kafka/kafka.go
cdc/sink/producer/kafka/kafka_test.go

better name for config complete func.
Rename it to fix wrong name.
Tests 
- No code
Code changes
Side effects
None
None
```release-note
None
```

sink(ticdc): better name for config complete func

---

metrics/grafana/ticdc.json

Fix borken EtcdWorker row.
| master | this PR |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/2150711/146777529-75ac83aa-60aa-4392-8592-492c4d163b1f.png) | ![image](https://user-images.githubusercontent.com/2150711/146777431-5fe4dacf-359b-4180-8466-b42528e94e00.png) |
Tests 
Import ticdc.json
```release-note
None (not released yet)
```

metrics(ticdc): fix EtcdWorker row

---

pkg/actor/system_test.go

Close #3963 
Tests 
- Unit test
```release-note
None
```

pkg/actor(ticdc): stable tests by extending timeout

---

cdc/capture/capture.go
cdc/owner/scheduler.go
cdc/processor/manager.go
cdc/processor/processor.go
cdc/server.go
pkg/config/config_test_data.go
pkg/config/debug.go
pkg/config/server_config.go

Issue Number: ref #4126 
- Added a user-configuration option `debug.enable-new-scheduler`.
Tests 
- Unit test
- Manual test
```release-note
None
```

config(cdc): add a switch EnableNewScheduler

---

CONTRIBUTING.md
pkg/version/check.go
pkg/version/check_test.go

Issue Number: close #4170
Indicate the component with the wrong version by hint info
Tests 
- Unit test
Code changes
```release-note
Add hint info to ErrNewSemVersion
```

version(cdc): add hint info to ErrNewSemVersion (#4170)

---

.github/dependabot.yml

Issue Number: ref #4478
add missing schedule property.
tested: https://github.com/hi-rustin/ticdc/pull/3#issuecomment-1022820341
Tests 
- No code
Code changes
None
Side effects
None
None
```release-note
None
```

github(dm): add missing schedule property

---

.github/ISSUE_TEMPLATE/ticdc-bug-report.yml

Issue Number: close #4534
Tests 
- No code
```release-note
None
```

.github(ticdc): request TiKV version

---

cdc/sink/producer/kafka/kafka.go
cdc/sink/producer/kafka/kafka_test.go
pkg/kafka/cluster_admin_client.go
pkg/kafka/cluster_admin_client_mock_impl.go
pkg/kafka/config.go

Issue Number: close #4675 
Tests 
- No code
Code changes
Side effects
```release-note
`None`.
```

remove skipAutoCreate failpoint from kafka test.

---

dm/syncer/syncer.go

as title
Tests 
- No harm 🤔 
```release-note
`None`.
```

syncer(dm): support more about Syncer with nil etcdcli

---

cdc/server.go

Issue Number: close #4746
Stop using deprecated PD API.
Tests 
Run TiCDC.
```release-note
None
```

cdc: fix pd health API

---

scripts/check-diff-line-width.sh

Issue Number: ref #4780 
* Fix check failure when there is no master branch
* Add color to WARN and ERROR
Tests 
- Unit test
```release-note
None
```

scripts(ticdc): refine check diff line

---

dm/dm/master/scheduler/latch_test.go
dm/dm/master/scheduler/scheduler_test.go
dm/dm/master/scheduler/worker_test.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/2164
migrate test-infra from gocheck to testify
Tests 
- Unit test
Code changes
- None
Side effects
- None
- None
```release-note
None.
```

test(master/scheduler): migrate test-infra to testify for master/scheduler pkg 

---

dm/dm/config/task.go
dm/tests/dmctl_basic/conf/get_task.yaml

Issue Number: close #4823
change default value to true
Tests 
- Unit test
- No code
Code changes
Side effects
```release-note
Enable online-ddl by default
```

online-ddl: change default value of online-ddl to true

---

dm/pkg/schema/tracker_test.go
pkg/sqlmodel/row_change.go
pkg/sqlmodel/row_change_test.go
pkg/sqlmodel/utils.go
pkg/sqlmodel/utils_test.go

Issue Number: close #4816 
- add tracker.Close
- also add a test case that SHOW CREATE TABLE in downstream returns placement rule comment (I get the output from RFC, not test it in real TiDB)
- move some files in sqlmodel package
Tests 
- Unit test
```release-note
`None`.
```

tracker(dm): add UT and fix uncleaned folder

---

cdc/capture/capture.go
cdc/processor/pipeline/actor_node_context_test.go
cdc/processor/pipeline/system/system.go
cdc/processor/pipeline/system/system_test.go
cdc/processor/pipeline/table_actor_test.go
cdc/sorter/leveldb/system/system.go
pkg/actor/system.go
pkg/actor/system_test.go

Issue Number: close #4887
Tests 
- Unit test
Code changes
```release-note
None
```

pkg,cdc: remove actor system stop errors

---

Makefile

Issue Number: ref  #3583
* change build scripts
Tests 
- No code
Code changes
Side effects
```release-note
`None`
```

chore(dm): tweak build command for webui

---

dm/dm/config/task_converters.go
dm/dm/config/task_converters_test.go

Issue Number: ref #3583 
Tests 
- Unit test
- No code
Code changes
Side effects
```release-note
Please add a release note.
`None`.
```

config(dm): fix convert when migrate rule is null

---

deployments/ticdc/docker/integration-test.Dockerfile

Issue Number: close https://github.com/pingcap/tiflow/issues/4943
Tests 
- No code
Code changes
None
Side effects
None
None
```release-note
None
```

docker(ticdc): fix broken sha256 check

---

.github/workflows/upgrade_dm_via_tiup.yaml

remove ansible in upgrade test
```release-note
None
```

test: remove ansible in upgrade test

---

dm/ui/src/components/CreateOrUpdateTask/index.tsx
dm/ui/src/pages/migration/replication-detail.tsx
dm/ui/src/pages/migration/source.tsx

Tests 
- Unit test
- No code
Code changes
Side effects
```release-note
Please add a release note.
```

dm(ui): only request when hit check button

---

Makefile
tests/integration_tests/_utils/start_tidb_cluster_impl
tests/integration_tests/_utils/start_tls_tidb_cluster_impl

Issue Number: close #4979
Tests 
```release-note
None
```

Makefile,tests(ticdc): adjust version and print version in tests

---

dm/ui/src/components/CreateOrUpdateTask/MigrateRule.tsx
dm/ui/src/components/CreateOrUpdateTask/index.tsx

Tests 
- Unit test
- No code
Code changes
Side effects
```release-note
Please add a release note.
```

dm: fix form data consistency issue

---

pkg/cmd/server/server.go

Issue Number: close #5029 
before:
after:
Tests 
- No code
Code changes
Side effects
```release-note
`None`.
```

cdc/cli: hidden sorter parameters from server command.

---

pkg/cmd/server/server.go

Issue Number: close pingcap/tiflow#5029
this is a manually cherry-pick of https://github.com/pingcap/tiflow/pull/5031
Tests 
Code changes
Side effects
```release-note
`None`.
```

cdc/cli: hidden sorter parameters from server command. (#5031)

---

cdc/owner/feed_state_manager.go
cdc/owner/owner.go
cdc/scheduler/schedule_dispatcher.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/5039
fix some typos and add log.
Tests 
- No code
Code changes
None
Side effects
None
None
```release-note
None
```

owner,scheduler(ticdc): fix some typos and add log

---

cdc/sink/codec/canal.go
cdc/sink/codec/canal_flat_test.go
cdc/sink/codec/canal_test.go

Issue Number: close #5136 
cherry-pick #4635, #4736 to the hot fix branch.
Tests 
- No code
Code changes
Side effects
```release-note
`None`.
```

codec(cdc): hot-fix for canal-json 

---

tests/integration_tests/http_api/run.sh

Issue Number: ref #2958 
Tests 
- No code
Code changes
Side effects
```release-note
None
```

tests (ticdc): skip one unstable http_api integration test case

---

dm/loader/util.go
dm/pkg/dumpling/utils.go
dm/pkg/dumpling/utils_test.go
dm/syncer/checkpoint.go

as title
Tests 
the test is done in dataflow engine
Code changes
```release-note
`None`.
```

*(dm): parse mydumper metadata from external storage

---

cdc/processor/processor.go
cdc/scheduler/balancer.go
cdc/sink/sink_manager.go

Issue Number: close #5259 
* extract `processor.getTableName` method
* `processor.tick` return `nextState`, which is not used, so remove it.
Tests 
- No code
Code changes
Side effects
```release-note
`None`.
```

processor(cdc): extract getTableName method

---

dm/dm/worker/server.go
dm/dm/worker/source_worker.go
dm/dm/worker/status.go

Issue Number: close https://github.com/pingcap/tiflow/issues/5249
Add lock protection for `w.cfg`.
Tests 
- Unit test
Code changes
- None
Side effects
- None
- None
```release-note
None
```

worker: add lock protection for w.cfg

---

dm/syncer/syncer.go

Issue Number: close #5267
Tests 
- No code
Code changes
Side effects
```release-note
`None`.
```

syncer(dm): fix wrong ts array init size

---

cdc/sorter/leveldb/compactor.go
cdc/sorter/leveldb/reader.go
cdc/sorter/leveldb/writer.go
pkg/actor/actor.go
pkg/actor/system.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/5039
Fix typos during code browsing.
Tests 
- No code
Code changes
None
Side effects
None
None
```release-note
None
```

sorter(ticdc): fix typos

---

cdc/sorter/leveldb/reader.go
cdc/sorter/leveldb/reader_test.go
cdc/sorter/leveldb/sorter.go
cdc/sorter/leveldb/writer.go
cdc/sorter/leveldb/writer_test.go
cdc/sorter/metrics.go
cdc/sorter/unified/merger.go
metrics/grafana/ticdc.json

Issue Number: ref #5357
before:
after:
```release-note
`Fix a metrics error in level db sorter`.
```

sorter, metric(ticdc): fix a metric error in level db sorter

---

cmd/kafka-consumer/main.go

Fix flaking tests.
cherry-pick all changes to kafka-consumer to fix  the flaking tests.
Tests 
Code changes
None
Side effects
None
None
```release-note
None
```

kafka-consumer(ticdc): cherry-pick all changes

---

dm/_utils/terror_gen/errors_release.txt
dm/dm/worker/source_worker.go
dm/errors.toml
dm/pkg/schema/tracker.go
dm/pkg/terror/error_list.go
dm/pkg/utils/db.go
dm/pkg/utils/db_test.go
dm/syncer/checkpoint.go
dm/syncer/checkpoint_test.go
dm/syncer/dbconn/db.go
dm/syncer/schema.go
dm/syncer/syncer.go
dm/syncer/syncer_test.go
dm/tests/_utils/check_sync_diff
dm/tests/_utils/test_prepare
dm/tests/dmctl_basic/conf/dm-task.yaml
dm/tests/dmctl_basic/conf/get_task.yaml
dm/tests/dmctl_basic/run.sh
dm/tests/expression_filter/run.sh
dm/tests/handle_error_3/run.sh
dm/tests/many_tables/conf/source1.yaml
dm/tests/many_tables/run.sh
dm/tests/new_relay/run.sh
dm/tests/openapi/client/openapi_task_check
dm/tests/relay_interrupt/run.sh
dm/tests/sequence_sharding_optimistic/run.sh
dm/tests/shardddl1/run.sh
dm/tests/shardddl4/run.sh

close pingcap/tiflow#5344
Tests 
- Unit test
- No code
Code changes
Side effects
```release-note
Please add a release note.
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality …
```

tracker(dm): close and recreate tracker when pause and resume (#5350)

---

cdc/processor/pipeline/table.go
cdc/scheduler/internal/tp/agent.go
cdc/scheduler/internal/tp/agent_test.go
cdc/scheduler/internal/tp/capture_manager.go
cdc/scheduler/internal/tp/capture_manager_test.go
cdc/scheduler/internal/tp/coordinator.go
cdc/scheduler/internal/tp/coordinator_test.go
cdc/scheduler/internal/tp/replication_manager.go
cdc/scheduler/internal/tp/replication_manager_test.go
cdc/scheduler/internal/tp/replication_set.go
cdc/scheduler/internal/tp/replication_set_test.go
cdc/scheduler/internal/tp/schedulepb/table_schedule_manual_test.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/4757
Support capture init and shutdown.
- Unit test
```release-note
None
```

tp: support capture init and shutdown

---

cdc/processor/pipeline/puller.go
cdc/processor/pipeline/table.go
cdc/processor/pipeline/table_actor.go
cdc/processor/processor.go
cdc/sink/mysql/mysql.go
cdc/sink/mysql/mysql_test.go
cdc/sink/mysql/mysql_worker.go
cdc/sink/mysql/mysql_worker_test.go
pkg/cmd/server/server_test.go
pkg/config/config_test_data.go
pkg/config/server_config.go

Issue Number: close #5726
- Unit test
- Manual test (add 
```release-note
`None`.
```

pipeline(ticdc): disable table actor

---

cdc/scheduler/internal/tp/capture_manager_test.go
cdc/scheduler/internal/tp/coordinator.go
cdc/scheduler/internal/tp/coordinator_test.go
cdc/scheduler/internal/tp/replication_manager.go
cdc/scheduler/internal/tp/replication_manager_test.go
cdc/scheduler/internal/tp/replication_set.go
cdc/scheduler/internal/tp/replication_set_test.go
cdc/scheduler/internal/tp/scheduler_balance.go
cdc/scheduler/internal/tp/scheduler_balance_test.go
cdc/scheduler/internal/tp/scheduler_rebalance.go
cdc/scheduler/internal/tp/scheduler_rebalance_test.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/4757
Rebalance tables when a new capture online.
- Unit test
```release-note
None
```

tp: support balance when add a new capture

---

tests/integration_tests/README.md

Issue Number: close https://github.com/pingcap/tiflow/issues/5840
reorder run integration tests instructions. We should try to run tests in docker as a priority.
- No code
No
No
```release-note
None
```

tests(ticdc): reorder run integration tests instructions

---

cdc/scheduler/internal/tp/capture_manager.go
cdc/scheduler/internal/tp/coordinator.go
cdc/scheduler/internal/tp/coordinator_test.go
cdc/scheduler/internal/tp/scheduler.go
cdc/scheduler/internal/tp/scheduler_balance.go
cdc/scheduler/internal/tp/scheduler_balance_test.go
cdc/scheduler/internal/tp/scheduler_basic.go
cdc/scheduler/internal/tp/scheduler_basic_test.go
cdc/scheduler/internal/tp/scheduler_rebalance.go
pkg/cmd/server/server_test.go
pkg/config/config_test_data.go
pkg/config/scheduler_config.go
pkg/config/server_config.go
pkg/config/server_config_test.go

Separate balance scheduler to basic and balance
- Unit test
```release-note
None
```

tp: separate balance scheduler to basic and balance

---

cdc/api/middleware/middleware.go
cdc/api/v1/api.go
cdc/api/v2/api.go
cdc/api/v2/changefeed.go
cdc/api/v2/model.go
cdc/api/v2/unsafe.go
cdc/api/v2/validator.go
pkg/api/internal/rest/request.go
pkg/api/v2/changefeed.go
pkg/api/v2/unsafe.go
tests/integration_tests/http_api/util/test_case.py

change api code style 
- Unit test
```release-note
None`.
```

api(ticdc): change api v2 code style

---

Makefile
dm/dm/master/server.go
dm/dm/master/server_test.go
dm/tests/_utils/wait_process_exit

Issue Number: close #5793 close #5746 ref #5089
- No code
```release-note
`None`.
```

test(dm): fix unstable tests

---

cdc/api/middleware/middleware.go
cdc/api/v2/changefeed.go
cdc/api/v2/model.go
pkg/api/v2/changefeed.go
pkg/cmd/cli/cli_changefeed_update.go
pkg/cmd/cli/cli_changefeed_update_test.go
tests/integration_tests/cli/run.sh

define changefeedinfo api v2 model
- Unit test
- No code
```release-note
`None`.
```

api(ticdc): define changefeedinfo api v2 model

---

cdc/api/v1/api.go
cdc/api/v2/changefeed.go
cdc/api/v2/model.go
cdc/api/v2/model_test.go
cdc/api/v2/tso.go
cdc/api/v2/unsafe.go
cdc/api/v2/validator.go
cdc/model/changefeed.go
cdc/model/changefeed_test.go
cdc/model/upstream_test.go
cdc/processor/processor.go
errors.toml
pkg/api/v2/api_client.go
pkg/cmd/cli/cli_changefeed_create.go
pkg/cmd/cli/cli_changefeed_create_test.go
pkg/cmd/cli/cli_changefeed_query.go
pkg/errors/errors.go
pkg/orchestrator/reactor_state.go
pkg/upstream/manager.go
pkg/upstream/upstream.go

- Unit test
- No code
```release-note
```

*(ticdc): Release upstream and fix some issues

---

cdc/sink/mysql/causality.go
cdc/sink/mysql/causality_test.go
cdc/sink/mysql/mysql.go

Issue Number: close https://github.com/pingcap/tiflow/issues/5891
Add a comment to mysql explaining how to detect conflicts
- No code
No 
No 
```release-note
None
```

sink/mysql(ticdc): add comments

---

README.md

Issue Number: ref #5687
- No code
No
No
```release-note
`None`.
```

refine readme add release, golang info

---

cdc/api/v1/api.go
cdc/api/v1/validator.go
cdc/api/v2/changefeed.go
cdc/api/v2/unsafe.go
cdc/capture/capture.go
cdc/owner/changefeed.go
cdc/owner/owner.go
cdc/owner/owner_test.go
cdc/processor/manager.go
cdc/processor/processor.go
pkg/cmd/factory/factory_impl.go
pkg/etcd/etcd.go
pkg/orchestrator/reactor_state.go
pkg/upstream/manager.go
pkg/upstream/manager_test.go
pkg/upstream/upstream.go
tests/integration_tests/http_api_tls/util/test_case.py

- Unit test
- No code
```release-note
```

(WIP)upstream(ticdc): refine upstream manager

---

cdc/api/v2/changefeed.go
cdc/api/v2/changefeed_test.go
cdc/api/v2/validator.go
errors.toml
pkg/errors/errors.go
pkg/etcd/etcd.go
pkg/etcd/etcd_test.go
pkg/orchestrator/reactor_state.go

- Unit test
- No code
```release-note
```

api(ticdc) refactor changefeed update v2 using transaction

---

cdc/api/interfaces.go
cdc/api/middleware/middleware.go
cdc/api/middleware/middleware_test.go
cdc/api/v2/unsafe.go
cdc/api/v2/validator.go
pkg/etcd/etcdkey_test.go
pkg/upstream/manager.go
pkg/upstream/manager_test.go
pkg/upstream/upstream.go
pkg/upstream/upstream_test.go
tests/integration_tests/http_api/util/test_case.py

- Unit test
- No code
```release-note
```

ut(ticdc): Add test cases

---

cdc/api/v2/changefeed.go
cdc/api/v2/model_test.go
cdc/api/v2/unsafe.go
cdc/api/v2/unsafe_test.go
cdc/api/v2/validator.go
cdc/api/v2/validator_test.go
pkg/migrate/migrate.go
pkg/migrate/migrate_test.go
tests/integration_tests/http_api_tls/run.sh
tests/integration_tests/http_api_tls/util/test_case.py

- Unit test
- No code
```release-note
```

test(ticdc): Fix bugs and add test cases

---

cdc/processor/processor.go
cdc/processor/processor_test.go

fb/latency(cdc): adjust add table finish condition

---

cdc/scheduler/internal/tp/scheduler.go
cdc/scheduler/internal/tp/scheduler_balance.go
cdc/scheduler/internal/tp/scheduler_basic.go
cdc/scheduler/internal/tp/scheduler_basic_test.go
cdc/scheduler/internal/tp/scheduler_drain_capture.go
cdc/scheduler/internal/tp/scheduler_manager.go
cdc/scheduler/internal/tp/scheduler_manager_test.go
cdc/scheduler/internal/tp/scheduler_move_table.go
cdc/scheduler/internal/tp/scheduler_rebalance.go

Prioritize schedulers, basic scheduler has the highest priority.
- Unit test
- No code
```release-note
None
```

tp: prioritize schedulers

---

cmd/kafka-consumer/main.go
pkg/cmd/util/helper.go
pkg/logutil/context.go
pkg/logutil/context_test.go
pkg/logutil/log.go
pkg/logutil/log_test.go

Issue Number: close #6015 
Merge some util function of engine to tiflow/pkg/logutil
- Unit test
```release-note
`None`.
```

logutil(cdc, engine): add some util function to logutil for cdc and engine

---

engine/client/client_test.go
engine/executor/server.go
engine/executor/worker/task_committer_test.go
engine/executor/worker/task_runner_test.go
engine/framework/taskutil/compat.go
engine/pkg/etcdutil/config.go
engine/pkg/etcdutil/join.go
engine/pkg/etcdutil/join_test.go
engine/pkg/etcdutil/service.go
engine/pkg/etcdutil/testing.go
engine/pkg/serverutil/discovery_keepalive.go
engine/pkg/serverutil/discovery_keepalive_test.go
engine/servermaster/campaign.go
engine/servermaster/cluster/election_test.go
engine/servermaster/config.go
engine/servermaster/etcd_test.go
engine/servermaster/server.go
engine/test/etcd_utils.go
engine/test/heartbeat_test.go
engine/test/util_test.go

Issue Number: ref #6022
- rename `engine/pkg/etcdutils` to `engine/pkg/etcdutil`
- rename `engine/pkg/serverutils` to `engine/pkg/serverutil`
- rename `engine/framework/utils` to `engine/framework/taskutil`
- Unit test
```release-note
None
```

pkg(engine): refine package name

---

cdc/processor/pipeline/metrics.go
cdc/processor/pipeline/sink.go
cdc/sink/mysql.go

Issue Number: close #6033 
- Unit test
- No code
```release-note
None
```

Cdc add duration log

---

pkg/migrate/migrate.go
pkg/migrate/migrate_test.go

- Unit test
- No code
```release-note
```

test(ticdc): Add migrator ut test cases

---

Makefile

Issue Number: ref https://github.com/pingcap/tiflow/issues/6039
Bump the version to `6.2.0-master`
- No code
No
No
```release-note
None
```

version(ticdc): bump the default RELEASE_VERSION

---

tests/integration_tests/big_txn/conf/workload
tests/integration_tests/big_txn/run.sh

Issue Number: close #6046 
Reduce the transaction size to ~50MB, which is 5 times larger than single-table quota.
```release-note
`None`.
```

tests(ticdc): fix unstable test big_txn

---

cdc/sinkv2/tablesink/main_test.go
cdc/sinkv2/tablesink/progress_tracker.go
cdc/sinkv2/tablesink/progress_tracker_test.go

Deleting elements during an iteration may cause an iterator exception.
- Unit test
No
No
```release-note
None
```

sinkv2(ticdc): fix progress can not advance issue and add tests

---

cdc/scheduler/internal/tp/scheduler_move_table_test.go
pkg/cmd/cli/cli_unsafe_reset.go
pkg/config/server_config.go
pkg/config/server_config_test.go
pkg/migrate/migrate.go
pkg/migrate/migrate_test.go
pkg/upstream/manager.go
pkg/upstream/upstream.go

rename old etcd data  after migration is done, the old etcd data will be stored under the prefix "/tidb/cdc/__backup__/0" prefix
if failed , print it to cdc log
- Unit test
- No code
```release-note
```

migrator(ticdc): Delete old changefeed

---

cdc/scheduler/internal/tp/agent.go
cdc/scheduler/internal/tp/agent_test.go
cdc/scheduler/internal/tp/capture_manager.go
cdc/scheduler/internal/tp/scheduler_basic.go
cdc/scheduler/internal/tp/scheduler_basic_test.go
cdc/scheduler/internal/tp/scheduler_rebalance.go

Issue Number: close #6112 
- Unit test
```release-note
`None`.
```

SchedulerV3: basic scheduler don't add tables to the stopping capture

---

cdc/processor/pipeline/puller.go
cdc/processor/pipeline/sink.go
cdc/processor/pipeline/sink_test.go
cdc/processor/pipeline/sorter.go
cdc/processor/pipeline/sorter_test.go
cdc/processor/pipeline/table_actor.go
cdc/processor/pipeline/table_actor_test.go

Issue Number: close #6138
remove replConfig in pipeline
- Unit test
```release-note
`None`.
```

pipeline(ticdc): remove replConfig in pipeline

---

cdc/api/v1/api_test.go
tests/integration_tests/changefeed_resume_with_checkpoint_ts/run.sh

Fix merge master to feature branch test failed issues
- Unit test
- No code
```release-note
`None`.
```

test(ticdc): Fix merge master to feature branch test failed issues

---

docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml

Issue Number: ref https://github.com/pingcap/tiflow/issues/5231
Fix incompatible configuration of transaction-atomicity in swagger.
- No code
```release-note
`None`.
```

docs(ticdc): fix incompatible configuration of transaction-atomicity

---

engine/executor/server/metastore.go
engine/executor/server/metastore_test.go
engine/executor/server/mocks/metastore_mock.go
engine/pkg/cmd/master/master.go
engine/pkg/dbutil/config.go
engine/pkg/dbutil/util.go
engine/pkg/meta/kvclient/client.go
engine/pkg/meta/kvclient/etcdkv/etcd_client.go
engine/pkg/meta/kvclient/etcdkv/etcd_client_test.go
engine/pkg/meta/metaclient/config.go
engine/pkg/orm/client.go
engine/pkg/orm/client_test.go
engine/servermaster/config.go
engine/servermaster/config_test.go
engine/servermaster/metastore_manager.go
engine/servermaster/metastore_manager_test.go
engine/servermaster/server.go
engine/test/e2e/e2e_test_cli.go

Issue Number: close #6173 
1. Add 'Schema' param to 'StoreConfig'
2. Unify 'StoreConfigParams' to 'StoreConfig'
3. Extract 'dbutil' pkg to make sql implement for kv client easier 
```release-note
`None`.
```

config(engine): Refine meta storeConfig(Part1)

---

errors.toml
pkg/cmd/factory/factory_impl.go
pkg/errors/cdc_errors.go
pkg/etcd/etcd.go
pkg/etcd/etcd_test.go
pkg/etcd/etcdkey.go
pkg/migrate/migrate.go
pkg/migrate/migrate_test.go

- Unit test
- No code
```release-note
`None`
```

cli(ticdc): add cli checks while using --pd

---

cdc/api/v2/model.go
cdc/api/v2/model_test.go
cdc/capture/capture.go
pkg/cmd/cli/cli_changefeed_create_test.go

Issue Number: ref #5663
fix api model filter bug
- Unit test
```release-note
`None`.
```

api(ticdc): fix api model filter bug

---

tests/integration_tests/consistent_replicate_gbk/run.sh
tests/integration_tests/consistent_replicate_nfs/run.sh
tests/integration_tests/consistent_replicate_s3/run.sh
tests/integration_tests/consistent_replicate_schedulerv3/run.sh

Issue Number: close #6167
Increased waiting time.
```release-note
`None`.
```

tests(ticdc): fix unstable s3 test

---

.github/workflows/dataflow_engine_chaos.yaml
engine/chaos/manifests/kind-cluster.yaml

Issue Number: ref #5640
Use multiple worker nodes in kind cluster, in order to make the tests more like to real world cases.
- Unit test
```release-note
None
```

chaos(engine): use multiple worker nodes in kind cluster

---

pkg/causality/internal/node_test.go

Issue Number: close #6227
- Disable parallel run on `TestNodeFree`.
- Unit test
No.
No.
```release-note
None.
```

pkg/causality: fix race caused by TestNodeFree

---

cdc/api/v2/changefeed.go

Issue Number: close #6311 
```release-note
None
```

apiV2 (ticdc): fix update changefeed return info

---

cdc/model/changefeed.go
cdc/model/errors.go
cdc/model/errors_test.go
cdc/owner/feed_state_manager.go
cdc/owner/feed_state_manager_test.go
dm/dm/config/task_test.go
errors.toml
pkg/errors/cdc_errors.go
pkg/errors/helper.go
pkg/errors/helper_test.go
pkg/txnutil/gc/gc_manager_test.go

Issue Number: ref #6160 
- Unit test
no
```release-note
None
```

error (ticdc): add changefeed not retry error

---

cdc/processor/pipeline/sorter.go
cdc/scheduler/internal/v3/agent.go
cdc/scheduler/internal/v3/agent_bench_test.go
cdc/scheduler/internal/v3/agent_test.go
cdc/scheduler/internal/v3/coordinator.go
cdc/scheduler/internal/v3/coordinator_bench_test.go
cdc/scheduler/internal/v3/replication_manager.go
cdc/scheduler/internal/v3/replication_manager_test.go
cdc/scheduler/internal/v3/replication_set.go
cdc/scheduler/internal/v3/replication_set_test.go
cdc/scheduler/internal/v3/scheduler_balance.go
cdc/scheduler/internal/v3/scheduler_basic.go
cdc/scheduler/internal/v3/scheduler_basic_test.go
cdc/scheduler/internal/v3/scheduler_drain_capture.go
cdc/scheduler/internal/v3/scheduler_drain_capture_test.go
cdc/scheduler/internal/v3/scheduler_manager.go
cdc/scheduler/internal/v3/scheduler_move_table.go
cdc/scheduler/internal/v3/scheduler_move_table_test.go
cdc/scheduler/internal/v3/scheduler_rebalance.go
cdc/scheduler/internal/v3/scheduler_rebalance_test.go
cdc/scheduler/internal/v3/table.go
cdc/scheduler/internal/v3/table_test.go

Add changefeed fields to scheduler logs.
- Unit test
No.
No.
```release-note
None
```

scheduler(ticdc): add changefeed to logs

---

cdc/server/metrics.go
cdc/server/metrics_server.go
cdc/server/server.go
cdc/server/server_test.go
pkg/cmd/server/server.go

Issue Number: ref #6356 
introduce `Server` interface, and move it to the corresponding package.
- No code
```release-note
`None`
```

server(cdc): introduce server package and add the interface

---

pkg/config/sink.go
pkg/config/sink_test.go

Issue Number: close #6360
- Unit test
- No code
```release-note
`None`.
```

config (ticdc): Fix sink protocol can no specify by config file.

---

cdc/kv/client.go
cdc/kv/metrics.go
cdc/kv/region_worker.go
pkg/workerpool/pool.go
pkg/workerpool/pool_impl.go

Issue Number: close #5610
reduce context switch for stateful events 
- Unit test
```release-note
`None`.
```

puller(ticdc): hotfix for 5.4.1- reduce context switch for stateful events 

---

cdc/kv/region_worker.go

Issue Number: ref #5610 
- Unit test
- No code
```release-note
None
```

kv(cdc): set enableOldValue correctly

---

cdc/owner/changefeed.go
cdc/owner/changefeed_test.go
cdc/owner/ddl_sink.go
tests/integration_tests/syncpoint/run.sh

This is a cherrypick of #6390 
Issue Number: close #4934 
```release-note
```

ddl_sink (ticdc): fix ddl sink nil point panic (#6390)

---

pkg/actor/system.go
pkg/util/failpoint.go
tests/mq_protocol_tests/main.go

Issue Number: closes #6480
See also https://github.com/pingcap/tidb/issues/36519
- No code
```release-note
None
```

typo(ticdc): Fix spelling of 'true'

---

cdc/scheduler/internal/v3/replication_set.go
cdc/scheduler/internal/v3/replication_set_test.go

Issue Number: close #6477
Set state to absent when there is no capture in replicationset.
- Unit test
No
No
```release-note
None
```

scheduler(ticdc): transit to Absent when captures are empty

---

engine/executor/dm/worker.go
engine/executor/dm/worker_test.go
engine/framework/logutil/util.go
engine/jobmaster/dm/api_test.go
engine/jobmaster/dm/checkpoint/agent.go
engine/jobmaster/dm/checkpoint/agent_test.go
engine/jobmaster/dm/dm_jobmaster.go
engine/jobmaster/dm/dm_jobmaster_test.go
engine/jobmaster/dm/openapi_test.go
engine/jobmaster/dm/task_manager.go
engine/jobmaster/dm/task_manager_test.go
engine/jobmaster/dm/worker_manager.go
engine/jobmaster/dm/worker_manager_test.go
engine/pkg/dm/message_agent.go
engine/pkg/dm/message_agent_test.go

replace log with embedded logger
- Unit test
```release-note
None
```

engine(dm): replace log with embedded logger

---

engine/pkg/meta/internal/sqlkv/sql_impl.go
engine/pkg/orm/client.go
engine/pkg/orm/log.go
engine/pkg/orm/log_test.go
engine/pkg/orm/util.go
pkg/logutil/log.go
pkg/logutil/log_test.go

Issue Number: close #6465 
Implement logger.Interface to self-defined the orm logger
- Unit test
```release-note
`None`.
```

orm(engine): Implement orm log

---

.github/workflows/dataflow_engine_chaos.yaml
engine/chaos/manifests/conf/server-master.toml
engine/chaos/manifests/metastore.yaml

Issue Number: close https://github.com/pingcap/tiflow/issues/6511
- Unit test
- No code
```release-note
None
```

chaos(engine): fix etcd-endpoints for servermaster

---

pkg/version/check.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/6039
bump compatible versions to v6.3.0.
- Unit test
No
No
```release-note
None
```

pkg/version(ticdc): bump compatible versions

---

dm/tests/run.sh
dm/tests/shardddl3_1/run.sh

Issue Number: close #3461
also this PR added `others_integration_3.txt`, after we modify the CI pipeline we can move some cases from others_integration_1 & 2 to it
- No code
```release-note
`None`.
```

test(dm): fix an unstable test and prepare to split tests

---

cdc/model/changefeed.go
cdc/sink/mq/mq.go
pkg/cmd/cli/cli_changefeed_create.go
pkg/cmd/cli/cli_changefeed_create_test.go
pkg/config/sink.go

Warning on using Pulsar sink. 
- No code
No
No
```release-note
None
```

sink(ticdc): warning on using pulsar sink

---

engine/servermaster/openapi.go
engine/servermaster/openapi_test.go
engine/test/e2e/e2e_test.go
engine/test/e2e/e2e_test_cli.go

Issue Number: ref #6255
- Use `application/json` as context-type in OpenAPI
- Unit test
```release-note
None
```

openapi(engine): use application/json in submit job api

---

Makefile

Issue Number: ref https://github.com/pingcap/tiflow/issues/6493
See more: https://github.com/pingcap/tiflow/pull/6595#discussion_r936421163
Add format and check targets for makefiles. 
- No code
No
No
```release-note
None
```

makefile(all): add format and check targets for makefiles

---

cdc/capture/capture.go
cdc/capture/capture_test.go

Issue Number: close #6646
Because TiCDC release-6.2 does not support cross version upgrade and stops
service during upgrade, it is impossible to perform graceful shutdown.
- Unit test
No.
No.
```release-note
None
```

capture(ticdc): disable best effort graceful shutdown

---

cdc/owner/changefeed.go
cdc/processor/pipeline/sink.go
cdc/redo/manager.go
cdc/redo/manager_test.go
cdc/redo/writer/blackhole_writer.go
cdc/redo/writer/writer.go
tests/integration_tests/consistent_replicate_s3_schev2/conf/changefeed.toml
tests/integration_tests/consistent_replicate_s3_schev2/conf/diff_config.toml
tests/integration_tests/consistent_replicate_s3_schev2/conf/server.toml
tests/integration_tests/consistent_replicate_s3_schev2/conf/workload
tests/integration_tests/consistent_replicate_s3_schev2/run.sh

Issue Number: close #6663 
This is a manaul cherry-pick of the #6518 
- No code
```release-note
`None`
```

redo(cdc): merge 0822 redo hotfix

---

dm/pkg/binlog/position.go
dm/pkg/binlog/position_test.go
dm/pkg/binlog/reader/reader.go
dm/syncer/binlogstream/binlog_locations.go
dm/syncer/binlogstream/binlog_locations_test.go
dm/syncer/binlogstream/streamer_controller.go
dm/syncer/binlogstream/streamer_controller_test.go
dm/syncer/binlogstream/util.go
dm/syncer/data_validator_test.go
dm/syncer/syncer.go
dm/syncer/syncer_test.go
dm/tests/drop_column_with_index/run.sh
dm/worker/source_worker.go

Issue Number: ref #6319
some renaming, split functions and simple unit tests
- Unit test
```release-note
`None`.
```

syncer(dm): refine codes to prepare combine location recorder

---

engine/executor/server.go
engine/pkg/externalresource/broker/broker.go
engine/pkg/externalresource/broker/file_manager.go

Issue Number: close #6777
- Apply the configuration to the broker.
- Unit test
- Manual test
No.
No.
```release-note
None.
```

executor(engine): Fix broker config not taking effect

---

dm/_utils/terror_gen/errors_release.txt
dm/errors.toml
dm/pkg/schema/tracker.go
dm/pkg/schema/tracker_test.go
dm/pkg/terror/error_list.go
dm/pkg/utils/common.go

Issue Number: close #6774 
as title
- Unit test
```release-note
`None`.
```

tracker(dm): use TiDB's mock session context to avoid panic

---

cdc/api/open.go
cdc/model/changefeed.go
cdc/model/changefeed_test.go
pkg/cmd/cli/cli_changefeed_create.go
pkg/cmd/cli/cli_changefeed_query.go
pkg/orchestrator/etcd_worker.go
pkg/util/uri.go
pkg/util/uri_test.go

Issue Number: close #6362 
1. changefeed info in log
```shell
[2022/08/19 16:28:23.560 +08:00] [INFO] [etcd_worker.go:466] ["[etcd worker] ==========Update State to ETCD=========="]
[2022/08/19 16:28:23.560 +08:00] [INFO] [etcd_worker.go:481] ["[etcd worker] update changefeed info"] [key=/tidb/cdc/changefeed/info/test-1] [value="{\"upstream-id\":0,\"sink-uri\":\"mysql://root:xxxx@127.0.0.1:3306/?time-zone=\",\"opts\":{},\"create-time\":\"2022-08-19T16:13:58.502125+08:00\",\"start-ts\":435394140828598273,\"target-ts\":0,\"admin-job-type\":0,\"sort-engine\":\"unified\",\"sort-dir\":\"\",\"config\":{\"case-sensitive\":true,\"enable-old-value\":true,\"force-replicate\":false,\"check-gc-safe-point\":true,\"filter\":{\"rules\":[\"test1.t1\",\"t …
```

changefeed (ticdc): Mask sensitive information in changefeed info

---

cdc/processor/pipeline/puller.go
cdc/processor/pipeline/sink.go

- Remove useless RsolvedTs API.
- No code
No
No
```release-note
None
```

sink(ticdc): remove useless API

---

dm/pkg/binlog/event/util.go
dm/pkg/binlog/position.go
dm/syncer/binlogstream/binlog_locations.go
dm/syncer/binlogstream/binlog_locations_test.go
dm/syncer/binlogstream/stream_modifier.go
dm/syncer/binlogstream/streamer_controller.go
dm/syncer/binlogstream/streamer_controller_test.go
dm/syncer/causality_test.go
dm/syncer/compactor_test.go
dm/syncer/data_validator.go
dm/syncer/dml_test.go
dm/syncer/filter.go
dm/syncer/filter_test.go
dm/syncer/job.go
dm/syncer/job_test.go
dm/syncer/opt_sharding_group_test.go
dm/syncer/optimist.go
dm/syncer/shardddl.go
dm/syncer/sharding-meta/shardmeta.go
dm/syncer/sharding_group.go
dm/syncer/syncer.go
dm/tests/fake_rotate_event/run.sh
dm/tests/handle_error/run.sh

Issue Number: ref #4287
don't let syncer maintain currentLocations, etc. Read them from streamController
- Unit test
```release-note
`None`.
```

syncer(dm): enable location recorder

---

.github/workflows/dataflow_engine_e2e.yaml
Makefile
cmd/tiflow-demoserver/kvdatamake.go
deployments/engine/docker-compose/1m1e.yaml
deployments/engine/docker-compose/1m3e.yaml
deployments/engine/docker-compose/3m3e.yaml
deployments/engine/docker-compose/demo.yaml
deployments/engine/docker-compose/dm_databases.yaml
deployments/engine/docker/dev.Dockerfile
docs/ci/command.md
engine/test/e2e/e2e_node_chaos_test.go
engine/test/integration_tests/README.md
engine/test/integration_tests/dm_basic/run.sh
engine/test/integration_tests/dm_case_sensitive/run.sh
engine/test/integration_tests/dm_collation/run.sh
engine/test/integration_tests/dm_full_mode/conf/diff_config.toml
engine/test/integration_tests/dm_full_mode/run.sh
engine/test/integration_tests/e2e_basic/run.sh
engine/test/integration_tests/e2e_node_failure/run.sh
engine/test/integration_tests/e2e_worker_error/run.sh
engine/test/integration_tests/run.sh
engine/test/utils/adjust_config
engine/test/utils/run_engine.sh
engine/test/utils/start_engine_cluster
engine/test/utils/stop_engine_cluster

Issue Number: ref #6255
1. Store integration test logs to `tmp/tiflow_engine_test/${TEST_NAME}`
2. Use nightly build of tidb cluster to run engine integration tests
```release-note
`None`.
```

test(engine): handle integration test logs properly

---

cdc/model/changefeed.go
cdc/model/changefeed_test.go
cdc/owner/changefeed.go
pkg/version/creator_version_gate.go
pkg/version/creator_version_gate_test.go

Issue Number: close #6874 
- Unit test
```release-note
None
```

changefeed (ticdc): fix mysql sink config contains protocol error

---

engine/executor/server.go
engine/internal/pkg/discovery/agent.go
engine/internal/pkg/discovery/agent_test.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/6867
Refactor `discovery.Agent` to use `ListMasters` and `ListExecutors` API.
- Unit test
- No code
```release-note
None
```

discovery(engine): refactor agent to use list api

---

engine/jobmaster/dm/api_test.go
engine/jobmaster/dm/dm_jobmaster.go
engine/jobmaster/dm/metadata/cluster_info.go
engine/jobmaster/dm/metadata/cluster_info_test.go
engine/jobmaster/dm/metadata/ddl.go
engine/jobmaster/dm/metadata/job.go
engine/jobmaster/dm/metadata/job_test.go
engine/jobmaster/dm/metadata/metadata.go
engine/jobmaster/dm/openapi_test.go
engine/jobmaster/dm/task_manager_test.go
engine/jobmaster/dm/worker_manager_test.go
engine/pkg/adapter/keyadapter.go

- remove job id prefix in metadata
- Unit test
```release-note
None
```

engine(dm): remove job id prefix in metadata

---

engine/pkg/notifier/notifier.go
engine/pkg/notifier/notifier_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/6911
- Unit test
- No code
```release-note
None
```

pkg/notifier(engine): fix receiver being blocked on closing

---

pkg/pdutil/api_client.go

Issue Number: close #6932 
```release-note
`None`.
```

pd(ticdc): fix collect member endpoint meet panic.

---

dm/syncer/ddl.go

Issue Number: ref #6909
- No code
```release-note
`None`.
```

fmt(*): fix comment format for go1.19

---

deployments/engine/docker-compose/1m1e.yaml
deployments/engine/docker-compose/1m3e.yaml
deployments/engine/docker-compose/1meta.yaml
deployments/engine/docker-compose/3m3e.yaml
dm/pb/hide_password.go
dm/pkg/utils/util.go
dm/pkg/utils/util_test.go
engine/enginepb/hide_sensitive.go
engine/enginepb/hide_sensitive_test.go
engine/test/integration_tests/dm_many_tables/conf/job.yaml
engine/test/integration_tests/dm_new_collation_off/conf/job.yaml
pkg/logutil/log_test.go
pkg/logutil/sensitive.go
pkg/logutil/sensitive_test.go

Issue Number: close #6917 
1. Migrate some function in `dm/pkg/utils/util.go` to `pkg/logutil/sensitive.go` for reuse of such code.
2. Implement `zapcore.ObjectMarshaler` for `Job and CreateJobRequest`.
- Unit test
```release-note
`None`.
```

log(engine, dm): hide sensitive info in log

---

engine/servermaster/scheduler/errors.go

Issue Number: close #6899 
```release-note
`None`.
```

error(engine): fix duplicated rpc error name 

---

dm/tests/sharding2/run.sh

Issue Number: ref #6909
if DM-worker runs too quickly, it will exit by failpoint and fail the script `check_rpc_alive `
- No code
```release-note
`None`.
```

test(dm): fix unstable CI

---

dm/tests/shardddl3/run.sh

Issue Number: close #7009
as title
- No code
```release-note
`None`.
```

test(dm): resume the task for kill-master test

---

cdc/sinkv2/tablesink/progress_tracker.go
cdc/sinkv2/tablesink/progress_tracker_test.go
cdc/sinkv2/tablesink/table_sink_impl.go
go.mod
go.sum

Issue Number: ref #5928 
Improve performance about sinkv2 progress tracker.
- Unit test
- Manual test
The manual test shows progress tracker won't be the bottleneck anymore.
```release-note
None
```

sinkv2(ticdc): improve sinkv2 progress tracker

---

cdc/sink/metrics/metrics.go
metrics/grafana/ticdc.json

Issue Number: close #7049 
merge `kvclient` and `events` panels together, and adjust the layout, remove useless some.
- Unit test
- No code
```release-note
`None`.
```

metrics(ticdc): merge kv client and events metrics monitoring together and simplication.

---

metrics/alertmanager/ticdc.rules.yml
metrics/grafana/ticdc.json

Issue Number: close #7050
Update metrics and alert rules.
- Manual test
No.
No.
```release-note
None
```

metrics: replace processor checkpoint with owner checkpoint

---

cdc/sink/mysql.go

Issue Number: close #6698
```release-note
None
```

mysql (ticdc): use white list for retryable error

---

cdc/metrics.go

Issue Number: close #5690
```release-note
fix no sorter metrics
```

metrics(ticdc): fix no sorter metrics

---

cdc/sinkv2/eventsink/blackhole/black_hole_dml_sink.go
cdc/sinkv2/eventsink/blackhole/black_hole_dml_sink_test.go
cdc/sinkv2/eventsink/blackhole/main_test.go
dm/pkg/log/log_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/7138
call callbacks in black hole sink.
- Unit test
No
No
```release-note
None
```

sinkv2(ticdc): call callbacks in black hole sink

---

engine/test/integration_tests/dm_many_tables/conf/job.yaml
engine/test/integration_tests/dm_many_tables/run.sh
engine/test/utils/run_sql

Issue Number: ref #6776
mimic print_status test
```release-note
`None`.
```

test(engine): add query job integration test

---

cdc/sinkv2/ddlsink/mq/kafka_ddl_sink.go
cdc/sinkv2/ddlsink/mq/mq_ddl_sink_test.go
cdc/sinkv2/eventsink/mq/kafka_dml_sink.go
cdc/sinkv2/eventsink/mq/mq_dml_sink_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/7190
correctly return the error message. Do not rewrite it.
- Unit test
No
No
```release-note
None
```

sinkv2(ticdc): correctly return the error message

---

engine/test/integration_tests/dm_collation/run.sh
engine/test/integration_tests/dm_sql_mode/data/db1.increment.sql
engine/test/integration_tests/dm_sql_mode/data/db1.prepare.sql
engine/test/integration_tests/dm_sql_mode/data/db2.increment.sql
engine/test/integration_tests/dm_sql_mode/data/db2.prepare.sql

Issue Number: ref #6776
```release-note
`None`.
```

test(engine): migrate DM GBK test

---

cdc/processor/processor.go
cdc/sinkv2/eventsink/factory/factory.go
cdc/sinkv2/eventsink/factory/factory_test.go
cdc/sinkv2/tablesink/table_sink_impl.go
cdc/sinkv2/tablesink/table_sink_impl_test.go

improve logs for table sink. Print changefeedID and checkpointTs.
- No code
No
No
```release-note
None
```

sinkv2(ticdc): improve logs for table sink

---

engine/chaos/cases/main.go
engine/executor/main_test.go
engine/executor/server.go
engine/executor/server_test.go
engine/executor/worker/task_committer_test.go
engine/framework/base_jobmaster.go
engine/framework/internal/worker/master_client_test.go
engine/framework/main_test.go
engine/framework/model/master_test.go
engine/jobmaster/cvsjob/cvs_job_master.go
engine/jobmaster/example/master_impl.go
engine/servermaster/campaign.go
engine/servermaster/http_test.go
engine/servermaster/jobmanager.go
engine/servermaster/main_test.go
engine/servermaster/server.go
engine/servermaster/server_test.go
engine/test/e2e/e2e_dm_test.go
pkg/httputil/httputil.go
pkg/httputil/httputil_test.go

Issue Number: ref #7271
- Fix all errors under the engine module, with `golangci-lint v1.50.0`
- Unit test
```release-note
None
```

lint(engine): fix all lint errors in engine module

---

engine/pkg/rpcerror/grpc.go

Issue Number: close https://github.com/pingcap/tiflow/issues/7316
- Unit test
- No code
```release-note
None
```

openapi(engine): log verbose request/response info for debug

---

metrics/grafana/ticdc.json

Issue Number: ref  https://github.com/pingcap/tiflow/issues/1606
update changefees status dashboard to display the status label.
- Manual test
- No code
No
No
```release-note
None
```

metric(ticdc): update changefees status dashboard

---

.github/pull_request_template.md

Issue Number: ref https://github.com/pingcap/tiflow/issues/5039
Fix typo. feature -> features
- No code
NO
NO
```release-note
None
```

github(all): fix typo in PR template

---

Makefile

Bump the value form `v6.3.0-master` to `v6.4.0-master`.
- No code
No
No
```release-note
None
```

makefile(all): bump the default release version

---

pkg/sorter/memory/doc.go
pkg/sorter/memory/event_sorter.go
pkg/sorter/memory/event_sorter_test.go
pkg/sorter/memory/main_test.go
pkg/sorter/sorter.go

Issue Number: ref #5928 
Add a memory table based sort engine for tests
- Unit test
```release-note
None
```

sinkv2(cdc): add a memory table based sort engine for tests

---

metrics/grafana/ticdc.json

Issue Number: close #7530
Correct expression
- No code
No.
No.
```release-note
None
```

grafana(ticdc): fix KV client batch resolved region count expression

---

engine/enginepb/hide_sensitive.go
engine/enginepb/hide_sensitive_test.go
engine/executor/server/metastore.go
engine/pkg/externalresource/internal/s3/file_manager.go

Issue Number:  ref #6917
hide sensitive info in log
- Unit test
```release-note
`None`.
```

log(engine): hide sensitive info in log

---

cdc/processor/processor.go
cdc/processor/sinkmanager/manager_impl.go
cdc/processor/sinkmanager/worker_impl.go
cdc/processor/sourcemanager/engine/factory/factory.go
cdc/processor/sourcemanager/engine/mounted_iter.go
cdc/processor/sourcemanager/engine/mounted_iter_test.go
cdc/processor/sourcemanager/engine/pebble/event_sorter.go
cdc/processor/sourcemanager/puller/puller_wrapper.go
pkg/config/server_config.go

Issue Number: ref #5928 
Fix some bugs about pull-based sink, introduced in some latest PRs.
- Unit test
```release-note
None
```

processor(ticdc): fix some bugs about pull-based sink

---

engine/servermaster/jobop/config.go

Issue Number: close #7666 
1. increase the total backoff time to 48 hours
- Unit test
- No code
```release-note
increase the total backoff time to 48 hours.
```

feat(backoff): increase the total backoff time to 48 hours

---

engine/servermaster/scheduler/scheduler.go
engine/servermaster/scheduler/scheduler_test.go
errors.toml
pkg/errors/engine_errors.go

Issue Number: close #7670 
- Unit test
```release-note
`None`.
```

scheduler(engine): fix scheduler panic

---

engine/executor/server/metastore.go

Issue Number: ref #6917
remove sensitive info in log
- Unit test
```release-note
`None`.
```

log(engine): remove sensitive info in log

---

cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/redo_log_worker.go
cdc/processor/sinkmanager/table_sink_worker.go
cdc/processor/sinkmanager/table_sink_worker_test.go
cdc/processor/sourcemanager/engine/pebble/event_sorter.go
cdc/processor/sourcemanager/puller/puller_wrapper.go

Issue Number: close https://github.com/pingcap/tiflow/issues/7674
[processor/sinkmanager(ticdc): fix error handle bug](https://github.com/pingcap/tiflow/commit/2a6919f09326379c0e26599d83f9ca17d8a324a6)
[processor/sinkmanager(ticdc): fix error filtered events bug](https://github.com/pingcap/tiflow/commit/a1e21e0a61041829689a24faf3767ffd23ed4f46)
[processor/sinkmanager(ticdc): fix data race in event sorter](https://github.com/pingcap/tiflow/commit/a5ea8b5ff09ee5a28930506cde6201a7c262a0a3)
- Unit test
No
No
```release-note
None
```

processor/sinkmanager(ticdc): refine error handle and skip empty event

---

engine/jobmaster/dm/dm_jobmaster.go

- add timeout for oncancel
- Unit test
- No code
```release-note
None
```

dm_jobmaster: add time out for waiting worker offline

---

scripts/canal/docker/Dockerfile

Issue Number: ref #2246
- add `-k` to curl
the cert is expired:
```
curl -o /etc/yum.repos.d/CentOS-Base.repo https://www.xmpan.com/Centos-6-Vault-Aliyun.repo
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
- Unit test
- No code
```release-note …
```

test(cdc): fix canal integration

---

metrics/grafana/tiflow.json

Issue Number: ref https://github.com/pingcap/tiflow/issues/6985
1. Add server monitor to engine.
2. Add a new variable `instance`.
3. Optimize the existing panel measurement units.
https://snapshots.raintank.io/dashboard/snapshot/U80Ntir3piC16oCHkp5joIR89oWUrVxp?orgId=2
```release-note
```

engine(metrics): add server monitor to engine

---

pkg/cmd/server/server_test.go
pkg/config/config_test_data.go
pkg/config/debug.go
pkg/config/server_config.go
tests/integration_tests/processor_err_chan/run.sh

Issue Number: close https://github.com/pingcap/tiflow/issues/7849
disable pull-based sink and update tests.
- Unit test
No
No
```release-note
None
```

config(ticdc): disable pull based sink

---

pkg/config/config_test_data.go
pkg/config/server_config.go

Issue Number: close #7855 .
Reduce sorter.MaxMemoryPercentage from 30% to 10%.
- Unit test
```release-note
None
```

sorter: reduce sorter memory percentage from 30% to 10%

---

engine/jobmaster/dm/api_test.go
engine/jobmaster/dm/dm_jobmaster.go
engine/jobmaster/dm/openapi_test.go
engine/jobmaster/dm/task_manager.go
engine/jobmaster/dm/task_manager_test.go
engine/test/e2e/e2e_dm_test.go
metrics/grafana/DM-Monitor-Professional.json
metrics/grafana/DM-Monitor-Standard.json

Issue Number: ref https://github.com/pingcap/tiflow/issues/6985
1. Add job_id variable to dm grafana.
- No code
```release-note
`None`.
```

metrics(dm, engine): add job_id variable to dm grafana

---

pkg/orchestrator/reactor_state.go

Issue Number: ref #7877
Test in release-6.5
Before this PR:
`orchestrator.(*EtcdWorker).applyPatchGroups` cost 7.96% CPU.
`json.Unmarshal` cost 6.37% CPU.
After this PR:
`orchestrator.(*EtcdWorker).applyPatchGroups` cost 2.58% CPU.
`json.Unmarshal` cost 2.58% CPU.
- Unit test
```release-note
None
```

pkg(ticdc): replace json lib with go-json in etcd worker

---

cdc/owner/owner.go
cdc/owner/owner_test.go

Issue Number: close #7882
- Use correct rfc error and error format
- Unit test
```release-note
None
```

owner(ticdc): refine error message of create changefeed delay

---

cdc/owner/owner.go
cdc/processor/manager.go

Issue Number: ref #5039
Remove useless comments.
- No code
```release-note
None
```

chore(ticdc): remove useless comment

---

dm/config/subtask.go
dm/syncer/checkpoint.go
dm/syncer/dbconn/db.go
dm/syncer/online-ddl-tools/online_ddl.go
dm/syncer/sharding_group.go
dm/syncer/syncer.go
engine/executor/dm/api.go
engine/executor/dm/api_test.go
engine/jobmaster/dm/api_test.go
engine/jobmaster/dm/config/config.go
engine/jobmaster/dm/config/config_test.go
engine/pkg/dm/topic.go
engine/test/e2e/e2e_dm_test.go

Issue Number: close #7933
- separate network metering from upstream & downstream
- Unit test
- No code
```release-note
`None`.
```

network(dm): meter network usage from upstream & downstream

---

CONTRIBUTING.md
README.md
README_DM.md
README_TiCDC.md

Issue Number: close #7994 
- Refine wording and format in 3 readme files and `CONTRIBUTING.md`
- Make descriptions consistent
- Update old links to the latest ones
- No code
No.
No.
```release-note
None
```

*: improve readme and update outdated links

---

cdc/processor/sinkmanager/redo_log_worker.go
cdc/processor/sourcemanager/engine/factory/factory.go

Issue Number: close #7986
Issue Number: close #7983 
- Unit test
- No code
```release-note
None
```

sinkv2(cdc): fix some races of source manager

---

dm/ui/src/components/CreateOrUpdateTask/MigrateRule.tsx

- Unit test
- No code
```release-note
Fix DM web block-allow list is not expected
```

fix(ui): update pattern

---

pkg/sqlmodel/multirow_test.go

Issue Number: ref #8057
Task-1
Add virtual generated column and stored generated column tests.
- Unit test
```release-note
None
```

tests(ticdc): gen multi rows update with generated column scenario

---

cdc/sinkv2/ddlsink/mysql/mysql_ddl_sink.go

Issue Number: close https://github.com/pingcap/tiflow/issues/8071
remove duplicate DDL statistics
None
No
No
```release-note
None
```

sinkv2(ticdc): remove duplicate DDL statistics

---

cdc/sink/mysql/mysql.go
cdc/sink/mysql/mysql_test.go

Issue Number: ref #8079 
- Unit test
- No code
```release-note
```

disable batch update dmls

---

pkg/pdutil/utils.go

Issue Number: ref #8110 #8115
- Unit test
```release-note
None
```

ticdc: workround for get source id error

---

cdc/api/v2/api.go
cdc/api/v2/model.go
cdc/api/v2/processor.go
docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml

Issue Number: ref #8019 
Implement the list processors for API v2
- Unit test
No
No
```release-note
None
```

apiv2(ticdc): implement the list processors

---

cdc/api/v2/api.go
cdc/api/v2/changefeed.go
cdc/api/v2/changefeed_test.go
cdc/api/v2/model.go
docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml

Issue Number: ref #8019 
Implement the get changefeed for API v2
- Unit test
No
No
```release-note
None
```

apiv2(ticdc): implmenet the GET changefeed

---

Makefile

bump the default version to v6.7.0
- No code
No
No
```release-note
None
```

Makefile(ticdc): bump the version to v6.7.0

---

cdc/api/v2/model.go
cdc/api/v2/model_test.go

Issue Number: close #8345
- Unit test
No
No
```release-note
None
```

cdc/api/v2: add missing scheduler config

---

pkg/chann/chann.go
pkg/chann/drainable_chann.go

Issue Number: ref #8255
remove close method of DrainableChann
- Unit test
```release-note
`None`.
```

pkg/chann(ticdc): remove close method of DrainableChann

---

pkg/sink/kafka/admin.go

Issue Number: close #8391 
This is introduced by #8228 
ignore topic exist error
- Unit test
```release-note
`None`
```

kafka(ticdc): ignore sarama admin create topic exist

---

cdc/api/v2/model.go
cdc/api/v2/model_test.go
cdc/model/changefeed_test.go
cdc/scheduler/internal/v3/agent/agent_test.go
cdc/scheduler/internal/v3/compat/compat.go
cdc/scheduler/internal/v3/compat/compat_test.go
cdc/scheduler/internal/v3/coordinator_test.go
cdc/scheduler/internal/v3/keyspan/reconciler_test.go
docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/config/config_test_data.go
pkg/config/replica_config.go
pkg/config/replica_config_test.go
pkg/config/scheduler_config.go
tests/integration_tests/cli/run.sh

Issue Number: close #8393
- Unit test
No
No
```release-note
None
```

config(ticdc): adjust config name

---

cdc/processor/sinkmanager/manager_test.go
cdc/processor/sinkmanager/table_sink_advancer.go
cdc/processor/sinkmanager/table_sink_advancer_test.go
cdc/processor/sinkmanager/table_sink_worker.go
cdc/processor/sinkmanager/table_sink_worker_test.go
cdc/processor/sinkmanager/table_sink_wrapper_test.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/8132
- add table sink advancer and test it
- refine table sink worker test
- Unit test
No
No
```release-note
None
```

sink(ticdc): add table sink advancer

---

cdc/owner/feed_state_manager.go
cdc/owner/feed_state_manager_test.go

Issue Number: close #8425
Only update epoch when state changes.
- Unit test
No.
No.
```release-note
None
```

owner(ticdc): only update epoch when state changes

---

cdc/api/v2/api_helpers_test.go
cdc/api/v2/changefeed.go
cdc/api/v2/model.go
pkg/cmd/cli/cli_changefeed_query.go
pkg/version/version.go

Issue Number: close #8433
use time.Time in changefeed info to keep compacibility 
- Unit test
```release-note
`None`.
```

apiv2(ticdc): use time.Time in changefeed info

---

cdc/api/v2/model.go
cdc/api/v2/model_test.go

Issue Number: close #8480
add ut for api default value
- Unit test
- No code
```release-note
`None`.
```

apiv2(ticdc): add ut for api default value

---

tests/integration_tests/api_v2/cases.go

Issue Number: close #8503
add more integration tests about api v2
- Unit test
```release-note
`None`.
```

apiv2(ticdc):  add more integration tests about api v2

---

cdc/processor/manager_test.go
cdc/processor/processor_test.go
cdc/processor/sinkmanager/manager_test.go
cdc/processor/sinkmanager/manager_test_helper.go
cdc/processor/sinkmanager/redo_log_worker_test.go
cdc/processor/sinkmanager/table_sink_worker_test.go
cdc/processor/sourcemanager/engine/memory/event_sorter.go
cdc/processor/sourcemanager/manager.go
cdc/processor/sourcemanager/puller/dummy_puller_wrapper.go
cdc/processor/sourcemanager/puller/puller_wrapper.go

Issue Number: close https://github.com/pingcap/tiflow/issues/8132
Reenable all skipped tests.
- Unit test
No
No
```release-note
None
```

processor(ticdc): make tests happy

---

cdc/sink/ddlsink/mq/kafka_ddl_sink.go

Issue Number: ref #8523 
* check error after create the admin client.
```release-note
`None`
```

kafka(ticdc): ddl sink create admin client check error.

---

cdc/redo/reader/file.go
cdc/redo/reader/file_test.go
cdc/redo/reader/reader.go
cdc/redo/reader/reader_test.go
pkg/applier/redo.go

Issue Number: ref #8056
1. After downloading a file, sort the file before writing it to the local disk to [avoid multiple disk access](https://github.com/pingcap/tiflow/pull/8407/files#diff-702fc02e577e50bc8109e25c72a283bd7cb82f4f9ce76e34aac437be0bedcd59R116).
- Unit test
- No code
```release-note
`None`.
```

redo(ticdc): simplify reader initialization

---

cdc/sinkv2/eventsink/txn/mysql/dml.go
cdc/sinkv2/eventsink/txn/mysql/dml_test.go
cdc/sinkv2/eventsink/txn/mysql/mysql.go
cdc/sinkv2/eventsink/txn/mysql/mysql_test.go
pkg/applier/redo_test.go
pkg/sink/mysql/config.go
pkg/sink/mysql/db_helper.go

Issue Number: ref #8057
cherry pick multi stmt sql feature (#8349) (#8395) (#8554) (#8627)
- Unit test
```release-note
Support multi statements SQL in mysql backend
```

cherry pick multi statement sql feature (#8349) (#8395) (#8554) (#8627)

---

cdc/entry/mounter.go
cdc/model/sink.go
cdc/processor/sinkmanager/manager_test.go
cdc/processor/sinkmanager/table_sink_worker_test.go
cdc/processor/sinkmanager/table_sink_wrapper_test.go
pkg/sink/codec/avro/avro.go
pkg/sink/codec/avro/avro_test.go
pkg/sink/codec/common/config.go
pkg/sink/codec/common/config_test.go

Issue Number: close #8788
- Unit test
```release-note
`None`
```

codec(ticdc): avro support row level checksum 

---

.github/workflows/ticdc_integration.yaml

Issue Number: close #8835
- Use install scripts from https://docs.docker.com/engine/install/ubuntu/
```release-note
None
```

ci: refine docker install scripts in github action ci

---

tests/integration_tests/run_group.sh

Issue Number: ref #8686
- Unit test
- No code
```release-note
```

tests(ticdc): add comment to storage sink

---

tests/integration_tests/csv_storage_multi_tables_ddl/run.sh
tests/integration_tests/lossy_ddl/run.sh

Issue Number: ref #8772
- Unit test
- No code
```release-note
```

tests(ticdc): fix broken storage tests

---

cdc/entry/schema/snapshot.go
cdc/entry/schema_storage.go
cdc/model/sink.go
cdc/model/sink_test.go
cdc/owner/schema.go
tests/integration_tests/canal_json_storage_partition_table/data/prepare.sql
tests/integration_tests/csv_storage_partition_table/data/prepare.sql
tests/integration_tests/ddl_reentrant/run.sh
tests/integration_tests/partition_table/data/prepare.sql

Issue Number: close #8956
- Unit test
- No code
```release-note
`FIx the issue of exchange partition can not cross schema`.
```

owner(ticdc): fix exchange partition ddl

---

cdc/processor/processor.go
cdc/scheduler/internal/v3/agent/table.go
cdc/scheduler/internal/v3/replication/replication_manager_test.go
cdc/scheduler/internal/v3/replication/replication_set.go
cdc/scheduler/internal/v3/replication/replication_set_test.go

Issue Number: close #9080
report resolvedTs when removing table 
- Unit test
```release-note
`None`.
```

processor, scheduler(ticdc): report resolvedTs when removing table

---

errors.toml
pkg/errors/cdc_errors.go
pkg/sink/kafka/admin.go
pkg/sink/kafka/cluster_admin_client.go
pkg/sink/kafka/cluster_admin_client_mock_impl.go
pkg/sink/kafka/options.go
pkg/sink/kafka/options_test.go
pkg/sink/kafka/v2/admin.go
pkg/sink/kafka/v2/admin_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/8959
add GetTopicConfig support to get the config correctly.
- Unit test
No
No
```release-note
None
```

pkg/sink(ticdc): add GetTopicConfig support

---

go.mod
go.sum
pkg/sink/kafka/v2/metrics_collector.go

Issue Number: close #9129 
```release-note
`None`
```

metrics(ticdc): fix inaccurate kafka v2 batch time metrics.

---

cdc/contextutil/ctx.go
cdc/contextutil/ctx_test.go
cdc/processor/processor.go
cdc/puller/ddl_puller.go
cdc/puller/memorysorter/entry_sorter.go

Issue Number: close #9147
remove table info from context
- Unit test
- No code
```release-note
`None`.
```

puller(ticdc): remove table info from context

---

cdc/api/v1/validator.go

Issue Number: close #9133
- Unit test
- No code
```release-note
fix a bug that  api v1 not parse protocol from uri
```

api(ticdc): fix api v1 not parse protocol from uri bug

---

tests/integration_tests/kafka_compression/run.sh

Issue Number: ref https://github.com/pingcap/tiflow/issues/2246
fix the flaky test. Add some wait time.
No
No
```release-note
None
```

tests(ticdc): fix the flaky test

---

dm/tests/case_sensitive/run.sh

- No code
```release-note
`None`.
```

test(dm): uncomment a test after tidb-tools update dependency

---

cdc/api/v2/model.go
cdc/api/v2/model_test.go
cdc/model/changefeed.go
docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/cmd/util/helper_test.go
pkg/config/config_test_data.go
pkg/config/replica_config.go
pkg/config/replica_config_test.go
pkg/config/sink.go
pkg/sink/codec/common/config.go
pkg/sink/codec/common/config_test.go
pkg/sink/codec/internal/message_key.go
pkg/sink/codec/open/open_protocol_encoder.go
pkg/sink/codec/open/open_protocol_message.go
pkg/sink/codec/open/open_protocol_message_test.go

Issue Number: close #9165, close #9188
- Unit test
```release-note
`None`
```

codec(ticdc): open-protocol support encode only handle key column if the message size large than the max message bytes

---

pkg/chann/chann.go

Issue Number: ref #9222 
Recycle memory for unbounded channel.
- Unit test
```release-note
None
```

cdc: recycle memory for unbounded channel

---

cdc/processor/processor.go
cdc/processor/processor_test.go
cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/redo_log_worker.go
cdc/processor/sinkmanager/table_sink_worker.go
cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/processor/sourcemanager/engine/engine.go
cdc/processor/sourcemanager/engine/memory/event_sorter.go
cdc/processor/sourcemanager/engine/mock/engine_mock.go
cdc/processor/sourcemanager/engine/pebble/event_sorter.go
cdc/processor/sourcemanager/engine/pebble/event_sorter_test.go
cdc/processor/sourcemanager/manager.go

Issue Number: close #9213 .
Use correct sorter resolved timestamp to collect table progresses.
- Unit test
```release-note
None
```

sorter(cdc): use correct resolved timestamp to check progress

---

pkg/sink/codec/avro/decoder.go
pkg/sink/codec/decoder.go

Issue Number: close #9231 
- Unit test
```release-note
`None`
```

codec(ticdc): refactor avro decoder by split the decode row method into small pieces

---

cdc/processor/sourcemanager/puller/puller_wrapper.go
cdc/puller/ddl_puller.go
cdc/puller/puller.go
cdc/puller/puller_test.go
metrics/alertmanager/ticdc.rules.yml

Issue Number: ref #9047 
- No code
```release-note
None
```

metrics (ticdc): remove stale alert rules

---

cdc/processor/processor.go
cdc/processor/processor_test.go
cdc/processor/sinkmanager/redo_log_advancer_test.go
cdc/redo/manager.go
cdc/scheduler/internal/table_executor.go
cdc/scheduler/internal/v3/agent/agent.go
cdc/scheduler/internal/v3/agent/agent_test.go
cdc/scheduler/internal/v3/agent/table.go

Issue Number: close #9172
- advance redo resolvedTs before start sink
- Unit test
- No code
```release-note
```

scheduler, processor(ticdc): advance redo resolvedTs before start sink

---

cdc/entry/mounter_test.go
pkg/sink/codec/avro/avro.go
pkg/sink/codec/avro/avro_test.go
pkg/sink/codec/avro/decoder.go
pkg/sink/codec/avro/decoder_test.go
pkg/sink/codec/avro/mock_schema_registry.go
pkg/sink/codec/avro/schema_registry_test.go

Issue Number: close #9275 
* implement own checksum calculation functionality.
- Unit test
```release-note
`None`
```

avro(ticdc): calculate checksum locally by follow tidb rules

---

cdc/capture/capture.go
engine/pkg/p2p/server.go
engine/pkg/p2p/server_integration_test.go
engine/servermaster/server.go
engine/test/integration_tests/dm_full_mode/run.sh
pkg/p2p/client.go
pkg/p2p/client_batch_sender.go
pkg/p2p/grpc_client.go
pkg/p2p/grpc_client_test.go
pkg/p2p/message_router.go
pkg/p2p/message_router_test.go
pkg/p2p/mock_cluster.go
pkg/p2p/model.go
pkg/p2p/server.go
pkg/p2p/server_client_integration_test.go
pkg/p2p/server_stream_handle.go
pkg/p2p/server_test.go

Issue Number: close #9271
- Implement [localMessageClient](https://github.com/pingcap/tiflow/pull/9211/files#diff-383b951c4b03d5a64a7163d3f9e73cc222afc3e6703494367d1cec2d0df9b80eR67-R114).
- Handle [rawMessage](https://github.com/pingcap/tiflow/pull/9211/files#diff-f4f5940c380388473c4ca734d83ac7dc52ccf96c5559f26289c9a9412d1f09a8R38-R41) in [p2p server](https://github.com/pingcap/tiflow/pull/9211/files#diff-c4eae5eb3eed9c8f62c2f92a78ef82f02b78a1c496bcec048e76ddec1f75c8d4R659-R691)
- Unit test
- No code
```release-note
If you don't think this PR …
```

pkg/p2p(ticdc): implement local client and server

---

cdc/kv/region_worker.go
cdc/owner/changefeed.go
cdc/owner/feed_state_manager.go
cdc/processor/processor.go
cdc/scheduler/internal/v3/coordinator.go
pkg/pdutil/clock.go
pkg/pdutil/clock_test.go
pkg/txnutil/gc/gc_manager.go

Issue Number: close #9294 
- Unit test
- No code
```release-note
```

pdutil (ticdc): refine pd clock interface

---

dm/tests/case_sensitive/run.sh

manually cherry-pick #9181 
Issue Number: ref #9215
- Unit test
- No code
```release-note
```

test(dm): reset SQL mode when exit test case

---

cdc/owner/changefeed.go
cdc/scheduler/internal/v3/coordinator.go
cdc/scheduler/internal/v3/coordinator_test.go
cdc/scheduler/internal/v3/info_provider_test.go
cdc/scheduler/internal/v3/replication/replication_manager.go
cdc/scheduler/internal/v3/replication/replication_set.go
cdc/scheduler/internal/v3/scheduler/scheduler_basic.go
pkg/spanz/btree_map.go

Issue Number: ref #9058
adjust some logic in scheduler
- Unit test
- No code
```release-note
```

scheduler(ticdc): adjust some logic in scheduler

---

cmd/storage-consumer/main.go
tests/integration_tests/big_txn/run.sh

Issue Number: ref #8772
- Unit test
- No code
```release-note
```

tests, consumer(ticdc): fix storage consumer

---

cdc/entry/schema/snapshot.go
cdc/model/schema_storage.go
cdc/model/sink.go

Issue Number: close #9311 
- Unit test
```release-note
`None`
```

schema(ticdc): fix some redundant logic and incorrect comment

---

pkg/util/external_storage.go

Issue Number: ref #8772, close #9316
1. check connection when create storage
- Unit test
- No code
```release-note
```

sink(ticdc): fix create storage sink

---

pkg/sink/codec/open/open_protocol_encoder.go
pkg/sink/codec/open/open_protocol_message.go
pkg/sink/codec/open/open_protocol_message_test.go

Issue Number: close #9336 
- Unit test
```release-note
`None`
```

codec(ticdc): adjust open protocol only output udated column

---

cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer_test.go
cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer_test.go

Issue Number: close #8493
- Unit test
```release-note
`None`
```

kafka(ticdc): remove parallel from kafka dml producer unit test

---

dm/pkg/checker/table_structure_test.go
dm/pkg/checker/utils.go

Issue Number: close #9247
- Unit test
```release-note
`None`.
```

checker(dm): handle expression UNIQUE index

---

cdc/sink/ddlsink/mq/ddlproducer/ddl_producer.go
cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_mock_producer.go
cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer_test.go
cdc/sink/ddlsink/mq/kafka_ddl_sink.go
cdc/sink/ddlsink/mq/mq_ddl_sink.go
cdc/sink/dmlsink/mq/dmlproducer/dml_producer.go
cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_mock_producer.go
cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer.go
cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer_test.go
cdc/sink/dmlsink/mq/kafka_dml_sink.go
cdc/sink/dmlsink/mq/mq_dml_sink.go
cdc/sink/dmlsink/mq/worker_test.go
pkg/sink/kafka/factory.go
pkg/sink/kafka/mock_factory.go
pkg/sink/kafka/sarama_factory.go
pkg/sink/kafka/sarama_factory_test.go
pkg/sink/kafka/v2/factory.go
pkg/sink/kafka/v2/factory_test.go

Issue Number: close #9367 
- Unit test
```release-note
`None`
```

kafka(ticdc): simplify the kafka sink initialization and close process

---

cdc/api/v2/model.go
cdc/api/v2/model_test.go
cdc/model/changefeed.go
cdc/sink/ddlsink/mq/mq_ddl_sink_test.go
cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer.go
cdc/sink/dmlsink/mq/kafka_dml_sink.go
docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/cmd/cli/cli_changefeed_create.go
pkg/cmd/util/helper_test.go
pkg/config/config_test_data.go
pkg/config/replica_config.go
pkg/config/replica_config_test.go
pkg/config/sink.go
pkg/sink/codec/common/config.go
pkg/sink/codec/common/config_test.go
pkg/sink/codec/open/open_protocol_decoder_test.go
pkg/sink/codec/open/open_protocol_encoder.go
pkg/sink/codec/open/open_protocol_encoder_test.go
pkg/sink/kafka/options_test.go
pkg/sink/kafka/v2/factory_test.go

Issue Number: close #9346 
* add changefeed level replica config to control how to handle large messages
- Unit test
```release-note
`None`
```

config(ticdc): add large message handle option config

---

cdc/api/v2/model.go
cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink_test.go
cdc/sink/ddlsink/factory/factory.go
docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/config/config_test_data.go
pkg/config/replica_config_test.go
pkg/config/sink.go
pkg/sink/cloudstorage/config.go
pkg/sink/cloudstorage/config_test.go
pkg/sink/cloudstorage/path.go
pkg/sink/cloudstorage/table_definition.go
pkg/sink/cloudstorage/table_definition_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/9360
- Unit test
- No code
```release-note
```

sink(ticdc): output column id as the unique flag for each column

---

metrics/grafana/ticdc.json

Issue Number: close #9399 
- No code
```release-note
`None`
```

metrics(ticdc): add claim check monitoring panels

---

cdc/sink/dmlsink/mq/kafka_dml_sink.go
cdc/sink/dmlsink/mq/mq_dml_sink.go
cdc/sink/dmlsink/mq/worker.go
cmd/kafka-consumer/main.go
pkg/config/sink.go
pkg/sink/codec/canal/canal_json_row_event_encoder.go
pkg/sink/codec/common/message.go
pkg/sink/codec/encoder.go
pkg/sink/codec/open/open_protocol_encoder.go

Issue Number: close #9427 
* rename `ClaimCheckEncoder` to `ClaimCheckLocationEncoder`
* refactor kafka consumer
* fix claim-check compression configuration check.
* adjust `NewClaimCheckFileName` method
- Unit test
```release-note
`None`
```

kafka(ticdc): kafka consumer refactor and adjust codec interface

---

cdc/entry/mounter_test.go
cmd/kafka-consumer/main.go
pkg/sink/codec/avro/avro.go
pkg/sink/codec/avro/avro_test.go
pkg/sink/codec/avro/avro_test_data.go
pkg/sink/codec/avro/decoder.go
pkg/sink/codec/avro/decoder_test.go
pkg/sink/codec/avro/schema_registry.go
pkg/sink/codec/avro/schema_registry_test.go

Issue Number: close #9428 
* refactor the avro encoder
- Unit test
```release-note
`None`
```

codec(ticdc): refactor avro encoder to make it easier to extend

---

cdc/api/middleware/middleware.go
tests/integration_tests/http_api/util/test_case.py
tests/integration_tests/http_api_tls/util/test_case.py

Issue Number: close #9474
abort request if error
- Unit test
```release-note
`None`.
```

api(ticdc):  fix api middleware issue

---

pkg/sink/kafka/admin.go

Issue Number: close #9480 
- Unit test
```release-note
`None`
```

kafka(ticdc): fix sarama admin client reset by error.

---

cdc/api/v2/changefeed.go
cdc/api/v2/changefeed_test.go
cdc/owner/feed_state_manager.go
pkg/retry/error_retry.go

Issue Number: close #9483 
- Unit test
```release-note
None
```

apiV2 (ticdc): list changefeed shows warning message

---

cdc/processor/processor.go
cdc/processor/processor_test.go

Issue Number: close #9378
do not ignore ErrRedoWriterStopped
- Unit test
- No code
```release-note
`Fix a bug that global resolvedTs could be stuck when redo is enabled`.
```

processor(ticdc): do not ignore ErrRedoWriterStopped

---

cdc/controller/controller.go
cdc/controller/controller_test.go
cdc/model/changefeed.go
cdc/owner/changefeed.go
cdc/owner/feed_state_manager.go
pkg/errors/helper.go
pkg/errors/helper_test.go
pkg/txnutil/gc/gc_manager.go
pkg/txnutil/gc/gc_manager_test.go

Issue Number: close #9543
1. calculate pending changefeed in gc 
2. Add NeedBlockGC method to [changefeed info](https://github.com/pingcap/tiflow/pull/9541/files#diff-583f738be01c00c61f9e1e77daf5cd95a6bed049479befd7f23adf6cf7e21749R208-R218)
- Unit test
- No code
```release-note
```

owner(ticdc): calculate pending changefeed in gc

---

pkg/upstream/upstream.go

Issue Number: close #9523
- Unit test
- No code
```release-note
`None`.
```

upstream(ticdc):  init client go global cfg

---

dm/tests/sync_collation/run.sh

Issue Number: close #9610
see issue
- Unit test
```release-note
`None`.
```

test(dm): fix integration test about utf8mb4_0900_ai_ci

---

cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/processor/sinkmanager/table_sink_wrapper_test.go

cherry-pick of #9618
Issue Number: close #9592
- Unit test
- No code
```release-note
```

sink(ticdc): cherry pick data loss fix to release 6.5

---

cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/processor/sinkmanager/table_sink_wrapper_test.go

cherry-pick of https://github.com/pingcap/tiflow/pull/9618
Issue Number: close #9592
- Unit test
- No code
```release-note
`None`.
```

sink(ticdc): cherry pick data loss fix to hotfix release

---

CONTRIBUTING.md
Makefile
README_DM.md
README_TiCDC.md
cdc/server/server_test.go
deployments/engine/docker/Dockerfile
deployments/engine/docker/dind.Dockerfile
deployments/ticdc/docker/Dockerfile
deployments/ticdc/docker/dev.Dockerfile
deployments/ticdc/docker/integration-test.Dockerfile
deployments/ticdc/docker/kafka-consumer.Dockerfile
deployments/ticdc/docker/storage-consumer.Dockerfile
dm/Dockerfile
engine/framework/worker_test.go
examples/golang/avro-checksum-verification/go.mod
examples/golang/canal-json-handle-key-only/go.mod
go.mod
go.sum
tools/check/go.mod

Issue Number: close #9616 
- No code
```release-note
None
```

go: update to 1.21

---

cdc/controller/controller.go
cdc/controller/controller_test.go

Issue Number: close #9633
- Unit test
- No code
```release-note
`None`.
```

gc(ticdc):  do not block gc if there is no changefeed

---

Makefile

- Unit test
```release-note
None
```

Makefile: bump version to v7.4.0-master

---

cdc/puller/ddl_puller.go
metrics/alertmanager/ticdc.rules.yml
pkg/config/replica_config.go
pkg/config/replica_config_test.go
pkg/config/scheduler_config.go

Issue Number: close #9645 
- Unit test
```release-note
None
```

config (ticdc): add checking for changefeed scheduler config

---

cdc/puller/multiplexing_puller.go

Issue Number: close #9663 .
Fix a minor code race.
- Unit test
```release-note
None
```

puller(cdc): fix a code race

---

cdc/scheduler/internal/v3/keyspan/mock.go
cdc/scheduler/internal/v3/keyspan/reconciler.go
cdc/scheduler/internal/v3/keyspan/reconciler_test.go
cdc/scheduler/internal/v3/keyspan/splitter_region_count.go
cdc/scheduler/internal/v3/keyspan/splitter_region_count_test.go
cdc/scheduler/internal/v3/keyspan/splitter_write.go
cdc/scheduler/internal/v3/keyspan/splitter_write_test.go
pkg/pdutil/api_client.go

Issue Number: close #9665
- Unit test
- No code
```release-note
`None`.
```

scheduller(ticc): fix uneven write keys distribution

---

tests/integration_tests/http_api/util/test_case.py

Issue Number: close #9682 
```release-note
None
```

tests (ticdc): fix unstable integration: http_api

---

metrics/grafana/TiCDC-Monitor-Summary.json
metrics/grafana/ticdc.json

Issue Number: close #9649 
- No code
```release-note
Fix wrong metrics calculation expression. 
```

metrics (ticdc): fix error metrics expression

---

pkg/compression/compress.go
pkg/config/large_message.go
pkg/config/large_message_test.go
pkg/config/replica_config_test.go
pkg/config/sink.go
pkg/sink/codec/common/config.go

Issue Number: close #9678 
- Unit test
```release-note
`None`
```

config(ticdc): refine the kafka config adjust and validation 

---

pkg/sink/pulsar/factory.go
pkg/sink/pulsar/logger.go

Issue Number: ref #9413
```release-note
None
```

pulsar (ticdc): pulsar use ticdc log

---

pkg/cmd/server/server_test.go
pkg/config/config_test_data.go
pkg/config/db.go
pkg/config/server_config.go
pkg/config/sorter.go

Issue Number: close #9655
1. remove unused cdc server configuration
2. update code comment
- Unit test
- No code
```release-note
`None`.
```

config(ticdc): remove unused cdc server configuration

---

cdc/owner/feed_state_manager.go
cdc/owner/feed_state_manager_test.go

Issue Number: close #9697
- Unit test
- No code
```release-note
```

owner(ticdc): fix changefeed backoff

---

tests/integration_tests/http_proxies/run-proxy.go

Issue Number: close #9721
add log for http_proxies integration test
- Unit test
- No code
```release-note
`None`.
```

proxy(ticdc): add error log for http proxy

---

pkg/config/replica_config_test.go
pkg/config/sink.go
pkg/util/uri.go
pkg/util/uri_test.go

Issue Number: close #9743
add ut for pr 9691
- Unit test
- No code
```release-note
`None`.
```

config(ticdc): add ut for pr 9691

---

cdc/sink/ddlsink/mq/kafka_ddl_sink.go
cdc/sink/ddlsink/mq/mq_ddl_sink.go
cdc/sink/ddlsink/mq/mq_ddl_sink_test.go
cdc/sink/ddlsink/mq/pulsar_ddl_sink.go
cdc/sink/dmlsink/mq/dispatcher/event_router.go
cdc/sink/dmlsink/mq/dispatcher/event_router_test.go
cdc/sink/dmlsink/mq/kafka_dml_sink.go
cdc/sink/dmlsink/mq/pulsar_dml_sink.go
cmd/kafka-consumer/main.go
cmd/pulsar-consumer/main.go

Issue Number: close #9760 
- Unit test
```release-note
`None`
```

kafka(ticdc): event router simplify to make it easier 

---

cdc/sink/dmlsink/mq/manager/pulsar_manager.go
cmd/pulsar-consumer/main.go
pkg/config/sink.go

Issue Number: ref #9413
```release-note
None
```

pulsar (ticdc): fix pulsar sink related errors 

---

scripts/download-integration-test-binaries.sh
tests/integration_tests/new_ci_collation/data/test1.sql
tests/integration_tests/new_ci_collation/data/test2.sql

Issue Number: close https://github.com/pingcap/tiflow/issues/9796
Add utf8mb4_0900_ai_ci related tests.
- Unit test
- No code
```release-note
`None`.
```

tests(ticdc): add utf8mb4_0900_ai_ci tests

---

cdc/kv/client.go

Issue Number: close #9739 
Fix an out of range panic.
- Unit test
```release-note
None
```

kvclient(cdc): fix an out of range panic in client

---

metrics/grafana/ticdc.json

1 add pulsar metrics template
Issue Number: ref https://github.com/pingcap/tiflow/issues/9413
- No code
```release-note
None
```

metrics, pulsar (ticdc): add pulsar metrics panel

---

cdc/kv/region_state.go
cdc/kv/region_worker.go
cdc/kv/shared_client.go
cdc/kv/shared_region_worker.go
cdc/kv/shared_stream.go

Issue Number: ref #9660 
Issue Number: close #9749  
Remove some noicy debug logs in kvclient module.
- No code
```release-note
None
```

kvclient(cdc): remove some noicy logs in the module

---

Makefile

- Unit test
```release-note
None
```

Makefile: bump version to v7.5.0-master

---

cdc/scheduler/internal/v3/agent/table.go
cdc/scheduler/internal/v3/replication/replication_set.go
cdc/scheduler/internal/v3/replication/replication_set_test.go

Issue Number: close #9769 
- Unit test
- Manual test 
```release-note
Fix a issue that may cause error when a changefeed was restarted.
```

scheduler (ticdc): does not return error when resolvedTs less than checkpoint

---

cdc/owner/ddl_manager.go
cdc/owner/schema.go
cdc/owner/schema_test.go
pkg/filter/filter.go
pkg/filter/filter_test.go

Issue Number: close #9819 
- Unit test
```release-note
Fix a bug that could lead to TiCDC replicating DDL events of ineligible tables.
```

ddlManager (ticdc): Fix a bug that could lead to TiCDC replicating DDL events of ineligible tables.

---

cdc/sink/dmlsink/mq/mq_dml_sink.go

Issue Number: ref #9855
- Unit test
```release-note
`None`
```

kafka(ticdc): fix kafka dml sink report error to sink manager

---

cdc/api/v1/api.go
cdc/api/v2/changefeed.go
cdc/api/v2/changefeed_test.go
cdc/capture/capture.go
cdc/controller/controller.go
cdc/controller/controller_test.go
cdc/controller/mock/controller_mock.go
pkg/etcd/etcd.go
pkg/etcd/etcd_test.go
pkg/etcd/mock/etcd_client_mock.go

Issue Number: close #9866
- Unit test
- No code
```release-note
None`.
```

controller(ticdc):  add CreateChangefeed func for controller

---

cdc/kv/client.go
cdc/kv/metrics.go
cdc/kv/regionlock/region_range_lock.go
cdc/kv/regionlock/region_range_lock_test.go
cdc/kv/shared_client.go
cdc/kv/shared_client_test.go
cdc/kv/sharedconn/conn_and_client.go
cdc/kv/sharedconn/conn_and_client_test.go
cdc/processor/sourcemanager/manager.go
cdc/puller/ddl_puller.go

Issue Number: ref #9222 
Add more metrics and debug logs for kv-client.
- No code
```release-note
None
```

kv-client(cdc): add more metrics and logs

---

pkg/sink/codec/simple/decoder.go
pkg/sink/codec/simple/encoder.go

Issue Number: close #9899 
- No code
```release-note
`None`
```

codec(ticdc): add simple encoder and decoder interface declaration.

---

pkg/upstream/manager.go

Issue Number: close #9915 
- Unit test
```release-note
fix panic caused by changefeed info is nil
```

changefeed(ticdc): check changefeed info is nil to prevent panic

---

cdc/server/server.go
cdcv2/capture/capture.go
pkg/cmd/server/server_test.go
pkg/config/cdc_v2.go
pkg/config/cdc_v2_test.go
pkg/config/config_test_data.go
pkg/config/debug.go
pkg/config/server_config.go

Issue Number: close #9913
add a flag to create new capture implememtation
- Unit test
- No code
```release-note
`None`.
```

server(ticc): add feature flag for cdc v2

---

cdc/owner/mock/status_provider_mock.go
cdc/owner/owner.go
cdc/owner/owner_test.go
cdc/owner/status_provider.go

Issue Number: close #9921
refine status provider interface
- Unit test
- No code
```release-note
`None`.
```

owner(ticdc): refine status provider interface

---

cdc/model/errors_test.go
cdcv2/metadata/model.go
cdcv2/metadata/sql/client.go
cdcv2/metadata/sql/client_orm.go
cdcv2/metadata/sql/client_test.go
cdcv2/metadata/sql/observation.go
pkg/config/replica_config.go

Issue Number: ref #9196
- Unit test
- No code
```release-note
```

metadata(cdc): add unit tests (part 3)

---

cdc/kv/regionlock/region_range_lock.go
cdc/kv/shared_client.go

Issue Number: ref #9222 
Log slowest regions and region holes to help debug potential bugs.
- No code
```release-note
None
```

kv-client(cdc): log slowest regions and region holes

---

cdc/kv/client.go
cdc/kv/region_worker.go
pkg/txnutil/lock_resolver.go

Issue Number: close #9980 
add more logs to help debug slow regions.
- No code
```release-note
None
```

kv-client(cdc): add more logs to help debug slow regions

---

Makefile

- Unit test
```release-note
None
```

Makefile: bump version to v7.6.0-master

---

cdc/redo/meta_manager.go
cdc/redo/reader/reader.go

Issue Number: ref #5039
Remove some repeat code
- Unit test
- No code
```release-note
```

redo(ticdc): remove some repeat code

---

cdc/puller/ddl_puller.go

Issue Number: close #9942
add detail information for ddl puller
- Unit test
- No code
```release-note
```

ddl(ticdc): add detail information for ddl puller

---

cdc/api/v2/model.go
cdc/api/v2/model_test.go
cdc/model/changefeed_test.go
cdc/owner/changefeed_test.go
cdc/redo/manager.go
cdc/redo/manager_test.go
cdc/redo/meta_manager_test.go
cdc/redo/writer/memory/encoding_worker.go
cdc/redo/writer/memory/file_worker.go
cdc/redo/writer/memory/main_test.go
cdc/redo/writer/memory/mem_log_writer.go
cdc/sinkv2/eventsink/cloudstorage/cloud_storage_dml_sink.go
docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/config/config_test_data.go
pkg/config/consistent.go
pkg/config/replica_config.go
pkg/filter/filter.go
pkg/redo/config.go
pkg/sink/cloudstorage/path.go
pkg/sink/cloudstorage/path_test.go
tests/integration_tests/api_v2/cases.go
tests/integration_tests/api_v2/model.go

Issue Number: close #10047
1.  change case-sensitive parameter default value to false
2. change the default value of encoding worker  count to 32
- Unit test
- No code
```release-note
`None`.
```

filter(ticdc): change case-sensitive parameter default value to false

---

cdc/api/v2/model.go
cdc/api/v2/model_test.go
cdc/owner/changefeed_test.go
cdc/processor/processor_test.go
cdc/redo/manager.go
cdc/redo/manager_test.go
cdc/redo/meta_manager_test.go
cdc/redo/writer/memory/encoding_worker.go
cdc/redo/writer/memory/file_worker.go
cdc/redo/writer/memory/main_test.go
cdc/redo/writer/memory/mem_log_writer.go
pkg/config/config_test_data.go
pkg/config/consistent.go
pkg/config/replica_config.go
pkg/redo/config.go
tests/integration_tests/api_v2/model.go

Issue Number: close #10048
- Unit test
- No code
```release-note
```

redo(ticdc): add writer related parameter

---

cdc/entry/schema_storage_test.go
cdc/model/schema_storage.go
cdc/sink/dmlsink/mq/transformer/columnselector/column_selector.go
cdc/sink/dmlsink/mq/transformer/columnselector/column_selector_test.go

Issue Number: close #10042 
- Unit test
```release-note
`None`
```

kafka(ticdc): column selector allow filter out columns if there are at least primary key or one unique key

---

cdc/scheduler/internal/v3/replication/metrics.go
cdc/scheduler/internal/v3/replication/replication_manager.go
metrics/grafana/ticdc.json

Issue Number: close #10053 
- No code
```release-note
None
```

puller(cdc): add metrics for slowest changefeed puller

---

cdc/owner/changefeed.go
cdc/processor/processor.go
cdcv2/capture/capture.go
cdcv2/owner/owner.go

Issue Number: close #10033
- Unit test
- No code
```release-note
```

owner(cdc): add owner for cdc v2

---

cdc/api/v2/model_test.go
cdc/model/changefeed_test.go
cdc/redo/writer/memory/mem_log_writer.go
pkg/config/replica_config.go
tests/integration_tests/api_v2/cases.go
tests/integration_tests/cli/run.sh

Issue Number: close #10047
- Unit test
- No code
```release-note
```

config(ticdc): change case-sensitive default value

---

pkg/sink/codec/canal/canal_entry.go
pkg/sink/codec/canal/canal_entry_test.go
pkg/sink/codec/canal/canal_json_row_event_encoder.go

Issue Number: close #10086
- Unit test
```release-note
`None`
```

codec(ticdc): canal-json decouple java type from the mysql type

---

cdc/redo/manager.go

Issue Number: close #10101
check flush interval first
- Unit test
- No code
```release-note
`None`.
```

redo(ticdc): fix redo zero flush interval panic issue

---

cdc/api/v2/changefeed.go
cdc/api/v2/changefeed_test.go

Issue Number: ref #9584 
- Unit test
```release-note
None
```

use upstream pd client in api v2

---

metrics/grafana/ticdc.json

Issue Number: close #10055
- Fix redo panels
- Add more log and metrics to storage sink, the write duration panel will take effect after #9954 is merged.
- Unit test
- No code
```release-note
```

metrics(ticdc): fix grafana configuration of ticdc

---

cdc/sink/dmlsink/cloudstorage/dml_worker.go
cdc/sink/dmlsink/mq/worker.go
cdc/sink/dmlsink/txn/mysql/mysql.go
cdc/sink/metrics/metrics.go
cdc/sink/metrics/statistics.go

Issue Number: close #10114
- Unit test
- storage sink
```release-note
```

sink(ticdc): add total write bytes counter to sink

---

cdc/processor/processor.go
cdc/redo/manager.go
cdc/redo/meta_manager.go
cdc/redo/writer/memory/encoding_worker.go
cdc/redo/writer/memory/file_worker.go
cdc/redo/writer/memory/mem_log_writer.go
cdc/sink/dmlsink/txn/mysql/mysql.go
metrics/alertmanager/ticdc.rules.yml

Issue Number: close #10113
- Unit test
- No code
```release-note
```

mereics(ticdc): add cdc_resolvedts_high_delay alert

---

cdc/kv/client.go
cdc/kv/region_state.go
cdc/kv/region_state_bench_test.go
cdc/kv/region_worker.go
cdc/kv/region_worker_test.go
cdc/scheduler/internal/v3/replication/metrics.go
cdc/scheduler/internal/v3/replication/replication_manager.go
metrics/grafana/ticdc.json
pkg/regionspan/region_range_lock.go
pkg/regionspan/region_range_lock_test.go
pkg/txnutil/lock_resolver.go

Cherry picks #9982 and #10054.
Issue Number: close #9980 
Issue Number: close #10053 
Cherry picks #9982 and #10054.
- No code
```release-note
None
```

cdc: cherry picks #9982 and #10054

---

cdc/kv/client.go
cdc/kv/region_worker.go
cdc/kv/region_worker_test.go
cdc/processor/sinkmanager/tasks.go
cdc/processor/sinkmanager/tasks_test.go
cdc/puller/frontier/frontier.go
cdc/puller/frontier/frontier_test.go
cdc/puller/puller.go

Issue Number: ref #10181 
Add some debug code for stuck ResolvedTs in puller.
- Unit test
```release-note
None
```

kv-client(cdc): debug frontier

---

cdc/owner/changefeed_test.go
cdc/owner/feed_state.go
cdc/owner/feed_state_manager.go
cdc/owner/feed_state_manager_test.go
cdc/owner/owner.go
pkg/orchestrator/reactor_state.go

Issue Number: close #10275
add an interface to decouple feed manager 
- Unit test
- No code
```release-note
`None`.
```

owner(ticdc): decouple feed state manager

---

cdc/entry/mounter.go
cdc/entry/mounter_test.go
cdc/model/schema_storage.go
pkg/sink/cloudstorage/table_definition.go
pkg/sink/codec/simple/encoder_test.go
pkg/sink/codec/simple/message.go
pkg/sink/codec/simple/message_test.go

Issue Number: ref #9898 
- Unit test
```release-note
None
```

simple (ticdc): fix table schema indexes does not contain primary key

---

cdc/puller/puller_test.go

Issue Number: close #10291
- Unit test
```release-note
`None`.
```

puller(ticdc): add ut for 10258

---

cdc/kv/client.go
cdc/puller/frontier/frontier.go
cdc/puller/frontier/frontier_test.go
cdc/puller/puller.go

ref pingcap/tiflow#10181
- Unit test
- No code
```release-note
```

puller(cdc): debug frontier (#10202) (#10269)

---

cdc/kv/client.go
cdc/kv/utils.go
cdc/kv/utils_test.go

Issue Number: ref #9739 
- Unit test
```release-note
None
```

kv-client(cdc): add more tests for special events with empty entries

---

go.mod
go.sum

`sourcegraph.com/sourcegraph/appdash` has been archived, and the original host has been removed.
Issue Number: close https://github.com/pingcap/tiflow/issues/10325
- Unit test
- No code
```release-note
None
```

*: fix package sourcegraph/appdash not found

---

cdc/entry/schema_test_helper.go
cdc/model/schema_storage.go
cdc/processor/sinkmanager/manager_test.go
cdc/sink/dmlsink/mq/transformer/columnselector/column_selector.go
cmd/kafka-consumer/main.go
pkg/sink/codec/avro/decoder.go
pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
pkg/sink/codec/common/verify_checksum.go
pkg/sink/codec/simple/decoder.go
pkg/sink/codec/simple/encoder.go
pkg/sink/codec/simple/encoder_test.go
pkg/sink/codec/simple/message.go
pkg/sink/codec/utils/test_utils.go
tests/integration_tests/kafka_simple_basic/conf/changefeed.toml
tests/integration_tests/kafka_simple_basic/run.sh

Issue Number: close #10250
- Unit test
```release-note
`None`
```

codec(ticdc): simple protocol support end-2-end checksum

---

cdc/kv/client.go
cdc/owner/changefeed.go
cdc/owner/ddl_sink.go
cdc/owner/ddl_sink_test.go
cdc/processor/processor.go
cdc/redo/writer/memory/file_worker.go
cdc/sink/dmlsink/txn/mysql/mysql.go
errors.toml
pkg/errors/cdc_errors.go

Issue Number: close #10361
- Unit test
- No code
```release-note
```

changefeed(ticdc): remove some panic log

---

cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
cdc/sink/dmlsink/cloudstorage/defragmenter.go
cdc/sink/dmlsink/cloudstorage/dml_worker.go

Issue Number: ref #10348
1.  Add some comments
2. Adjust variable names to make them more understandable.
3. Correct the incorrect usage of `defer time.Since()`
- No code
```release-note
None
```

mq (ticdc): improve readability of some code

---

cdc/kv/client.go
cdc/kv/region_state.go
cdc/kv/region_state_bench_test.go
cdc/kv/region_worker.go
cdc/kv/region_worker_test.go
cdc/scheduler/internal/v3/replication/metrics.go
cdc/scheduler/internal/v3/replication/replication_manager.go
metrics/grafana/ticdc.json
pkg/regionspan/region_range_lock.go
pkg/regionspan/region_range_lock_test.go
pkg/txnutil/lock_resolver.go

Issue Number: ref #10157
- Unit test
- No code
```release-note
```

puller(cdc): more tests and logs for frontier and kv-client

---

cdc/capture/capture.go
cdc/model/capture.go
cdc/model/capture_test.go
pkg/etcd/etcdkey.go

Issue Number: close #10375
add deploy info to capture
- Unit test
```release-note
```

capture(ticdc): add deploy info to capture

---

cdc/api/v2/changefeed.go
cdc/api/v2/changefeed_test.go
tests/integration_tests/synced_status/run.sh

Issue Number: ref https://github.com/pingcap/tiflow/issues/10289
update info message to make more clear
- Unit test
- No code
```release-note
```

cdc: update info message for ‘/api/v2/changefeeds/{changefeed_id}/synced’

---

pkg/config/OWNERS

Refs:
- https://github.com/ti-community-infra/configs/pull/1011
- Unit test
- No code
```release-note
None
```

chore(pkg/config): add OWNERS file to support auto label on pull request

---

cdc/api/v2/model.go
cdc/kv/client.go
cdc/kv/client_bench_test.go
cdc/kv/client_test.go
cdc/kv/metrics.go
cdc/kv/region_worker.go
cdc/model/changefeed_test.go
cdc/processor/pipeline/puller.go
cdc/processor/processor.go
cdc/processor/sinkmanager/manager_test.go
cdc/processor/sinkmanager/table_sink_worker_test.go
cdc/processor/sourcemanager/manager.go
cdc/processor/sourcemanager/puller/puller_wrapper.go
cdc/puller/ddl_puller.go
cdc/puller/puller.go
cdc/puller/puller_test.go
pkg/config/config_test_data.go
pkg/config/replica_config.go

Issue Number: ref #10388
- Unit test
- No code
```release-note
```

kvclient(ticdc): add worker busy monitor

---

cdc/puller/frontier/frontier.go
cdc/puller/frontier/frontier_test.go
cdc/puller/frontier/list.go
cdc/puller/puller.go

Issue Number: ref #10157 
- Unit test
- No code
```release-note
```

cp 10339 to hotfix

---

cdc/kv/client.go
cdc/kv/region_state.go
cdc/kv/region_worker.go
cdc/kv/regionlock/region_range_lock.go
cdc/kv/regionlock/region_range_lock_test.go
cdc/puller/frontier/frontier_test.go
pkg/spanz/convert.go
pkg/spanz/convert_test.go

- Unit test
- No code
```release-note
```

puller(cdc): more tests and logs for frontier and kv-client (#10333)

---

pkg/sink/codec/simple/message.go
pkg/sink/codec/simple/message.json
pkg/sink/codec/simple/message_test.go

Issue Number: close #10455 
* Remove the `ID` from the `columnSchema`, since it's useless.
* Adjust avro schema, make it follow the official convention.
- Unit test
```release-note
`None`
```

codec(ticdc): simple protocol avro schema adjust to follow official convention.

---

Makefile

Issue Number: close https://github.com/pingcap/tiflow/issues/10448
- Unit test
```release-note
None
```

makefile: remove codecov upload in makefile

---

cdc/processor/sourcemanager/manager.go

We will enable `multiplexing` when it is `true`, not `false`. The meaning of the previous comment content was reversed.
Issue Number: close #10469
- No code
```release-note
None
```

fix the comment of SourceManager.multiplexing

---

pkg/sink/codec/simple/avro.go
pkg/sink/codec/simple/encoder_test.go
pkg/sink/codec/simple/message.go
pkg/sink/codec/simple/message.json

Issue Number: close #10480 
- Unit test
```release-note
`None`
```

codec(ticdc): add unit test to cover integer value checksum calculation.

---

cdc/puller/frontier/frontier.go
cdc/puller/frontier/frontier_test.go

Issue Number: ref #10181
This is cherry-pick from #10488, to fix the resolved ts stuck problem
- Unit test
```release-note
`None`
```

puller(ticdc): fix resolvedTs get stuck when region split and merge

---

cdc/processor/memquota/mem_quota.go

The panic message should be "MemQuota.record".
Issue Number: close #10478
- No code
```release-note
None
```

Fix the panic message of MemQuota.Record

---

tests/integration_tests/_utils/tiflash-users.toml

Issue Number: ref #10457 
- No code
```release-note
None
```

*: fix tiflash ci failure

---

go.mod
go.sum

Issue Number: close #10534
upgrade pd client to fix the panic issue
- Unit test
- No code
```release-note
`None`.
```

puller(ticdc): upgrade pd client to fix panic issue

---

deployments/engine/docker/Dockerfile

- use global go mod server is slow, we need speed up fetching go mod
- add goproxy arg for dockerfile, easier to build with internal goproxy server
- Unit test
- No code
```release-note
```

feat: add goproxy env for dockerfile

---

scripts/download-integration-test-binaries.sh

Issue Number: close #10531 
Correct PD binary query for tests.
- No code
```release-note
None
```

tests: correct pd binary for tests

---

cdc/redo/manager_test.go
pkg/config/consistent.go

Issue Number: close #10072
- Unit test
```release-note
None
```

redo (ticdc): add comments for redo log config and make TestLogManagerInOwner more stable

---

pkg/sqlmodel/multirow.go
pkg/sqlmodel/multirow_test.go
pkg/sqlmodel/row_change_test.go

Issue Number: ref #10386 
revert some changes in `pkg/sqlmodel` introduced by https://github.com/pingcap/tiflow/pull/10483 which cause dm integration test failure.
- Unit test
- No code
```release-note
None
```

*: fix dm integration test failure

---

pkg/sink/codec/simple/encoder_test.go

Issue Number: ref #10634 
* add partition table related DDL event unit test
- Unit test
```release-note
`None`
```

codec(ticdc): add partition related ddl event unit test to the simple protocol

---

go.mod
go.sum

Issue Number: close #10647
support building CDC using golang version 1.22
- Unit test
- No code
```release-note
`None`.
```

compile(*):  support go 1.22

---

deployments/ticdc/docker/pulsar-integration-test.Dockerfile

Issue Number: close #10639 
Issue Number: ref #10653 
add a docker file to build a docker image, with this image we can run the integration test and run pulsar cluster in one container.  so it's possible to customize the pulsar cluster authentication, like mtls, oauth2.0 in integration tests.
- Unit test
- No code
```release-note
`None`.
```

test(ticdc): add pulsar integration test docker file

---

pkg/sink/codec/canal/canal_json_decoder.go
pkg/sink/codec/common/helper.go
pkg/sink/codec/common/verify_checksum.go
pkg/sink/codec/simple/avro.go
pkg/sink/codec/simple/decoder.go
pkg/sink/codec/simple/marshaller.go
pkg/sink/codec/simple/message.go
pkg/sink/codec/simple/message_test.go

Issue Number: close #10661
* For the enum and set type, encode the index and mask integer into the dml message
- Unit test
```release-note
`None`.
```

codec(ticdc): simple protocol encode index for the enum and set type

---

engine/executor/server.go
engine/framework/registry/registry.go
engine/test/integration_tests/dm_full_mode/run.sh
pkg/errorutil/util.go
pkg/errorutil/util_test.go

Issue Number: close #10701
- No code
```release-note
```

engine: retry on create worker err

---

go.mod
go.sum
pkg/filter/sql_event_filter.go
pkg/filter/sql_event_filter_test.go

Issue Number: ref #10511 
- Unit test
```release-note
None
```

filter (ticdc): add unit test case to cover all event type for event filter

---

pkg/sink/codec/avro/avro.go
pkg/sink/codec/avro/avro_test.go
pkg/sink/codec/avro/decoder.go

Issue Number: ref #8869 
* encode and decode DDL event 
- Unit test
```release-note
`None`
```

codec(ticdc): avro encode DDL event 

---

cdc/entry/schema_storage.go

Issue Number: close #10769
use atomic to read and write reslovedTs in MockSchemaStorage
- Unit test
```release-note
None
```

Make UT TestGenerateTableSinkTaskWithBarrierTs more stable

---

.github/workflows/check_and_build.yaml
Makefile
cdc/scheduler/internal/v3/replication/replication_manager.go
dm/tests/run_group.sh
engine/test/integration_tests/run_group.sh
tests/integration_tests/run_group.sh

Issue Number: close #10773
make the test script compatible with older versions of bash
- Unit test
```release-note
`None`.
```

*(ticdc): make the test script compatible with older versions of bash

---

pkg/version/check.go
pkg/version/check_test.go

Issue Number: close #10807
- Unit test
- No code
```release-note
```

pkg/version(ticdc): bump max version

---

engine/pkg/meta/internal/sqlkv/sql_impl.go
engine/pkg/meta/internal/sqlkv/sql_impl_test.go
engine/test/integration_tests/dm_lightning_checkpoint/run.sh

Issue Number: close #10833
- Unit test
```release-note
```

engine: fix wrong SQL concat with LIKE ?%

---

cdc/capture/capture.go
cdc/scheduler/internal/v3/agent/agent.go
cdc/scheduler/internal/v3/coordinator.go
cdc/scheduler/internal/v3/member/capture_manager.go
cdc/scheduler/internal/v3/member/capture_manager_test.go
cdc/scheduler/internal/v3/replication/replication_manager.go
cdc/scheduler/internal/v3/scheduler/scheduler_balance.go
cdc/scheduler/internal/v3/scheduler/scheduler_balance_test.go
cdc/scheduler/internal/v3/scheduler/scheduler_basic.go
cdc/scheduler/internal/v3/scheduler/scheduler_manager.go
pkg/orchestrator/reactor_state.go

Issue Number: ref #10342
In hundreds of changefeed scenarios, the added log information is helpful.
- Unit test
- No code
```release-note
```

*(ticdc): always print changefeed id in scheduler and etcd worker

---

pkg/sink/codec/simple/encoder.go
pkg/sink/codec/simple/message.go

Issue Number: close #10837 
* ignore the column if the value cannot be found from the encoded message.
- Unit test
```release-note
`None`
```

codec(ticdc): simple protocol decoder ignore generated column if the value cannot be found

---

pkg/version/check.go
pkg/version/check_test.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/10807
- Unit test
- No code
```release-note
```

pkg/version(ticdc): bump max version for release 7.1

---

Makefile

Issue Number:  ref https://github.com/pingcap/tiflow/issues/7488
- Unit test
```release-note
None
```

Makefile: bump version to v8.1.0-master

---

pkg/causality/conflict_detector.go
pkg/causality/internal/node.go
pkg/causality/internal/node_test.go
pkg/causality/internal/slots_test.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/10341
1. revert pr 10780 since we need more tests to enable this feature in release-6.5
- Unit test
- No code
```release-note
`None`.
```

*(ticdc): Revert pr 10780 for release-6.5

---

cdc/owner/changefeed_test.go
cdc/owner/feed_state_manager_test.go
cdc/processor/processor_test.go
cdc/puller/ddl_puller_test.go
cdc/vars/vars.go

Issue Number: close #10884
ChangefeedVars is only used in ut test cases, remove it to simplify codebase
- No code
```release-note
`None`.
```

test(ticdc): remove ChangefeedVars

---

cdc/kv/region_state.go
cdc/kv/region_state_bench_test.go
cdc/kv/regionlock/region.go
cdc/kv/shared_client.go
cdc/kv/shared_client_test.go
cdc/kv/shared_region_worker.go
cdc/kv/shared_region_worker_test.go
cdc/kv/shared_stream.go
cdc/processor/sourcemanager/manager.go
cdc/processor/sourcemanager/sorter/engine.go
cdc/puller/ddl_puller.go
cdc/puller/multiplexing_puller.go
cdc/puller/multiplexing_puller_test.go

Issue Number: ref #10879
1. Renaming and Adjusting Data Structures: The singleRegionInfo structure has been renamed to regionInfo, and some of its fields have been adjusted. For example, requestedTable has been replaced with subscribedTable, which helps to more accurately reflect the purpose and content of the structure.
2. Function Signature and Logic Updates: Multiple functions have had their signatures modified to use the new regionInfo structure instead of the old singleRegionInfo. The internal logic of the functions has also been updated to accommodate the new data structures and naming.
3. Code Refactoring and Optimization: Redundant goroutines have been removed, and the code logic of kvClient has been simplified to make the code more clear and efficient.
- No code
```release-note …
```

kv, puller (ticdc):  eliminating unnecessary goroutines, streamlining the kvClient's operation, and reducing code complexity.

---

cdc/entry/schema_test_helper.go
pkg/sink/codec/builder/codec_test.go
pkg/sink/codec/craft/craft_decoder.go
pkg/sink/codec/craft/craft_encoder_test.go
pkg/sink/codec/craft/message_encoder.go
pkg/sink/codec/internal/batch_tester.go
pkg/sink/codec/internal/column.go
pkg/sink/codec/open/open_protocol_encoder_test.go
pkg/sink/codec/open/open_protocol_message.go
pkg/sink/codec/open/open_protocol_message_test.go

Issue Number: close #10913
- Unit test
```release-note
`None`
```

codec(ticdc): open-protocol unit test embrace schema test helper

---

cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
cdc/sink/dmlsink/txn/mysql/mysql.go
cdc/syncpointstore/mysql_syncpoint_store.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/10862
Add more error query information to the returned error to facilitate users to know the cause of the failure.
- Unit test
- 
```release-note
`None`.
```

log(ticdc): Add more error query information to the returned error to facilitate users to know the cause of the failure

---

dm/tests/_utils/run_tidb_server

Issue Number: close #10975
```release-note
```

test(dm): set tidb_enable_dist_task = 0

---

dm/pkg/schema/tracker.go
dm/pkg/schema/tracker_test.go

Issue Number: ref #5334
- Unit test
```release-note
```

schematracker(dm): ensure no MockStore in future

---

Makefile

- Unit test
```release-note
None
```

Makefile: bump version to v8.2.0-master

---

cdc/sink/dmlsink/mq/mq_dml_sink.go
pkg/sink/codec/bootstraper.go

Issue Number: close #11032 
```release-note
None
```

simple (ticdc): fix bootstrap event is not sent

---

cdc/entry/schema_storage_test.go
cdc/model/schema_storage.go

Issue Number: close #11063
* fetch the primary key column information by using tidb table info provided method.
* add more unit test case to cover non integer primary key.
- Unit test
```release-note
`None`
```

schema(ticdc): query the primary key column names in an easier way

---

dm/checker/check_test.go
dm/checker/checker.go
dm/checker/cmd.go

Issue Number: close #10850
- Unit test
```release-note
```

checker(dm): make precheck warn/error limit public

---

dm/pkg/utils/common.go
go.mod
go.sum

dep: update tidb-tools

---

cdc/kv/shared_client.go
cdc/kv/shared_client_test.go
pkg/txnutil/lock_resolver.go

Issue Number: close #11074 
- No code
```release-note
None
```

kv (ticdc): reduce some verbose log

---

cdc/model/schema_storage.go
pkg/sink/codec/simple/avro.go
pkg/sink/codec/simple/decoder.go
pkg/sink/codec/simple/encoder.go
pkg/sink/codec/simple/encoder_test.go
pkg/sink/codec/simple/marshaller.go
pkg/sink/codec/simple/message.go
tests/integration_tests/kafka_simple_claim_check/conf/changefeed.toml
tests/integration_tests/kafka_simple_claim_check/run.sh
tests/integration_tests/kafka_simple_claim_check_avro/conf/changefeed.toml
tests/integration_tests/kafka_simple_claim_check_avro/run.sh
tests/integration_tests/kafka_simple_handle_key_only/conf/changefeed.toml
tests/integration_tests/kafka_simple_handle_key_only/run.sh
tests/integration_tests/kafka_simple_handle_key_only_avro/conf/changefeed.toml
tests/integration_tests/kafka_simple_handle_key_only_avro/run.sh

Issue Number: close #11057 
* enable checksum for simple protocol related integration tests.
* simplify the unit test, improve the coverage from around 85% to 90%
```release-note
`None`
```

tests(ticdc): simple protocol claim check integration test enable checksum

---

dm/tests/openapi/run.sh
dm/worker/subtask.go

Issue Number: close #10839 
- for a task in invalid stage(create task but no start), report an error instead of panic
```release-note
```

dm: fix panic of openapi operate-schema

---

dm/checker/check_test.go
dm/checker/checker.go
dm/config/checking_item.go
dm/config/checking_item_test.go
dm/pkg/checker/binlog.go
dm/pkg/checker/lightning.go
dm/pkg/checker/lightning_test.go
dm/pkg/dumpling/utils.go

Issue Number: close https://github.com/pingcap/tiflow/issues/11115
- as title
- Unit test
- No code
```release-note
```

dm: support empty check for physical mode

---

cdc/processor/sourcemanager/sorter/pebble/db.go
pkg/cmd/server/server_test.go
pkg/config/config_test_data.go
pkg/config/db.go
pkg/config/server_config.go
pkg/spanz/hash_map.go

Issue Number: close #11078 
* trigger compaction more frequently
* use a better hash function for table IDs
- Unit test
```release-note
None
```

cdc: adjust sorter options to avoid Seek CPU usage exploding

---

cdc/puller/frontier/frontier.go
cdc/puller/frontier/frontier_test.go
scripts/download-integration-test-binaries.sh
tests/integration_tests/sequence/run.sh

…(#10488) (#10493)
ref pingcap/tiflow#10157
- Unit test
- No code
```release-note
```

puller(ticdc):  fix resolvedTs get stuck when region split and merge (hotfix)

---

go.mod

Issue Number: close #11199 
Remove useless lines from `go.mod`.
- No code
```release-note
None
```

*: tidy go mod

---

tests/integration_tests/ddl_reentrant/run.sh

Issue Number: ref #10859
- Unit test
- No code
```release-note
```

ticdc: Add test for ddl `exchange partition ... without validation`

---

pkg/sink/codec/csv/csv_decoder_test.go
pkg/sink/codec/csv/csv_encoder_test.go
pkg/sink/codec/maxwell/maxwell_encoder_test.go
pkg/sink/codec/maxwell/maxwell_message_test.go
pkg/sink/codec/utils/field_types.go

Issue Number: close #11225
* csv unit test use schema test helper to generate dml event.
* maxwell unit test use schema test helper to generate dml event.
- Unit test
```release-note
`None`
```

codec(ticdc): csv and maxwell unit test use schema test helper to reduce code complexity

---

metrics/grafana/ticdc.json

Issue Number: close #11347
add kafka compression ratio description for grafana
- Unit test
- No code
```release-note
`None`.
```

metrics(ticdc):  add kafka compression ratio description for grafana

---

cmd/kafka-consumer/consumer.go
cmd/kafka-consumer/writer.go

Issue Number: close #11358 
- Unit test
```release-note
`None`
```

consumer(ticdc): do not panic the consumer if visit the kafka broker meet error

---

Makefile
pkg/version/version.go

Issue Number: close #11450 
```release-note
None
```

pkg/version(*): Improve Go version reporting

---

cmd/kafka-consumer/main.go
cmd/storage-consumer/main.go
pkg/cmd/redo/apply.go

Issue Number: close #11428
Only allow local servers to access it to avoid attackers.
- Unit test
```release-note
`None`.
```

ticdc: fix cleartext Transmission

---

metrics/grafana/ticdc.json

Issue Number: close https://github.com/pingcap/tiflow/issues/10796
fix metrics calculation for Ownership history
- Unit test
- No code
```release-note
`None`.
```

metrics(ticdc): fix metrics calculation for Ownership history

---

cdc/owner/ddl_manager.go
cdc/sink/ddlsink/mysql/async_ddl.go
cdc/sink/ddlsink/mysql/async_ddl_test.go
cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
cdc/sink/ddlsink/mysql/mysql_ddl_sink_test.go
pkg/errors/reexport.go
tests/integration_tests/clustered_index/run.sh

Issue Number: close #10682
- [Always wait for async ddl done before executing the next normal ddl](https://github.com/pingcap/tiflow/pull/11476/files#diff-67001e77c3d88c6c47cfed312c5b1f5f36d2a404163aefb5da2939fce5051674R96)
- Note: [wait indefinitely](https://github.com/pingcap/tiflow/pull/11476/files#diff-67001e77c3d88c6c47cfed312c5b1f5f36d2a404163aefb5da2939fce5051674R111-R121) here to avoid pointless retries
- Any errors encountered will be [ignored](https://github.com/pingcap/tiflow/pull/11476/files#diff-67001e77c3d88c6c47cfed312c5b1f5f36d2a404163aefb5da2939fce5051674R127-R133) in the check, and if the add index operation in downstream is not complete at this point, TiCDC will fall back to the current master's behavior.
- Unit test
- Manual test 
```release-note
`None`.
```

sink, ddl(ticdc): support add index ddl in downstream

---

pkg/config/sink.go

Issue Number: close #11461
This pull request refactors the `applyParameterBySinkURI` method in the `SinkConfig` struct to simplify the error handling logic, improve code clarity, and reduce redundancy.
1. **Removed Redundant Maps and Logging:**
- The original implementation utilized two maps (`cfgInSinkURI` and `cfgInFile`) to store mismatched configuration parameters from the sink URI and configuration file. This approach, while functional, introduced unnecessary complexity and redundancy in handling errors.
- The use of `log.Panic` for mismatched configurations was replaced by constructing error messages directly, because it is completely unnecessary.
2. **Simplified Error Handling Logic:**
- In the refactored code, `strings.Builder` is used to directly construct error messages for …

sink(ticdc): refactor the error handing in SinkConfig.applyParameterBySinkURI()

---

cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
cdc/sink/metrics/metrics.go
cdc/sink/metrics/statistics.go
metrics/grafana/ticdc.json

Issue Number: close #11511
* split the `Output DDL Count & Executing Duration` into `Executed DDL Count / Minute` and `DDL Executing Duration`
* adjust log fields order, since the `query` might be very long, so put it as the last field
Executed DDL Count / Minute
```
sum(increase(ticdc_sink_ddl_exec_count{k8s_cluster="$k8s_cluster",tidb_cluster="$tidb_cluster",namespace=~"$namespace",changefeed=~"$changefeed",instance=~"$ticdc_instance"}[1m])) by (namespace,changefeed,instance)
```
DDL Executing Duration
```
histogram_quantile(0.99, sum(rate(ticdc_sink_ddl_exec_duration_bucket{k8s_cluster="$k8s_cluster",tidb_cluster="$tidb_cluster",namespace=~"$namespace",changefeed=~"$changefeed",instance=~"$ticdc_instance"}[1m])) by (le,namespace,changefeed,instance))
```
``` …
```

metrics(ticdc): fix ddl executed count metrics

---

tests/integration_tests/bdr_mode/run.sh

Issue Number: close #11517
This integration test is disabled previously, since the tikv may panic, enable this.
- Unit test
```release-note
`None`
```

tests(ticdc): enable brd mode test

---

dm/tests/download-integration-test-binaries.sh
scripts/download-integration-test-binaries.sh

Issue Number: close #11563 
When branch is not valid, try to use `master` branch instead.
```release-note
`None`.
```

test(ticdc,dm): modify download-integration-test-binaries script

---

cdc/scheduler/internal/v3/replication/replication_set.go

Issue Number: close #11562 
As titile
- Unit test
```release-note
`None`.
```

scheduler(ticdc): modify scheduler monitoring

---

cdc/entry/mounter.go

Issue Number: close #11525 
- Unit test
```release-note
`None`
```

mounter(ticdc): release-7.5 ignore checksum v2

---

dm/tests/download-compatibility-test-binaries.sh
dm/tests/download-integration-test-binaries.sh
scripts/download-integration-test-binaries.sh

Issue Number: close https://github.com/pingcap/tiflow/issues/11575
Related to this PR: https://github.com/PingCAP-QE/ci/pull/3111
- Unit test
```release-note
None
```

chore: support specify the branch for downloading dependencies through env variable

---

cdc/model/sink.go

Issue Number: close #11537 
As title.
- Unit test
```release-note
None
```

sink(ticdc): reduce log print when using CDC sync data to Kafka with nil values in column 

---

cdc/sink/ddlsink/mysql/mysql_ddl_sink.go

Issue Number: ref #11530 
As title.
- Unit test
```release-note
`None`.
```

sink(ticdc): update defaultSupportVectorVersion

---

cdc/kv/metrics.go
cdc/redo/common/metric.go
cdc/redo/manager.go
cdc/redo/meta_manager.go
cdc/redo/writer/file/file.go
cdc/redo/writer/file/file_test.go
cdc/redo/writer/memory/file_worker.go
cdc/sink/dmlsink/cloudstorage/dml_worker.go
cdc/sink/metrics/cloudstorage/metrics.go
metrics/grafana/TiCDC-Monitor-Summary.json
metrics/grafana/ticdc.json

Issue Number: close #11664
1. Update worker_busy_ratio calculation. 
2. Split redo metrics by log type.
- Unit test
```release-note
None
```

metric(cdc): fix uncorrect metric WorkerBusyRatio

---

tests/integration_tests/foreign_key/conf/cf.toml
tests/integration_tests/foreign_key/conf/diff_config.toml
tests/integration_tests/foreign_key/data/prepare.sql
tests/integration_tests/foreign_key/run.sh

Issue Number: close #11702
Modify the foreign key test to add a new case about log filter.
- Unit test
- No code
```release-note
None
```

tests: add foreign key tests with log filter

---

dm/syncer/causality.go

- Unit test
```release-note
```

syncer(dm): add more comment about causality(or dependency detect)

---

cdc/owner/ddl_manager.go
pkg/version/check.go
tests/integration_tests/bank/case.go
tests/integration_tests/bank/run.sh

Issue Number: close #11806
```release-note
```

tests(ticdc): fix bank test

---

tests/integration_tests/ddl_attributes/run.sh

Issue Number: ref https://github.com/pingcap/tidb/pull/57758
When TiDB updates ttl_job_interval, we have to follow up.
```release-note
`None`
```

test(ticdc): update the default value of ttl_job_interval

---

cdc/entry/schema_storage.go
cdc/puller/ddl_puller.go
cdc/puller/ddl_util.go
pkg/ddl/util.go
pkg/ddl/util_test.go
tests/integration_tests/batch_add_table/run.sh

Issue Number: close #11774
**Description**
I implemented a new function, SplitQueries, which utilizes TiDB’s parser to parse and split SQL statements correctly. This ensures robust handling of complex SQL strings, including those with special characters in column names.
**Key Changes**
1. Introduced SplitQueries function
* This function uses TiDB’s parser to split a concatenated SQL string into individual queries.
* The parser generates an Abstract Syntax Tree (AST) for the SQL string, and each AST node is restored into a complete query with a semicolon appended.
2. Replaced Existing Query Splitting Logic
* Updated all parts of the codebase where query splitting occurs to use the new SplitQueries function.
* This ensures consistency and correctness across the project.
**Notes**
This …

ddl(ticdc): fix query splitting issue by using TiDB parser

---

cmd/kafka-consumer/consumer.go
cmd/kafka-consumer/event_group.go

Issue Number: close #11829 
remove sort event by the commit-ts
- Unit test
```release-note
`None`
```

consumer(ticdc): remove order events

---

dm/pkg/storage/utils.go
go.mod

Issue Number: close https://github.com/pingcap/tiflow/issues/11912
delete file in azure ignore blob file not exist error
create task with azure dir
1. target dir is empty dir
backup success
2. target dir is not empty dir
backup success
3. target dir contain sub dir
backup success
4. run dump and load task success
```log
dmctl test cmd: "query-status test-load" with max 10 retries
got=1 expected=1
dmctl test cmd: "query-status test-load" with max 100 retries
got=0 expected=1
command: query-status test-load "stage": "Finished" count: 0 != expected: 1, failed the 0-th time, will retry again
got=1 expected=1
check diff successfully
```
```release-note
Please refer to [Release Notes Language Style …
```

dm: delete file ignore blob file not exist

---

.github/workflows/dm_mariadb_master_down_and_up.yaml

Issue Number: close #4287 
- download docker-compose in github action
```release-note
None
```

dm: download docker-compose in github action

---

tests/integration_tests/generate_column/conf/changefeed.toml
tests/integration_tests/generate_column/data/prepare.sql
tests/integration_tests/generate_column/data/stored.sql
tests/integration_tests/generate_column/data/virtual.sql
tests/integration_tests/generate_column/run.sh

Issue Number: ref #11704
enable storage sink and pulsar sink.
```release-note
`None`
```

test(ticdc): modify generated column test

---

dm/dumpling/dumpling.go
dm/dumpling/dumpling_test.go
dm/pkg/dumpling/utils.go
dm/tests/openapi/client/openapi_task_check
dm/tests/openapi/run.sh

Issue Number: close https://github.com/pingcap/tiflow/issues/11984
If not table migrate rule set, add system tables filter both in uppercase and lowercase for dump task
- Unit test
```release-note
```

dm: add system table filter default for dump task

---

pkg/sink/codec/avro/avro.go
scripts/download-integration-test-binaries.sh

- Unit test
- No code
```release-note
Fix incorrect encoding default value in Avro protocol.
```

sink(ticdc): fix incorrect encoding default value in Avro protocol

---

pkg/sink/codec/avro/avro.go

Issue Number: ref https://github.com/pingcap/tiflow/pull/12018
- Unit test
- No code
```release-note
sink(ticdc): fix incorrect encoding default value in Avro protocol.
```

sink(ticdc): fix incorrect encoding default value in Avro protocol 

---

pkg/sink/codec/avro/avro_test.go
pkg/sink/codec/common/helper.go
tests/integration_tests/debezium/docker-compose.yml

Issue Number: close #11727
https://github.com/PingCAP-QE/ci/pull/3208 cause this issue, and we have to revert https://github.com/pingcap/tiflow/pull/11649.
After this pr,an invalid character is replaced by a replacementChar.
- Unit test
```release-note
```

sink(ticdc): fix incorrect sanitize

---

tests/integration_tests/multi_source/main.go

Issue Number: ref #11879
Set an upper bound to prevent the insertion of duplicate entries.
```release-note
None
```

test(ticdc): fix multi_source test

---

Makefile

Issue Number: ref #11672
- Unit test
- No code
```release-note
None
```

build: add sync-diff-inspector target into `build` make task

---

pkg/config/replica_config.go

Issue Number: close #12088 
- Unit test
- No code
```release-note
```

scheduler: support mysql sink split table

---

cmd/kafka-consumer/writer.go
pkg/sink/codec/debezium/codec.go

Issue Number: close #12107 
support ActionCreateTables ddl.
- Unit test
```release-note
`None`.
```

codec(ticdc): fix unsupport DDL type about debezium protocol

---

cmd/kafka-consumer/event_group.go
cmd/kafka-consumer/writer.go

Issue Number: close #12111
- Unit test
```release-note
`None`
```

consumer(ticdc): adjust consumer log level

---

.github/workflows/check_and_build.yaml
.github/workflows/dataflow_engine_chaos.yaml
.github/workflows/dm_binlog_999999.yaml
.github/workflows/dm_chaos.yaml
.github/workflows/dm_mariadb_master_down_and_up.yaml
.github/workflows/dm_upstream_switch.yaml

Issue Number: close #12119 
- No code
```release-note
None
```

CI: Upgrade to actions/cache@v4

---

metrics/grafana/tiflow.json

Issue Number: close https://github.com/pingcap/tiflow/issues/12152
- Remove undefined panel in useless `Cluster-Tiflow` dashboard.
- Unit test
- No code
```release-note
None
```

remove undefined panel

---

tests/integration_tests/tidb_mysql_test/r/date_formats.result
tests/integration_tests/tidb_mysql_test/t/date_formats.test

Issue Number: ref #11879
The query execution plan result is not necessary for TiCDC and could be removed without impact.
- Unit test
```release-note
`None`.
```

test(ticdc): remove incorrect query execution plan in tidb_cdc_test

---

pkg/filter/expr_filter.go

Issue Number: close #12230
- Unit test
- No code
```release-note
```

eventfilter: simplify the way to eval virtual column

---

cdc/model/mounter.go
cdc/model/mounter_test.go
cdc/model/schema_storage.go
cdc/model/schema_storage_test.go
pkg/filter/expr_filter.go
pkg/filter/expr_filter_test.go
tests/integration_tests/event_filter/conf/cf.toml
tests/integration_tests/event_filter/data/test.sql
tests/integration_tests/event_filter/run.sh
tests/integration_tests/syncpoint/run.sh

…ual columns (#12211) (#12220)
Issue Number: close pingcap/tiflow#12206
This is a cherry pick of https://github.com/pingcap/tiflow/pull/12211
- Unit test
- No code
```release-note
```

event filter: fix panic when evaluate expressions for table with virtual columns

---

go.mod
go.sum

Issue Number: ref #12249
- Unit test
```release-note
`None`.
```

*: bump jwt and jose2go
