cdc/processor/pipeline/table.go
cdc/processor/pipeline/table_actor.go
cdc/processor/processor_test.go
cdc/scheduler/internal/tp/agent.go
cdc/scheduler/internal/tp/agent_bench_test.go
cdc/scheduler/internal/tp/agent_test.go
cdc/scheduler/internal/tp/capture_manager.go
cdc/scheduler/internal/tp/replication_manager.go
cdc/scheduler/internal/tp/replication_set.go
cdc/scheduler/internal/tp/scheduler_rebalance.go
cdc/scheduler/internal/tp/table.go
cdc/scheduler/internal/tp/table_test.go
pkg/config/server_config.go

Issue Number: ref #4757
let the `agent` handle different table state, this makes the message report table's state more accurate.
- Unit test
```release-note
`None`.
```

fb/latency(cdc): agent to be table state awared, to handle different p2p messages.

---

cdc/api/util.go
cdc/owner/owner.go
cdc/owner/owner_test.go
pkg/api/v1/changefeed.go
pkg/cmd/cli/cli_changefeed_list.go
pkg/cmd/cli/cli_changefeed_query.go
pkg/cmd/cli/cli_changefeed_resume.go
tests/integration_tests/_utils/check_etcd_meta_not_exist
tests/integration_tests/changefeed_error/run.sh
tests/integration_tests/multi_capture/run.sh
tests/integration_tests/processor_resolved_ts_fallback/run.sh
tests/integration_tests/sorter/run.sh

- Unit test
- No code
```release-note
```

fix integration test failed

---

cdc/redo/writer/writer_test.go

Issue Number: close #5736 
Wait for gc to be invoked before closing `Writer`
- Unit test
```release-note
`None`.
```

tests(ticdc): fix unstable TestWriterRedoGC

---

cdc/api/interfaces.go
cdc/api/middleware/middleware.go
cdc/api/util.go
cdc/api/v1/api.go

Issue Number: close #5888
called abort in the middleware
- Manual test
- send requests to none-ower CDC server and check the console
No
No
```release-note
`None`
```

api(ticdc): fix panic after middleware refactor

---

cdc/api/v1/api.go
cdc/api/v2/api.go
cdc/api/v2/model.go
cdc/api/v2/tso.go
cdc/api/v2/tso_test.go
cdc/api/v2/unsafe.go
cdc/api/v2/validator.go
cdc/model/changefeed.go
cdc/model/http_model.go
docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/api/v2/tso.go
pkg/api/v2/unsafe.go
pkg/cmd/cli/cli_changefeed_create.go
pkg/cmd/cli/cli_changefeed_resume.go
pkg/cmd/cli/cli_changefeed_statistics.go
pkg/cmd/cli/cli_unsafe_delete_service_gc_safepoint.go
pkg/cmd/cli/cli_unsafe_resolve_lock.go
tests/integration_tests/http_api/util/test_case.py
tests/integration_tests/http_api_tls/util/test_case.py

- Unit test
- No code
```release-note
```

cli(ticdc): cli support multi stream

---

cdc/owner/owner.go

Issue Number: ref #4774
- This PR is the combined cherry-pick of both #4775 and #4998
Tests 
- Unit test
- Manual test
```release-note
Fix TiCDC incorrectly display stale metrics data on dashboard.
```

owner(cdc): backport stale metrics fix to 5.3

---

cdc/api/validator/validator.go
cdc/model/changefeed.go
cdc/model/changefeed_test.go
cdc/owner/ddl_sink.go
cdc/owner/feed_state_manager_test.go
cdc/processor/processor.go
cdc/processor/processor_test.go
cdc/sink/metrics/statistics.go
cdc/sink/mq/mq.go
cdc/sink/mq/mq_test.go
cdc/sink/mysql/mysql.go
cdc/sink/mysql/mysql_params.go
cdc/sink/mysql/mysql_params_test.go
cdc/sink/mysql/mysql_test.go
cdc/sink/sink.go
cdc/sink/sink_test.go
cmd/kafka-consumer/main.go
pkg/applier/redo.go
pkg/cmd/cli/cli_changefeed_create.go
pkg/cmd/cli/cli_changefeed_update.go
pkg/orchestrator/reactor_state_test.go
scripts/avro-local-test.sh
scripts/canal/canal-local-test.sh

Issue Number: ref https://github.com/pingcap/tiflow/issues/5849
remove useless opts for MQ sink.
This PR simply removes the dead code.
Before.
You pass opts it won't do anything, but it won't report an error.
After the change.
You pass opts again cli will report an error.
Upgrade
The original parameters won't work after the upgrade, and it won't panic.
- Unit test
No
No, I didn't find any docs about this arg.
```release-note
None
```

sink/mq,sink/mysql(ticdc): remove useless opts for MQ and MySQL sink

---

cdc/scheduler/internal/tp/capture_manager.go
cdc/scheduler/internal/tp/coordinator.go
cdc/scheduler/internal/tp/replication_manager.go
cdc/scheduler/internal/tp/replication_manager_test.go
cdc/scheduler/internal/tp/replication_set.go
cdc/scheduler/internal/tp/replication_set_test.go
cdc/scheduler/internal/tp/scheduler_basic.go
tests/integration_tests/move_table/main.go

* tp: clean up metrics and add logs
* tp: cleanup running task when a table has shutdown
* tests: skip check move table results
- Unit test
Run tests/integration_tests/move_table/main.go to test move tables.
```release-note
None
```

tp: cleanup metrics and fix a bug that ignore schedule task mistakenly

---

engine/pkg/externalresource/manager/gc_runner.go

Issue Number: close #5832, also close #5699
In #5832, `r.client.DeleteResource` failed because of `database table is locked: resource_meta"`, which is acceptable because database operation could fail.
In the next retry of `*DefaultGCRunner.gcOnce`, `handler(ctx, res)` returns resource not found error because the local file resource had been removed, but resource meta in metastore is not removed.
In this PR, when removing resource rpc returns resource not found, ignore this error and continue to delete resource from resourcemeta
- Unit test
```release-note
None
```

resource(engine): fix skipping resource meta remove in gc retry

---

cdc/scheduler/internal/tp/replication_set.go
cdc/scheduler/internal/tp/replication_set_test.go

Fix an issue that interrupts replication.
- Unit test
```release-note
None
```

tp: fix same primary and source error on move table

---

cdc/processor/processor.go

Issue Number: close #5951 
- No code
```release-note
`None`.
```

processor(cdc): simplify get table name.

---

cdc/scheduler/internal/base/agent.go
cdc/scheduler/internal/base/agent_mock.go
cdc/scheduler/internal/base/processor_agent.go
cdc/scheduler/internal/base/protocol/protocol.go

Cleanup unused changes to schedulerv2.
- Unit test
```release-note
None
```

tp: cleanup changes to schedulerv2

---

engine/executor/worker/ctx.go
engine/executor/worker/ctx_test.go
engine/executor/worker/internal/info.go
engine/executor/worker/internal/runnables.go
engine/executor/worker/task_committer.go
engine/executor/worker/task_committer_test.go
engine/executor/worker/task_runner.go
engine/executor/worker/task_runner_test.go
engine/executor/worker/test_util.go
engine/framework/internal/worker/master_client.go
engine/framework/internal/worker/master_client_test.go
engine/framework/worker.go
engine/framework/worker_test.go
engine/pkg/clock/clock.go

Issue Number: close #5969
TODO
- When worker receives a stale heartbeat pong message from master, don't reset `lastMasterAckedPingTime`
- Use `clock.MonotonicTime` as submit time in task context instead of `time.Time`
- Unit test
```release-note
None
```

framework(engine): fix stale pong heartbeat causes ack time fallback

---

Makefile
pkg/version/check.go

Issue Number: close https://github.com/pingcap/tiflow/issues/6039
change version from `9999.0.0` to `6.2.0-alpha`
- No need
No
No
```release-note
Fix the wrong maximum compatible version number
```

version(ticdc): fix check version to 6.2.0-alpha

---

engine/client/base_executor_client.go
engine/client/client_test.go

Issue Number: close #6006 
- Use non-blocking mode in `grpc.Dial`.
- Unit test
No.
No.
```release-note
None.
```

clients(engine): use non-blocking dial for executors

---

cdc/scheduler/internal/tp/scheduler_move_table.go
cdc/scheduler/internal/tp/scheduler_move_table_test.go
cdc/scheduler/internal/tp/scheduler_rebalance.go
cdc/scheduler/internal/tp/scheduler_rebalance_test.go

Issue Number: close #6098
`MoveTable` and `Rebalance` may be triggered when the capture is draining.
After the capture drained, it becomes `stopping`, then `MoveTable` and `Rebalance` request should be ignored, otherwise the drained capture will always reject add the table.
- Unit test
```release-note
`None`.
```

schedulerV3 (cdc): ignore manual request if capture is stopping

---

dm/tests/full_mode/run.sh

align with https://github.com/pingcap/tidb/pull/35136
```release-note
`None`.
```

test(dm): align TiDB SHOW statement output

---

.github/workflows/dataflow_engine_chaos.yaml

Issue Number: ref #5640
Support to trigger dataflow engine chaos test in workflow.
The same as dm chaos test workflow, usage example:
```release-note
None
```

chaos(engine): add pr trigger in engine chaos test

---

engine/chaos/manifests/time-shift-dataflow.yaml

Issue Number: ref #5640
and  #6143
`v1alpha1.TimeChaosSpec.Value: ReadString: expects " or n, but found 5`
- Value should be a string type.
- Use random-max-percent to add some randomness.
- Unit test
```release-note
None
```

chaos(engine): fix time shift case, use correct string type

---

pkg/etcd/etcd.go
pkg/etcd/etcd_test.go
pkg/migrate/migrate.go

Issue Number: ref #5301
fix backup key issue
change from 
`/tidb/cdc/__backup__/0//tidb/cdc/changefeed/info/6974d70f-d798-4046-8f06-f969d4c766f1`
to 
`/tidb/cdc/__backup__/0/tidb/cdc/changefeed/info/6974d70f-d798-4046-8f06-f969d4c766f1`
- Unit test
- No code
```release-note
`None`.
```

migration(ticdc): fix backup key issue

---

cdc/scheduler/internal/v3/scheduler_drain_capture.go
cdc/scheduler/internal/v3/scheduler_drain_capture_test.go

Issue Number: close #6230 
Fix panic when drain an imbalanced cluster
- Unit test
No
No
```release-note
None
```

scheduler(ticdc): fix panic when drain an imbalanced cluster

---

cdc/redo/reader/file.go
cdc/redo/reader/reader.go
cdc/redo/writer/file.go
cdc/redo/writer/file_test.go
cdc/sorter/unified/file_backend_test.go
cmd/cdc/hack/dbus_linux.go
dm/pkg/schema/tracker.go
engine/executor/config_test.go
engine/executor/server_test.go
engine/jobmaster/dm/dm_jobmaster_test.go
engine/pkg/externalresource/broker/file_manager.go
engine/pkg/externalresource/broker/local_broker.go
engine/pkg/meta/internal/etcdkv/mock.go
engine/servermaster/server_test.go
engine/test/e2e/e2e_dm_test.go
engine/test/e2e/e2e_test.go
pkg/api/internal/rest/request.go
pkg/api/internal/rest/request_test.go
pkg/logutil/log_test.go
pkg/tcpserver/tcp_server_test.go
tests/integration_tests/move_table/main.go

Issue Number: close #6261 
replace `io/ioutil` with `io` and `os` package.
```release-note
replace `io/ioutil` with `io` and `os` package.
```

chore: io/ioutil change to package io and os

---

cdc/redo/writer/writer.go
cdc/redo/writer/writer_test.go

Issue Number: ref #6277 
After #6313 is merged, cdc instance can panic if redo meta regresses. It can really happend when a cdc instance restarts.
This PR ignored redo meta regress. 
- Unit test
```release-note
None
```

cdc: ignore redo log meta regress for restarting

---

engine/chaos/cases/config.go
engine/chaos/manifests/conf/server-master.toml
engine/chaos/manifests/metastore.yaml

Issue Number: ref #5640
- We share the same app label between framework mysql pod and business etcd pod, which leads to an unexpected service router from metastore service
```
metastore svc --> mysql
| --> etcd
```
- Just separate them
```
metastore-framework svc --> mysql
metastore-business svc --> etcd
```
- verified in https://github.com/pingcap/tiflow/runs/7442423420?check_suite_focus=true
```release-note
None
```

chaos(engine): fix metastore selector in k8s

---

dm/tests/drop_column_with_index/run.sh
dm/tests/gtid/conf/source1.yaml
dm/tests/gtid/conf/source2.yaml
dm/tests/shardddl_optimistic/run.sh

Issue Number: close #6105
- if checking the resulte of resume too quickly, we will see the old error
- in `gtid` test case we manually removed relay log, so when relay log is download, the task may not be able to find the position in checkpoint. We rely on auto-resume to handle it.
- No code
```release-note
`None`.
```

test(dm): fix some unstable test

---

tests/integration_tests/http_api/run.sh

Issue Number: ref #5474 
cherry pick 5473
- Unit test
```release-note
`None`.
```

tests(ticdc): use python3 to run http_api test to fix failed integration_test

---

dm/tests/gtid/run.sh

Issue Number: close #6105
if the task is stopped at gtid set xxx:1-3, because we will remove local relay log files and it will start to pull relay log from 1-3:6 because we manually FLUSH LOGS here, the task will fail
- No code
```release-note
`None`.
```

test(dm): wait data is replicated to fix unstable test

---

pkg/cmd/cli/cli_unsafe_reset.go
pkg/cmd/factory/factory_impl.go
pkg/cmd/factory/factory_impl_test.go

Issue Number: close #6458 
Check the PD address(es) by trying to create a PDClient before creating the EtcdClient. The address is guaranteed to represent a valid PD cluster if the PDClient was created successfully.
Previous checks assume the PD address is correct if the EtcdClient got created successfully. However, the EtcdClient can be created without error as long as there is a gRPC service, and it may not a real PD/Etcd cluster. 
- Manual test
- Start a tidb cluster and a ticdc cluster
- Operate cdc cli `cdc cli changefeed list --pd=xxx`, but use the cdc server address as the wrong pd address. 
- Check the error message. It should tell the user to check the pd address 
No
No
```release-note
`Bug fix: handle error correctly with wrong pd address but with a grpc service`
```

cli(cdc): handle error correctly with wrong pd address but with a grpc service

---

dm/tests/checkpoint_transaction/run.sh

Issue Number: close #6528
syncer will sleep 0.5 seconds for each DML job, and there'are 30 DML jobs. So we have confident to check the log every seconds to know syncer is processing inside the transaction.
- No code
```release-note
`None`.
```

test(dm): fix unstable test due to rely on sleep X seconds

---

engine/pkg/config/constants.go
engine/pkg/srvdiscovery/etcd_impl.go

Issue Number: close #6524
- Disable endpoints auto sync in etcd client.
- Add a timeout to `getSnapshot` operation in service discovery lib.
- Unit test
```release-note
None
```

srvdiscovery(engine): disable etcd auto sync, add timeout to snapshot op

---

cdc/scheduler/internal/v3/capture_manager.go
cdc/scheduler/internal/v3/capture_manager_test.go
cdc/scheduler/internal/v3/replication_manager.go
cdc/scheduler/internal/v3/replication_manager_test.go
cdc/scheduler/internal/v3/replication_set.go
cdc/scheduler/internal/v3/replication_set_test.go
cdc/scheduler/internal/v3/scheduler_balance.go
cdc/scheduler/internal/v3/scheduler_basic.go
cdc/scheduler/internal/v3/scheduler_basic_test.go

Issue Number: close #6538
Do not promote secondary when there are other captures. It prevents premature promotion after restarting commit.
- Unit test
No.
No.
```release-note
None
```

scheduler(ticdc): fix premature promotion after restarting commit

---

cdc/capture/capture_test.go
cdc/model/http_model.go
cdc/model/http_model_test.go
cdc/processor/processor.go
cdc/processor/processor_test.go
cdc/scheduler/internal/agent.go
cdc/scheduler/internal/v2/processor_agent.go
cdc/scheduler/internal/v2/processor_agent_test.go
cdc/scheduler/internal/v3/agent/agent.go
cdc/scheduler/internal/v3/agent/agent_test.go
cdc/scheduler/rexport.go

Issue Number: close #4757 
Set liveness to stopping when it is drained by DrainCapture API.
It prevents unnecessary owner switch during rolling upgrade.
- Unit test
| master branch | this PR |
| -- | -- |
| <img width="922" alt="image" src="https://user-images.githubusercontent.com/2150711/182794842-e00059be-6262-494d-9505-6f8a395e2485.png"> | <img width="919" alt="image" src="https://user-images.githubusercontent.com/2150711/182790823-e443da77-3849-45b1-9fd1-67c31cea261a.png"> |
```release-note
None
```

scheduler,processor(ticdc): update capture liveness by heartbeat

---

engine/pkg/client/errors.go
engine/pkg/client/executor_group.go
engine/pkg/client/executor_group_test.go

Issue Number: close #6621 
- Reduced the retry timeout for non-existent executors.
- Added a tombstone mechanism in `ExecutorGroup` to make such `GetExecutorClient` calls fail fast. 
- Unit test
No.
No.
```release-note
None.
```

client(engine): implement tombstones in ExecutorGroup

---

engine/framework/base_jobmaster.go
engine/jobmaster/dm/api.go
engine/jobmaster/dm/api_test.go
engine/jobmaster/dm/dm_jobmaster.go
engine/jobmaster/dm/dm_jobmaster_test.go
engine/jobmaster/dm/openapi_test.go

Issue Number: close #6615 
'JobMasterID' and 'ID' return the same id to user and we don't need the `JobMasterID` to return `JobManagerID` actually,
so remove 'JobMasterID'  method to avoid confusion
```release-note
`None`.
```

framework(engine): remove 'JobMasterID' method from 'BaseJobMaster' interface

---

engine/pkg/meta/mock/clientconn_mock.go

Issue Number: close #6665 
We don't use connection pool in sqlite, 
so set `MaxOpenConns` to 1 for sqlite connection to avoid unexpected `database table is lock` error.
```release-note
`None`.
```

test(engine): fix 'database table is lock' bug for sqlite backend test

---

dm/pkg/schema/tracker.go
dm/pkg/schema/tracker_test.go

Issue Number: close #5315
during the refactor of schema tracker, I found this issue is not hard to fix
- Unit test
```release-note
Fix a problem that DM will report `Specified key was too long` error
```

tracker(dm): fix downstream table structure reports key too long

---

cdc/owner/owner.go
cdc/owner/owner_test.go
pkg/txnutil/gc/testing.go
pkg/upstream/manager.go

Issue Number: close #6677 
when drain the capture, one capture drop all tables on it, and another capture add tables, which means the capture can contact tikv, which means tikv's version should be compatible with cdc.
- Unit test
```release-note
`None`.
```

api(cdc): drain capture also check store version

---

pkg/version/check.go
pkg/version/check_test.go

change cdc version from [6.3.0, 8.0.0), to [6.3.0-alpha, 8.0.0-alpha), so that `6.3.0-master` in the range.
- Unit test
```release-note
None`
```

version(ticdc): adjust cdc version range to 6.3.0-alpha ~ 8.0.0-alpha

---

dm/tests/checkpoint_transaction/run.sh
dm/tests/others_integration_1.txt
dm/tests/others_integration_2.txt
dm/tests/others_integration_3.txt

Issue Number: close #6704 
move some tests from other_1, other_2 to other_3
- No code
```release-note
`None`.
```

test(dm): split other test cases and fix unstable test

---

cdc/capture/capture.go
cdc/processor/processor.go
pkg/upstream/upstream.go

Issue Number: close #6714 
cdc panic due to visit nil pointer of `*ChangefeedReactorState`
* print log by use non-nil `changefeedID`, instead of `*ChangefeedReactorState` to prevent nil pointer, which cause the panic.
Upgrade pd to `v6.3.0`, which is not supported by `v6.2.0`, init upstream failed, `processor.changefeed` is not initialized, so cause the nil.
```release-note
`None`.
```

processor(ticdc): fix log make cdc instance panic

---

cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
cdc/sinkv2/ddlsink/mq/kafka_ddl_sink.go
cdc/sinkv2/ddlsink/mq/mq_ddl_sink.go
cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_producer.go
cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_producer_test.go
cdc/sinkv2/eventsink/mq/kafka_dml_sink.go
cdc/sinkv2/eventsink/mq/mq_dml_sink.go
cdc/sinkv2/eventsink/mq/worker.go
cdc/sinkv2/eventsink/txn/event.go
cdc/sinkv2/eventsink/txn/worker.go
cdc/sinkv2/metrics/kafka/collector.go
cdc/sinkv2/metrics/statistics.go
cdc/sinkv2/tablesink/progress_tracker.go

remove useless role in eventsink, because we only use it in processor.
- Unit test
No
No
```release-note
None
```

sinkv2(ticdc): remove useless role in eventsink

---

cdc/owner/changefeed.go
cdc/processor/pipeline/sink.go
cdc/processor/processor.go
cdc/redo/main_test.go
cdc/redo/manager.go
cdc/redo/manager_test.go
cdc/redo/options.go
cdc/redo/writer/blackhole_writer.go
cdc/redo/writer/file.go
cdc/redo/writer/main_test.go
cdc/redo/writer/writer.go
cdc/redo/writer/writer_test.go

Issue Number: close #6695 
Reusing log write in redo manager should be in a correct way
- Unit test
```release-note
None
```

redo(ticdc): owner and processores shouldn't share one redo log writer

---

pkg/cmd/cli/cli.go
pkg/cmd/cli/cli_changefeed_update.go
pkg/cmd/cli/cli_changefeed_update_test.go
pkg/cmd/cli/cli_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/6728
Drop interactive cmd support.
- Manual test
No
No
```release-note
None
```

cli(ticdc): drop interactive cmd support

---

deployments/engine/docker-compose/1m1e.yaml
deployments/engine/docker-compose/1m3e.yaml
deployments/engine/docker-compose/1meta.yaml
deployments/engine/docker-compose/dm_databases.yaml

Issue Number: ref #6554
Fix following error
```bash
$ docker-compose -f 1meta.yaml up -d
ERROR: The Compose file './1meta.yaml' is invalid because:
services.mysql-standalone.environment.MYSQL_ALLOW_EMPTY_PASSWORD contains true, which is an invalid type, it should be a string, number, or a null
```
Either `MYSQL_ALLOW_EMPTY_PASSWORD: "yes"` or `MYSQL_ALLOW_EMPTY_PASSWORD: 1` is valid
- Check docker compose runs normally 
```release-note
None
```

deployment(engine): fix invalid variable type in docker compose env

---

engine/pkg/meta/internal/sqlkv/sql_impl.go
engine/pkg/meta/internal/sqlkv/sql_impl_test.go

Issue Number: close #6869 
Return an empty resp when error is 'record not found'
- Unit test
```release-note
`None`.
```

meta(engine): KV interface method 'Get' return an empty response when meets 'record not found'

---

Makefile
deployments/engine/docker-compose/1m1e.yaml
deployments/engine/docker-compose/1m3e.yaml
deployments/engine/docker-compose/1meta.yaml
deployments/engine/docker-compose/3m3e.yaml
deployments/engine/docker-compose/dm_databases.yaml
engine/test/integration_tests/run.sh
engine/test/utils/check_case.sh

Issue Number: ref #6255
1. Use mysql8.0 in meta store to facilitate debugging integration tests in arm platform.
2. fix mysql authentication error of mysql8.0.
3. add check script to engine integration tests.
```release-note
`None`.
```

engine(test): fix mysql authentication error

---

engine/framework/model/master.go
engine/framework/model/master_test.go
engine/pkg/orm/client_test.go

Issue Number: ref #6270
- Added an `ext` field in `MasterMetaKVData` for better extensibility.
- Unit test
No.
No.
```release-note
None.
```

model(engine): support ext field in MasterMetaKVData

---

engine/test/integration_tests/dm_basic/run.sh
engine/test/utils/wait_mysql_online.sh

Issue Number: close #6923 
1. Add option --try-nums to the wait_mysql_online script
2. Increase the try nums for `dm_basic` test
```
$./wait_mysql_online.sh xxx
Unknown parameter: xxx
Only support: --host/--port/--user/--password/--try-nums
```
```
[Verifying database root@127.0.0.1:3306 is started...
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0 …
```

test(engine): add option --try-nums to the wait_mysql_online script

---

engine/servermaster/serverutil/watch_executors.go
engine/servermaster/serverutil/watch_executors_test.go

Issue Number: close #6964
- Fixed a bug in deferred closing of the receiver.
- Unit test
No.
No.
```release-note
None.
```

serverutil(engine): fix panic in WatchExecutors

---

Makefile
engine/framework/fake/fake_worker.go
engine/test/integration_tests/tiflow_job_finished/conf/fake_job.json
engine/test/integration_tests/tiflow_job_finished/run.sh

Issue Number: close #6978 
Set fake worker inner status to extMsg even the case when worker is finished or canceled
```release-note
`None`.
```

test(engine): fix fake job integration test fail when the worker is finished

---

.golangci.yml
engine/pkg/meta/internal/registry.go
engine/pkg/meta/mock/clientconn_mock.go

Issue Number: ref #2162
- Turn on `include-go-root` in depguard check in order to check standard library
- Replace `log` with `github.com/pingcap/log`
- Unit test
```release-note
None
```

lint(*): fix standard library is not checked in depguard

---

pkg/config/config_test_data.go
pkg/config/server_config.go

Issue Number: close https://github.com/pingcap/tiflow/issues/7030
Increase the default table memory quota to 64MiB.
- Unit test
No
No
```release-note
Increase the default table memory quota to 64MiB
```

config(ticdc): increase the default table memory quota to 64MiB

---

cdc/owner/changefeed.go
cdc/owner/metrics.go
cdc/owner/owner.go
metrics/grafana/ticdc.json

Issue Number: ref #4757
add latency duration percentile monitoring
```release-note
`None`.
```

changefeed(ticdc): add metrics to track lag distribution

---

cdc/owner/owner.go
cdc/owner/owner_test.go

Issue Number: close #7043, ref #4757
allow changefeeds abnormal in the cluster when check the healthy
- Unit test
```release-note
`None`.
```

owner(ticdc): fix query healthy 500 since changefeed paused.

---

dm/pkg/schema/tracker.go
dm/pkg/schema/tracker_test.go

Issue Number: close #5315
during the refactor of schema tracker, I found this issue is not hard to fix
- Unit test
```release-note
Fix a problem that DM will report `Specified key was too long` error
```

tracker(dm): fix downstream table structure reports key too long (#6661)

---

engine/framework/base_jobmaster.go
engine/framework/base_jobmaster_test.go
engine/framework/master.go
engine/framework/metadata/metadata.go
engine/framework/model/master.go
engine/framework/model/master_test.go
engine/pkg/orm/client.go
engine/pkg/orm/client_test.go
engine/pkg/orm/model/common.go

Issue Number: close #7021
- Update `error_message` field before job master calls `doClose`
- Change the interface signature of `UpdateJob` to explicit way, which means the parameter contains all fields that need to be updated.
- Unit test
```release-note
None
```

framework(engine): record error message when job master closes

---

metrics/grafana/ticdc.json

Issue Number: close #7040
Change metrics from ticdc_sink_received_row_changed_event_size_bucket to ticdc_sink_large_row_changed_event_size_bucket;
- Unit test
- No code
no
no
```
`None`
```

metrics(ticdc) : fix incorrect display of panel about large data event size (MySQL)

---

dm/syncer/ddl.go
dm/syncer/syncer.go
engine/pkg/orm/client.go
engine/servermaster/jobop/backoff.go

Issue Number: close #6628 
Modification to `job.ddls` is put to the place as late as possible, which is just before `db.ExecuteSQLWithIgnore`.
The appearing time of the Warn message is reduced by adding conditions to trigger it. Now only when no timezone information was retrieved from `GetTimezoneByStatusVars` and upstream timezone has not been previously set, the warn message would be triggered.
The changes in `engine/pkg/orm/client.go` and `engine/servermaster/jobop/backoff.go` are caused by `make fmt` of go version 1.19.
No.
No.
```release-note
Reduce the appearing time of the warning message "found error when getting timezone from binlog status_vars" in dm-worker log.
```

syncer(dm): Fix follow-up bugs after fixing nondeterministic DDL

---

engine/test/e2e/docker.json
engine/test/e2e/e2e_test.go

Issue Number: close #7102
- Use smaller data size
- Use `require.NoError` to check nil error
- Unit test
```release-note
None
```

test(engine): use smaller dataset to stable e2e test

---

dm/tests/safe_mode/run.sh

Issue Number: ref #4159, close #7099
- the worker1 didn't enter sync status and execute dml, after check_diff before kill_worker, so its SafeModeExitPoint is yet same as its GlobalCheckpoint(beginPosition). This is the unstable reason.
```release-note
`None`
```

test(DM): add check log contain to `safe-mode` integration test

---

pkg/pdutil/clock.go

Issue Number: close    https://github.com/pingcap/tiflow/issues/7201
Fix a deadlock issue. Release the lock as soon as possible, otherwise `Run` and `Close` will cause a deadlock.
- Unit test
No
No
```release-note
None
```

pkg/pdutil(ticdc): fix a deadlock issue

---

cdc/sink/codec/maxwell/maxwell_message_test.go

Issue Number: close #5069 
add a unit test to verify that binary `[]uint8` can be correctly encoded.
- Unit test
```release-note
`None`.
```

codec(ticdc): add unit test to cover maxwell message encode binary data

---

dm/_utils/terror_gen/errors_release.txt
dm/errors.toml
dm/loader/lightning.go
dm/pkg/retry/errors.go
dm/pkg/terror/error_list.go
dm/worker/server_test.go
dm/worker/task_checker_test.go

Issue Number: ref #7068
lightning itself is a long time runnning import job, so it already has handled retry. It's no need to let DM add retry mechanism.
- Unit test
```release-note
`None`.
```

lightning(dm): all lightning errors are not auto-resumeable

---

engine/pkg/orm/util_test.go

Issue Number: ref #7271
- enable one more unit test in engine orm pkg
- Since the index sequence of generated create table DDL are nondeterministic, we use regex `.*` to match the index part. 
- Unit test
```release-note
None
```

pkg(engine): enable orm initialize test

---

engine/pkg/orm/util_test.go

Issue Number: close #7271
#7287
ref: https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/37767/pipeline/
```go
[2022-10-08T07:27:02.392Z] === Failed
[2022-10-08T07:27:02.392Z] === FAIL: engine/pkg/orm TestInitialize (0.04s)
[2022-10-08T07:27:02.392Z] [2022/10/08 15:26:34.536 +08:00] [ERROR] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=4.594175ms] [sql="CREATE TABLE `resource_meta` (`seq_id` bigint unsigned AUTO_INCREMENT,`created_at` datetime(3) NULL,`updated_at` datetime(3) NULL,`project_id` varchar(128) not null,`id` varchar(128) not null,`job_id` varchar(128) not null,`worker_id` varchar(128) not null,`executor_id` varchar(128) not null,`gc_pending` BOOLEAN,`deleted` BOOLEAN,PRIMARY KEY (`seq_id`),INDEX `idx_rei` (`executor_id`,`id`),UNIQUE INDEX …
```

test(eninge): fix unstable index sequence in orm generated sql

---

cdc/capture/capture.go

Issue Number: close #7294 
when the owner exit, it does not clean up metrics in time before set the owner to nil.
before set the owner to nil, clean up old owner's pending jobs and metrics by call `AsyncStop`
- No code
```release-note
`None`.
```

owner(ticdc): async close the owner before set the owner to nil to clean up pending jobs and metrics

---

cdc/owner/barrier.go
cdc/owner/changefeed.go
cdc/owner/owner.go
cdc/processor/processor.go
errors.toml
pkg/errors/cdc_errors.go
pkg/upstream/manager.go
pkg/upstream/manager_test.go

Issue Number: close #7291 
1. Extract a func to check the state of `upstream` of changefeed when it ticks, which simplifies the code of `Tick` method.
2. Add some comments in the `handleBarrier` method of changefeed to make the logic more easier to understand.
3. Make `upstremManager`'s  `Tick` method thread-safe, since it is called by `Owner` and `processorManager` in a same capture.
- No code
```release-note
None
```

changefeed (ticdc): extract a method and add some comments

---

dm/pkg/checker/privilege.go
dm/pkg/checker/privilege_test.go

Issue Number: close #7317 
so no need to let checker require this privilege
- Unit test
```release-note
DM precheck no longer reports lacking privileges of INFORMATION_SCHEMA
```

checker: infoschema does not need privilege to access

---

dm/pkg/utils/db.go
dm/pkg/utils/db_test.go
engine/framework/metadata/metadata.go
engine/pkg/orm/client.go
engine/pkg/orm/client_test.go
engine/pkg/orm/mock/client_mock.go
engine/pkg/orm/util.go
engine/pkg/orm/util_test.go
engine/servermaster/jobmanager.go
engine/servermaster/jobmanager_test.go

Issue Number: close #7322
- Insert into job master meta directly instead of the old check and upsert way.
- Unit test
```release-note
None
```

jobmanager(engine): insert job directly when handling create API

---

pkg/orchestrator/etcd_worker.go

Issue Number: close #7374
1. changefeed `rate.Limit(tickRate)` to `rate.Every(timerInterval)`,  this will fix if the tick interval is greater than  1 second, etcd worker will be always rate limited.
2. increase burst of rate limit from 1 to 2, since the p2p scheduler will not write too much etcd data
- Unit test
```release-note
`None`.
```

etcd(ticdc): adjust etcd worker rate limit

---

.github/workflows/dataflow_engine_e2e.yaml
Makefile
deployments/engine/docker/Dockerfile

Issue Number: ref #5668
- Dockerfile is used to publish tiflow(engine) image, we remove tiflow-demo-server from the image
- Jenkins integration test contains the engine e2e basic test, so remove it from the github action to be compatible with the new docker image
- Unit test
```release-note
None
```

Dockerfile(engine): remove tiflow demo from default dockerfile

---

deployments/engine/docker-compose/config/executor.toml
deployments/engine/docker-compose/config/template_executor.toml
deployments/engine/helm/tiflow/values.yaml
engine/executor/config.go

Issue Number: ref #6849
`session-ttl` is used in etcd based session, it is no longer used after #6949
Since it is break compatibility, we also need to update template in tiflow-operator.
- Unit test
```release-note
None
```

config(engine): remove deprecated session-ttl config from executor

---

engine/pkg/externalresource/broker/broker.go
engine/pkg/externalresource/broker/broker_test.go

Issue Number: close #7399
> https://github.com/pingcap/tiflow/blob/9abde064c9a50aef77ffd3aa8be609d3265e4ed0/engine/pkg/externalresource/broker/broker.go#L343-L357
> 
L349 and L353 are non-atomic operations. If a worker successfully executes L349 but fails in L353, there will be an inconsistency between the resource and meta data (In this case, the resource does not exist while meta still exists).
And we can avoid this problem by handling the cleanBeforeOpen option before getting persistent resource
- Unit test
```release-note
`None`.
```

engine(externalresource): handle cleanBeforeOpen option before getting persisted resource

---

engine/executor/dm/worker.go
engine/framework/base_jobmaster.go
engine/framework/worker.go
engine/jobmaster/dm/api_test.go
engine/jobmaster/dm/dm_jobmaster.go
engine/jobmaster/dm/dm_jobmaster_test.go
engine/jobmaster/dm/openapi_test.go
engine/jobmaster/dm/utils.go
engine/jobmaster/dm/worker_manager.go
engine/jobmaster/dm/worker_manager_test.go
engine/pkg/externalresource/broker/broker.go
engine/pkg/externalresource/broker/broker_test.go
engine/pkg/externalresource/broker/interfaces.go
engine/test/integration_tests/dm_many_tables_local/conf/diff_config.toml
engine/test/integration_tests/dm_many_tables_local/conf/job.yaml
engine/test/integration_tests/dm_many_tables_local/run.sh

Issue Number: ref #7114
1. Add IsS3StorageEnabled to BaseWorker and BaseMaster.
2. Generate resource id by storage config.
- Unit test
```release-note
`None`.
```

engien(dm, externalstorage): generate resource id by storage config

---

deployments/engine/helm/minio/minio.yaml
engine/chaos/cases/dm/case.go

Issue Number: close #7426 
we generate insert and delete for different sources.
```
source1 delete key 1
source2 insert key 1
```
If the latency of source1 is greater than source2, than the worker of source2 will report duplicate key 1 error.
- chaos
```release-note
None
```

test(chaos): fix duplicate entry due to concurrency delete and insert.

---

engine/pkg/client/discovery_client.go
engine/pkg/client/internal/call.go
engine/pkg/externalresource/internal/s3/file_manager.go
engine/pkg/externalresource/model/config.go

Issue Number: close #7442
1. Remove infinite retry in RegisterExecutor.
2. Remove unused c.S3.RoleARN check in external storage.
- Unit test
```shell
2022/10/25 17:53:15.546 +08:00] [INFO] [version.go:47] ["Welcome to TiFlow Executor"] [release-version=v6.3.0-master] [git-hash=38662c76239b6e0237ad9f389a0ca128d24c5bc4] [git-branch=fix_executor_stuck] [utc-build-time="2022-10-25 09:52:51"] [go-version="go version go1.19.2 linux/amd64"] [failpoint-build=false]
[2022/10/25 17:53:15.546 +08:00] [INFO] [server.go:98] ["creating executor"] [config="{\"name\":\"executor-127.0.0.1:10340\",\"log\":{\"level\":\"info\",\"file\":\"\",\"max-size\":0,\"max-days\":0,\"max-backups\":0,\"error-output\":\"\"},\"join\":\"127.0.0.1:10240\", …
```

engine(pkg/client): remove infinite retry in RegisterExecutor

---

cdc/processor/pipeline/sorter.go

Issue Number: close #7514
decrease the value after sorter processed a event
- Unit test
```release-note
`None`.
```

sorter(ticdc): fix remainEvents metric

---

engine/pkg/notifier/notifier.go
engine/pkg/notifier/notifier_test.go
engine/servermaster/executor_manager.go
engine/servermaster/executor_manager_test.go
engine/servermaster/server.go
engine/servermaster/server_test.go

Issue Number: close #7506
- Flush should return immediately if notifier has been closed.
- Unit test
```release-note
None
```

notifier(engine): fix Flush deadloop in closed notifier

---

dm/syncer/syncer.go
dm/syncer/syncer_test.go

Issue Number: close #7493
as title
- Unit test
```release-note
Fix sometime DM task is stopped with error "Unknown placement policy"
```

syncer(dm): remove placement rule table option for tracker

---

engine/framework/base_jobmaster.go
engine/framework/fake/fake_master.go
engine/framework/master.go
engine/framework/master_test.go
engine/jobmaster/cvsjob/cvs_job_master.go
engine/jobmaster/dm/dm_jobmaster_test.go
engine/jobmaster/dm/worker_manager.go
engine/jobmaster/dm/worker_manager_test.go
engine/jobmaster/example/master_impl.go
engine/servermaster/jobmanager.go
engine/servermaster/jobmanager_test.go

Issue Number: ref #5673
- `CreateWorkerV2` delegates `CreateWorker`, use one `CreateWorker` instead.
- All options passed in `CreateWorkerOptions` will be printed in `ScheduleTask` request.
- Unit test
```release-note
None
```

framework(engine): simplify CreateWorker API

---

cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/manager_impl.go
cdc/processor/sinkmanager/manager_impl_test.go
cdc/processor/sinkmanager/table_progress_heap.go
cdc/processor/sinkmanager/table_progress_heap_test.go
cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/processor/sinkmanager/table_sink_wrapper_test.go

Consider the table state when generating tasks. If the table sink state is not replicating, then skip it.
- Unit test
No
No
```release-note
None
```

sinkmanager(ticdc): consider table state when generate tasks

---

dm/tests/_utils/run_tidb_server
dm/tests/shardddl3/run.sh

test(dm): set clustered index behaviour to old version

---

cdc/processor/sinkmanager/manager_impl.go
cdc/processor/sinkmanager/manager_impl_test.go
cdc/processor/sinkmanager/mem_quota.go
cdc/processor/sinkmanager/mem_quota_test.go
cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/processor/sinkmanager/table_sink_wrapper_test.go
cdc/processor/sinkmanager/worker.go
cdc/processor/sinkmanager/worker_impl.go
cdc/processor/sinkmanager/worker_impl_test.go

Release mem quota when removing a table.
Abort the task and refund the unused memory quota. Also, do not put the progress back into the heap.
No
No
```release-note
None
```

sinkmanager(ticdc): release mem quota when remove a table

---

cdc/scheduler/internal/v2/agent.go
cdc/scheduler/internal/v2/schedule_dispatcher.go
engine/pkg/externalresource/manager/service.go
engine/pkg/rpcutil/middleware.go
go.mod
go.sum
pkg/logutil/log.go

Issue Number: close https://github.com/pingcap/tiflow/issues/7573
Replace deprecated `log.With` with `log.L().With`. See https://github.com/pingcap/log/issues/32.
- Unit test
- No code
```release-note
None
```

log(all): replace deprecated log.With

---

Makefile
engine/executor/dm/unitholder.go

Issue Number: ref #7343
- df-service will call `get job api` which calls `dm status`, but current impl will get source status every time, if the source is down, it won't return after 30s timeout, which will make df-service `get/list job` timeout and fails. so change `unit.Status` to use cached source status.
- Unit test
- No code
```release-note
`None`.
```

engine: unit status use cached source status

---

engine/framework/internal/master/worker_creator.go
engine/servermaster/jobmanager.go
engine/servermaster/jobmanager_test.go

Issue Number: close #7646
- Unit test
```release-note
None
```

framework(engine): fix label lost when job is failover

---

engine/executor/dm/unitholder.go
engine/executor/dm/unitholder_test.go
engine/executor/dm/worker.go

- create new ctx to get source status
- Unit test
- No code
```release-note
None
```

engine(dm): use new ctx rather than ctx of tick to get source status

---

engine/jobmaster/dm/dm_jobmaster.go
engine/jobmaster/dm/dm_jobmaster_test.go

Issue Number: close #7691
- ignore nil extra status bytes for OnWorkerOnline
- Unit test
```release-note
None
```

jobmaster(engine/dm): fix empty worker status for OnWorkerOnline/OnWorkerOffline

---

engine/executor/dm/worker.go

Issue Number: close #7476 
- log error only when task stage changed
- Unit test
- No code
```release-note
None
```

fix log flood when worker error

---

dm/tests/_utils/run_tidb_server

follow up https://github.com/pingcap/tidb/pull/39267
- No code
```release-note
`None`.
```

test(dm): turn off tidb_ddl_enable_fast_reorg

---

engine/jobmaster/dm/api.go
engine/jobmaster/dm/dm_jobmaster.go
engine/pkg/dm/message_agent.go

Issue Number: close #7710
- get `finished_unit_status` after query worker to avoid finished_unit_status hasn't set and worker finished in the middle of the request, and cause unit status(such as load) is missing
- Unit test
- No code
```release-note
`None`.
```

engine: make sure get-job-status can see unit status either in task_status or finished_unit_status

---

dm/syncer/util.go

- use schema/table name as cache key to filter binlog
- Unit test
- No code
```release-note
None
```

binlog_filter: use table name instead of table id as cache key

---

cdc/sinkv2/eventsink/cloudstorage/dml_worker.go

Issue Number: ref #6797 
- Before this PR:
When iterating `events` in L143:
https://github.com/pingcap/tiflow/blob/e7e2894c18c1a538458c66770bd17a255676b854/cdc/sinkv2/eventsink/cloudstorage/dml_worker.go#L135-L143
some items may have been mistakenly overwritten by L256, so the table checkpoint will not be updated anymore.
https://github.com/pingcap/tiflow/blob/e7e2894c18c1a538458c66770bd17a255676b854/cdc/sinkv2/eventsink/cloudstorage/dml_worker.go#L255-L257
- After this PR:
Clone a new slice to detach with the old one, so as to prevent the slice overwriting problem from happening.
- Unit test
```release-note
None
```

sink(ticdc): Fix a slice overwriting problem

---

cdc/processor/processor.go
cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/manager_test.go
cdc/processor/sinkmanager/redo_log_worker.go
cdc/processor/sinkmanager/table_sink_worker.go
cdc/processor/sinkmanager/table_sink_worker_test.go
cdc/processor/sourcemanager/manager.go

See: https://github.com/pingcap/tiflow/issues/5928#issuecomment-1318253453
move mounted iter into sourceManager.
- Unit test
No
No
```release-note
None
```

processor/sourcemanager(ticdc): move mounted iter into sourceManager

---

cdc/processor/manager.go
cdc/processor/processor.go
cdc/processor/sinkmanager/manager.go
cdc/processor/sourcemanager/manager.go
cdc/sinkv2/eventsink/txn/worker.go

Issue Number: close https://github.com/pingcap/tiflow/issues/7780 
Cancel the context before we close the processor. Otherwise, we might be stuck when closing the sink.
Add some logs when closing the processor.
- No code
No
No
```release-note
None
```

processor(ticdc): cancel the context before closing the processor

---

metrics/grafana/DM-Monitor-Professional.json
metrics/grafana/DM-Monitor-Standard.json

Issue Number: ref #6985 
1. Add job_id variable to dm grafana.
2. Change some variable variable definition (such as `task, source and instance`) so that engine and dm can share the same grafana.
Note: Currently only `dump` and `syncer` monitors are available to the engine. In the future, load's monitoring will be replaced with lightning's, and monitors for other modules will gradually be added to the grafana panel. Within this week, we will delete [the original dm‘s monitoring files](https://github.com/pingcap/tiflow/tree/master/dm/metrics/grafana) on the premise of maintaining compatibility
Verify that the panel can support both engine and dm:
1. engine 
- [DM-professional](https://snapshots.raintank.io/dashboard/snapshot/EbElU3R2xNH8SlpoVmfnNCscJII5FIPw?orgId=2)
- …

metrics(dm, engine): add support for engine in dm grafana

---

cdc/entry/mounter_test.go
cdc/model/sink.go

this is a manually cherry-pick for #7891 
---
Issue Number: close #7890 
skip the index
- Unit test
```release-note
`None`.
```

model(cdc): fix BuildTiDBTableInfo panic when UNIQUE index exists #7891

---

cdc/processor/pipeline/sorter.go
cdc/processor/pipeline/sorter_test.go
cdc/processor/pipeline/table_actor.go
cdc/processor/processor.go
cdc/sorter/db/db.go
cdc/sorter/db/db_test.go
cdc/sorter/db/message/task.go
cdc/sorter/db/reader.go
cdc/sorter/db/reader_test.go
cdc/sorter/db/sorter.go
cdc/sorter/db/sorter_test.go
cdc/sorter/db/system/system.go
cdc/sorter/db/system/system_test.go
cdc/sorter/db/writer.go
cdc/sorter/db/writer_test.go

Issue Number: ref #7720 
* Replace TableID with tablepb.Span in sorter
- Unit test
No
No
```release-note
None
```

sorter/db,processor: replace table ID with Span 

---

cdc/sinkv2/eventsink/cloudstorage/dml_worker.go

Issue Number: ref #7886
replicate 1000 tables with 40 million old data, no incremental data. After lag equalizes, the heap information is as follows: 
before:
after:
- Unit test
- No code
```release-note
```

sink(ticdc): fix eventFragment memory leak in cloud storage sink

---

cdc/processor/processor.go
cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/table_sink_worker_test.go
cdc/processor/sinkmanager/table_sink_wrapper_test.go
cdc/sinkv2/eventsink/factory/factory.go
cdc/sinkv2/eventsink/factory/factory_test.go
cdc/sinkv2/tablesink/progress_tracker.go
cdc/sinkv2/tablesink/progress_tracker_test.go
cdc/sinkv2/tablesink/table_sink_impl.go
cdc/sinkv2/tablesink/table_sink_impl_test.go
pkg/config/debug.go

Issue Number: ref #7720 
* Replace TableID with tablepb.Span in sink v2
- Unit test
No
No
```release-note
None
```

sinkv2,processor: replace table ID with Span

---

dm/syncer/expr_filter_group.go
dm/syncer/expr_filter_group_test.go
dm/tests/expression_filter/conf/dm-task2.yaml
dm/tests/expression_filter/data/db1.increment2.sql
dm/tests/expression_filter/run.sh

Issue Number: close #7831 
I forget the case that a table has both insert and update expression filter
- Unit test
```release-note
Fix a bug that when both "update" and "non-update" type expression filters are used in one table, all UPDATE row changes are skipped
```

expression_filter(dm): fix append update filter for non-update item

---

cdc/sorter/db/buffer.go
cdc/sorter/db/buffer_test.go
cdc/sorter/db/reader.go
cdc/sorter/db/reader_test.go
cdc/sorter/db/sorter.go

Issue Number: close #7913
close https://github.com/pingcap/tidb/issues/39819
Split large txn during sorter read.
- Unit test
Yes, it might cause performance regression.
No.
```release-note
Fix an OOM issue when TiCDC replicates big transactions
```

sorter(ticdc): split large txn

---

engine/jobmaster/dm/api.go
engine/jobmaster/dm/api_test.go

Issue Number: ref #7115
- introduced by https://github.com/pingcap/tiflow/pull/7711, which cause `existUnitState` not inited, so duration is not calculated
- Unit test
- No code
```release-note
`None`.
```

engine: fix duration not updated

---

cdc/capture/capture.go

Issue Number: close #7918
if c.reset() meet error between [L204 and L246](https://github.com/pingcap/tiflow/pull/7921/files#diff-4f24fb50f8768cd676f96ed676da601c83670784c3af3fac055361e7b035efd9R206-R246), capture will panic. So, we should check if c.election is nil before close it.
- Unit test
```release-note
`None`.
```

capture(ticdc): fix cdc panic when async close capture 

---

engine/jobmaster/dm/metadata/job.go
engine/jobmaster/dm/metadata/job_test.go
metrics/grafana/DM-Monitor-Professional.json
metrics/grafana/DM-Monitor-Standard.json

Issue Number: ref #7115
- now we uses the same grafana dashboard for dm in OP and engine(https://github.com/pingcap/tiflow/pull/7881), so we need to use same enum value as dmpb for engine task stage, to avoid confusion
- Unit test
- No code
```release-note
`None`.
```

engine(dm): use same enum value as dmpb for engine task stage

---

cdc/server/server_test.go
engine/pkg/client/executor_client_test.go
engine/test/e2e/e2e_dm_test.go
pkg/cmd/cli/cli_changefeed_list_test.go
pkg/cmd/cli/cli_changefeed_query_test.go
pkg/fsutil/preallocate_test.go
pkg/security/credential.go
pkg/security/test_util.go

Issue Number: close #7908
1. use GetClientCertificate and GetCertificate in tls.config
- Unit test
- No code
```release-note
`support online load tls config in TiCDC`.
```

pkg/security(ticdc): support online load tls config (#7927)

---

cdc/puller/ddl_puller_test.go
cdc/puller/puller.go
cdc/puller/puller_test.go

GetResolvedTs is not used, remove it to simplify the Puller interface
Issue Number: close #7956
remove GetResolvedTs
- Unit test
```release-note
`None`
```

puller(ticdc): remove GetResolvedTs from Puller interface

---

go.mod
go.sum

Issue Number: close #7969 ref https://github.com/go-mysql-org/go-mysql/pull/760
- update go-mysql dependency
- manually test(replace upstream with mariadb)
- chaos test
```release-note
None
```

bug-fix: update go-mysql to fix mariadb panic

---

cdc/sink/mysql/mysql.go
cdc/sinkv2/eventsink/txn/mysql/mysql.go
cdc/sinkv2/eventsink/txn/mysql/mysql_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/7982
use separate ctx for each DML to avoid the timeout when executing the big Txn.
No
No
```release-note
Fix the bug that context deadline was exceeded when replicating data without split big txn
```

sink(ticdc): use separate ctx for each DML

---

README.md

Issue Number: ref #5687
- `coveralls.io` was used to combine coverage of unit tests and integration tests, which has been deprecated for one year.
- No code
```release-note
None
```

readme(*): remove deprecated coverage link

---

pkg/causality/internal/slots.go
pkg/causality/internal/slots_test.go

Issue Number: close #7974
- In original `Free` implement, if `keys` contain two or more successive key that have the same slot index, only the first key can be locked when accessing slots.
- Unit test
```release-note
None
```

causality(ticdc): fix slot could not be locked during free

---

cdc/sink/mysql/mysql.go
cdc/sink/mysql/mysql_test.go
pkg/sink/mysql/db_helper.go

Signed-off-by: kennytm <kennytm@gmail.com>
Issue Number: close #7989
Use `sql.NullString` to receive the result of `select @@sql_mode`. Treat NULL as empty string.
- Unit test
No
No
```release-note
```
Fix compatibility issue when using Alibaba AnalyzeDB for MySQL as TiCDC sink

mysql(ticdc): handle the case when @@sql_mode is null

---

pkg/cmd/cli/cli_changefeed_helper.go
pkg/cmd/cli/cli_changefeed_update.go
pkg/cmd/cli/cli_unsafe.go

Issue Number: close #7903
print error msg if an invalid input was read
Manual test (add detailed scripts or steps below)
1. before
```bash
Error: EOF
Replicate lag (121h36m31.6s) is larger than 1 days, large data may cause OOM, confirm to continue at your own risk [Y/N]
```
2. after
```bash
Replicate lag (380h54m19.605s) is larger than 1 days, large data may cause OOM, confirm to continue at your own risk [Y/N]
Received invalid input: EOF, abort the command.
Abort changefeed create.
```
```release-note
`None`.
```

cmd(ticdc): print error msg if an invalid input was read

---

cdc/model/changefeed.go
cdc/model/changefeed_test.go
pkg/config/replica_config.go
pkg/config/replica_config_test.go

Issue Number: close #8007 
- Auto fix `memory-quota` if it is zero in changefeed info from etcd.
- Auto fix `memory-quota` if it is zero when creating a new changefeed.
- Unit test
```release-note
Fix memory-quota is set to zero unexpectedly which will cause replication stuck.
```

changefeed(ticdc): fix memory quota incompatible from 6.5.0

---

cdc/server/server.go
engine/pkg/p2p/message_sender.go
engine/pkg/p2p/server_integration_test.go
pkg/cmd/server/server_test.go
pkg/config/config_test_data.go
pkg/config/messages.go
pkg/config/messages_test.go
pkg/p2p/client.go
pkg/p2p/client_connector.go
pkg/p2p/client_test.go
pkg/p2p/message_router_test.go
pkg/p2p/mock_cluster.go
pkg/p2p/server.go
pkg/p2p/server_client_integration_test.go
pkg/p2p/server_wrapper.go
pkg/p2p/server_wrapper_test.go

Issue Number: close #8004
Use a larger max receive message size to address ResourceExhausted issue.
- Unit test
- Manual test
Setup a changefeed that replicate 72k tables.
No.
No.
```release-note
Fix an issue that checkpoint can not advance when replicating many tables.
```

p2p(ticdc): use a larger max receive message size

---

cdc/api/v1/validator.go
cdc/api/v2/api_helpers.go
cdc/api/v2/api_helpers_test.go
cdc/api/v2/changefeed.go
errors.toml
pkg/config/sink.go
pkg/config/sink_test.go
pkg/errors/cdc_errors.go

Issue Number: close #7935
1. For testing purposes, make [blackhole compatible with any protocol](https://github.com/pingcap/tiflow/pull/7980/files#diff-1aa9ba3321cb0edb368a32b5084da34322b0f9d6a600019beb724ab63bc5e071R308). 
2. Replace `defaultMqTxnAtomicity` and  `defaultMysqlTxnAtomicity` with `defaultTxnAtomicity`. Remove the logic for [changing default value of TxnAtomicity](https://github.com/pingcap/tiflow/pull/7980/files#diff-1aa9ba3321cb0edb368a32b5084da34322b0f9d6a600019beb724ab63bc5e071L267-L292)) and simplify such logic in [`ShouldSplitTxn`](https://github.com/pingcap/tiflow/pull/7980/files#diff-1aa9ba3321cb0edb368a32b5084da34322b0f9d6a600019beb724ab63bc5e071R68) and [`validate`](https://github.com/pingcap/tiflow/pull/7980/files#diff-1aa9ba3321cb0edb368a32b5084da34322b0f9d6a60001 …

api,config(ticdc): support update transaction-atomicity and protocol via config file

---

cdc/processor/sourcemanager/engine/mounted_iter.go
cdc/processor/sourcemanager/engine/mounted_iter_test.go

Issue Number: ref #5928
remove redundant nextToMount in MountedEventIter
- Unit test
```release-note
`None`.
```

sinkv2(ticdc): remove redundant nextToMount in MountedEventIter

---

engine/servermaster/jobmanager_test.go

Issue Number: close #8032
It is easy to reproduce the panic with following patch
```diff
diff --git a/engine/servermaster/jobmanager_test.go b/engine/servermaster/jobmanager_test.go
index 12d14fce7..c6a93e5b5 100644
--- a/engine/servermaster/jobmanager_test.go
+++ b/engine/servermaster/jobmanager_test.go
@@ -91,6 +91,7 @@ func TestJobManagerCreateJob(t *testing.T) {
}
job, err := mgr.CreateJob(ctx, req)
require.NoError(t, err)
+       time.Sleep(time.Second)
err = mockMaster.Poll(ctx)
require.NoError(t, err)
```
- The root cause is if create worker is called before `mockMaster.Poll`, the `Poll` will trigger more callbacks, where some of fileds of job manager is not initialized in this unit test.
- Since this test verifies the `CreateWorker` staff, it is safe to remove …

tests(engine): fix unstable unit test in jobmanager

---

cdc/processor/pipeline/puller.go
cdc/processor/sourcemanager/puller/puller_wrapper.go
cdc/puller/ddl_puller.go
cdc/puller/puller.go
cdc/puller/puller_test.go

Issue Number: close #8027
not use span size to check if the puller is a ddl puller, use a bool passed by caller
- Unit test
```release-note
`None`.
```

puller(ticdc): fix frontier metrics label

---

cdc/sink/codec/encoder_group.go

Issue Number: close #8041
do not close the output channel when exit the encoder group
- No code
```release-note
`None`
```

encoder(ticdc): do not close the output channel to prevent data race.

---

go.mod
go.sum
pkg/cmd/server/server_test.go
pkg/config/config_test_data.go
pkg/config/debug.go
pkg/config/server_config.go
pkg/sink/kafka/v2/manual_balancer.go

Issue Number: close #8081, close #8082 
* add `enable-kafka-sink-v2` to the `Debug` configuration.
* update go mod to import kafka-go
* add a new folder `pkg/sink/kafka/v2`and `muanal_balancer.go` as the placeholder.
- Unit test
```release-note
`None`
```

sink(ticdc): add knob to controll enable kafka sink v2 and add basic dependency scaffold

---

cdc/sinkv2/tablesink/table_sink_impl.go
cdc/sinkv2/tablesink/table_sink_impl_test.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/4954
remove useless event ID in the table sink
- Unit test
No
No
```release-note
None
```

sinkv2(ticdc): remove useless event ID in the table sink

---

Makefile
cdc/api/v2/model.go
cdc/owner/changefeed_test.go
cdc/redo/common/metric.go
cdc/redo/manager.go
cdc/redo/manager_test.go
cdc/redo/reader/file.go
cdc/redo/writer/file.go
cdc/redo/writer/writer.go
cdc/redo/writer/writer_test.go
cdc/sinkv2/eventsink/txn/worker.go
deployments/ticdc/docker/test.Dockerfile
engine/pkg/externalresource/internal/s3/file_manager.go
errors.toml
metrics/grafana/ticdc.json
pkg/config/consistent.go
pkg/config/replica_config.go
pkg/errors/cdc_errors.go
pkg/redo/config.go

Issue Number: close #8074, close #8028
1. Use uuid in redo meta filename to avoid frequent access to the same object.
2. Add metricRedoWorkerBusyRatio to redoManager.
4. Fix the limit on flush-interval.
5. Add test.Dockerfile facilitate testing. 
- Unit test
```release-note
`None`.
```

redo(ticdc): use uuid in redo meta filename 

---

cdc/sink/mq/manager/kafka_manager.go
cdc/sink/mq/manager/kafka_manager_test.go
cdc/sink/mq/mq.go
cdc/sinkv2/ddlsink/mq/kafka_ddl_sink.go
cdc/sinkv2/eventsink/mq/kafka_dml_sink.go
cdc/sinkv2/util/helper.go
pkg/sink/kafka/client.go
pkg/sink/kafka/client_mock_impl.go
pkg/sink/kafka/cluster_admin_client_mock_impl.go
pkg/sink/kafka/v2/kafka-go-client.go

Issue Number: close #8164 
* `Partitions` and `Topic` methods removed from the `Client` interface
- No code
```release-note
`None`
```

kafka(ticdc): simplify the client interface by remove partition and topic methods

---

cdc/sink/mq/producer/kafka/kafka.go
cdc/sink/mq/producer/kafka/kafka_test.go
errors.toml
pkg/errors/cdc_errors.go
pkg/sink/kafka/options.go
pkg/sink/kafka/options_test.go
pkg/sink/kafka/sarama.go

Issue Number: close https://github.com/pingcap/tiflow/issues/8098
- make required acks configuration configurable, please see https://github.com/pingcap/tiflow/issues/8098#issuecomment-1411652359
- skip check `min.insync.replicas` if required acks is not all, please see https://github.com/pingcap/tiflow/issues/8098#issuecomment-1411655843
- add a warning if TiCDC can not find the `min.insync.replicate` configuration, please see https://github.com/pingcap/tiflow/issues/8098#issuecomment-1413109862
No
Yes, I'll update it later.
```release-note
Make Kafka producer's required acks configuration configurable
```

pkg/sink(ticdc): make require acks configuration configurable

---

cdc/redo/writer/file.go
cdc/redo/writer/writer.go
engine/pkg/externalresource/internal/s3/storage_factory.go
go.mod
pkg/redo/config.go
pkg/util/external_storage.go

Issue Number: close #8089 
Set the default timeout for accessing external storage to 15 minutes
- Unit test
- Manual test 
1. run consistent_replicate_storage_s3 test
2. stop minio manually
3. sleep 5 minutes
4. restart minio
The test passed and the following logs were found:
```release-note
`Fix the issue that redo log cannot tolerate network faults for more than 6 seconds`.
```

redo(ticdc): set default timeout for accessing external storage to 15 minutes

---

cdc/processor/sinkmanager/manager.go

Issue Number: close #8216
When close the sink manager, close the sink factory at the last, after make sure all sink workers exited.
- No code
```release-note
`None`
```

sinkV2(ticdc): sink manager close the sink factory at the last

---

pkg/sink/kafka/admin.go

Issue Number: close #8225, close #8223
`AdminClient` may meet `write: broken pipe`, it's a know issue have not been addressed yet.
* reset the `admin client` if meet `broken pipe` error.
```release-note
None`
```

kafka(ticdc): reset the admin client to fix broken pipe

---

cdc/sink/mq/manager/kafka_manager.go
pkg/sink/kafka/admin.go
pkg/sink/kafka/cluster_admin_client.go
pkg/sink/kafka/cluster_admin_client_mock_impl.go
pkg/sink/kafka/v2/admin.go

Issue Number: ref #8225 
* admin client use cached client's topics and partitions
- Unit test
```release-note
`None`
```

kafka(ticdc): sarama admin client use cached topic and partitions

---

pkg/cmd/server/server_test.go
pkg/config/config_test_data.go
pkg/config/server_config.go
pkg/config/server_config_test.go
tests/integration_tests/server_config_compatibility/conf/server.toml

Issue Number: ref https://github.com/pingcap/tiflow/issues/8132
mark per table memory quota deprecated
- Unit test
No
No
```release-note
None
```

config(ticdc): mark per table memory quota deprecated

---

deployments/ticdc/docker/integration-test.Dockerfile

Issue Number: ref https://github.com/pingcap/tiflow/issues/8327
remove useless sha256sum check. Because we download it from the official website, it is safe to not check it.
- No code
No
No
```release-note
None
```

deployments(ticdc): remove useless sha256sum check

---

cdc/model/codec/codec.go
cdc/model/codec/codec_test.go
cdc/model/sink.go
cdc/model/sink_gen.go
cdc/redo/reader/blackhole_reader.go
cdc/redo/reader/file.go
cdc/redo/reader/reader.go
cdc/redo/reader/reader_test.go
cdc/sink/ddlsink/factory/factory.go
cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
cdc/sink/ddlsink/mysql/mysql_ddl_sink_test.go
pkg/applier/main_test.go
pkg/applier/redo.go
pkg/applier/redo_test.go

Issue Number: close #8361
1. Support for applying ddl event in applier
2. Read and decode log events in background goroutines in logReader. 
3. [Add TableName field to RedoDDLEvent](https://github.com/pingcap/tiflow/pull/8362/files#diff-6d2f9b5931ca742dd70204701ec3baa8cce6350a61e29d55a0e85176b7618fcaR112).
- Unit test
```release-note
`support for applying ddl event in redo log`.
```

redo(ticdc): support for applying ddl event in applier

---

pkg/sink/kafka/v2/factory_test.go

Issue Number: ref #8241 
Add more ut for kafka sink v2, increase the coverage rate of factory.go from 20% to 37.1%
```release-note
`None`
```

ticdc(test): add more ut for kafka sink v2 

---

metrics/grafana/ticdc.json

Issue Number: ref #8255
- Use correct metric name `ticdc_sink_txn_queue_duration_count`
- Use different `refId` for different metric group, otherwise the metric panel will hang and show nothing.
Before this PR            |  After this PR
:-------------------------:|:-------------------------:
```release-note
None
```

metrics(ticdc): fix conflict detect metric template

---

cdc/owner/changefeed.go
cdc/scheduler/internal/v3/coordinator.go
cdc/scheduler/internal/v3/coordinator_test.go
cdc/scheduler/internal/v3/info_provider_test.go
cdc/scheduler/internal/v3/keyspan/mock.go
cdc/scheduler/internal/v3/keyspan/reconciler.go
cdc/scheduler/internal/v3/keyspan/reconciler_test.go
cdc/scheduler/internal/v3/keyspan/splitter_region_count.go
cdc/scheduler/internal/v3/keyspan/splitter_region_count_test.go
cdc/scheduler/rexport.go

Issue Number: ref #7720
Add splitter interface to support splitting span by region written keys in #8496
- Unit test
No.
No.
```release-note
None
```

scheduler(ticdc): add splitter interface

---

cdc/entry/mounter.go
cdc/entry/mounter_test.go

Issue Number: close #8490 
* For float32 types, fetch it from the`datum` by use the corresponding method.
- Unit test
```release-note
Fix float32 types precision lost
```

mounter(ticdc): mount float32 value correctly to avoid the precision lost.

---

metrics/grafana/ticdc.json

Issue Number: close https://github.com/pingcap/tiflow/issues/8524
move checkpoint ts and resolved ts p99 panels into lag analyze row.
- No code
No
No
```release-note
Move checkpoint ts and resolved ts p99 panels into lag analyze row
```

metrics(ticdc): move checkpoint ts and resolved ts p99 panels into lag analyze row

---

cdc/sink/ddlsink/mq/kafka_ddl_sink.go
cdc/sink/dmlsink/mq/kafka_dml_sink.go

Issue Number: close #8523 
* check admin client is not nil before close it.
```release-note
Fix cdc server panic when all Kafka servers are unavailable
```

kafka(ticdc): fix kafka sink panic when kill the downstream kafka 

---

cdc/api/owner/owner.go
cdc/api/status/status.go
cdc/api/v1/api.go
cdc/api/v1/api_test.go
cdc/api/v1/validator.go
cdc/api/v2/capture.go
cdc/api/v2/capture_test.go
cdc/api/v2/changefeed.go
cdc/api/v2/changefeed_test.go
cdc/api/v2/status.go
cdc/api/v2/status_test.go
cdc/api/v2/unsafe.go
cdc/api/v2/unsafe_test.go
cdc/capture/capture.go
cdc/capture/capture_test.go
cdc/capture/mock/capture_mock.go
cdc/server/server.go
pkg/etcd/etcd.go
pkg/etcd/mock/etcd_client_mock.go

Issue Number: close #8484
1. Allow access etcd client after a capture has been drained.
2. Do not return error in `campaignOwner` after a capture has been drained.
- Unit test
Run TiCDC cluster in a k8s cluster and rolling restart all TiCDC nodes.
No.
No.
```release-note
Fix an issue that TiCDC cluster can not graceful upgrade in k8s
```

capture(ticdc): fix graceful shutdown in k8s

---

pkg/sink/cloudstorage/path.go
pkg/sink/cloudstorage/path_test.go

Issue Number: ref #8189
1. Reuse index number in storage sink if the last file does not exists.
- Unit test
```release-note
`None`.
```

sink(ticdc): reuse index number in storage sink

---

cdc/processor/memquota/mem_quota.go
cdc/redo/reader/reader.go
errors.toml
go.mod
pkg/applier/redo.go
pkg/errors/cdc_errors.go
pkg/util/memory_checker.go

Issue Number: ref #8056
1. Limit [total memory usage](https://github.com/pingcap/tiflow/pull/8494/files#diff-a4f2a9712d65b01443a6b810b343317221039c2558b867f82d3d2c3c1fe18e0dR32) in reader.
2. Add memory quota in redo applier.
- Unit test
```release-note
`Fix the issue that redo apply may cause OOM`.
```

redo(ticdc): limit memory usage in applier

---

cdc/entry/schema_storage_test.go
cdc/model/sink.go

Issue Number: close #8548
- Unit test
```release-note
None
```

schema(ticdc): add unit test for handle key column

---

pkg/sink/codec/avro/avro.go
pkg/sink/codec/avro/avro_test.go
pkg/sink/codec/avro/avro_test_data.go

Issue Number: close #8490
* parse `mysql.TypeFloat` by using `float32`
- Unit test
```release-note
Fix avro float type precision by using float32 to parse the data correctly
```

codec(ticdc): avro decode float by using float32

---

cdc/redo/main_test.go
cdc/redo/meta_manager_test.go

Issue Number: ref #8056
1. Modify parameters before starting parallel tests
- Unit test
```release-note
`None`.
```

redo(ticdc): fix data race issue in meta manager tests

---

pkg/applier/redo.go

Issue Number: close #8591
1.  fix resolvedTs regression in applier's memory quota record
- Unit test
```release-note
`None`.
```

redo(ticdc): fix resolvedTs regression in applier's memory quota record

---

pkg/sink/mysql/config.go

Issue Number: close #8622
Turn off multi statement sql, we need to locate the large packet problem.
- Unit test
```release-note
None
```

sink(ticdc): turn off multi statement sql by default

---

dm/pkg/retry/errors.go
pkg/errorutil/util.go
pkg/errorutil/util_test.go

Issue Number: ref #8662 
Error `github.com/go-sql-driver/mysql.ErrInvalidConn`, it should be retryable.
- No code
```release-note
None
```

*(pkg): retry on invalid connection

---

dm/loader/lightning.go
dm/loader/lightning_test.go

This PR is a cherry-pick of https://github.com/pingcap/tiflow/pull/8671
---
Issue Number: close https://github.com/pingcap/tiflow/issues/8672
Modify lightnig's disk quota when we set DM's `disk-quota-physical` a non-negative value.
- Unit test
```release-note
None
```

DM: fix default physical import mode disk quota

---

engine/test/integration_tests/dm_lightning_checkpoint/run.sh

- do not check database because task may immediately finished
- Unit test
- No code
```release-note
```

engine(dm): fix unstable engine test dm_lightning_checkpoint

---

cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/manager_test.go
cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/processor/sinkmanager/table_sink_wrapper_test.go

Issue Number: close #8664 
```release-note
Fix a sorter panic issue caused by uint64 overflow.
```

sinkManager (ticdc): Fix a sorter panic issue caused by uint64 overflow.

---

docs/design/2023-03-15-ticdc-storage-sink.md

Issue Number: ref #6797
1. add design document for storage sink
- No code
```release-note
`None`.
```

doc(ticdc): add design document for storage sink

---

dm/syncer/dml.go
dm/tests/expression_filter/conf/dm-task2.yaml
dm/tests/expression_filter/data/db1.increment2.sql
dm/tests/expression_filter/data/db1.prepare2.sql
dm/tests/expression_filter/run.sh

Issue Number: ref #7028
MySQL's latin1 charset is not the usual "latin1" ISO8859_1 charset.
```release-note
None
```

syncer(dm): fix wrong MySQL latin1 decoder

---

cdc/sink/dmlsink/txn/mysql/mysql.go
cdc/sink/dmlsink/txn/mysql/mysql_test.go

Issue Number: close #8732
BatchDML should calculate `approximateSize`
- Unit test
```release-note
None
```

sink(ticdc): fix incorrect approximateSize in batch dml

---

cdc/model/sink.go
cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/table_sink_wrapper_test.go
cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink_test.go
cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink_test.go
cdc/sink/dmlsink/cloudstorage/defragmenter_test.go
cdc/sink/dmlsink/cloudstorage/dml_worker.go
cdc/sink/dmlsink/cloudstorage/dml_worker_test.go
cdc/sink/dmlsink/cloudstorage/encoding_worker_test.go
cdc/sink/dmlsink/event_appender.go
cdc/sink/dmlsink/event_appender_test.go
cdc/sink/dmlsink/factory/factory.go
cdc/sink/dmlsink/factory/factory_test.go
cdc/sink/tablesink/table_sink_impl.go
cdc/sink/tablesink/table_sink_impl_test.go
cmd/kafka-consumer/main.go
cmd/storage-consumer/main.go
pkg/applier/redo.go
pkg/sink/cloudstorage/path.go
pkg/sink/cloudstorage/path_test.go
pkg/sink/cloudstorage/table_definition.go
pkg/sink/cloudstorage/table_definition_test.go
tests/integration_tests/canal_json_storage_basic/run.sh
tests/integration_tests/csv_storage_basic/run.sh

Issue Number: close #8666
1. Set `TableInfoVersion` in [SingleTableTxn](https://github.com/pingcap/tiflow/pull/8751/files#diff-eb40c4235fa377719c71b4d416eb38d4f4134b281758dd43687ca525d0ca3549R669), which is [max{TableSinkStartTs, TableInfo.Version}](https://github.com/pingcap/tiflow/pull/8751/files#diff-021e72c7db585ee751d1c0c1985e4e552434699a2e2dcfa5afff9f86513a3225R121-R125).
2. Use correct `TableinfoVersion` in [TableDefinition](https://github.com/pingcap/tiflow/pull/8751/files#diff-ae808f9ebdd6f78efc57b1ee58e765b909c12be355cb2defffe7b44728ca6e44R198).
3. Use [loacl storage in integration test to facilitate debug](https://github.com/pingcap/tiflow/pull/8751/files#diff-0dac0ea75b05049ecd2a171ef67193c96891fc2677187257e06314dea92343d7R30).
- Unit test
- Manual test (add …

sink(ticdc): fix table version used in storage sink

---

cdc/processor/processor_test.go
cdc/processor/sinkmanager/manager.go

Issue Number: close #8802 
- Unit test
```release-note
Fix a bug that leads to changefeed stuck when sinkManager run fails.
```

processor, sink (ticdc): fix processor stuck since sinkmanager run fails

---

pkg/sqlmodel/causality.go
pkg/sqlmodel/row_change_test.go

Issue Number: close #8803
temporary skip considering the multi-value index in CausalityKeys. In future we should evaluate the generating expression to get the value of causality key.
- Unit test
```release-note
`None`.
```

sqlmodel: skip considering multi-value index in CausalityKeys

---

cdc/sinkv2/eventsink/factory/factory.go

Issue Number: close #8805
1. fix TxnEventAppender.startTs in CreateTableSink
- Unit test
```release-note
`None`.
```

sink(ticdc): fix TxnEventAppender.startTs in CreateTableSink

---

cdc/entry/mounter.go

Issue Number: close #8819 
* let the `verifyChecksum` return the checksum version.
```release-note
`None`
```

mounter(ticdc): adjust verify checksum method to get the checksum version

---

pkg/cmd/util/helper_test.go
pkg/config/replica_config.go
pkg/config/replica_config_test.go

Issue Number: close #8854 
* adjust replica config, e2e checksum functionality only works for the kafka sink changefeed.
- Unit test
```release-note
`None`
```

config(ticdc): integrity only works for kafka sink

---

pkg/sink/codec/avro/avro.go
pkg/sink/codec/common/config.go
pkg/sink/codec/common/config_test.go

Issue Number: close #8869
Originally, avro does not support encode DDL and checkpoint event, which means the downstream kafka consumer does not the DDL exsitance and data stream progress, this is incompatible with the current cdc kafka consumer.
* add a new config in the sink url, named `avro-enable-watermark`
* encoding DDL and checkpoint event so that can be sink to the kafka
- Unit test
```release-note
`None`
```

codec(ticdc): avro encode watermark event to be compatible with consumer

---

cdc/api/v2/changefeed_test.go
cdc/model/changefeed_test.go
cdc/owner/changefeed.go
cdc/owner/feed_state_manager.go
cdc/owner/feed_state_manager_test.go
cdc/owner/owner.go
cdc/owner/owner_test.go
errors.toml
pkg/errors/cdc_errors.go
pkg/errors/helper.go
pkg/errors/helper_test.go
pkg/txnutil/gc/gc_manager.go
pkg/txnutil/gc/gc_manager_test.go
tests/integration_tests/changefeed_fast_fail/run.sh
tests/integration_tests/changefeed_resume_with_checkpoint_ts/run.sh
tests/integration_tests/multi_tables_ddl/run.sh
tests/integration_tests/multi_tables_ddl_v2/run.sh

Issue Number: close #8403 
gc (ticdc): Instead of keeping restarting error changefeed in 24 hours, put the error changefeed into failed state and calculate the ticdc global gc safepoint based on checkpoint ts of all changefeeds and give users 24 hours grace period to handle the failed changefeed.
e.g.,
Have two ChangeFeeds,
cf1(failed) with checkpointTs ts1
cf2(normal) with checkpointTs ts2
the global gc safepoint will be:
min(ts2, max(ts1, currentPDTs - 24 hours))
After this pr being merged:
* Following errors will be set to fail directly:
```
ErrExpressionColumnNotFound,
ErrExpressionParseFailed,
ErrSchemaSnapshotNotFound,
ErrSyncRenameTableFailed,
ErrChangefeedUnretryable,
ErrGCTTLExceeded, 
ErrSnapshotLostByGC,
ErrStartTsBeforeGC,
```
* all other errors will be retried no more than 90 …

gc (ticdc): optimize the algorithm calculating gc safepoint 

---

cdc/capture/capture.go
cdc/capture/election.go
tests/integration_tests/availability/owner.sh

Issue Number: close #8877 #8868
1. deploy 1 tidb cluster with 3 pd and 2 cdc.
2.  create a changefeed 
3. kill pd leader 
4. no cdc processor exit abnormally 
```release-note
Fix processor exit unexpectedly when some pd node fail
```

capture (ticdc): fix processor exit unexpectedly when some pd node fail

---

cdc/api/v2/model.go
cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink_test.go
cdc/sink/dmlsink/cloudstorage/dml_worker_test.go
cmd/storage-consumer/main.go
docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
pkg/cmd/util/helper_test.go
pkg/config/sink.go
pkg/config/sink_test.go
pkg/sink/cloudstorage/config.go
pkg/sink/cloudstorage/config_test.go
pkg/sink/cloudstorage/path.go
pkg/sink/cloudstorage/path_key.go
pkg/sink/cloudstorage/path_key_test.go
pkg/sink/cloudstorage/path_test.go

Issue Number: close #8919
use 20 digits to generage index number in storage sink.
- Unit test
- No code
```release-note
`Fix a issue of that index number used by storage sink may overflow`.
```

sink(ticdc): add index config to storage sink

---

deployments/ticdc/docker/integration-test.Dockerfile

Issue Number: close https://github.com/pingcap/tiflow/issues/8758
Install wget and add cache.
No
No
```release-note
None
```

deployments(ticdc): install wget and add cache

---

cdc/entry/schema/snapshot.go
cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
tests/integration_tests/canal_json_storage_partition_table/data/prepare.sql
tests/integration_tests/csv_storage_partition_table/data/prepare.sql

Issue Number: close #8914
1. Store source tableInfo in ddl.PreTableInfo.
2. Write table def to source table directory.
- Unit test
```release-note
`None`.
```

schema, sink(ticdc): fix exchange partition

---

Makefile
cmd/kafka-consumer/main.go
cmd/storage-consumer/main.go
deployments/ticdc/docker/kafka-consumer.Dockerfile
deployments/ticdc/docker/storage-consumer.Dockerfile

Issue Number: ref #8973
log version in consumer
- Unit test
1. storage consumer
```shell
/usr/bin/docker
DOCKER_BUILDKIT=1 docker build -f ./deployments/ticdc/docker/storage-consumer.Dockerfile . -t ticdc:storage-consumer  --platform linux/amd64
[+] Building 64.8s (14/14) FINISHED                                                                    
=> [internal] load build definition from storage-consumer.Dockerfile                             0.0s
=> => transferring dockerfile: 49B                                                               0.0s
=> [internal] load .dockerignore                                                                 0.0s
=> => transferring context: 78B …
```

makefile, cmd(ticdc): log version in consumer

---

Makefile
cdc/model/owner.go
cdc/owner/changefeed.go
cdc/owner/ddl_manager.go
cdc/owner/ddl_manager_test.go
cdc/redo/manager.go
cdc/redo/meta_manager.go
tests/integration_tests/consistent_replicate_ddl/conf/diff_config.toml
tests/integration_tests/consistent_replicate_ddl/run.sh

Issue Number: close #8963
1. [Decouple globalResolvedTs and globalBarrierTs](https://github.com/pingcap/tiflow/pull/8964/files#diff-953746562776cf8aa41cd4a971df8c546649d2721ae787607aed2069f3b44eb0R381-R382).
2. [Add a redo ddl barrier to prevent resolvedTs from being advanced too early](https://github.com/pingcap/tiflow/pull/8964/files#diff-22d25e82af60f580f09cf3ace50f4c276f10b5e0d29beb6f4999598605bb39f4R457-R465).
- Unit test
- No code
```release-note
`Fix the isuue that resolvedTs may be advanced too early when redo enabled`.
```

owner, redo(ticdc): decouple globalResolvedTs and globalBarrierTs

---

cdc/api/v2/changefeed.go
cdc/api/v2/model.go
cdc/entry/mounter_group.go
cdc/model/changefeed.go
cdc/model/owner.go
cdc/model/owner_test.go
cdc/owner/changefeed.go
cdc/owner/ddl_sink.go
cdc/owner/feed_state_manager.go
cdc/processor/processor.go
cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/redo_log_advancer_test.go
cdc/processor/sourcemanager/manager.go
cdc/puller/ddl_puller.go
cdc/redo/manager.go
cdc/redo/meta_manager.go
cdc/sink/dmlsink/txn/mysql/mysql.go
pkg/util/runnable.go
pkg/util/time.go
tests/integration_tests/_utils/check_changefeed_status
tests/integration_tests/changefeed_error/run.sh
tests/integration_tests/kafka_sink_error_resume/run.sh

Issue Number: ref #8657 
Report model internal warnings to users by `api/v2/changefeeds/{ID}/status`.
example of `api/v2/changefeeds/{ID}/status`:
```
{"state":"normal","resolved_ts":441531555227631620,"checkpoint_ts":441531531923030068,"last_warning":{"time":"2023-05-17T15:40:12.504878333+08:00","addr":"10.2.7.2:8300","code":"CDC:ErrMySQLConnectionError","message":"[CDC:ErrMySQLConnectionError]fail to open MySQL connection: dial tcp 10.2.6.117:4000: connect: connection refused"}}
```
```release-note
None
```

(processor/cdc): report module internal warnings

---

cdc/processor/sourcemanager/engine/pebble/db.go
pkg/config/config_test_data.go
pkg/config/server_config.go
pkg/config/sorter.go

Issue Number: close #8974
Disable SortEngine pebble block-cache by default.
- Unit test
```release-note
None
```

(sorter/cdc): disable block cache by default

---

cdc/api/v2/model_test.go
cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink_test.go
cdc/sink/dmlsink/cloudstorage/dml_worker_test.go
pkg/cmd/util/helper_test.go
pkg/config/replica_config.go
pkg/sink/cloudstorage/config_test.go
pkg/sink/cloudstorage/path_test.go
tests/integration_tests/api_v2/cases.go

Issue Number: close #8997 
cherry pick of #8998 
- Unit test
- No code
```release-note
`Set default value of DateSeparator to day`.
```

sink(ticdc): set default value of DateSeparator to day(#8998)

---

cdc/processor/processor.go
cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/manager_test.go
cdc/processor/sinkmanager/redo_log_worker.go
cdc/processor/sinkmanager/table_sink_advancer.go
cdc/processor/sinkmanager/table_sink_worker.go
cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
cdc/sink/dmlsink/event_sink.go
cdc/sink/dmlsink/factory/factory.go
cdc/sink/dmlsink/mq/mq_dml_sink.go
cdc/sink/dmlsink/mq/mq_dml_sink_test.go
cdc/sink/dmlsink/txn/txn_dml_sink.go
cdc/sink/tablesink/progress_tracker.go
cdc/sink/tablesink/table_sink.go
cdc/sink/tablesink/table_sink_impl.go
pkg/config/config_test_data.go
pkg/config/server_config.go
tests/integration_tests/sink_hang/run.sh

Issue Number: ref #8657 
Issue Number: close #9008 
Fix some bugs introduced by #8949 .
- Unit test
```release-note
None
```

(sink/cdc): fix some bugs introduced by #8949

---

cdc/api/v2/model.go
cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
cdc/sink/ddlsink/mq/kafka_ddl_sink.go
cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer_test.go
cdc/sink/dmlsink/mq/kafka_dml_sink.go
docs/design/2023-03-15-ticdc-storage-sink.md
docs/package-lock.json
docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml
go.mod
pkg/config/sink.go
pkg/security/sasl.go
pkg/sink/kafka/factory.go
pkg/sink/kafka/mock_factory.go
pkg/sink/kafka/oauth2_token_provider.go
pkg/sink/kafka/oauth2_token_provider_test.go
pkg/sink/kafka/options.go
pkg/sink/kafka/options_test.go
pkg/sink/kafka/sarama.go
pkg/sink/kafka/sarama_factory.go
pkg/sink/kafka/sarama_factory_test.go
pkg/sink/kafka/sarama_test.go
pkg/sink/kafka/v2/factory.go
pkg/sink/kafka/v2/factory_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/8865
add oauth support for sarama Kafka sink. 
Added:
- SASLOAuthClientID  (required)
- SASLOAuthClientSecret  (required)
- SASLOAuthTokenURL (required)
- SASLOAuthScopes 
- SASLOAuthGrantType (default: client_credentials)
- [Manual test](https://github.com/pingcap/tiflow/pull/8938#issuecomment-1556648439)
No
No
```release-note
Add OAuth support for Sarama Kafka sink
```

pkg/sink(ticdc): add oauth support for sarama Kafka sink

---

cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer.go
pkg/sink/kafka/factory.go
pkg/sink/kafka/metrics_collector.go
pkg/sink/kafka/v2/metrics_collector.go

Issue Number: close #9041 
* add a context to the kafka dml producer to control close the underline metrics collector and the producer running goroutine
```release-note
`None`
```

kafka(ticdc): use context to close the mq dml sink and the metrics collector

---

cdc/entry/mounter.go
cdc/entry/mounter_test.go
pkg/sink/cloudstorage/table_definition.go
pkg/sink/cloudstorage/table_definition_test.go

Issue Number: close #9066
add table default value definition for storage sink
- Unit test
need to update user documentation
```release-note
`Add table default value definition for storage sink`.
```

sink(ticdc): add table default value definition for storage sink

---

cdc/processor/memquota/mem_quota.go
cdc/processor/memquota/mem_quota_test.go
cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/redo_log_advancer_test.go
cdc/processor/sinkmanager/redo_log_worker_test.go
cdc/processor/sinkmanager/table_sink_advancer_test.go
cdc/processor/sinkmanager/table_sink_worker_test.go

Issue Number: close #9073
Issue Number: close #9067 
In `SinkManager.Run` or `SinkManager.Close`, we wait a `WaitGroup`, which is associated to sink workers and redo workers.
But sink workers and redo workers can be blocked on `MemQuota.BlockAcquire`, so the wait can't be finished forever.
- Unit test
```release-note
None
```

sink(cdc): close MemoryQuota to stop SinkManager correctly

---

pkg/sink/codec/avro/avro.go
pkg/sink/codec/avro/decoder.go
pkg/sink/codec/avro/decoder_test.go

Issue Number: close #9069 
* encode DDL event simply to prevent send too much to the kafka.
* fix avro decoder verify empty checksum
* set columns correctly for the update event
```release-note
`None`
```

codec(ticdc): fix avro decode update event incorrectly and do not verify empty checksum

---

cdc/processor/memquota/mem_quota.go
cdc/processor/memquota/mem_quota_test.go
cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/table_sink_worker.go

Issue Number: close #9092
The bug is introduced by #8949 . When restarting a table sink without re-build the processor, mem quota isn't cleared correctly.
- Unit test
- No code
```release-note
None
```

sink(cdc): clear memquota when restart a table sink

---

cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
cdc/sink/dmlsink/cloudstorage/dml_worker.go

Issue Number: close #8894
- remove buffer pool in storage sink worker
- performance test: up to 100k rows pwe seconds when replcation 16 tables.
- Unit test
- Integration testi
```release-note
`None`.
```

sink(ticdc): remove buffer pool in storage sink worker

---

cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/manager_test.go
cdc/processor/sinkmanager/redo_log_worker_test.go
cdc/processor/sinkmanager/table_sink_worker_test.go
cdc/processor/sourcemanager/engine/engine.go
cdc/processor/sourcemanager/engine/memory/event_sorter.go
cdc/processor/sourcemanager/engine/memory/event_sorter_test.go
cdc/processor/sourcemanager/engine/mock/engine_mock.go
cdc/processor/sourcemanager/engine/pebble/event_sorter.go
cdc/processor/sourcemanager/engine/pebble/event_sorter_test.go
cdc/processor/sourcemanager/manager.go
cdc/scheduler/internal/v3/agent/agent.go
cdc/scheduler/internal/v3/agent/agent_test.go
cdc/scheduler/internal/v3/replication/replication_set.go
errors.toml
pkg/errors/cdc_errors.go

Issue Number: ref #9125
1. [replace some panic with error](https://github.com/pingcap/tiflow/pull/9123/files#diff-611c458bf74f42ab3d7a19a921d8fa0bc9b6ee4839c4ba8e1fd84d675a1a351eL935-R942)
2. [record startTs in sorter engine](https://github.com/pingcap/tiflow/pull/9123/files#diff-f86f3d17eb7fd26e62cbecdf61468b41d39bc825d0f155aa261161fca24fc1b6R30)
- Unit test
- No code
```release-note
```

scheduler, processor(ticdc): replace some panic with error

---

cmd/kafka-consumer/main.go
pkg/sink/codec/avro/avro.go
pkg/sink/codec/avro/avro_test.go
pkg/sink/codec/avro/decoder.go
pkg/sink/codec/avro/decoder_test.go
pkg/sink/codec/common/config.go

Issue Number: close #9137 
* avro use codec `common.Config`, and remove `Options`
- Unit test
```release-note
`None`
```

codec(ticdc): refactor avro encoder to use code config directly to avoid duplicate option

---

cdc/owner/changefeed.go
cdc/owner/changefeed_test.go
cdc/owner/ddl_manager.go
cdc/owner/owner_test.go
cdc/processor/processor.go
cdc/scheduler/internal/scheduler.go
cdc/scheduler/internal/v3/coordinator.go
cdc/scheduler/internal/v3/coordinator_test.go
cdc/scheduler/internal/v3/info_provider_test.go
cdc/scheduler/internal/v3/replication/replication_manager.go
cdc/scheduler/internal/v3/replication/replication_manager_test.go
cdc/scheduler/rexport.go
cdc/scheduler/schedulepb/barrier.go
tests/integration_tests/consistent_replicate_ddl/run.sh

Issue Number: ref #9058
- Unit test
```release-note
None
```

chngefeed (ticdc): move resolvedTs into globalBarrierTs when redo log is enabled.

---

cdc/owner/changefeed.go
cdc/processor/processor.go

Issue Number: close #9173 #9177 
Delete the status metric of a changefeed when it is removed.
```release-note
None
```

changefeed (ticdc): remove status of a changefeed after it is removed

---

cdc/owner/ddl_manager.go

Issue Number: close #8828 
- No code
```release-note
None
```

ddlManager (ticdc): only log once when executing a ddl

---

cdc/sink/dmlsink/txn/mysql/mysql.go
cdc/sink/dmlsink/txn/mysql/mysql_test.go
pkg/applier/redo_test.go
pkg/sink/mysql/config.go

Issue Number: close #9180 
```release-note
None
```

mysql (ticdc): only set write source when downstream is supported

---

cdc/api/v1/api_test.go
cdc/api/v2/api_helpers_test.go
cdc/api/v2/api_test.go
cdc/api/v2/changefeed_test.go
cdc/model/changefeed.go
cdc/model/owner.go
cdc/model/owner_test.go
cdc/owner/changefeed.go
cdc/owner/changefeed_test.go
cdc/owner/feed_state_manager.go
cdc/owner/mock/status_provider_mock.go
cdc/owner/owner.go
cdc/owner/status_provider.go
cdc/processor/processor_test.go
pkg/etcd/etcd_test.go
pkg/migrate/migrate_test.go
pkg/orchestrator/reactor_state_test.go

Issue Number: ref #9058, ref #9235
- Unit test
```release-note
None
```

changefeed (ticdc): remove resolvedTs from etcd

---

.github/workflows/check_and_build.yaml
.github/workflows/ticdc_integration.yaml

Ref:
- PingCAP-QE/ci#2129
update check and build and cdc integration test github workflows: skip triggering when only changes to markdown files or `OWNERS` files.
- No code
No
No
```release-note
None
```

ci: skip some CI builds when only changed to documents and OWNERS files

---

metrics/alertmanager/ticdc.rules.yml

Issue Number: ref #9266 
```release-note
None
```

metrics (ticdc): add changefeed status alert rules

---

cdc/entry/mounter.go
cdc/entry/mounter_test.go
pkg/sink/codec/avro/avro.go

Issue Number: close #9259 
* mounter set the default value for the enum type explicitly, to make `enum.Value` set correctly.
- Unit test
```release-note
`None`
```

mounter(ticdc): enum type default value set explicitly to avoid wrong enum value fetched by the encoder

---

pkg/sink/kafka/metrics_collector.go

Issue Number: close https://github.com/pingcap/tiflow/issues/8959
Update/Get Kafka cluster every 30min.
No
No
```release-note
Only get Kafka cluster metadata every 30 minutes
```

pkg/sink(ticdc): Update Kafka cluster every 30min

---

errors.toml
pkg/errors/cdc_errors.go
pkg/errors/helper.go
pkg/txnutil/gc/gc_manager.go
pkg/txnutil/gc/gc_manager_test.go

Issue Number: close #9303 
Issue Number: close #9243 
If the service responsible for blocking the garbage collection process, make sure to verify if the checkpoint timestamp of the changefeed has surpassed the time-to-live (TTL) for garbage collection when ticking.
- No code
NA
NA
```release-note
A changefeed will fail if it is the service block the gc of the update stream TiDB and has surpassed the gc-ttl.
```

cdc: fail the changefeed blocking global gc and suppressing the gc-ttl

---

cdc/processor/manager_test.go
cdc/processor/processor.go
cdc/processor/processor_test.go
cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/manager_test_helper.go
cdc/redo/manager.go
cdc/redo/meta_manager.go
cdc/scheduler/internal/table_executor.go
cdc/scheduler/internal/v3/agent/agent.go
cdc/scheduler/internal/v3/agent/agent_test.go
cdc/scheduler/internal/v3/agent/table.go

Issue Number: close https://github.com/pingcap/tiflow/issues/9172
set flushed resolvedTs when start table 
- Unit test
- No code
```release-note
```

redo, processor(ticdc): set flushed resolvedTs when start table

---

cdc/processor/sinkmanager/table_sink_worker.go
cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/sink/tablesink/table_sink_impl_test.go

Issue Number: ref #9309 .
When closing a table sink, use `read lock` instead of `write lock`.
This can avoid etcd tick hang.
- Unit test
```release-note
None
```

sink(cdc): reduce lock when closing table sinks

---

.codecov.yml
Makefile

Codecov's `Flags` should be better be used to split test types and the `components` feature better for components management.
The comonent management is a new feature in codecov, currently we used it in codecov page of `pingcap/tidb`. 
Ref:
- https://docs.codecov.com/docs/flags
- https://docs.codecov.com/docs/components
- PingCAP-QE/ci#2171
- migrate flag mangement to Automatic Flag Management: only only with the components flags, also we need to support unit and integration and other test type's covrage data.
- add component management configuration, it no need to set when upload coverage, it will auto display in codecov.io page.
- No code
```release-note
None
```

ci: add component management to `.codecov.yaml` and migrate flag manage

---

cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/manager_test.go

Issue Number: close #9272 
Limit `sinkManager` retry on `SinkInternal` error at most 30 minutes. 
- Unit test
```release-note
None
```

sink (ticdc): add retry backoff and limit for sinkManager

---

cdc/entry/mounter_test.go
cmd/kafka-consumer/main.go
cmd/storage-consumer/main.go
pkg/sink/codec/avro/decoder.go
pkg/sink/codec/avro/decoder_test.go
pkg/sink/codec/builder/codec_test.go
pkg/sink/codec/canal/canal_json_decoder.go
pkg/sink/codec/canal/canal_json_decoder_test.go
pkg/sink/codec/craft/craft_decoder.go
pkg/sink/codec/craft/craft_encoder_test.go
pkg/sink/codec/csv/csv_decoder.go
pkg/sink/codec/csv/csv_decoder_test.go
pkg/sink/codec/decoder.go
pkg/sink/codec/internal/batch_tester.go
pkg/sink/codec/open/open_protocol_decoder.go
pkg/sink/codec/open/open_protocol_decoder_test.go
pkg/sink/codec/open/open_protocol_encoder_test.go

Issue Number: close #9332 
#9187 add the `onlyHandleKey` to the decoder's `NextRowChangedEvent` method, this PR revert it, since:
* It makes the caller's logic complicated
* we also support `claim-check`, it's unnecessary to expose such to the outside of the decoder
I'd like to wrap all details in the decoder itself, to make caller easier.
- Unit test
```release-note
`None`
```

codec(ticdc): remove 2nd parameter from the decoder interface.

---

cdc/sink/ddlsink/mq/ddlproducer/ddl_producer.go
cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_mock_producer.go
cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer_test.go
cdc/sink/ddlsink/mq/kafka_ddl_sink.go
cdc/sink/ddlsink/mq/mq_ddl_sink_test.go
cdc/sink/dmlsink/factory/factory_test.go
cdc/sink/dmlsink/mq/dmlproducer/dml_producer.go
cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_mock_producer.go
cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer.go
cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer_test.go
cdc/sink/dmlsink/mq/kafka_dml_sink.go
cdc/sink/dmlsink/mq/mq_dml_sink_test.go
cdc/sink/dmlsink/mq/worker_test.go
pkg/sink/kafka/mock_factory.go

Issue Number: close #8493 
- Unit test
- No code
```release-note
`None`
```

kafka(ticdc): use sarama mock producer in the unit test to workaround the data race

---

pkg/p2p/server.go

Issue Number: close #9354
fix panic issue when peer is not found
- Unit test
- No code
```release-note
`None`.
```

p2p(ticdc): fix panic issue when peer is not found

---

cdc/processor/sinkmanager/manager.go

Issue Number: ref #9370, ref #9226
No need to close table sink when closing sinkManager since the backend dmlSink will be closed.
- Unit test
- No code
```release-note
```

sink, processor(ticdc): do not close table sink when closing sinkManager

---

cdc/api/v2/changefeed_test.go
cdc/api/v2/model.go
cdc/api/v2/model_test.go
cdc/api/v2/processor.go
cdc/api/v2/processor_test.go
cdc/model/changefeed.go
cdc/model/changefeed_test.go
cdc/model/errors.go
cdc/model/http_model_test.go
cdc/owner/changefeed.go
cdc/owner/feed_state_manager.go
cdc/owner/feed_state_manager_test.go
cdc/owner/owner.go
pkg/cmd/cli/cli_changefeed_list_test.go
pkg/migrate/migrate_test.go
tests/integration_tests/changefeed_error/run.sh

Issue Number: ref #9273
After this PR, the error status of changefeed will be removed, and the warning status will be added.
The changefeed status transition is shown in the following figure.
1. The user pauses changefeed, and changefeed enters the `stopped` state.
2. The user resumes changefeed, and changefeed returns to the `normal` state.
3. Changefeed encounters an error and enters the `warning` state. Changefeed automatically retries in the `warning` state.
4. If the changefeed retry is successful and the `CheckpointTs` advances beyond the `CheckpointTs` when the error occurred, the changefeed enters the `normal` state.
5. If the changefeed error retry exceeds the maximum retry time limit, it enters the `failed` state. After entering the `failed` state, the changefeed will block the …

changefeed (ticdc): remove error state and add pending, warning state

---

cdc/owner/ddl_sink.go
cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/manager_test.go
pkg/filter/filter_test.go
pkg/retry/error_retry.go
pkg/retry/error_retry_test.go

Issue Number: ref #9272 
- Unit test
```release-note
None
```

sink (ticdc): Add retry limit for ddl sink

---

cdc/owner/feed_state_manager.go
cdc/owner/feed_state_manager_test.go
pkg/txnutil/gc/gc_manager.go

Issue Number: ref #5647 close #8382 close #9388
- Unit test
```release-note
None
```

changefeed (ticdc): don't set changefeed to failed state when error retry reach limit

---

cdc/capture/capture.go
cdc/capture/election.go
cdc/owner/owner.go
pkg/orchestrator/etcd_worker.go

Issue Number: close #9344
1. Do not resign owner when ErrNotOwner is encountered
2. Close processorManager as soon as possible
- Unit test
```release-note
`None`.
```

owner(ticdc): do not resign owner when ErrNotOwner is encountered

---

cdc/api/middleware/middleware.go
cdc/api/util.go
cdc/api/v2/api.go
cdc/api/v2/api_test.go
cdc/api/v2/changefeed_test.go
cdc/api/v2/processor_test.go
cdc/controller/controller.go
cdc/controller/mock/controller_mock.go
cdc/controller/query.go

Issue Number: close #9411
forward changefeed related api to changefeed owner capture
- Unit test
- No code
```release-note
`None`.
```

api(ticdc): forward changefeed related api to changefeed owner capture

---

tests/integration_tests/_utils/start_tidb_cluster_impl

Issue Number: close https://github.com/pingcap/tiflow/issues/9425
Reduce the total block-cache size of TiFlash proxy from 19GB to 4GB
- Unit test
- No code
```release-note
None
```

Fix tiflash block-cache size && remove useless config

---

dm/loader/lightning.go
dm/loader/lightning_test.go
dm/loader/metrics.go

Issue Number: close #9359
- register loader metric on engine, and remove useless metrics
start a job, see we can see metric of loader error
```
dm_loader_exit_with_error_count{job_id="1110282",project_id="73876",resumable_err="false",source_id="source-1290068",task="1110282",tenant="30073",worker_id="xxxx"} 6
dm_worker_task_state{job_id="1110282",project_id="73876",source_id="source-1290068",task="1110282",tenant="30073"} 15
```
- No code
```release-note
`None`.
```

engine: register loader metric

---

cdc/capture/capture.go
cdc/controller/controller_test.go
cdc/owner/owner_test.go
cdc/processor/manager_test.go
pkg/orchestrator/etcd_worker.go
pkg/orchestrator/etcd_worker_bank_test.go
pkg/orchestrator/etcd_worker_test.go
pkg/orchestrator/interfaces.go
pkg/orchestrator/reactor_state.go
pkg/orchestrator/reactor_state_test.go

Issue Number: ref #9344
1.  Wait `CaptureSessionTTL/2` seconds before removing a capture from GlobalReactorState.
- Unit test
- No code
```release-note
`Fix a bug that could result in double writes after a CDC node disconnects from etcd.`.
```

pkg/orchestrator(ticdc): add timeout before remove capture

---

pkg/sink/codec/common/config.go
pkg/sink/codec/common/config_test.go

Issue Number: close #9478 
* disallow changefeed enable `force-replicate` when using `delete-only-output-handle-key-columns`
* disallow changefeed enable `force-replicate` when using handle-key-only
* disallow changefeed enable `force-replicate` when using avro protocol.
- Unit test
```release-note
`None`
```

config(ticdc): handle key only not allow force-replicate

---

cdc/puller/ddl_puller.go
cdc/puller/ddl_puller_test.go

Issue Number: close #9476
- Unit test
- No code
```release-note
```

puller(ticdc): fix renameTables ddl job

---

pkg/sqlmodel/causality.go
pkg/sqlmodel/causality_test.go
pkg/sqlmodel/row_change_test.go

Issue Number: close #9489 
convert the key to lower case could detect case insensitive conflict, it may introduce fake conflict when the collation is case sensitive, but it won't affect the correctness of dm, because it only introduces a sync point
generate load with conflicting key of the schema mentioned in the issue, before the change the replication could be broken within tens of minutes, after the change, it has been running for over 10 hours without issue
- No code
```release-note
```

sqlmodel(dm): generate key in lower case

---

cdc/entry/schema/snapshot.go
cdc/puller/ddl_puller.go
cdc/puller/ddl_puller_test.go

Issue Number: ref #9488 
This PR make rename table ddl like: `rename table test.t1 to ignore.t1` can be replicated. (The schema name `ignore` means it does not match the changefeed filter rule.)
- Unit test
```release-note
None
```

ddlPuller (ticdc): fix rename table ddl

---

cdc/entry/mounter.go
cdc/model/sink.go
cdc/model/sink_gen.go
cdc/sink/dmlsink/txn/event.go
cdc/sink/dmlsink/txn/event_test.go
cdc/sink/dmlsink/txn/txn_dml_sink_test.go

Issue Number: close #9533 
- Unit test
- No code
```release-note
`None`
```

mysql(ticdc): consider collation when build the causality key

---

dm/pkg/retry/errors.go
dm/pkg/retry/strategy.go
dm/syncer/data_validator.go
dm/syncer/data_validator_test.go
dm/syncer/validate_worker.go
dm/syncer/validate_worker_test.go
dm/syncer/validator_checkpoint.go
dm/syncer/validator_checkpoint_test.go
dm/unit/unit.go
dm/unit/unit_test.go

Issue Number: close #9257
- fix deadlock between error-process-routine and worker routine when err channel is full
- remove object lock when `fillResult`
- enhance retry by reusing the resumable errors in syncer
- No code
```release-note
dm: fix validator deadlock and enhance retry
```

dm: fix validator deadlock and enhance retry

---

cdc/sink/dmlsink/mq/kafka_dml_sink.go
cdc/sink/dmlsink/mq/mq_dml_sink.go
cdc/sink/dmlsink/mq/worker.go
cdc/sink/metrics/mq/metrics.go
pkg/sink/codec/canal/canal_json_decoder.go
pkg/sink/codec/canal/canal_json_row_event_encoder.go
pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
pkg/sink/codec/canal/canal_json_txn_event_encoder.go
pkg/sink/codec/common/message.go
pkg/sink/codec/open/open_protocol_decoder.go
pkg/sink/codec/open/open_protocol_encoder.go
pkg/sink/codec/open/open_protocol_encoder_test.go
pkg/sink/kafka/claimcheck/claim_check.go
pkg/sink/kafka/claimcheck/metrics.go

Issue Number: close #9528, close #9529
* use `uuid` to generate object key for claim check large message
* add e2e unit test to cover claim-check functionality for both open-protocol and canal-json
- Unit test
```release-note
`None`
```

kafka(ticdc): add unit test to cover claim-check functionality and use uuid to generate object key

---

cdc/capture/capture.go
cdc/capture/election.go
cdc/owner/owner.go
cdc/owner/owner_test.go
cdc/processor/manager.go
cdc/processor/manager_test.go
cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/table_sink_worker.go
cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/processor/sinkmanager/table_sink_wrapper_test.go
cdc/sinkv2/tablesink/table_sink_impl.go
cdc/sinkv2/tablesink/table_sink_impl_test.go
errors.toml
pkg/errors/cdc_errors.go
pkg/errors/helper.go
pkg/orchestrator/etcd_worker.go
pkg/orchestrator/etcd_worker_bank_test.go
pkg/orchestrator/etcd_worker_test.go
pkg/orchestrator/interfaces.go
pkg/orchestrator/reactor_state.go
pkg/orchestrator/reactor_state_test.go
pkg/p2p/server.go
pkg/txnutil/gc/gc_manager.go
pkg/txnutil/gc/gc_manager_test.go

Issue Number: ref #9535, #9344, #9450
- Unit test
- No code
```release-note
```

owner, sink(ticdc): cherry-pick memory quota, gc and failover related fix

---

cdc/kv/client.go
cdc/kv/region_worker.go
cdc/kv/region_worker_test.go

Issue Number: close #9520
1. reafactor some codes
2. wait worker exit before evictAllRegions in `eventFeedSession.receiveFromStream`
- Unit test
- No code
```release-note
`Fix the issue that caused panic when rebuilding grpc connections to tikv`.
```

kv-client(ticdc): fix panic when close receiveFromStream

---

cdc/processor/sinkmanager/manager.go
pkg/config/replica_config.go
pkg/config/sink.go

Issue Number: close #9561
always check nil value of advanceTimeoutInSec
- Unit test
- No code
```release-note
```

sink(ticdc): always check nil pointer of advanceTimeoutInSec

---

cdc/entry/mounter.go
cdc/model/errors.go
cdc/model/errors_test.go
cdc/owner/ddl_sink.go
cdc/owner/feed_state_manager.go
cdc/processor/sinkmanager/manager.go
cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
pkg/errors/helper.go
pkg/errors/helper_test.go
pkg/filter/expr_filter.go

Issue Number: close #9582 .
DDL sink errors shouldn't be treated as unretryable.
```release-note
None
```

sink(cdc): ddl sink errors shouldn't fail changefeed quickly

---

cdc/kv/client.go
cdc/kv/region_worker.go

Issue Number: close #9595
- Unit test
- No code
```release-note
```

kv-client(ticdc): evictAllRegions after close receiveEvents goroutine

---

cdc/sinkv2/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
cdc/sinkv2/ddlsink/cloudstorage/cloud_storage_ddl_sink_test.go

Issue Number: ref #9602
Write checkpointTs every two seconds in storage sink
- Unit test
- No code
```release-note
`Fix the issue of gcs write limit caused by frequent metadata updates in the storage sink`.
```

sink(ticdc): add limit to storage ddl sink

---

dm/syncer/syncer.go
dm/syncer/syncer_test.go
dm/worker/subtask.go

Issue Number: close #9605
- reset recorded ts on syncer restart
- test using  steps in the issue, before the change, lag keeps growing, became 0 after this pr
```
before 
➜  dm curl -s "127.0.0.1:8361/metrics" | grep -v '#'| grep dm_syncer_replication_lag_gauge
dm_syncer_replication_lag_gauge{source_id="mysql-3307",task="test",worker="worker-1"} 303
➜  dm curl -s "127.0.0.1:8361/metrics" | grep -v '#'| grep dm_syncer_replication_lag_gauge
dm_syncer_replication_lag_gauge{source_id="mysql-3307",task="test",worker="worker-1"} 313
after
➜  dm curl -s "127.0.0.1:8361/metrics" | grep -v '#'| grep dm_syncer_replication_lag_gauge
dm_syncer_replication_lag_gauge{source_id="mysql-3307",task="test",worker="worker-1"} 0
➜  dm curl -s "127.0.0.1:8361/metrics" | grep -v '#'| grep …
```

dm: fix lag keeps growing when failed ddl is skipped and no following ddl

---

cdc/owner/feed_state_manager.go
cdc/owner/feed_state_manager_test.go
tests/integration_tests/changefeed_error/run.sh
tests/integration_tests/kafka_sink_error_resume/run.sh

Issue Number: close #9594 
Ensure that the changefeed remains in the warning state if it encounter an warning and its checkpoint does not proceed. This will allow the list changefeed API to display the error message for a warning changefeed.
- unit test
```release-note
make changefeed list show warning message report by sinkManager
```

changefeed (ticdc): make changefeed list show warning message report by sinkmanager

---

cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/processor/sinkmanager/table_sink_wrapper_test.go

Issue Number: close #9592
Before this pr, [asyncCloseAndClearTableSink always returns true](https://github.com/pingcap/tiflow/pull/9618/files#diff-f1a821fc6bccdd087045289477de1ba938f0174afc2fed865a66d5264548abd7L334), no matter whether the underlying table sink successfully closed. During two-phase scheduling, this error can cause the new node's table sink to write data downstream before the old node's table sink actually exits. And this problem is more likely to be repeated in batch write scenarios (such as storage sink).
- Unit test
- No code
```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a …
```

sink(ticdc): fix data loss

---

cdc/sink/codec/common/config_test.go
pkg/config/sink.go

Issue Number: close #9669
check if the LargeMessageHandleConfig is nil first
- Unit test
- No code
```release-note
`None`.
```

kafka(ticdc):  fix panic issue when sasl enabled by config file

---

dm/syncer/syncer.go

Issue Number: close #9587 
- apply online ddl before track ddl
we track the original ddl when use binlog skip feature, if user skip the RENAME TABLE statement for an online DDL, they indeed want to skip the real ALTER TABLE statement, then we track the wrong statement.
- manually test
```
run a online ddl which make tidb failed
binlog skip -b binlog-pos(the pos of RENAME TABLE statement)
operate-schema get
```
table should have right schema
```release-note
```

dm: track table schema for online ddl when use binlog skip

---

cdc/processor/sinkmanager/redo_log_worker.go
cdc/processor/sinkmanager/redo_log_worker_test.go
cdc/processor/sinkmanager/table_sink_worker.go
cdc/processor/sinkmanager/table_sink_worker_test.go

Issue Number: close #9685 .
Call `defer func() { handleSpecialSinkInternalErrors() }` before `fetchFromCache`.
- Unit test
```release-note
None
```

sink(cdc): fix "dead dmlSink" error in sink workers

---

dm/syncer/opt_sharding_group.go
dm/syncer/opt_sharding_group_test.go
dm/syncer/syncer.go

Issue Number: close https://github.com/pingcap/tiflow/issues/9588
- reset optimistic sharding group keeper when syncer resume
when syncer resume, the remain sharding group keeper infos will block replication if we not reset it
- Unit test
```release-note
```

dm: reset optimistic sharding group keeper when syncer resume

---

cdc/api/v2/model_test.go
cdc/model/sink.go
cdc/model/sink_test.go
cdc/processor/sinkmanager/redo_log_worker.go
cdc/processor/sinkmanager/table_sink_worker.go
cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/processor/sinkmanager/table_sink_wrapper_test.go
cdc/sink/ddlsink/factory/factory.go
cdc/sink/dmlsink/blackhole/black_hole_dml_sink.go
cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
cdc/sink/dmlsink/event.go
cdc/sink/dmlsink/event_sink.go
cdc/sink/dmlsink/factory/factory.go
cdc/sink/dmlsink/mq/dispatcher/partition/index_value.go
cdc/sink/dmlsink/mq/kafka_dml_sink.go
cdc/sink/dmlsink/mq/mq_dml_sink.go
cdc/sink/dmlsink/mq/pulsar_dml_sink.go
cdc/sink/dmlsink/txn/txn_dml_sink.go
cdc/sink/tablesink/table_sink_impl.go
cdc/sink/tablesink/table_sink_impl_test.go
pkg/cmd/util/helper_test.go
pkg/config/config_test_data.go
pkg/config/replica_config.go
pkg/config/sink.go
pkg/sink/codec/encoder_group.go
pkg/sink/sink_type.go

Issue Number: close #9689
- Unit test
```release-note
`None`
```

sink(ticdc): split the updat events all at once

---

cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/manager_test.go
cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/sink/dmlsink/factory/factory.go
tests/integration_tests/hang_sink_suicide/run.sh

Issue Number: close #9736 .
Issue Number: close #9695 .
Other sink categories like `Txn` or `CloudStorage` can handles table sink progress callbacks good enough: callbacks won't be lost forever if sink factory fails internally. Otherwise an error will be reported instead, which can cause sink factory re-established correctly.
We only have met the callback lose issue for MQ sinks, so only check sink stuck for MQ sink is enough.
- Unit test
```release-note
None
```

sink(cdc): only check sink stuck for MQ sinks

---

cdc/sink/dmlsink/mq/kafka_dml_sink.go
pkg/sink/kafka/claimcheck/claim_check.go

Issue Number: close #9737 
* set the external storage timeout to 5m
```release-note
`None`
```

kafka(ticdc): claim check set the timeout default to 5m to prevent stuck too long if the external storage is unavailable.

---

cdc/server/server.go
pkg/cmd/server/server.go

Issue Number: close #9745
check if the capture is nil or not when Drain capture
- Unit test
- No code
```release-note
`None`.
```

server(ticdc): fix panic issue if capture is not initialized

---

cdc/api/v2/api_helpers_test.go
cdc/api/v2/changefeed.go
cdc/api/v2/changefeed_test.go

Issue Number: close #9584 
```release-note
Fix a bug that may cause TiCDC OpenAPI fails when PD scale-in after scale-out.
```

openAPI (ticdc): fix openapi use old addrs to create pdClient

---

cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
cdc/sink/ddlsink/mysql/mysql_ddl_sink_test.go
pkg/applier/redo_test.go

Issue Number: close #9644
After this pull request, the "add index" DDL will be executed asynchronously, and it will no longer block the progression of DML replication. There is a risk associated with executing the "add index" DDL in this manner: If an error occurs during the execution of the "add index" DDL in downstream TiDB, the DDL may be lost. However, the likelihood of this situation occurring is low since the DDL was executed successfully upstream, and it will not impact the data correctness downstream.
- Unit test
```release-note
TiCDC exec adding index DDL  asynchronously and does not block checkpoint ts
```

ddl(ticdc): async exec add index ddl

---

cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/scheduler/internal/v3/agent/agent.go
cdc/scheduler/internal/v3/agent/agent_test.go
cdc/scheduler/internal/v3/replication/replication_manager.go
cdc/scheduler/internal/v3/replication/replication_manager_test.go

Issue Number: close #9769 
* make owner scheduler broadcast correct ResolvedTs if redo is enbaled;
* correct the check about comparing resolvedTs and checkpointTs in processor;
- Unit test
```release-note
None
```

sink(cdc): fix the check about resolvedTs and checkpointTs

---

engine/servermaster/server.go
errors.toml
pkg/election/elector.go
pkg/election/elector_test.go
pkg/election/mock/storage_mock.go
pkg/election/storage.go
pkg/election/storage_orm.go
pkg/election/storage_orm_test.go
pkg/election/storage_sql.go
pkg/election/storage_sql_test.go
pkg/errors/cdc_errors.go

Issue Number: close #9768
1. Update different rows bansed on [isLeaderChanged](https://github.com/pingcap/tiflow/pull/9752/files#diff-ecb644f7060077bee2dde9a48196ecd49a9c5e4b5f8b22a041b8ad3a267e9a32R145-R153)
- Unit test
- No code
```release-note
`None`.
```

pkg/election(ticdc): implement gorm based election

---

cdc/server/server.go
pkg/cmd/server/server_test.go
pkg/config/config_test_data.go
pkg/config/server_config.go

Issue Number: close #9762
1. disable gc tunner by default
2. if server memory size is greater than 512G, disable gc tuner
- Unit test
- No code
```release-note
disable gc tuner by default
```

server(ticdc): use TiDB gcTuner in a more reasonable way

---

pkg/config/sink.go
pkg/config/sink_test.go

Issue Number: close #9609
limit delimiter to single character.
- Unit test
- No code
```release-note
`Fix the issue of delimiter could be configured as multiple characters in the csv protocol`
```

sink(ticdc): fix csv delimiter

---

cdc/processor/manager.go
cdc/processor/manager_test.go
cdc/processor/processor.go
cdc/processor/processor_test.go

Issue Number: close #9780
1. make the processor tick logic not depend on the reactor anymore.
2. add Processor interface
- Unit test
- No code
```release-note
`None`.
```

processor(ticdc): decouple processor from reactor

---

dm/master/shardddl/optimist_test.go
dm/pkg/shardddl/optimism/lock.go
dm/pkg/shardddl/optimism/lock_test.go
dm/tests/shardddl2/run.sh

Issue Number: close #9788
- if a DDL not effect table schema, sync it directly
- Unit test
```release-note
```

dm: sync partition DDL even if upstream schema is not equal in optimistic mode

---

cdc/puller/multiplexing_puller.go

Issue Number: close #9815 .
Enlarge table resolved ts buffer size from `16` to `256`. It will be enough for most cases, even if the table contains 100K regions.
- No code
```release-note
None
```

puller(cdc): enlarge table resolved ts buffer size

---

pkg/util/uri.go
pkg/util/uri_test.go

Issue Number: close #9831
mask 
"access-token",
"key",
"signature",
"credentials",
"private-key",
"client_secret",
"client_id",
- Unit test
- No code
```release-note
`None`.
```

config(ticdc): mask more security query parameter

---

pkg/cmd/server/server_test.go
pkg/config/config_test_data.go
pkg/config/server_config.go

Issue Number: close #9673 
Disable kv-client.enable-multiplexing by default.
```release-note
None
```

cdc: disable kv-client.enable-multiplexing by default

---

cdc/processor/manager.go
cdc/processor/manager_test.go
cdc/processor/processor.go
cdc/processor/processor_test.go
cdc/scheduler/internal/v3/agent/agent.go
cdc/scheduler/rexport.go
pkg/etcd/etcd.go
pkg/etcd/mock/etcd_client_mock.go

Issue Number: close #9861
1. define an interface to return owner-capture information
2. init processor with that interface
- Unit test
- No code
```release-note
`None`.
```

p2p(ticdc): remove etcd dependency from p2p agent

---

cdc/kv/shared_client.go
cdc/kv/shared_stream.go

Issue Number: close #9841 
* reduce backoff of loading regions from `5s` to `100ms`;
* fix a nil pointer panic;
```release-note
None
```

client(cdc): use a small backoff to load regions

---

cdc/processor/sinkmanager/table_sink_worker.go
cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/processor/sourcemanager/engine/pebble/event_sorter.go
cdc/processor/sourcemanager/engine/pebble/event_sorter_test.go

Issue Number: close #9849
When removing a table, the table can be cleared from `SortEngine` but there is still a task in `tableSinkWorker`. When it tries to create an iterator to access table data, it panics.
When creates an iterator on an unexist table, just returns an empty iterator.
- Unit test
```release-note
None
```

sorter(cdc): fix panics of accessing sort engine

---

cdcv2/metadata/metadata.go
cdcv2/metadata/model.go
cdcv2/metadata/sql/client.go
cdcv2/metadata/sql/client_orm.go
cdcv2/metadata/sql/observation.go
cdcv2/metadata/sql/uuid.go
cdcv2/metadata/sql/uuid_test.go
errors.toml
go.mod
pkg/errors/cdc_errors.go

Issue Number: close #9871
1. Extract [new client interface](https://github.com/pingcap/tiflow/pull/9864/files#diff-df5be604641b0a21457ede9555f4e6e1a3cc86cd74e2759ff48ca0d9700a0739R31-R34) to handle options, such as timeout.
2. Implement [sql-based uuid generator](https://github.com/pingcap/tiflow/pull/9864/files#diff-0147ec4c9f7b5b6ad61d76a4df8479b16bca88b8cf4db9922933bf03ec86929aR99-R154).
3. [Refactor querier interface](https://github.com/pingcap/tiflow/pull/9864/files#diff-a86fba1ff4e22021451169a4baf4122004d7fd5206fd1fafbe06a4ee4dec9175R27-R31).
- Unit test
- No code
```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-gui …
```

metadata(cdc): implement sql UUID generator and refactor client

---

cdc/sink/dmlsink/mq/mq_dml_sink.go

Issue Number: ref #9855
- Unit test
```release-note
`None`
```

kafka(ticdc): fix kafka dml sink report error to sink manager (#9879)

---

cdc/owner/feed_state_manager.go
cdc/owner/feed_state_manager_test.go
cdc/owner/owner.go
pkg/orchestrator/reactor_state.go

Issue Number: close #9892
[reset internal state of feedStateManager when shouldBeRunning is false](https://github.com/pingcap/tiflow/pull/9893/files#diff-501a5d79c9eb6daaefb02f468e671628f80f282aa90e34b913cacf17c0a242ddR439-R441)
- Unit test
- No code
```release-note
`Fix a bug that changefeed fails directly when a warning is encountered after resume`.
```

reset internal state of feedStateManager when shouldBeRunning is false

---

cdc/owner/changefeed.go
cdc/processor/processor.go
cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/manager_test.go
cdc/scheduler/internal/v3/agent/main_test.go
cdc/scheduler/internal/v3/compat/main_test.go
cdc/scheduler/internal/v3/coordinator.go
cdc/scheduler/internal/v3/coordinator_bench_test.go
cdc/scheduler/internal/v3/keyspan/main_test.go
cdc/scheduler/internal/v3/member/main_test.go
cdc/scheduler/internal/v3/replication/main_test.go
cdc/scheduler/internal/v3/replication/replication_manager.go
cdc/scheduler/internal/v3/replication/replication_manager_test.go
cdc/scheduler/internal/v3/replication/replication_set.go
cdc/scheduler/internal/v3/replication/replication_set_test.go
cdc/scheduler/internal/v3/scheduler/main_test.go
cdc/scheduler/internal/v3/scheduler/scheduler.go
cdc/scheduler/internal/v3/scheduler/scheduler_balance.go
cdc/scheduler/internal/v3/scheduler/scheduler_balance_test.go
cdc/scheduler/internal/v3/scheduler/scheduler_basic.go
cdc/scheduler/internal/v3/scheduler/scheduler_basic_test.go
cdc/scheduler/internal/v3/scheduler/scheduler_drain_capture.go
cdc/scheduler/internal/v3/scheduler/scheduler_drain_capture_test.go
cdc/scheduler/internal/v3/scheduler/scheduler_manager.go
cdc/scheduler/internal/v3/scheduler/scheduler_manager_test.go
cdc/scheduler/internal/v3/scheduler/scheduler_move_table.go
cdc/scheduler/internal/v3/scheduler/scheduler_move_table_test.go
cdc/scheduler/internal/v3/scheduler/scheduler_rebalance.go
cdc/scheduler/internal/v3/scheduler/scheduler_rebalance_test.go
cdc/scheduler/internal/v3/transport/main_test.go

Issue Number: close #9830, close #9774
1. [Init replication set with flushed redo resolvedTs](https://github.com/pingcap/tiflow/pull/9851/files#diff-34b0a3a4c7c7a719f2f0a8e9d837d1666a341db7035322505381c3482a979776R75-R88).
2. [Clenaup resolvedTs and reset it when initlizing changefeed](https://github.com/pingcap/tiflow/pull/9851/files#diff-953746562776cf8aa41cd4a971df8c546649d2721ae787607aed2069f3b44eb0R604).
- Unit test
```release-note
`None`
```

scheduler(ticdc): fix invlaid checkpoint when redo enabled

---

pkg/txnutil/gc/gc_manager.go

Issue Number: close #9895
use atomic bool to fix the data race
- Unit test
- No code
```release-note
`None`.
```

gc(ticdc): fix data race in gc manager

---

cdc/capture/capture.go
cdc/controller/controller.go
cdc/controller/mock/controller_mock.go
cdc/owner/mock/owner_mock.go
cdc/owner/owner.go

Issue Number: close #9930
with meta store,  we can not have the reactor mode to tick the owner or controller,  so remove reactor from owner and controller interface
- Unit test
- No code
```release-note
`None`.
```

capture(ticdc): remove reactor from owner and controller interface

---

cdc/sink/dmlsink/txn/mysql/mysql.go

Issue Number: close #9935 
- Unit test
```release-note
`None`
```

mysql(ticdc): use string join to build multi statement sql.

---

dm/pkg/binlog/position.go
dm/syncer/checkpoint.go
dm/syncer/syncer.go

Issue Number: close #9676 
Substitute String() call for variable comparison:
emptyMySQLGTIDSet, _   = gmysql.ParseMysqlGTIDSet("")
emptyMariaDBGTIDSet, _ = gmysql.ParseMariadbGTIDSet("")
to speed up algorithm. 
- Unit test
- No code
No.
No.
```release-note
```

Removed String() call in favor of variable substitution.

---

cdc/sink/ddlsink/mq/mq_ddl_sink_test.go
cdc/sink/dmlsink/mq/manager/kafka_manager.go
cdc/sink/dmlsink/mq/manager/kafka_manager_test.go
cdc/sink/util/helper.go
cdc/sink/util/helper_test.go

Issue Number: close #9952
* adjust the partition number to user specified value in the kafka topic manager.
- Unit test
```release-note
fix the partition number specified in the sink-uri is not correctly used
```

kafka(ticdc): topic manager return the partition number specified in the sink-uri

---

pkg/config/sink_protocol.go
pkg/sink/codec/simple/decoder.go
pkg/sink/codec/simple/encoder.go
pkg/sink/codec/simple/encoder_test.go
pkg/sink/codec/simple/message.go

Issue Number: close #9900 
- Unit test
```release-note
`None`
```

codec(ticdc): kafka simple encoding protocol support encoding checkpoint event.

---

cdc/entry/mounter_test.go
cdc/model/sink.go

Issue Number: close #9812 
- Unit test
```release-note
None
```

mysql (ticdc): fix batch dml delete sql gennerate error

---

cdc/api/v2/model.go
cdc/api/v2/model_test.go
cdc/model/changefeed.go
cdc/owner/ddl_sink.go
cdc/owner/ddl_sink_test.go
pkg/config/config_test_data.go
pkg/config/replica_config.go
pkg/filter/expr_filter.go
pkg/filter/expr_filter_bench_test.go
pkg/filter/expr_filter_test.go
pkg/filter/filter.go
pkg/filter/sql_event_filter.go
pkg/filter/sql_event_filter_test.go
pkg/filter/utils_test.go
pkg/orchestrator/reactor_state_test.go
scripts/check-diff-line-width.sh

Issue Number: close #9876 
- Unit test
```release-note
Add sql mode config for changefeed 
```

config, changefeed  (ticdc): add sql mode config for changefeed

---

cdc/redo/manager.go
cdc/redo/manager_test.go

Issue Number: close #9998, ref #9960
use meta flush interval in redo ddl manager
- Unit test
- No code
```release-note
```

redo(ticdc): use meta flush interval in redo ddl manager

---

cdc/redo/manager.go
cdc/redo/meta_manager.go
pkg/version/version.go

Issue Number: close #10026
- Unit test
- No code
```release-note
`None`.
```

redo(ticdc): fix meta manager wrong flush interval bug

---

pkg/sink/codec/open/open_protocol_encoder_test.go
pkg/sink/kafka/claimcheck/claim_check.go
pkg/sink/kafka/claimcheck/claim_check_test.go

Issue Number: close #10036
- Unit test
```release-note
`None`
```

kafka(ticdc): claim check do not use filepath join to build the full file path.

---

cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
pkg/sink/cloudstorage/path.go
pkg/sink/cloudstorage/path_test.go

Issue Number: close #10041, close #10044
1. To solve #10041, use unbounded channel in dml_sink.
2. To solve #10044, use subDir in storage.Walk.
- Unit test
- No code
```release-note
```

sink(ticdc): use subDir in storage.Walk

---

cdc/owner/ddl_manager.go
tests/integration_tests/bdr_mode/data/start.sql
tests/integration_tests/bdr_mode/data/up.sql

Issue Number: close #10079 
```release-note
fix in bdr mode cdc can not replicate a table's dmls after drop and re-create it
```

ddl_manager (ticdc): fix in bdr mode cdc can not replicate a table's dmls after drop and re-create it 

---

cdc/processor/sinkmanager/redo_cache.go
cdc/processor/sinkmanager/redo_cache_test.go
cdc/processor/sinkmanager/table_sink_worker.go
cdc/processor/sinkmanager/table_sink_worker_test.go

Issue Number: close #10065 .
Let's focus on file `cdc/processor/sinkmanager/table_sink_worker.go`. #10065 panics if
* redo is enabled;
* sink memory quota is almost full;
* there are transactions larger than 8M;
* when handling one large transaction, `fetchFromCache` returns `drained=false`;
* then the condition `for advancer.hasEnoughMem() && !task.isCanceled()` is broken immediately;
* changefeed is paused and then resumed, table sink is faster than redo.
After that, the variable `lastPos` can be less than `lowerBound.Prev()`, which is not expected.
- Unit test
```release-note
None
```

sink(cdc): avoid sinking redundant events in some rare cases with redo enabled

---

Makefile
cmd/cdc/fips.go
pkg/version/check.go
pkg/version/check_test.go

Issue Number: close #9962 
1. add support to build FIPS-ready cdc binary following the info shown in https://github.com/pingcap/tidb/pull/47949
2. add `-fips` in the release version of FIPS-ready binary
3. support sanitize version with `-fips` suffix when do version check
- Unit test
Make sure the version sanitize process works with `-fips` suffix;
```
ENABLE_FIPS=1 make cdc
go tool nm bin/cdc | grep boring
```
Check the boringcrypto linked via cgo, some function names like:
```
6d3aa60 t local.crypto/internal/boring._Cfunc__goboringcrypto_AES_cbc_encrypt.abi0
6d3abc0 t local.crypto/internal/boring._Cfunc__goboringcrypto_AES_ctr128_encrypt.abi0
6d3ad20 t local.crypto/internal/boring._Cfunc__goboringcrypto_AES_decrypt.abi0
6d3ade0 t …
```

Makefile(ticdc): support build cdc in fips mode

---

cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/manager_test.go
cdc/processor/sinkmanager/table_sink_worker.go
cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/sink/dmlsink/blackhole/black_hole_dml_sink.go
cdc/sink/tablesink/table_sink.go
cdc/sink/tablesink/table_sink_impl.go

Issue Number: close #10091 
In `SinkManager`, suppose there is a table with `checkpointTs=100` and `lastWrittenPos=110`, and sync-point is also `110`.
And then, the sink backend fails, the sink should be re-started at `100`.
However, when generating sink tasks, `SinkManager` finds the table has no more available events after `lastWrittenPos=110`, and it can't detect the sink backend failure any more.
With the PR this behavior is corrected.
- Unit test
```release-note
None
```

sink(cdc): always handle sink failures for cases with sync-point enabled

---

pkg/sink/cloudstorage/path.go

Issue Number: close #10137
this pr remove the schema file checking, because some cdc will generate a tmp file and then rename it, but these two operation is not atomic,so if ticdc is stopped after generating the tmp file, cdc has no chance to rename the tmp file,  cdc will panic again and again because of the checking logic
- Unit test
- No code
```release-note
`None`.
```

cloudstorage(ticdc):  Remove nfs schema file check

---

cdc/owner/changefeed.go
cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
cdc/sink/dmlsink/cloudstorage/dml_worker.go
cdc/sink/metrics/cloudstorage/metrics.go
pkg/config/sink.go

Issue Number: close #10115
add more log and metrics to storage sink, the write duration panel will take effect after #9954 is merged.
- Unit test
- No code
```release-note
```

sink(ticdc): add more log and metrics to storage sink

---

cdc/api/v2/model.go
cdc/redo/meta_manager_test.go
cdc/sink/dmlsink/cloudstorage/dml_worker.go
pkg/config/sink.go
pkg/sink/cloudstorage/config.go
pkg/sink/cloudstorage/config_test.go

Issue Number: close #10098, close #10172
- Unit test
- [for nfs](https://snapshots.raintank.io/dashboard/snapshot/1zIuhH1hCYDZ4BMOG32cueEUf46SXMfl) 
- [for s3] (https://snapshots.raintank.io/dashboard/snapshot/lUb2qBcnsLZJ1QlKVrZ0fS6vTLDsXyCy)
```release-note
```

sink(ticdc): use multi part s3 uploader in storage sink

---

dm/ui/.eslintrc.js
dm/ui/package.json
dm/ui/plugins/vite-plugin-i18next-scanner/index.js
dm/ui/plugins/vite-plugin-i18next-scanner/package.json
dm/ui/plugins/vite-plugin-i18next-scanner/worker.js
dm/ui/plugins/vite-plugin-next-react-router/index.js
dm/ui/plugins/vite-plugin-next-react-router/package.json
dm/ui/tsconfig.json
dm/ui/vite.config.js
dm/ui/yarn.lock

Issue Number: close  #9630 
- Unit test
- No code
```release-note
```

fix(ui): move vite plugin to repo

---

cdc/kv/client.go
cdc/kv/shared_client.go
cdc/processor/sinkmanager/tasks.go
cdc/processor/sinkmanager/tasks_test.go

Issue Number: close #10168 
Issue Number: close #10169 
Issue Number: close #10164 
* Limit concurrency for scaning regions;
* Increase sink task range from `5s` to `30m`.
- No code
```release-note
None
```

cdc: fixes minor bugs #10168 and #10169

---

cdc/kv/region_worker.go

Issue Number: close #10095 
* use mutext to protect the worker pool 
- Unit test
```release-note
fix the kv client worker pool initialization meet data race
```

kvclient(ticdc): fix the workerpool data race

---

cdc/puller/puller.go
pkg/cmd/server/server_test.go
pkg/config/config_test_data.go
pkg/config/debug.go
pkg/config/server_config.go

Issue Number: close #10181
detect if the resolved ts is stuck, if so , restart  the changefeed
- Unit test
- No code
```release-note
`None`.
```

puller(ticdc):  detect resolved ts stuck in puller

---

cdc/kv/client.go
cdc/kv/shared_client.go
cdc/puller/frontier/frontier.go
cdc/puller/frontier/frontier_test.go
cdc/puller/puller.go

Issue Number: ref #10181 
Add some debug code for stuck ResolvedTs in puller.
- Unit test
```release-note
None
```

puller(cdc): debug frontier

---

cdc/scheduler/internal/v3/replication/replication_set.go

Issue Number: close https://github.com/pingcap/tiflow/issues/10224
update stats only when it's not empty to make metrics updating normally
- Unit test
- No code
```release-note
None
```

scheduler(ticdc): Updating ReplicationSet.stats only when stats is not empty

---

cdc/api/v2/model.go
cdc/redo/writer/memory/file_worker.go
pkg/config/consistent.go
pkg/util/external_storage.go
tests/integration_tests/consistent_replicate_storage_s3/conf/changefeed.toml

Issue Number: close #10226
add a new consistent configuration item and default value is 0,   if the value is great than 1, use multi part s3 uploader in  redo
- Unit test
- No code
```release-note
`None`.
```

redo(ticdc): use multi part s3 uploader in  redo

---

dm/syncer/syncer.go

Issue Number: close #10204 
This makes the logging on the warning level less noisy and adds detail to the TableMap event logs.
```release-note
Logging of `TableMapEvent` and `FormatDescriptionEvent` was changed from the warning level to the info level.
```

syncer(dm): Improve logging of ignored TableMap/FormatDesc

---

cdc/puller/puller.go

Issue Number: close #10256 
check if the resolved ts is advanced before
- Unit test
- No code
```release-note
`None`.
```

puller(ticdc):  fix stuck detect issue

---

pkg/sink/cloudstorage/path.go
pkg/sink/cloudstorage/path_test.go

Issue Number: close #10284
- Unit test
- No code
```release-note
`None`.
```

cloudstorage(ticdc):  write meta file if not found and add ut for 10137

---

cdc/api/v2/model.go
pkg/cmd/util/changefeed_storage_sink.toml
pkg/config/config_test_data.go
pkg/config/sink.go
pkg/sink/codec/common/config.go
pkg/sink/codec/csv/csv_message.go
pkg/sink/codec/csv/csv_message_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/10167
When changefeed configuration set:
```
[sink.csv]
output-old-value = true
```
As https://github.com/pingcap/tiflow/issues/10167 described, sink to csv replace update with a pair of delete and insert, in this way to record the old value for UPDATE statement, so it is possible to generate undo DML for some data repairing cases.
Before this change, the CSV output statement of `update schema.table set name="def" where id=1 and name="abc"` is
```
U, table, schema, [commit-ts], 1, def
```
After this change, the CSV output looks like:
```
D, table, schema, [commit-ts], 1, abc
I, table, schema, [commit-ts], 1, def
```
- Unit test
After set `[sink.csv] output-old-value = true` configuration for the sink to storage changefeed, for …

sink to csv: output old value to CSV files

---

cdc/api/v2/model.go
cdc/api/v2/model_test.go
cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/manager_test.go
dm/tests/lightning_mode/run.sh
dm/tests/tls/run.sh
pkg/config/config_test_data.go
pkg/config/consistent.go
pkg/config/replica_config.go

close pingcap/tiflow#10143
#	cdc/processor/sinkmanager/manager.go
- Unit test
- No code
```release-note
```

redo(cdc): custom redo event cache and disable it by default (#10139)

---

pkg/sqlmodel/multirow.go
pkg/sqlmodel/row_change.go
pkg/sqlmodel/utils.go
pkg/sqlmodel/utils_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/10313
Optimize O(N*N) time complexity generated column check to O(N) by building generated columns name set.
- Unit test
```release-note
`None`.
```

sqlmodel(*): optimize O(N*N) generated column check to O(N)

---

cdc/sink/dmlsink/txn/mysql/mysql.go

Issue Number: close https://github.com/pingcap/tiflow/issues/10322
Set session variables first and then execute DMLs, in this way everything is expected when the downstream is other mysql compatible databases (not TiDB).
- Unit test
```release-note
`None`.
```

sink-mysql(cdc) set variables first and then execute DMLs

---

cdc/kv/shared_client.go
metrics/grafana/ticdc.json

Issue Number: ref #9222 
1. Fix eventFeedGauge metric for kvclient.SharedClient.
2. Use wildcards in PromQL expressions to be compatible with different versions of EventFeed
After the metrics are fixed:<img width="910" alt="图片" src="https://github.com/pingcap/tiflow/assets/8407317/986aeb6a-4df7-4343-9614-1d29de593402">
```release-note
None
```

kv-client(cdc): fix metrics for kvclient.SharedClient

---

cdc/sink/dmlsink/mq/mq_dml_sink.go
cdc/sink/dmlsink/mq/worker.go
cdc/sink/dmlsink/mq/worker_test.go
pkg/sink/codec/encoder.go
pkg/sink/codec/encoder_group.go

Issue Number: close #10348 
- No code
```release-note
None
```

mq (ticdc): make some code more readable.

---

pkg/config/sink.go
pkg/config/sink_test.go

Issue Number: ref #9969 
Some customers use separator like `|@|` in their env. So we need to relief the delimiter restriction further to support at most 3 characters.
- Unit test
```release-note
None
```

csv(cdc): delimiter supports at most 3 characters

---

pkg/config/sink.go
pkg/sink/codec/builder/encoder_builder.go
pkg/sink/codec/common/config.go
pkg/sink/codec/debezium/codec.go
pkg/sink/codec/debezium/codec_test.go
pkg/sink/codec/debezium/debezium_test.go
pkg/sink/codec/debezium/encoder.go
pkg/util/json_writer.go
pkg/util/json_writer_test.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/1799
Benchmark (with schema):
```
BenchmarkEncodeOneTinyColumn-10    	  425042	      2734 ns/op	     256 B/op	      12 allocs/op
BenchmarkEncodeLargeText-10        	  342390	      3566 ns/op	     256 B/op	      12 allocs/op
BenchmarkEncodeLargeBinary-10      	  319641	      3497 ns/op	    1410 B/op	      15 allocs/op
```
Benchmark (without schema):
```
BenchmarkEncodeOneTinyColumn-10    	 2771671	       430.0 ns/op	       0 B/op	       0 allocs/op
BenchmarkEncodeLargeText-10        	  974575	      1250 ns/op	       0 B/op	       0 allocs/op
BenchmarkEncodeLargeBinary-10      	  978442	      1143 ns/op	    1154 B/op	       3 allocs/op
```
- Unit test
```release-note
Please refer to [Release Notes Language Style …
```

cdc: Support schema for Debezium output protocol

---

dm/tests/all_mode/conf/dm-task.yaml
go.mod
go.sum

Issue Number: close #10282
log error instead of return it
- Unit test
```release-note
```

binlog-filter: log error instead of return it

---

dm/pkg/schema/tracker.go
dm/pkg/schema/tracker_test.go

close pingcap/tiflow#10308
Issue Number: close #10308
set enable cluster index to off for downstream tracker
- Unit test
```release-note
```

dm: set enable cluster index to off for downstream tracker (#10346)

---

pkg/causality/conflict_detector.go
pkg/causality/internal/node.go
pkg/causality/internal/node_test.go
pkg/causality/internal/slots_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/10341
- Remove early conflict resolving optimization for the conflict detector, prevent workload skew issue described in https://github.com/pingcap/tiflow/issues/10341
- Simplify the whole code logic, make it more easy to maintain.
- Unit test
```release-note
`None`.
```

sink-to-mysql(cdc) simplify conflict detector, prevent workload skew issue

---

cdc/puller/frontier/frontier.go
cdc/puller/frontier/frontier_test.go
cdc/puller/frontier/list.go
cdc/puller/puller.go
cdc/puller/puller_test.go

Issue Number: ref #10181
In puller, print the context node for lastSlowestRange. eg: 
```
require.Equal(t, `[a @ 20] [b @ 20] [c @ 20] [d @ 20] [f @ Max] `, f.SpanString(spCD))
```
- Unit test
- No code
```release-note
```

puller(ticdc): add more log for puller

---

dm/pkg/checker/mysql_server.go
dm/pkg/checker/mysql_server_test.go
dm/pkg/checker/utils_test.go
dm/tests/dmctl_command/run.sh
dm/tests/extend_column/run.sh

Issue Number: close #10405 
DM supports MySQL 8.0 GA.
- Unit test
No.
https://github.com/pingcap/docs/pull/15959
https://github.com/pingcap/docs-cn/pull/15985
```release-note
DM supports MySQL 8.0 GA.
```

dm: support MySQL 8.0 GA

---

dm/master/config.go
dm/tests/tls/run.sh

Issue Number: close #10413
after etcd upgrading, the default value of `EnableGRPCGateway` becomes true, so we need to manually turn it off. see https://github.com/pingcap/dm/issues/1458
```release-note
`None`
```

test: enable tls test for DM

---

cdc/api/v2/changefeed.go
cdc/api/v2/changefeed_test.go
cdc/owner/mock/owner_mock.go
cdc/owner/owner.go
cdcv2/owner/owner.go
errors.toml
pkg/errors/cdc_errors.go
pkg/etcd/client_test.go
pkg/etcd/etcd.go
pkg/etcd/etcd_test.go
pkg/etcd/etcdkey_test.go
pkg/etcd/mock/etcd_client_mock.go
pkg/etcd/util_test.go

Issue Number: close #10430
there are two apis that update or create upstream information:
1. create changfeed and upstreamPUT /api/v2/changefeeds/{changefeed_id}
2. update changefeed and upstream POST /api/v2/changefeeds
And, the expected usage of these apis is:
1. Avoid modifying the same changefeed concurrently .
2. Avoid modifying the same upstream concurrently.
Before this PR, when a changefeed is created, cdc always updates the uptream information, regardless of whether the uptream changes.  As a result, when different ChangeFeeds are created concurrently, cdc conflicts with concurrent updates to the same upstream key.
To solve this issue, we should only update upstreamInfo that has changed when creating changefeed.
------
Besides, cdc did not perform any checks when updating …

api(ticdc): only update upstreamInfo that has changed

---

cdc/model/sink.go
cdc/processor/sinkmanager/metrics.go
cdc/sink/dmlsink/txn/mysql/mysql.go
cdc/sink/dmlsink/txn/worker.go

Issue Number: ref #10457
1. remove some no longer used code.
2. adjust some logs
- Unit test
- No code
```release-note
None
```

cdc: remove unused code and add some logs

---

.codecov.yml

Issue Number: close https://github.com/pingcap/tiflow/issues/10473
To make the codecov status just informational in github commit statuses on components and flags level, not fail the 
commit statuses.
- Unit test
```release-note
None
```

chore: make the codecov status informational to not affect the PR commit status

---

cdc/api/middleware/middleware.go
cdc/api/v1/api.go
tests/integration_tests/http_api/run.sh
tests/integration_tests/http_api/util/test_case.py
tests/integration_tests/http_api_tls/util/test_case.py

Issue Number: close #10470
http_api is not robust, the get_processor case will fail if the first changefeed  returned by getProcessors API is paused. `api/v1/processors/{changefeed_id}/{capture_id}` API always return status code `400`.   because paused changefeed will not be scheduled to capture.
- Unit test
- No code
```release-note
`None`.
```

test(ticdc):  fix http_api integration test

---

pkg/sink/codec/simple/avro.go
pkg/sink/codec/simple/decoder.go
pkg/sink/codec/simple/encoder.go
pkg/sink/codec/simple/encoder_test.go
pkg/sink/codec/simple/marshaller.go
pkg/sink/codec/simple/message.go
pkg/sink/codec/simple/message.json
pkg/sink/codec/simple/message_test.go

Issue Number: close #10474 
* Encode `TableID` into simple protocol DML and DDL message content
- Unit test
```release-note
`None`
```

codec(ticdc): simple protocol add table id as message field

---

cdc/puller/frontier/frontier.go
cdc/puller/frontier/frontier_test.go
cdc/puller/puller.go

Issue Number: ref #10157
Always delete the the mapping in `cachedRegions` when a span's regionID changes. 
This can prevent an old span node in the frontier from becoming an orphan node, which would cause the resolvedTs of the corresponding span to not be updated.
- Unit test
```release-note
Fix a bug where region split and merge cause the changefeed resolvedTs to get stuck.
```

puller(ticdc):  fix resolvedTs get stuck when region split and merge

---

cdc/scheduler/internal/v3/replication/replication_manager.go

Issue Number: close #10482
1. [Record the correct progress in slowestTablePullerResolvedTs](https://github.com/pingcap/tiflow/pull/10484/files#diff-ec8c2629076697b5b91801313d52d043e53e4418f0317c4b944d380cdaca1466R861-R864)
2. [For tables with equal checkpoints, set the table with the smallest resovedTs to the slowest table](https://github.com/pingcap/tiflow/pull/10484/files#diff-ec8c2629076697b5b91801313d52d043e53e4418f0317c4b944d380cdaca1466R630-R631)
- Unit test
```release-note
`None`.
```

metrics(ticdc): fix slowest table metrics in scheduler

---

cdc/owner/changefeed.go
cdc/owner/metrics.go
metrics/grafana/TiCDC-Monitor-Summary.json
metrics/grafana/ticdc.json

Issue Number: close #10449, close #10447, close #10438
1. For #10449, always cleanup metrics [whether the changefeed has been cleaned or not](https://github.com/pingcap/tiflow/pull/10459/files#diff-953746562776cf8aa41cd4a971df8c546649d2721ae787607aed2069f3b44eb0R732-L759).
2. For #10447, use the type of ticdc_kvclient_pull_event_count to distinguish incresmental scan and real-time raft log.
3. For #10438, add changefeedStartTimeGauge metric, which record the changefeed create time and restart time. **Note that** changefeedStartTimeGauge records the physical time with ***millisecond precision.***
- Unit test
- No code
```release-note
`None`.
```

owner, metrics(ticdc): fix metrics

---

cdc/entry/mounter.go
cdc/entry/mounter_test.go
cdc/model/schema_storage.go
cdc/model/schema_storage_test.go
cdc/model/sink.go
cdc/sink/dmlsink/txn/mysql/mysql.go
cdc/sink/dmlsink/txn/mysql/mysql_test.go
pkg/applier/redo_test.go

Issue Number: ref #10386 
Fix and improve `BuildTiDBTableInfo`;
1. Add mock column id and mock index id for the generated TableInfo;
2. Add checks to verify the legality of the arguments;
3. Fix some small incorrect behaviour of the previous implementation including set charset and collation correctly;
Fix the wrong behavior that a primary column is always set an extra unique key flag in `WrapTableInfo`;
Add some helper method on `TableInfo` to query related information for columns;
- Unit test
```release-note
None
```

cdc: fix build table info

---

cdc/api/v1/validator.go
cdc/api/v2/api_helpers.go
cdc/processor/sinkmanager/manager.go
cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink_test.go
cdc/sink/dmlsink/cloudstorage/dml_worker.go
cdc/sink/dmlsink/cloudstorage/dml_worker_test.go
cdc/sink/dmlsink/factory/factory.go
cdc/sink/validator/validator.go
cdc/sink/validator/validator_test.go
cmd/kafka-consumer/main.go
cmd/pulsar-consumer/main.go
cmd/storage-consumer/main.go
errors.toml
pkg/applier/redo.go
pkg/errors/cdc_errors.go
pkg/pdutil/clock.go
pkg/sink/cloudstorage/path.go
pkg/sink/cloudstorage/path_test.go

Issue Number: close #10352, ref #10374
- Use pdClock instead of local clock to generate date seperator.
- Unit test
- No code
```release-note
`Fix the issue that date seperator generated by the storage sink may roll back in table scheduling scenarios`.
```

sink(ticdc): use pd clock in storage sink

---

cdc/api/v2/model.go
cdc/api/v2/model_test.go
cdc/model/changefeed_test.go
pkg/cmd/cli/cli_changefeed_create_test.go
pkg/config/filter.go
pkg/filter/utils.go
pkg/migrate/migrate_test.go
tests/integration_tests/api_v2/cases.go
tests/integration_tests/api_v2/model.go

Issue Number: ref #10457
Remove useless code about MySQLReplicationRules. It's deprecated and not used now.
- No code
```release-note
None
```

filter(ticdc): Remove useless code about MySQLReplicationRules

---

cdc/entry/mounter.go
cdc/entry/schema/snapshot.go
cdc/entry/schema/snapshot_test.go

Issue Number: close #10522
like truncate table logic,  when a table partition is truncated ,  CDC should add this partition ID to the memory map, then get a key encoded by this partition ID,  mounted should ignore it,  otherwise mourner will  failed to decode the key.
- Unit test
- No code
```release-note
`None`.
```

mounter(ticdc): fix truncate table partition cause mounter failed issue

---

cdc/api/v2/model.go
pkg/sink/codec/csv/csv_message.go
pkg/sink/codec/csv/csv_message_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/10167
1. Add new column "is-updated" when enable output-old-value to indicate whether the row is updated or just original insert/delete.
2. Make output-old-value config take effects. 
- Unit test
set changefeed configuration add do some insert/update/delete events:
[sink.csv]
include-commit-ts = true
output-old-value = true
the output csv looks like 
"I","t1","test",447240134323863555,false,1,2
"I","t1","test",447240134323863555,false,3,4
"I","t1","test",447240134323863555,false,5,6
"I","t1","test",447240134323863555,false,7,8
"D","t1","test",447240137390686212,true,1,2
"I","t1","test",447240137390686212,true,1,10
- No code
```release-note
Please refer to …
```

Add new column "is-updated" for output-old-value in csv protocol

---

cdc/api/v1/validator.go
cdc/api/v2/api_helpers.go
cdc/api/v2/api_helpers_test.go

Issue Number: close #10499
When creating and resuming the changefeed, make sure the `start-ts` is not in the future, this should be helpful to prevent the changefeed not make progressing after initialized, since the `start-ts` is not coming yet.
- Unit test
```release-note
validate the start-ts when creating and resuming changefeed
```

cli(ticdc): verify start-ts to make sure it's not in the future

---

cdc/puller/frontier/frontier.go
cdc/puller/frontier/frontier_test.go

Issue Number: ref pingcap/tiflow#10157
- Unit test
- No code
```release-note
```

puller(ticdc): fix resolvedTs get stuck when region split and merge (hotfix)

---

cdc/api/v2/model.go
cdc/entry/mounter.go
cdc/model/sink.go
cdc/model/sink_gen.go
pkg/config/config_test_data.go
pkg/config/sink.go
pkg/sink/codec/common/config.go
pkg/sink/codec/csv/csv_message.go
pkg/sink/codec/csv/csv_message_test.go

Issue Number: ref #10167
Add a new config called "output_handle_key" enable to output handle key info in csv protocol
set changefeed configuration add do some insert/update/delete events:
[sink.csv]
include-commit-ts = true
output-old-value = true
output-handle-key = true
the output csv looks like
"I","t3","test",447353152622297101,false,"{5, 2}",5,2,3 
I","t6","test",447353152596082707,false,"1",10,22,3
- Unit test
- No code
```release-note
None
```

csv(ticdc): Add a new config "output_handle_key" in csv protocol to support output handle key info in csv protocol

---

cdc/entry/mounter_test.go
pkg/sink/codec/simple/avro.go
pkg/sink/codec/simple/decoder.go
pkg/sink/codec/simple/encoder_test.go
pkg/sink/codec/simple/marshaller.go
pkg/sink/codec/simple/message.go
pkg/sink/codec/simple/message.json

Issue Number: close #10563
* fix the primary key that cannot be found, by sort columns after all indexes were found.
* adjust simple avro schema, remove useless field
* add more unit test to the simple protocol encoding.
- Unit test
- No code
```release-note
`None`
```

codec(ticdc): simple protocol fix primary key not found and adjust schema

---

cdc/entry/schema_test_helper.go
cdc/kv/client.go
cdc/kv/client_test.go
cdc/kv/region_worker.go
cdc/kv/region_worker_test.go

Issue Number: close #10239 
1. Add an ID to the `eventFeedStream` struct to identify a stream and prevent it from being deleted unexpectedly.
2. Bind the cancel function of a gRPC stream to its `eventFeedStream` to prevent the stream from being canceled unexpectedly.
3. Reduce the number of calls to `s.deleteStream` to only once to prevent the stream from being deleted unexpectedly.
1. Add hard code `time.sleep(5 * time.second)` before calling `s.deleteStream` in both unfixed and fixed version of code. 
2. Deploy a TiDB cluster with 3 TiKV nodes and 1 TiCDC server, create a changefeed. 
3. Patch the changed cdc binary, and restart a TiKV node randomly and observe the changefeed's lag. 
unfixed cdc:
fixed cdc:
From the above graphs, it is …

kv (ticdc): fix kvClient reconnection downhill loop

---

cdc/api/v2/unsafe_test.go
cdc/capture/capture.go
cdc/http.go
cdc/server/server.go
cdcv2/capture/capture.go
pkg/etcd/client.go
pkg/security/credential.go
pkg/upstream/main_test.go
pkg/upstream/manager.go
pkg/upstream/manager_test.go
pkg/upstream/upstream.go
pkg/upstream/upstream_test.go

Issue Number: ref #10375, ref https://github.com/pingcap/tidb/issues/50723
1. Use `/topology/ticdc/{clusterID}/{ip:port}` to store topology info.
2. Support querying server config via `/config` api.
- Unit test
```release-note
`None`.
```

upstream, api(ticdc): support topology and config 

---

scripts/download-integration-test-binaries.sh

Issue Number: close #10588
all checksum integration tests is failed because of upstream tidb changes,  in this PR we use a specified tidb commit to run integration tests
- Unit test
- No code
```release-noteNone`.
```

tests: specify tidb commit

---

cdc/syncpointstore/mysql_syncpoint_store.go
pkg/filter/filter.go
pkg/filter/filter_test.go
pkg/filter/utils.go
pkg/filter/utils_test.go
tests/integration_tests/bdr_mode/conf/cf.toml
tests/integration_tests/bdr_mode/conf/down.toml
tests/integration_tests/bdr_mode/conf/up.toml
tests/integration_tests/bdr_mode/run.sh

Issue Number: close #10576 
Make isSysSchema() also treat `tidb_cdc` as a system schema. 
This also helps the case of non-BDR "A→B→C" scenario, where the syncpoint table of A→B polluted B→C.
When the schema `tidb_cdc` is considered as a system schema, it will not be listened to by CDC at all.
- Unit test
```release-note
Fix a bug that causes syncpoint table being replicated by cdc.
```

filter (ticdc): fix synpoint table is replicated in BDR mode

---

cmd/pulsar-consumer/main.go
pkg/sink/pulsar/factory.go
pkg/sink/pulsar/logger.go
pkg/sink/pulsar/logger_test.go

Issue Number: close #10604
Just make `Logger` and `Entry` use the same structure.
- Unit test
```release-note
None
```

pulsar/logger: ensure the .With*() fields are logged

---

tests/integration_tests/bdr_mode/data/up.sql

Issue Number: close #10619 
This issue occurs because the "add index" operation may take some time to complete downstream. If we add and drop the same index sequentially, the "drop index" operation may fail because the index doesn't exist yet, as the "add index" operation has not finished.
To ensure the success of the "add index" operation, a `SLEEP(30)` command is added before the "drop index" operation.
```release-note
None
```

tests (ticdc): make bdr_mode integration test more stable

---

cdc/processor/sinkmanager/redo_log_worker.go
cdc/processor/sinkmanager/table_sink_worker.go
cdc/processor/sourcemanager/sorter/metrics.go
cdc/processor/sourcemanager/sorter/pebble/event_sorter.go

Issue Number: close #10641 
#10467 introduces a bug that `SortEngine` disk space can't be recycled if redo isn't enabled. This PR corrects it.
And, add a metric to count stale table range cleaning.
here is a test for **WITHOUT the patch** and **WITH the patch**:
```release-note
None
```

sorter(cdc): correct stale table range cleaning and metric it

---

cmd/pulsar-consumer/main.go

Issue Number: close #10653
add some command line options to support oauth2 and mtls auth,  so we can test pulsar sink with oauth2 or mtls enabled in integrations tests.
- Unit test
- No code
```release-note
`None`.
```

test(ticdc): pulsar consumer support oauth and mtls auth

---

cmd/kafka-consumer/main.go
pkg/sink/codec/simple/decoder.go

Issue Number: close #10678
* if the table info not found, cache the message into a list
* after the table info received, decode the message into event if possible
* kafka consumer check cached event and consume it
- Unit test
- No code
```release-note
`None`
```

codec(ticdc): simple protocol decoder support cache message and return table info delayed events

---

dm/syncer/dml.go
dm/tests/many_tables/run.sh
dm/tests/shardddl1_1/conf/single-source-no-sharding.yaml
dm/tests/shardddl1_1/run.sh

Issue Number: close #10672 
ref: https://dev.mysql.com/doc/refman/8.0/en/binary-varbinary.html
if column is binary type, we should padding it with \0, otherwise the where condition will also be false
```release-note
Fixed the issue where data loss could occur when the upstream primary key is of binary type.
```

dm: fix update dml loss if binary column is primary key

---

dm/syncer/dml.go
dm/tests/many_tables/run.sh
dm/tests/shardddl1_1/conf/single-source-no-sharding.yaml
dm/tests/shardddl1_1/run.sh

close pingcap/tiflow#10672
Issue Number: close #10672 
ref: https://dev.mysql.com/doc/refman/8.0/en/binary-varbinary.html
if column is binary type, we should padding it with \0, otherwise the where condition will also be false
```release-note
Fixed the issue where data loss could occur when the upstream primary key is of binary type.
```

dm: fix update dml loss if binary column is primary key (#10685)

---

cdc/entry/schema/snapshot.go
cdc/entry/schema_storage.go
cdc/entry/schema_storage_test.go
cdc/entry/validator.go

Issue Number: ref #10457 
- No code
```release-note
None
```

entry (ticdc): logs all tables to be replicated when changefeed initialized

---

cdc/sink/dmlsink/mq/dispatcher/event_router.go
cdc/sink/dmlsink/mq/dispatcher/event_router_test.go
cdc/sink/dmlsink/mq/dispatcher/partition/default.go
cdc/sink/dmlsink/mq/dispatcher/partition/default_test.go

Issue Number: close #10712
- Unit test
- No code
```release-note
use table dispatcher as the default dispatcher to guarantee the avro protocol dispatch behavior backward compatibility
```

kafka(ticdc): use table dispatcher as the default dispatcher

---

pkg/sink/codec/bootstraper.go
pkg/sink/codec/bootstraper_test.go

Issue Number: ref #9898 
After a rename table ddl happens, the `tableStatistic` of the table in `bootstraper` should be updated.
- Unit test
```release-note
None
```

simple (ticdc): fix simple rename table ddl handle error

---

cdc/kv/client.go

Issue Number: close #10718
As described in the issue comment https://github.com/pingcap/tiflow/issues/10718#issuecomment-1980122405, the problem is caused by the goroutine that writes the channel not being uniformly managed by the wait method of the parent goroutine group that created it. 
Therefore, this PR uses the same goroutine group to manage the child goroutines to avoid the occurrence of the problem.
```release-note
Fix a bug that may cause cdc panic.
```

kv (ticdc): fix kv client data race panic

---

go.mod
go.sum

Issue Number: close #10673
Use a cloned repo to replace the official seahash, because the original seahash repo has been removed.
- Unit test
```release-note
None
```

go.mod: replace seahash with a valid github repo

---

cdc/model/schema_storage.go
pkg/sink/codec/canal/type_test.go

Issue Number: close #10743 
* `rowColInfos` should only be used to decode datums from the raw bytes, do not fetch column id from it.
- Unit test
```release-note
`None`
```

codec(ticdc): do not abuse rowcodec.ColInfo to fetch the column id 

---

cdc/kv/shared_client.go
cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/redo/manager.go
cdc/redo/meta_manager.go
pkg/util/atomic.go
pkg/util/atomic_test.go

Issue Number: close #10613
1. [update barrierTs when starting table](https://github.com/pingcap/tiflow/pull/10740/files#diff-f1a821fc6bccdd087045289477de1ba938f0174afc2fed865a66d5264548abd7R168). Ref [the resaon](https://github.com/pingcap/tiflow/issues/10613#issuecomment-1983173348)
2. Extract a [new util](https://github.com/pingcap/tiflow/pull/10740/files#diff-ba333197f13ad9389bf03b0261938edd52c195094307c506a071bbbac99cc330R27) to simplify code base.
- Unit test
```release-note
Fix a bug that may cause TiCDC panic when scheduling tables.
```

sinkManger(ticdc): update barrierTs when starting table

---

cdc/processor/sourcemanager/sorter/pebble/event_sorter.go

Issue Number: close #10738
The problematic code snippet here:https://github.com/pingcap/tiflow/blob/e5edb1906cc6c1c3addf9e82120ebefd96b13e81/cdc/processor/sourcemanager/sorter/pebble/event_sorter.go#L466-L482
is a busy loop that continuously polls an input channel and does some work when an item is available. 
The issue here is with the 'default' clause in the select statement. If there's no item available in the 'inputCh' channel, it will immediately continue to the next iteration instead of blocking until an item is available or the 's.closed' channel is closed. This could lead to high CPU usage as the loop is continuously running.
This PR replace the 'default' clause with a ticker. This will cause the goroutine to block when there's no work to do, reducing CPU usage. 
- Unit test
- …

ticdc: Fix CPU surge problem in sorter

---

scripts/generate-protobuf.sh

Issue Number: close #10756
use `find` instead of  `shopt -s globstar` to make it works in various basic os envs
test generate protobuf in both linux and macos
```release-note
None
```

ticdc: Fix generate-protobuf.sh to make it works in various basic os envs

---

.github/workflows/check_and_build.yaml
pkg/causality/internal/node.go
pkg/causality/internal/node_test.go
pkg/causality/tests/integration_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/10762
The data race problem is because `maybeReadyToRun` and `Free` maybe called simultaneously.
Consider the following scenario:
A only depends B, and B call B's remove first, and reduce A's removedDependencies to 0
Then A just call A's `maybeReadyToRun`, and assign to a worker and remove and free itself
Simultaneously, B call A's maybeReadyToRun.
Besides to avoid use too much mutex.lock, we don't choose to add lock in `maybeReadyToRun`, but let `RandWorkerID` do in `assign`. It protected by mutex, and will first check whether the node is assigned before, which can avoid to call `RandWorkerID` when it is nil.
- Unit test
```release-note
None
```

ticdc: Fix data race problem in Node

---

pkg/redo/config.go

Issue Number: close #10710
- return ErrStorageInitialize if the external storage initialization fails
- Use a smaller DefaultTimeout, since changefeed will be restart when meet error.
- Unit test
- No code
```release-note
`None`.
```

redo(ticdc): return ErrStorageInitialize if the external storage initialization fails

---

cdc/server/server_test.go

Issue Number: close #10783
increase the timeout threshold to make test stable.
- Unit test
```release-note
None
```

ticdc: make UT TestServerTLSWithCommonNameAndRotate more stable

---

Makefile
docs/swagger/docs.go
docs/swagger/swagger.json
docs/swagger/swagger.yaml

Issue Number: close #10790
QA team will use the swagger.json to check the open API's compatibility, this  PR add swagger gen to generate swagger.json file
- Unit test
- No code
```release-note
`None`.
```

api(ticdc):  add swagger gen back

---

cdc/entry/mounter.go
cdc/entry/mounter_test.go
cdc/entry/schema_test.go

Issue Number: close #10803
* convert the datum to the specific column type
- Unit test
```release-note
`None`
```

mounter(ticdc): default value convert to the correct data type

---

OWNERS_ALIASES
cdc/api/v2/OWNERS

Signed-off-by: wuhuizuo <wuhuizuo@126.com>
Issue Number: close #10819
- No code
```release-note
None
```

chore(ticdc): add OWNERS file in cdc api folder

---

cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
pkg/sink/cloudstorage/path.go
pkg/sink/cloudstorage/path_test.go

Issue Number: close #10815 
Currently, the **date part** in storage file path is formatted using local timezone. 
And in the test `TestRemoveExpiredFilesWithoutPartition`, the `checkpointTS` is generated using UTC timezone. But when removing expired files in `RemoveExpiredFiles`, the **date str** is formatted using local timezone. This will make the test fail in some specific timezone.
- Unit test
```release-note
None.
```

ticdc: fix unstable test TestRemoveExpiredFilesWithoutPartition

---

Makefile
cdc/http.go

Issue Number: ref #10773
- After #10765, sed is compatiable with both OSX and Linux. And gsed is not supported in makefile, so just remove it. 
- Fix `/config` api and return the correct server config.
- Unit test
- No code
```release-note
```

makefile, api(ticdc): remove gsed and fix config api

---

pkg/etcd/client_test.go

Issue Number: close #10771
In test TestRetry, we try to change `maxTries` to reduce test time, which makes this test is not thread safe.
So it can't run parallel with other tests like `TestDeleteCaptureInfo`, which will also use maxTries.
Thus we delete `t.Parallel()` here to make the test run successfully with an acceptable test time.
- Unit test
```release-note
None
```

ticdc: Fix unstable test TestRetry

---

cdc/owner/changefeed_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/10785
This ut want to exam that in a changefeed with redo, when we remove changefeed, there will only left one delete mark file in redo dir.
Here are two places will influence the delete mark file. One is after removing changefeed. We will do cleanup, and delete all logs and create delete mark file. The other is in `preCleanupExtStorage()`, which is called in `Run()`. 
`Run()` is called in `tick()`, but is a background goroutine. Therefore, sometimes, `preCleanupExtStorage()` is actually called after  we create delete mark file, make the test failed.
Thus, we add sleep, try to make `preCleanupExtStorage()` called before we remove the changefeed.
- Unit test
```release-note
None
```

ticdc: make UT TestRemoveChangefeed more stable

---

pkg/txnutil/gc/gc_manager.go
pkg/txnutil/gc/gc_manager_test.go

Issue Number: close #10688
fix data race
- Unit test
- No code
```release-note
`None`.
```

gc(ticdc):  fix data race in gc manager

---

metrics/alertmanager/ticdc.rules.yml
metrics/grafana/ticdc.json

Issue Number: close https://github.com/pingcap/tiflow/issues/10796
In the issue, because the duration of owner's tick is larger than 30s, makes the rate calculation to be 0 instead of 1.
To avoid this situation, I enlarge the duration in metrics to 240s, which we can regard it's must be longer than owner's tick. Otherwise, ticdc must be under a terrible performance. Thus, in this way, we can make the metrics more stable.
test in the issue case
```release-note
None
```

ticdc: fix metrics `ownership histroy` to be more stable

---

pkg/config/server_config.go
tests/integration_tests/cli_tls_with_auth/run.sh

Issue Number: close #10544
1. enable client auth
2. fix cli_tls_with_auth for pulsar
- Unit test
- No code
```release-note
`Support client authentication by mutual tls and tidb credentials`.
```

test(ticdc): enable client auth feature and fix cli_tls_with_auth for pulsar

---

cdc/scheduler/internal/v3/replication/replication_set.go
cdc/scheduler/internal/v3/replication/replication_set_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/10856
Initialize ReplicationSet stats with checkpointTs. Only when a table into ReplicationSetStateReplicating state, then owner will update stats based on handleMessage. 
Thus, if we don't initialize stats at the beginning, before the table into ReplicationSetStateReplicating state, it can't join to calculation the minimal puller resolve ts.  It will lead some misleading when some table is stuck in incremental scan.
I add sleep for a while in incremental scan logic. Then I exam the minimal puller resolved ts before the table created and after the table created. We can see before the table created, the minimal puller resolved ts will stuck, and back to increase continuely after …

ticdc: correctly initialize replicationSet to make puller resolved ts calculation correctly

---

cdc/kv/metrics.go
cdc/kv/shared_client.go
metrics/grafana/ticdc.json

Issue Number: ref #10862
Add metrics to observe slow initialize region count
```release-note
None
```

ticdc: Add metrics to observe slow initialize region count

---

cdc/model/sink.go

Issue Number: close https://github.com/pingcap/tiflow/issues/10859
Determine whether it is necessary to add without validation in the `exchange partition`.
- Manual test 
test the case mentioned in issue, and check the result in downstream db.
```release-note
None
```

ticdc: fix ddl `exchange partition xxxx with validation` to deal with `with validation` correctly

---

pkg/version/check.go
pkg/version/check_test.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/10807
- Unit test
- No code
```release-note
```

pkg/version(ticdc): bump max version for release 7.5

---

cdc/kv/shared_stream.go
cdc/kv/sharedconn/conn_and_client.go
tests/integration_tests/kafka_big_txn_v2/run.sh

Issue Number: close #10799
* use errgroup context to control grpc stream, to make it can be canceld.
* do not set the grpc stream to nil after `CloseSend`
- Unit test
- No code
```release-note
`None`
```

kvclient(ticdc): close the grpc client after all goroutine exited to prevent data race and panic

---

cdc/kv/shared_client.go
cdc/puller/multiplexing_puller.go
scripts/generate-mock.sh

Issue Number: ref #10880 
Reduce the delay of the resolvedTs required to trigger the sending of resolve stale lock requests, adjusting from 20s to 4s. This can more actively request the upstream TiKV to advance the resolvedTs as soon as possible.
In the test environment, after using this PR, the changefeed CheckpointTs lag caused by the rolling restart of TiKV and TiDB is stable between 6-15s.
```release-note
None
```

kvClient (ticdc): resolve stale lock more aggressively to reduce resolvedTs lag

---

metrics/grafana/ticdc.json

Issue Number: ref #10862
Add incremental scan long time region count metrics.
- Unit test
- No code
```release-note
None
```

ticdc: Add incremental scan long time region count metrics

---

pkg/causality/conflict_detector.go
pkg/causality/internal/node.go
pkg/causality/internal/node_test.go
pkg/causality/internal/slots_test.go
pkg/causality/tests/integration_test.go

Issue Number: ref #10896
- No code
```release-note
None
```

sink(ticdc): Revert changes related to the conflict detector

---

cdc/processor/processor.go
cdc/processor/processor_test.go

Issue Number: close #10921
If a processor is not initialized and then call writerDebugInfo command, ticdc will panic because of tableManager is nil
this PR will check if the processor is initialized or not, if not initialized, then print a log, false add a ut case to cover it.
- Unit test
- No code
```release-note
`None`.
```

processor(ticdc): Fix processor panic issue

---

cdc/entry/mounter_test.go
cdc/entry/schema_storage_test.go
cdc/entry/schema_test.go
cdc/puller/ddl_puller_test.go
cdc/sink/dmlsink/mq/transformer/columnselector/column_selector_test.go
pkg/sink/codec/debezium/debezium_test.go
pkg/spanz/span.go
pkg/version/check.go

Issue Number: ref https://github.com/pingcap/tiflow/issues/10908
Remove pulling ddl change from DDLJobList and DDLJobAddIdxList, which is an too old version ddl implementations(in 5.x). 
- Unit test
```release-note
None
```

ddl(ticdc): Remove pulling ddl change from DDLJobList and DDLJobAddIdxList

---

cdc/processor/sourcemanager/sorter/factory/pebble.go
cdc/processor/sourcemanager/sorter/pebble/db.go
cdc/processor/sourcemanager/sorter/pebble/db_test.go
cdc/processor/sourcemanager/sorter/pebble/event_sorter_test.go

Issue Number: close #10933 
Custom some options for PebbleDB.
This PR specified an instance-shared table cache with a suitable size. So seek operations can cache some blocks instead of reading them from disk every time.
Idle CPU Usage (before):
Idle CPU Usage (after):
```release-note
None
```

cdc: reduce seek CPU usage on PebbleDB sorter

---

cdc/entry/mounter.go
cdc/entry/mounter_test.go

Issue Number: close #10931 
* Ensure to correctly set the default value for the timestamp. It's in UTC and needs to be changed to the timezone set by TiCDC.
- Unit test
```release-note
`None`
```

mounter(ticdc): timezone fill default value should also consider tz.

---

cdc/redo/reader/reader.go
pkg/cmd/redo/apply.go
pkg/util/memory.go

Issue Number: close #10900
1. Set memory limit for redo applier.
2. Enable pprof for redo applier to simplify troubleshooting.
- Unit test
- No code
```release-note
```

redo(ticdc): enable pprof and set memory limit for redo applier

---

pkg/sink/codec/avro/avro.go
pkg/sink/codec/avro/decoder_test.go

Issue Number: close #10774 
- Unit test
```release-note
`None`
```

codec(ticdc): add more logs to the avro encoding to help detect potential key encoding failed issure

---

cdc/processor/processor.go
cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/manager_test_helper.go
pkg/sink/mysql/config.go

Issue Number: close #11022 
Pass cloned `replicaConfig` instead of `lastInfo` to the `New` method of `sinkManager` to ensure the `sourceID` is set correctly.
```release-note
None
```

sink (ticdc): fix sourceID error

---

scripts/download-integration-test-binaries.sh
tests/integration_tests/sequence/run.sh

Issue Number: close #11015
- Unit test
- No code
```release-note
`None`.
```

test(ticdc): enable sequence test

---

cdc/sink/dmlsink/txn/mysql/dml.go
cdc/sink/dmlsink/txn/mysql/dml_test.go
cdc/sink/dmlsink/txn/mysql/mysql.go
cdc/sink/dmlsink/txn/mysql/mysql_test.go

Issue Number: close #10972 
run sysbench oltp_update_non_index and compare the performance.
Sink throughput increase from 22k to 34k.
Downstream tidb cpu usage decrease from 1600% to 1300%.
```release-note
None
```

sink(ticdc): only enable batch dml for more than one row

---

cdc/owner/feed_state_manager.go
cdc/owner/feed_state_manager_test.go

Issue Number: close #10998
When changefeed state has changed, reacquiring `changefeed-error-stuck-duration`. `feedStateManager` checks for new value about `changefeedErrorStuckDuration` every `feedStateManager.Tick` call so that it can sense the updated value.
- Unit test
1. start a CDC server
2. run script
```bash
bin/cdc cli changefeed create -c test --sink-uri "kafka://127.0.0.1:9092/test?topic=test&protocol=open-protocol&max-message-bytes=41943040&compressionType=ZLIB" --changefeed-id="test"
bin/cdc cli changefeed pause --changefeed-id="test"
bin/cdc cli changefeed update --changefeed-id="test" --config=changefeed.toml
bin/cdc cli changefeed resume --changefeed-id="test"
```
changefeed.toml
```toml
changefeed-error-stuck-duration = …
```

owner(ticdc): update changefeed configuration changefeed-error-stuck-duration correctly

---

cdc/redo/writer/memory/encoding_worker.go
cdc/redo/writer/memory/file_worker.go
cdc/redo/writer/memory/mem_log_writer_test.go

Issue Number: close #10124
- return internal error in redo writer
- Unit test
- No code
```release-note
`None`.
```

redo(ticdc): return internal error in redo writer

---

OWNERS_ALIASES
cmd/dm-ctl/OWNERS
cmd/dm-master/OWNERS
cmd/dm-syncer/OWNERS
cmd/dm-worker/OWNERS
dm/OWNERS
engine/OWNERS

Issue Number: close #11100 
Add prow OWNERS files to dm and engine code paths.
- No code
```release-note
None
```

ci: add prow OWNERS for dm and engine modules

---

cdc/sink/dmlsink/txn/event.go
cdc/sink/dmlsink/txn/event_test.go
pkg/causality/conflict_detector.go
pkg/causality/internal/main_test.go
pkg/causality/internal/node.go
pkg/causality/internal/node_test.go
pkg/causality/internal/slots.go
pkg/causality/internal/slots_test.go
pkg/causality/tests/integration_test.go
pkg/causality/tests/worker.go
pkg/causality/txn_cache.go
pkg/causality/txn_cache_test.go

Issue Number: close #10973
- Remove some [useless and redundant logic](https://github.com/pingcap/tiflow/pull/10954/files#diff-641e339f15eae87ec78b7587b36a9a3382d5146711891ca9fedb978795ef48fbL160-L166).
- Move `sortAndDedupHashes` to [`pkg/causality/internal/slots.go`](https://github.com/pingcap/tiflow/pull/10954/files#diff-b49550d6a0ca757c148ad5d5d447be44db187d60d460f7af731f7aec369b1542R55), since it is used to solve the false positive problem caused by hash conflicts in slots. 
- For `txnEvent` interface, rename `GenSortedDedupKeysHash` to `ConflictKeys` to ensure semantic consistency, because the implementers should not care about internal implementations of conflict_detector. 
- Unit test
- No code
```release-note …
```

pkg/causality(cdc): refactor and simplify conflict detector

---

cdc/entry/schema/snapshot.go

Issue Number:  close #11124 
ref #11109
1. Use [[ListSimpleTables](https://github.com/pingcap/tidb/blob/master/pkg/meta/meta.go?rgh-link-date=2024-05-15T10%3A54%3A07Z#L1026)]([pingcap/tidb@master/pkg/meta/meta.go#L1026](https://github.com/pingcap/tidb/blob/master/pkg/meta/meta.go?rgh-link-date=2024-05-15T10%3A54%3A07Z#L1026)) to retrieve TableNameInfo. This only includes the name and ID of a table, making it smaller than TableInfo.
2. Apply a filter to the retrieved TableNameInfos to locate the tables of interest.
3. Use [[GetTable](https://github.com/pingcap/tidb/blob/master/pkg/meta/meta.go?rgh-link-date=2024-05-15T10%3A54%3A07Z#L1219)]([pingcap/tidb@master/pkg/meta/meta.go#L1219](https://github.com/pingcap/tidb/blob/master/pkg/meta/meta.go?rgh-link-date=2024-05-15T10%3A54%3A07Z#L1219)) …

snapshot (ticdc): reduce list tables time consumption

---

cmd/kafka-consumer/main.go
pkg/sink/codec/simple/decoder.go
pkg/sink/codec/simple/message.go

Issue Number: close #11088
* set the table id when decode the handle key only event
* consumer panics if commit-ts less than the resolved ts
* update resolved ts after receive resolved ts event and ddl event.
```release-note
`None`
```

codec(ticdc): simple decoder set the table id on handle key only event and make consumer more strict on the ts order

---

cdc/redo/reader/reader.go
cdc/redo/reader/reader_test.go
pkg/applier/redo.go

Issue Number: close https://github.com/pingcap/tiflow/issues/11096
1. Fix the less function of logHeap to make dml event of redo log in the same txn sorted as delete/update/insert.
2. use startTs instead of commitTs in redo apply to distinguish different txns.
- Unit test
create mysql sink changefeed with redo log on
run gotpc workload
After 30m, pause changefeed and run redo apply
```release-note
None
```

(redo)ticdc: fix the event orderliness in redo log

---

cdc/sink/dmlsink/txn/mysql/mysql_test.go
pkg/sink/mysql/db_helper.go

Issue Number: close #11128
When the downstream is a mysql cluster behind a workload balancer on the cloud, the workload balancer may provide an access point using domain name;
When cdc access the downstream using the domain name, the connection will use database `information_schema` automatically. In this case, when query `select tidb_version()`, the downstream will report error for non-root user like: Access denied for user xxx to database 'information_schema'.
- Unit test
```release-note
None
```

*(cdc): accept access denied error when query tidb_version

---

pkg/errorutil/util.go
pkg/errorutil/util_test.go

Issue Number: close #11143 
- Unit test
1. create a changefeed;
2. run set global sql_require_primary_key=true; on downstream tidb cluster;
3. run create table t (a int, b varchar(200) not null unique key); on upstream tidb cluster;
4. check the changefeed state to see whether is reports a warning or error quickly;
```release-note
None
```

sink(ticdc): quick fail on create table error without primary key when downstream sql_require_primary_key is set

---

tests/integration_tests/api_v2/cases.go

Issue Number: ref #10781
1.  add integration test check after resign ticdc owner
- Unit test
```release-note
`None`.
```

test(ticdc):  Add more test cases 

---

cdc/model/schema_storage.go
cdc/model/schema_storage_test.go

Issue Number: close #11179 
- Unit test
```release-note
`None`
```

schema(ticdc): remove the useless indices offset field from the table info

---

pkg/filter/utils.go
pkg/filter/utils_test.go

Issue Number: ref #10457
- No code
```release-note
`None`.
```

filter(ticdc): Fix verify table rules 

---

cdc/model/sink.go
cdc/model/sink_test.go
cdc/sink/dmlsink/event_appender.go
cdc/sink/dmlsink/txn/event.go
cmd/kafka-consumer/main.go
cmd/pulsar-consumer/main.go
pkg/applier/redo.go
pkg/sink/codec/bootstraper.go
pkg/sink/codec/craft/model.go
pkg/sink/codec/maxwell/maxwell_message.go
pkg/sink/codec/open/open_protocol_message.go
pkg/sink/codec/simple/encoder_test.go

Issue Number: close #11194
* add one method `GetTableID() int64` to the `RowChangedEvent` struct
- Unit test
```release-note
`None`
```

model(ticdc): add one method to get the row changed event corresponding table id

---

cdc/sink/dmlsink/mq/dispatcher/partition/index_value_test.go
pkg/sink/codec/simple/encoder_test.go
pkg/sink/codec/simple/message.go

Issue Number: close #11236 
* set index id to distinguish each index
- Unit test
```release-note
`None`
```

codec(ticdc): simple decoder set column flag incorrectly since miss index id 

---

pkg/sink/mysql/db_helper.go

Issue Number: close #11213
remove error detection in `checkIsTiDB` to avoid unexcept error when the downstream is different mysql-class server
- Unit test
- No code
```release-note
None
```

mysql(ticdc): remove error filter when check isTiDB in backend init

---

cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer.go
pkg/sink/kafka/factory.go
pkg/sink/kafka/mock_factory.go
pkg/sink/kafka/sarama.go
pkg/sink/kafka/v2/factory.go
pkg/sink/kafka/v2/factory_test.go

Issue Number: close #11264 
* kafka producer accept the `common.Message` as argument
- Unit test
```release-note
`None`
```

kafka(ticdc): producer accept message struct as parameter to simplify the signature

---

cdc/model/kv.go
cdc/processor/processor.go
cdc/processor/sinkmanager/manager.go
cdc/processor/sinkmanager/manager_test.go
cdc/processor/sinkmanager/manager_test_helper.go
cdc/processor/sinkmanager/redo_log_worker.go
cdc/processor/sinkmanager/table_sink_worker.go
cdc/processor/sinkmanager/table_sink_wrapper.go
cdc/processor/sourcemanager/manager.go
cdc/processor/sourcemanager/puller/dummy_puller_wrapper.go
cdc/processor/sourcemanager/puller/multiplexing_puller_wrapper.go
cdc/processor/sourcemanager/puller/puller_wrapper.go
cdc/puller/ddl_puller.go
cdc/puller/multiplexing_puller.go
cdc/puller/multiplexing_puller_test.go
pkg/sink/sink_type.go

Issue Number: close #11219
After https://github.com/pingcap/tiflow/pull/11030, we introduce a mechanism to get the current timestamp `thresholdTS` from pd when changefeed starts, and split all update kv entries which `commitTS` is smaller than the `thresholdTS`. 
This mechanism has the following problem:
1. There are two cdc nodes `A` and `B`, and `B` start before `A`, that is `thresholdTSB` < `thresholdTSA`;
2. The sync task of table `t` is first on `A`;
3. Table `t` has an update event which `commitTS` is smaller than `thresholdTSA` and larger than `thresholdTSB`. So the update event is split to a delete event and an insert event on node `A`;
4. But the delete event and insert event cannot be send to the downstream in an atomic way. So if after the delete event is send to downstream and …

puller(ticdc): fix wrong update splitting behavior after table scheduling

---

cdc/owner/changefeed.go
cdc/owner/feed_state_manager.go

Issue Number: close #11277
changefeed will detect when handle warning errors if the checkpoint ts is stuck, if changefeed's checkpoint ts is not forward for 30 minutes, changefeed will be changed to the `fail` state.
when closing a changefeed,  the `checkpointTsAdvanced` time is reset to 0,  but the warning errors in warningCh is not cleaned up,  So when ticdc ticks the closed changefeed again and handle the old warning errors. the following condition is always true,   changefeed will be set to the `fail` state.
```
checkpointTsStuck := time.Since(m.checkpointTsAdvanced) > m.changefeedErrorStuckDuration
```
this PR will drain warningCh when closing changefeed
- Unit test
- No code
```release-note
`None`.
```

owner(cdc): drain warnings when closing changefeed

---

cdc/processor/sourcemanager/sorter/pebble/event_sorter.go

Issue Number: close #11278 
Fix a bug that Pebble sorter can be stucked when closing a processor.
- No code
```release-note
None
```

sorter(cdc): fix a bug that Pebble sorter can be stucked when closing a processor

---

cdc/puller/multiplexing_puller.go
cdc/scheduler/internal/v3/agent/table.go
cdc/scheduler/internal/v3/transport/transport.go
pkg/cmd/server/server_test.go
pkg/config/config_test_data.go
pkg/config/messages.go

Issue Number: close #11215
Increase the p2p configuration to [cache more messages](
https://github.com/pingcap/tiflow/pull/11182/files#diff-358c265c3f948b652ae6b967663c7f4a6e72b613151fa38f51f6e180bbc2820eR52-R57)
- Unit test
Deploy ticdc cluster(7 nodes, 8c16g, replicating 150k tables, 1 changefeed) with the following configuration:
```toml
[debug.scheduler]
add-table-batch-size = 1000
```
1. Before this pr: 
The scheduling task took up to 3 hours to complete:
2. This pr:
The dispatch task was completed in 10 minutes:
No
No
```release-note
`None`.
```

pkg/p2p(ticdc): fix default p2p config

---

pkg/redo/config.go

Issue Number: close #11311
do not report unretryable error when initializing s3 storage, because this kind of error is retryale,  return ErrStorageInitialize if the external storage initialization fails.
```release-note
`None`.
```

s3(ticdc): do not report unretryable error when initializing s3 storage

---

cdc/model/sink.go
cdc/redo/reader/reader.go
cdc/redo/reader/reader_test.go

Issue Number: close #11096
Considering the row info in 6.5 is not the same as 8.1, to support the comparation, we need to support related isUpdate/isDelete/isInsert
- Unit test
create mysql sink changefeed with redo log on
run gotpc workload
After 30m, pause changefeed and run redo apply
```release-note
`None`.
```

redo(ticdc): fix orderliness of redo

---

cdc/sinkv2/eventsink/txn/worker.go

This reverts commit 053cdaf4a6853e8c9fd4bff1deeb686d1fdb2654.
Issue Number: close #11323 
Revert #11287.
When applying events from Redo logs, events are not attached with `TableID`. Now we can revert this PR to avoid the problem. 
- No code
```release-note
None
```

Revert "cdc: log slow conflict detect every 60s (#11251) (#11287)"

---

metrics/grafana/ticdc.json
pkg/sink/codec/common/compress.go
pkg/sink/kafka/metrics_collector.go

Issue Number: close #11314
follow the kafka producer compression ratio definition: https://pkg.go.dev/github.com/IBM/sarama#section-readme
```
compression ratio = Size of original data / Size of compressed data * 100
```
- Unit test
- No code
```release-note
`None`.
```

metrics(ticdc): Fix kafka compress ratio issue

---

pkg/sink/codec/open/open_protocol_encoder_test.go
pkg/sink/codec/open/open_protocol_message.go

Issue Number: close #11012
add ut case for open protocol to cover case when `output-old-value` is disabled and `delete-only-output-handle-key-columns` is enabled
- Unit test
- No code
```release-note
`None`.
```

sink(ticdc): add ut case for open protocol

---

cdc/sink/ddlsink/factory/factory.go
cdc/sink/ddlsink/mq/pulsar_ddl_sink_test.go
cdc/sink/dmlsink/factory/factory.go
cdc/sink/dmlsink/mq/dmlproducer/pulsar_dml_producer_test.go
pkg/config/sink.go
pkg/sink/pulsar/config.go
pkg/sink/pulsar/config_test.go
pkg/sink/sink_type.go

Added support for HTTP and HTTPS schema for pulsar downstream. Currently, only pulsar and pulsar+ssl support is there.
Issue Number: close #11336 
-> In addition to pulsar and pulsar+ssl schema types in pulsar changefeed creation , users will now will able to create changefeeds with HTTP and HTTPS  type as broker schema for pulsar client.   
Clients have to use: 
1. pulsar+http -> for creating pulsar changefeed with HTTP endpoint
2. pulsar+https -> for creating pulsar chnagefeed with HTTPS endpoint.
1. Unit test
2. Feature test by deploying the image on  k8s environment and creating multiple changefeeds.
-> It should not cause any performance regression or break compatibility. It only addition schema addition for pulsar client creation.
Documentation for pulsar sink should be update: …

ticdc : http & https support in pulsar schema for pulsar downstream type changefeed creation.

---

cmd/kafka-consumer/writer.go

Issue Number: close #11386 
- Unit test
```release-note
`None`
```

consumer(ticdc): do not panic the consumer if read previous offset message

---

cdc/entry/mounter.go
tests/integration_tests/kafka_simple_basic/data/data.sql
tests/integration_tests/kafka_simple_basic/run.sh
tests/integration_tests/kafka_simple_basic_avro/data/data.sql

Issue Number: close #11383
* add more DDL and DML changes in the integration test
- Unit test
```release-note
`None`
```

test(ticdc): add more integration test dml to cover checksum

---

Makefile

Issue Number: close #11345 
keep same with tidb and pd components.
master branche:
- v8.3.0-master-dirty => v8.3.0-alpha-1-ga2e621937-dirty
- v8.3.0-master => v8.3.0-alpha-1-ga2e621937
release branches:
- v8.2.0-alpha-90-ga2e621937 // first version of the branch will not be changed.
- v8.1.0-90-ga2e621937 // new LTS patch versions also will not be changed.
- v8.2.0 // when it taged in RC and GA building.
- Unit test
- No code
```release-note
None
```

build: simply the release version composing step

---

cdc/model/sink.go
cdc/model/sink_test.go

Issue Number: close #11402
* set the checksum field to 0 after split the update event
- Unit test
```release-note
fix the checksum field not set to 0 after split update event
```

sink(ticdc): split update event also set the checksum field to 0

---

go.mod
go.sum

Issue Number: close #11408
to include https://github.com/pingcap/tidb/pull/54761
- No code
```release-note
Fix DM fails to replicate DDL of LIST partitioning tables.
```

dep(*): update tidb to include DM SchemaTracker fix

---

cmd/kafka-consumer/writer.go

Issue Number: close #11413 
- Unit test
```release-note
`None`
```

consumer(ticdc): partition resolved ts fallback ignore caused by read offset message

---

dm/pkg/schema/tracker.go
dm/pkg/schema/tracker_test.go

Issue Number: close #11459
DM schema tracker uses the default tidb max-index-length config (3072), regardless of the config value of the downstream tidb. If the downstream tidb configures a larger value, then ddls that execute successfully against the downstream TiDB could fail in the schema tracker.
While DM's schema tracker makes an effort to suppress these kinds of errors, it only applies to single column, non-unique indexes.
This change updates the config of DM schema tracker to use the maximum max-index-length, or 3072*4 (12288). Ideally, DM would use the config of the downstream TiDB directly. However, we already are less strict w/ queries against DM schema tracker (running queries in non-strict, suppressing errors), and can extend the max length to maximum allowable. This way, we …

schematracker(dm): Increase max-index-length config for dm schema tracker

---

cdc/api/v2/model.go
pkg/config/config_test_data.go
pkg/config/large_message.go
pkg/config/large_message_test.go
pkg/sink/codec/canal/canal_json_decoder.go
pkg/sink/codec/canal/canal_json_row_event_encoder.go
pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
pkg/sink/codec/open/open_protocol_encoder.go
pkg/sink/codec/simple/decoder.go
pkg/sink/codec/simple/encoder.go
pkg/sink/codec/simple/encoder_test.go
pkg/sink/kafka/claimcheck/claim_check.go
pkg/sink/kafka/claimcheck/claim_check_test.go

Issue Number: close #11396
* introduce new configuration `claim-check-raw-value` to the large message handle claim-check functionality
- Unit test
```release-note
kafka sink claim check functionality support send value as object to external storage
```

kafka(ticdc): claim check support large message raw value format

---

cdc/entry/mounter.go

Issue Number: close #11468
* if verification on the old value checksum v1 failed, just skip it, print some logs to warn it.
- Unit test
```release-note
`None`
```

mounter(ticdc): do not report error is verify old value checksum v1 failed

---

metrics/alertmanager/ticdc.rules.yml

Issue Number: close https://github.com/pingcap/tiflow/issues/10796
Fix alter calculation for cdc_multiple_owners and cdc_no_owners
- Unit test
- No code
```release-note
`None`.
```

alter(ticdc): fix alter calculation for cdc_multiple_owners and cdc_no_owners

---

cdc/sink/dmlsink/mq/dispatcher/topic/expression.go
cdc/sink/dmlsink/mq/dispatcher/topic/expression_test.go
errors.toml
pkg/errors/cdc_errors.go

Issue Number: close #11160
return invalid topic expression in ErrKafkaInvalidTopicExpression to facilitate troubleshooting.
- Unit test
- No code
```release-note
```

sink(ticdc): return invalid topic expression in ErrKafkaInvalidTopicExpression

---

cdc/sink/ddlsink/mysql/async_ddl_test.go
cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
cdc/sink/ddlsink/mysql/mysql_ddl_sink_test.go
cdc/sink/dmlsink/txn/mysql/mysql.go
cdc/sink/dmlsink/txn/mysql/mysql_test.go
cdc/sink/dmlsink/txn/txn_dml_sink.go
errors.toml
pkg/applier/redo_test.go
pkg/errors/cdc_errors.go
pkg/sink/mysql/db_helper.go
pkg/sink/mysql/factory.go
pkg/sink/observer/observer.go

Issue Number: close #11490
**Overview:**
This PR addresses the challenges associated with creating multiple database connections during the establishment of downstream connections using a Sink URI, particularly in the context of unit testing. The changes introduce a flexible interface and supporting implementations that allow for distinct handling of temporary and standard connections, simplifying the testing process.
**Key Changes:**
1. **Introduction of `IDBConnectionFactory` Interface:**
- Defined an interface `IDBConnectionFactory` with two methods:
- `CreateTemporaryConnection`: For creating a temporary connection to the downstream database.
- `CreateStandardConnection`: For creating the standard connection used in normal operations.
- This separation of concerns allows different …

mysql sink(ticdc): Refactor DB Connection Creation to Facilitate Unit Testing

---

dm/pkg/parser/common.go
dm/pkg/parser/common_test.go

Issue Number: close #11503
> If the database name is omitted, the statement applies to the default database. In that case, an error occurs if there is no default database.
https://dev.mysql.com/doc/refman/8.4/en/alter-database.html
- Unit test
- Manual test
```release-note
DM sync unit support ALTER DATABASE default database SQL
```

parser(dm): support ALTER DATABASE default database

---

tests/integration_tests/README.md

Issue Number: close #11508 
This PR updates the official documentation regarding integration tests for TiCDC to address a potential issue with version mismatches between TiCDC and related TiDB ecosystem components such as TiDB, TiKV, and PD.
Previously, the documentation recommended running:
```bash
make prepare_test_binaries community=true
```
to download TiCDC-related binaries for integration testing. This command triggers the `scripts/download-integration-test-binaries.sh` script, which, if no version is specified, defaults to downloading version 8.1.0 of TiDB, TiKV, and PD. However, when TiCDC releases new versions, the script is not always updated promptly. As a result, TiCDC may end up running tests with outdated TiDB components, leading to potential incompatibility issues.
This PR …

docs(ticdc): Update Integration Test Documentation to Avoid Version Mismatch Issues in TiCDC

---

cdc/processor/sourcemanager/engine/pebble/event_sorter.go

Issue Number: close https://github.com/pingcap/tiflow/issues/6367
Issue Number: close https://github.com/pingcap/tiflow/issues/10853
This PR is extracted from #10899 , which fixes the bug that value can be corrupted when accessing sorter.
It's hard to construct a test case for the change because the value corruption can't be reproduced stable. So we just ignore it.
- No code
```release-note
None
```

sorter: fix the bug that value can be corrupted when accessing sorter

---

cdc/owner/barrier.go
cdc/owner/changefeed.go

Issue Number: close #11553 
* use `MinTableBarrierTs` as the checkpoint barrier.
- Unit test
```release-note
`None`.
```

changefeed(ticdc): fix barrier ts set incorrectly cause monitor become year

---

cdc/scheduler/internal/v3/agent/agent.go
cdc/scheduler/internal/v3/replication/replication_manager.go
metrics/grafana/ticdc.json
pkg/config/db.go
pkg/config/debug.go
pkg/config/kvclient.go
pkg/config/server_config.go

Issue Number: close #11574 
* CPU usage should be remove when the db actor removed
* `Read duration - Release` and `Read OPS - Release` are not tracked.
- Unit test
```release-note
`None`
```

metrics(ticdc): fix some missing db sorter related metrics

---

cdc/processor/sourcemanager/sorter/pebble/event_sorter.go

Issue Number: close #11576 
Correct a metric.
- No code
```release-note
None
```

sorter: correct wrong metric about next duration

---

cdc/owner/changefeed.go
cdc/owner/changefeed_test.go
cdc/owner/ddl_manager.go
cdc/owner/ddl_manager_test.go

Issue Number: close #11565 
* when the changefeed start, send bootstrap messages in a separate goroutine.
* before the ddl manager report all bootstrap message delievered, the changefeed cannot deliever any event, skip send ddl event and scheduling tables
* if send bootstrap messages failed, report error to the changefeed
- Unit test
```release-note
`None`
```

changefeed(ticdc): send bootstrap message asynchronously to prevent block other changefeeds

---

cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
cdc/sink/dmlsink/txn/mysql/mysql.go
cdc/syncpointstore/mysql_syncpoint_store.go
pkg/sink/mysql/db_helper.go
pkg/sink/observer/observer.go

Issue Number: close #11505
**Description**:
This PR refactors the `CheckIsTiDB` function in response to internal discussions. Previously, the function returned an `error` which was not necessary, as the external callers should not care about the error of the `CheckIsTiDB` function due to https://github.com/pingcap/tiflow/issues/11213.
**Changes**:
1. Removed the `error` return type from `CheckIsTiDB`.
2. Replaced the error log with a warning to handle cases where querying the TiDB version fails.
3. Updated comments to explain the background and rationale for the change.
- Unit test
No
No
```release-note
None
```

mysql(ticdc): remove returned error and modify the log in `CheckIsTiDB `

---

cdc/entry/mounter.go

Issue Number: close #11524
* ignore the checksum if not v1 (version != 0)
- Unit test
```release-note
None
```

mounter(ticdc): ignore checksum v2

---

tests/integration_tests/kafka_simple_basic/data/data.sql
tests/integration_tests/kafka_simple_basic_avro/data/data.sql

Issue Number: close #11583 
remove rows before `add column xxx default now();`
```release-note
`None`.
```

test(ticdc): fix data inconsistence on integration_tests

---

cdc/puller/ddl_puller.go
errors.toml
pkg/errors/cdc_errors.go

Issue Number: close #11507
**Description:**
This PR addresses an issue in TiCDC where a mismatch between the number of queries in `Job.Query` and the number of `TableInfo` entries in `Job.BinlogInfo.MultipleTableInfos` leads to an `index out of range` panic. This issue originates from TiDB's fast create table functionality, which previously merged multiple DDL jobs into a single batch but failed to correctly merge their corresponding queries. As a result, the length of `Job.Query` did not match the number of tables in `Job.BinlogInfo.MultipleTableInfos`, causing TiCDC to panic during DDL job processing.
This issue has been fixed in TiDB (see issue [tidb#53076](https://github.com/pingcap/tidb/issues/53076) and PR [tidb#53515](https://github.com/pingcap/tidb/pull/53515)). However, since …

ddl(ticdc): Add error handling for mismatched `Job.Query` and `Job.BinlogInfo.MultipleTableInfos` in TiCDC

---

cdc/entry/schema/snapshot.go
cdc/entry/schema_storage.go
cdc/entry/schema_test.go
cdc/entry/schema_test_helper.go
cdc/owner/ddl_manager_test.go
cdc/puller/ddl_puller.go
cdc/puller/ddl_puller_test.go

Issue Number: ref #https://github.com/pingcap/tidb/issues/53930
in TiDB https://github.com/pingcap/tidb/pull/55946, we have changed how job args are encoded/decoded for renametable, cdc should adapt to it.
- No code
```release-note
```

cdc: use typed args for renametables and adapt args v2

---

cdc/kv/region_state.go
cdc/kv/shared_client.go
cdc/kv/shared_region_worker.go
cdc/kv/shared_stream.go
cdc/processor/processor.go
cdc/processor/tablepb/table.go

Issue Number: close #11621 
* add table id to kv client logs, so we can know the region corresponding table
- Unit test
```release-note
`None`.
```

kvclient(ticdc): add table id to kv client logs

---

scripts/download-integration-test-binaries.sh

Issue Number: close #11631
**Description:**
This PR addresses the reoccurrence of the `tar` extraction issue in `scripts/download-integration-test-binaries.sh` following a refactor, where the `--wildcards` option was omitted. This option is necessary for wildcard pattern matching in certain versions of `tar` to correctly extract the required binaries for PD.
In a previous issue:#11512 and pr:#11513, a similar problem was identified and resolved by adding the `--wildcards` option to the `tar` command. However, during the refactoring of the script, this option was unintentionally removed, causing the issue to resurface.
The current command:
https://github.com/pingcap/tiflow/blob/4e177d94ca41d5f49a44c5545adfca1c72820f87/scripts/download-integration-test-binaries.sh#L156 …

integration test(ticdc): Reintroduce `--wildcards` Option in tar Command for download-integration-test-binaries.sh

---

cdc/api/v2/changefeed.go
tests/integration_tests/changefeed_error/run.sh

Issue Number: close https://github.com/pingcap/tiflow/issues/11642
Make the previous error message not return when changefeed state is stopped / finished / removed, to avoid confused.
- Unit test
- No code
```release-note
None
```

api(ticdc): Not show the error info during query the changefeed when state is stopped, finished and removed

---

dm/tests/import_v10x/run.sh

Issue Number: close #11680
This PR fixes the import_v10x test case in DM’s CI, which has been failing due to recent changes in TiDB. TiDB modified how the default int type is displayed when using the SHOW CREATE TABLE statement, causing the test to break. ref: https://github.com/pingcap/tidb/pull/56529
I have updated the import_v10x test to accommodate the changes made in TiDB’s handling of int types in SHOW CREATE TABLE. This ensures compatibility with the latest version of TiDB and prevents the test from failing in future CI runs.
- Unit test
No.
No.
```release-note
None
```

ci(dm): Fix DM `import_v10x` Test Failure Due to TiDB int Type Display Change

---

dm/worker/join.go

ref https://github.com/pingcap/tiup/pull/2464#discussion_r1818605891
Issue Number: close https://github.com/pingcap/tiflow/issues/4287
- add retry for dm-worker to join dm-master
```
./tiup-playground nightly --dm-master 1 --dm-worker 1 --dm-worker.binpath /home/gmhdbjd/code/tiflow/bin/dm-worker --without-monitor --db 0 --kv 0 --pd 0 --tiflash 0
Start dm-master instance: v8.4.0-alpha-nightly
Start dm-worker instance: /home/gmhdbjd/code/tiflow/bin/dm-worker
```
```release-note
```

dm: add retry for dm-worker to join dm-master

---

cmd/kafka-consumer/writer.go

Issue Number: close #11482 
Add partition check and old message check about simple protocol
- Unit test
```release-note
None
```

kafka(ticdc): fix kafka consumer doesn't check partition and old message

---

cdc/redo/writer/memory/encoding_worker.go
cdc/redo/writer/memory/mem_log_writer_test.go
pkg/redo/config.go
pkg/sink/kafka/claimcheck/claim_check.go
pkg/util/external_storage.go

Issue Number: close #11744
This issue is introduced in [#11011](https://github.com/pingcap/tiflow/pull/11011/files#diff-8b2ddec5af3b57f214bfdb001433260df573dacedd7bb28e16ca9e5fe80a72e0R134). If redo encoding worker closed since `context canceld`(ref the [fix](https://github.com/pingcap/tiflow/pull/11747/files#diff-8b2ddec5af3b57f214bfdb001433260df573dacedd7bb28e16ca9e5fe80a72e0R134)), the external module is not aware of the internal error anyway. Then the checkpoinTs/resolvedTs may continue to advance normally even if the redo writer has been closed. 
- Unit test
```release-note
`Fix a bug where the redo module could not report errors correctly`.
```

ticdc(redo, sink): return correct error in redo writer & fix default retryer

---

cdc/api/v2/api.go
tests/integration_tests/availability/owner.sh

Issue Number: close #11769
/api/v2/owner/resign forward to owner node
- Unit test
- No code
```release-note
`None`.
```

fix resign owner api not processed by owner node bug

---

dm/syncer/dbconn/db.go

Issue Number: close #11489
Redact query arguments in dm log when there is retryable error happen in dm syncer.
Have searched for arguments in dm source code to find if there are any missing part for redacting, this one seems like the last missing piece.
- Unit test
- No code
```release-note
```
None

Redact query arguments in dm log

---

dm/pkg/dumpling/utils.go
dm/pkg/dumpling/utils_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/11735
Handle the new format of binlog metadata from mariadb to read the binlog position.
Not.
Not.
```release-note
None
```

dm: handle the query in metadata from binlog

---

pkg/sink/codec/encoder_group.go
scripts/download-integration-test-binaries.sh

Issue Number: close #11773
As title. The maximum value is CPU count * 10
- Unit test
```release-note
`None`.
```

sink(ticdc): limit encoder-concurrency to avoid crash

---

cdc/owner/ddl_manager.go
cdc/puller/ddl_puller.go
cdc/puller/ddl_puller_test.go

Issue Number: close #11765
- Unit test
```release-note
Fix a bug that may cause error when encounter a  truncate table DDL of a ineligible table.
```

puller: fix a bug that may cause error when replicate truncate table ddl

---

cdc/entry/schema/snapshot.go

Issue Number: close #11827 
* use rwlock to control `DumpToString` method
- Unit test
```release-note
`None`
```

snapshot(ticdc): fix the data race when log set to debug caused by print logs

---

cmd/kafka-consumer/consumer.go
cmd/kafka-consumer/event_group.go
cmd/kafka-consumer/main.go

Issue Number: close #11818 
Delete event sorting and add debug logs
- Unit test
```release-note
`None`.
```

consumer(ticdc): modify kafka consumer

---

cdc/entry/schema_test_helper.go
cdc/model/sink.go
pkg/sink/codec/avro/avro_test.go
pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
pkg/sink/codec/open/open_protocol_encoder_test.go
pkg/sink/codec/simple/avro.go
pkg/sink/codec/simple/encoder_test.go
pkg/sink/codec/simple/message.go

Issue Number: close #11846 
* when the simple protocol encode row events, set the table id by using the physical table id, instead of the logic id.
https://github.com/pingcap/tiflow/pull/11845/files#diff-7503164863112a4d454976ac5347d75a046c600a1ab3d5914a741eec262bba79R255
https://github.com/pingcap/tiflow/pull/11845/files#diff-ab57979355b5c3e268e38318362ab236cb5c8a3a27662d4aa79eeadb865da617R557
* add more unit test to cover that `open-protocol` table id is is set correctly.
* add unit test to cover that `canal-json` does not set the table id.
- Unit test
```release-note
fix the row message table id not set by the physical table id cause the consumer don't known the table partition the row belongs to.
```

codec(ticdc): simple protocol set table id by using the physical table id

---

dm/ctl/master/start_task.go
dm/tests/tls/conf/dm-task-3.yaml
dm/tests/tls/run.sh

When task configuration contains both shard-mode and TLS configuration, start task fails
Issue Number: close #11842
The content of the task configuration file is replaced with the TLS context populated when TLS configuration exists. The changed configuration file content generates false positives in the pre-checking logic. Reordering the pre-checking and loading of the TLS context can make it work in such cases.
```release-note
None
```

dm: fix start task check when both shard-mode and TLS are configured

---

cdc/entry/schema/snapshot.go
cdc/entry/schema_storage.go

Issue Number: close #11884
This PR fixes a deadlock issue in the `Snapshot` implementation:
**Deadlock in Recursive Read Locking:** Although Go’s `sync.RWMutex` allows recursive read locks, they can result in deadlocks if a write lock is requested during the recursive read lock execution. This blocks the outer read lock from releasing, preventing the write lock from proceeding.
This PR refactors lock usage patterns to avoid recursive read locking.
---
Recursive calls involving `RWMutex.RLock()` can result in deadlocks when a write lock is requested during the recursive read lock execution. This behavior arises because Go’s `sync.RWMutex` prioritizes write locks over read locks.
Here is an example that illustrates the problem:
```go
func (s *Snapshot) Operation() {
s.rwlock.RLock()
defer …
```

snapshot(ticdc): fix ddl puller and ddl manager stuck caused by two dead lock

---

tests/integration_tests/region_merge/conf/pd_config.toml
tests/integration_tests/region_merge/run.sh

Issue Number: ref #11879 
Ensuring "region merge" is expected
```release-note
`None`.
```

test(ticdc): fix region_merge test case

---

cdc/redo/writer/memory/encoding_worker.go
cdc/redo/writer/memory/mem_log_writer_test.go

Issue Number: close #11852 
A select blocks until one of its cases can run, then it executes that case. It chooses one at random if multiple are ready.
In these cases, encodingWorkerGroup may run `WriteEvents` or `FlushLog` successfully even if encoding worker is closed. 
```go
select {
case <-ctx.Done():
return ctx.Err()
case err := <-e.closed:
return errors.WrapError(errors.ErrRedoWriterStopped, err, "encoding worker is closed")
case e.inputChs[idx] <- event: // executes even if encoding worker is closed
return nil
}
```
- Unit test
```release-note
`None`.
```

redo(ticdc): Fix RedoLogWriter unit test

---

cdc/entry/schema_storage.go
cdc/puller/ddl_puller.go
tests/integration_tests/ddl_with_exists/conf/diff_config.toml
tests/integration_tests/ddl_with_exists/run.sh
tests/integration_tests/ddl_with_exists/test.go
tests/integration_tests/run_group.sh

Issue Number: close #11839
- Unit test
- No code
```release-note
```

ddl(ticdc): ignore ddl with schemaversion 0

---

cdc/kv/client_mock_test.go
cdc/kv/shared_client.go
cdc/kv/shared_client_test.go
cdc/kv/shared_stream.go
pkg/version/check.go

Issue Number: close #11766 
Change the retry logic to reload region when `client.GetStore` failed.
- Unit test
```release-note
Fix the problem that changefeed may get stuck after scaling out new tikv nodes.
```

puller: fix retry logic when check store version failed

---

dm/tests/mariadb_master_down_and_up/docker-compose.yml
dm/tests/upstream_switch/docker-compose.yml

Issue Number: close #11811
ref https://github.com/pingcap/tidb/issues/58372
concurrent create or replace view will cause tidb report table not exist error in v7.5.1, this is fix in later version, update image version to fix the test
```release-note
```

dm: use nightly tidb instead of latest to fix table not exist error

---

pkg/filter/sql_event_filter.go
pkg/filter/sql_event_filter_test.go
tests/integration_tests/event_filter/conf/cf.toml
tests/integration_tests/event_filter/conf/diff_config.toml
tests/integration_tests/event_filter/data/test.sql
tests/integration_tests/event_filter/data/test_rename.sql
tests/integration_tests/event_filter/run.sh

Issue Number: close #11946
Event Filter wrongly uses the current table info with "rename" DDLs and It should use the previous table info to filter events.
- Unit test
```release-note
Fix incorrect event filter with "rename table" DDLs
```

filter(ticdc): fix incorrect event filter with "rename" DDLs

---

pkg/sink/codec/debezium/encoder.go

Issue Number: close #11876 
We use `EnableTiDBExtension` to control whether to encode watermark event. After that, it will be up to users to set.
- Unit test
```release-note
`None`.
```

sink(ticdc): add parameter to enable watermark events in the Debezium protocol

---

pkg/logutil/log.go
pkg/sink/kafka/sarama.go

Issue Number: close #11935 
* `config.Net.MaxOpenRequest` is set to 1 
* `config.Producer.Retry.Max` is set to 0, to disable the internal retry mechanism
- Unit test
This is tested by an internal E2E test, which inject network partition between the random cdc node and random kafka server. Before this PR, the test case cannot be passed, and we found out-of-order message by reading consumer log, after this PR it can be passed, and no out-of-order message.
```release-note
fix the sarama retry caused out-of-order message by set retry count to 0 as a workaround
```

kafka(ticdc): sarama do not retry if produce message failed to prevent out of order

---

cmd/pulsar-consumer/main.go
pkg/sink/codec/canal/canal_json_message.go

Issue Number: ref #11879
The delete event currently does not assign the "table id" and "partition". It leads to DMLs order being incorrect.
```release-note
`None`.
```

sink(ticdc): fix incorrect table info in delete event

---

pkg/etcd/client.go

Issue Number: close #11997 
Add AutoSyncInterval to etcd client which is accidentally removed by https://github.com/pingcap/tiflow/pull/9661
- Unit test
- No code
```release-note
None.
```

config AutoSyncInterval to etcd client

---

pkg/sink/codec/canal/canal_json_message.go
pkg/sink/codec/canal/canal_json_row_event_encoder.go
pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
pkg/sink/codec/canal/canal_json_txn_event_decoder.go
pkg/sink/codec/canal/canal_json_txn_event_decoder_test.go

This reverts commit 44a46bf23fe31995f120454b29de6feb839d1bc6.
Issue Number: close #11993 
- Unit test
```release-note
`None`
```

codec(ticdc): Revert "codec(ticdc): canal-json encode table id (#11875)"

---

pkg/sink/codec/avro/avro.go
tests/integration_tests/avro_basic/data/data.sql
tests/integration_tests/avro_basic/run.sh

Issue Number: close #11994
treat as a `nil` when the default value is the string literal "null" 
```release-note
Fix incorrect encoding default value in Avro protocol.
```

sink(ticdc): fix incorrect encoding default value in Avro protocol

---

pkg/cmd/cli/cli_changefeed_create.go
pkg/cmd/cli/cli_changefeed_update.go
pkg/cmd/util/helper.go

Issue Number: close #11979
Report a warning to the user if config sink.enable-partition-separator is set explicitly in the config file.
1. create a changefeed with sink.enable-partition-separator set in config file.
2. update the changefeed with sink.enable-partition-separator set in config file.
```release-note
`None`.
```

*: add warning to deprecate config sink.enable-partition-separator in the future

---

cdc/sink/codec/canal/canal_json_encoder.go
cdc/sink/codec/common/config.go

Issue Number: close #11707
- Unit test
```release-note
fix the canal-json dml message end by the terminator
```

codec(ticdc): canal-json message do not end by terminator if using kafka sink

---

cdc/api/v2/changefeed.go
cdc/api/v2/changefeed_test.go
tests/integration_tests/synced_status_with_redo/run.sh

Issue Number: close #12004
When the api request doesn't contain any pd address, we previously use the old pd address to create a new pd client.
If the old pd address are all scaled-in, the newly created pd client cannot connect to the upstream.
To fix this problem, in this case we should use pd client in the default upstream of the capture which can manage pd scale-in/scale-out internally.
- Unit test
1. Deploy a cluster with 3 pds;
2. Scale out 3 new pds;
3. Transfer pd leader;
4. Scale in 3 old pds;
5. Create changefeed;
```release-note
Fix create changefeed after scale in pds in some scenarios.
```

api(cdc): fix create changefeed after scale-in pd

---

cdc/entry/mounter_test.go
cdc/model/codec/codec.go
cdc/model/schema_storage.go
cdc/model/sink.go
pkg/sink/cloudstorage/table_definition.go
pkg/sink/codec/debezium/codec.go
pkg/sink/codec/debezium/helper.go
pkg/sink/codec/debezium/helper_test.go
pkg/sink/codec/simple/avro.go
pkg/sink/codec/simple/encoder_test.go
pkg/sink/codec/simple/message.go

Issue Number: close #12037
`OriginDefaultValue` is used as the column value when the default value is invisible. 
It should not be used as the `default` field.
**Affected protocol**
- Cloud Storage
- Simple
- Avro
- Debezium
- Unit test
```release-note
fix incorrect `default` field.
```

sink(ticdc): fix incorrect `default` field

---

cdc/api/v1/api.go
cdc/api/v1/api_test.go
cdc/api/v2/api_helpers.go
cdc/api/v2/changefeed.go
cdc/api/v2/changefeed_test.go
errors.toml
pkg/check/cluster.go
pkg/check/cluster_test.go
pkg/errors/cdc_errors.go

Issue Number: close #12062, #11767
This PR implements a mechanism to prevent TiCDC from using the same TiDB cluster as both upstream and downstream. The approach relies on retrieving the Cluster ID from `mysql.tidb` in TiDB and comparing it with the upstream Cluster ID obtained from PD.  
- Fetch the upstream Cluster ID from PD via gRPC.  
- Query the downstream Cluster ID from TiDB’s `mysql.tidb`.  
- Compare the Cluster IDs during changefeed creating, resuming and updating operation.  
- Reject changefeed operation if the upstream and downstream Cluster IDs match.  
- Add error handling and logging.  
1. Create a changefeed using cmd: `cdc cli changefeed create --server=http://127.0.0.1:8300 --sink-uri="mysql://root:@127.0.0.1:8300/" …

feat(ticdc): prevent using the same TiDB cluster as both upstream and downstream

---

pkg/sink/sink_type.go

MQ fields like DispatchRules not getting honor in pulsar+http protocol for pulsar changefeeds because pulsar+http and pulsar+https protocols were not added iin IsMQScheme function. It is bug fix for the same. The bug was introduced in below PR:https://github.com/pingcap/tiflow/pull/11338
Issue Number: ref #12068 
-> pulsar+http and pulsar+https protocols are added in IsMQScheme function so that MQ related fields will get picked up for these protocols
1. Unit test
2. Feature test by deploying the image on  k8s environment and creating multiple changefeeds.
-> It should not cause any performance regression or break compatibility. It only addition schema addition for pulsar client creation.
```release-note
Bug fix for  pulsar+http and pulsar+https schema  pulsar protocols to honor MQ fields. …
```

ticdc:bug fix - added pulsar+http and pulsar+https protocols in IsMQScheme to honor MQ fields in changefeed

---

cdc/kv/shared_stream.go

Issue Number: close https://github.com/pingcap/tiflow/issues/12081
Add cdc version in deregister request header.
The reason why this is needed is described in the issue.
- No code
```release-note
None.
```

puller: fix potential stuck

---

tests/integration_tests/multi_source/main.go

Issue Number: ref #11879
TiDB may set an incorrect auto_increment column when DDL/DML sqls execute concurrently.
related issue: https://github.com/pingcap/tidb/issues/55846
- Unit test
```release-note
`None`.
```

test(ticdc): fix duplicate entry about multi_source test

---

pkg/cmd/server/server.go

Issue Number: close #12101
This PR refactors and exports the TiCDC server `options` struct to be publicly accessible, which is needed in #12098.
- Unit test
No.
No.
```release-note
None
```

server(ticdc): export ticdc server options struct for public use in new architecture

---

pkg/cmd/server/server.go
pkg/cmd/server/server_test.go

Issue Number: close #12104
This PR capitalizes all fields in the Options struct to make them publicly accessible. Previously, the struct itself was made public, but its fields remained private, limiting its usability in the new TiCDC architecture.
- Unit test
No.
No.
```release-note
None
```

server(ticdc): make options struct fields public for ticdc new architecture

---

cdc/model/schema_storage.go
cdc/model/schema_storage_test.go
cdc/sink/dmlsink/mq/dispatcher/partition/columns.go
cdc/sink/dmlsink/mq/dispatcher/partition/columns_test.go
cdc/sink/dmlsink/mq/dispatcher/partition/index_value.go
cdc/sink/dmlsink/mq/dispatcher/partition/index_value_test.go
tests/integration_tests/mq_sink_dispatcher/conf/changefeed.toml
tests/integration_tests/mq_sink_dispatcher/conf/diff_config.toml
tests/integration_tests/mq_sink_dispatcher/conf/new_changefeed.toml
tests/integration_tests/mq_sink_dispatcher/run.sh

Issue Number: close #12103
According to [MySQL doc](https://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html), column and index names are not case-sensitive on any platform. 
Make cdc compatible with it.
- Unit test
```release-note
Treat column and index names as case-insensitive in dispatchers configuration.
```

sink(ticdc): Treat column and index names as case insensitive

---

cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
pkg/util/external_storage.go
pkg/util/external_storage_test.go

Issue Number: close #9162 
- Unit test
- Manual test
1. I created a container on Azure.
2. I modified the `WriteFile` function as follows to make it easier to throw a context timeout error.
```bash
func (s *extStorageWithTimeout) WriteFile(ctx context.Context, name string, data []byte) error {
timeout := s.timeout
if counter.Load()%10 == 0 {
// Make it more likely to timeout
timeout = 5 * time.Millisecond
}
ctx, cancel := context.WithTimeout(ctx, timeout)
counter.Add(1)
defer cancel()
return s.ExternalStorage.WriteFile(ctx, name, data)
}
```
3. I compiled the modified CDC and created a changefeed to synchronize data to Azure Blob Storage.
```bash
./cdc cli changefeed create -c test --sink-uri="azure://dongmen-test/cdc?protocol=canal-json&account-name=${}account-key=${}" 
```
4. I wrote …

cloudstorage: fix a bug that may cause storage sink get stuck

---

sync_diff_inspector/source/chunks_iter.go
sync_diff_inspector/source/source_test.go
sync_diff_inspector/splitter/limit.go
sync_diff_inspector/splitter/random.go
sync_diff_inspector/splitter/splitter_test.go

Issue Number: close https://github.com/pingcap/tiflow/issues/12141
There are two problems solved in this PR
The first is unexpected error(see https://github.com/pingcap/tiflow/issues/12141#issuecomment-2826624187). To fix this, some of the mock queries are replaced with failpoint to make tests more stable.
The second is data race problem(see https://github.com/pingcap/tiflow/issues/12141#issuecomment-2826666728). To fix this, `WaitGroup.Add` and `WaitGroup.Wait` operations are moved into one goroutine.
- Unit test
- Test should be more stable after this PR.
- No code
```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide. …
```

sync_diff_inspector: fix flaky test TestMysqlRouter

---

pkg/sink/codec/debezium/codec_test.go
tests/integration_tests/debezium/sql/ddl.sql

Issue Number: ref #11566
1. Fix the incorrect unit test about drop table.
2. Add a rename table case in the integration test.
- Unit test
```release-note
`None`.
```

codec(ticdc): fix test in debezium protocol

---

cdc/sink/ddlsink/mq/kafka_ddl_sink.go
cdc/sink/ddlsink/mq/mq_ddl_sink.go
cdc/sink/ddlsink/mq/mq_ddl_sink_test.go
cdc/sink/ddlsink/mq/pulsar_ddl_sink.go
cdc/sink/dmlsink/mq/kafka_dml_sink.go
cdc/sink/dmlsink/mq/manager/kafka_manager.go
cdc/sink/dmlsink/mq/manager/kafka_manager_test.go
cdc/sink/util/helper.go
cdc/sink/util/helper_test.go
pkg/sink/kafka/admin.go
pkg/sink/kafka/cluster_admin_client.go
pkg/sink/kafka/cluster_admin_client_mock_impl.go
pkg/sink/kafka/factory.go
pkg/sink/kafka/mock_factory.go
pkg/sink/kafka/options.go
pkg/sink/kafka/options_test.go
pkg/sink/kafka/sarama.go
pkg/sink/kafka/sarama_factory.go
pkg/sink/kafka/sarama_factory_test.go
pkg/sink/kafka/v2/admin.go
pkg/sink/kafka/v2/factory.go

Issue Number: close #12171
This PR addresses the issue of frequent broken pipe errors in CDC when connecting to Kafka. The user reported that multiple clusters frequently triggered CDC alerts (cdc changefeed meet error) with the error message `write tcp ...: write: broken pipe`, occurring on average once every dozens of minutes. Although CDC appeared to function normally — with business operations unaffected and checkpoint lag remaining within acceptable limits — the alerts persisted.
The reason is that CDC had recently removed retries in the Sarama Kafka client (used by CDC) — reducing the retry count from 3 to 0 in #11870. This change was originally made to avoid potential message reordering issues. However, disabling retries caused CDC to surface connection-related errors directly, …

sarama: add keep-alive mechanism for sarama connections

---

cdc/scheduler/internal/v3/keyspan/mock.go
cdc/scheduler/internal/v3/keyspan/splitter_region_count.go

Issue Number: close https://github.com/pingcap/tiflow/issues/12221
use `LoadRegionsInKeyRange` instead of `ListRegionIDsInKeyRange` to speed up the region scanning performance
- Unit test
We make a tidb cluster with nearly 5w regions(region size is 5MB)
After optimization, the time cost of scanning regions reduce to **450ms** from **10s**.
- No code
```release-note
```

scheduler: Speed ​​up region scanning before table splitting

---

cdc/model/schema_storage.go
cdc/sink/dmlsink/mq/dispatcher/partition/columns.go
cdc/sink/dmlsink/mq/dispatcher/partition/columns_test.go
cdc/sink/dmlsink/mq/dispatcher/partition/index_value.go
cdc/sink/dmlsink/mq/dispatcher/partition/index_value_test.go

Issue Number: close #12103
This pr https://github.com/pingcap/tiflow/pull/12132 makes the column and index names case-insensitive in dispatcher. But it also miscalculates the partition with the lowercase column name.
The `ColumnsDispatcher` and `IndexValueDispatcher` now correctly use the original column names for hashing, ensuring consistent and accurate data partitioning.
- Unit test
```release-note
`None`.
```

sink(ticdc): calculate partition by the orignal column name

---

pkg/util/external_storage.go
pkg/util/external_storage_test.go

Issue Number:  close https://github.com/pingcap/tiflow/issues/12277
Fixes TiCDC cloud storage sink flapping (start/stop spam) on Azure Blob caused by premature context cancellation during reads.
Symptoms included:
- “Failed to read data from azure blob, data info: pos='0', count='1': context canceled”
- “failed to generate data file path”
- “dead dmlSink”
The regression seems to be introduced by https://github.com/pingcap/tiflow/commit/0e6782b71. Switching to GetExternalStorageWithDefaultTimeout wrapped `Open` with a timeout and canceled it immediately, breaking subsequent Read() calls that reuse the Open() context.
Before: Open wrapped the passed context with `context.WithTimeout` and deferred `cancel()`. Since many backends bind the reader’s lifetime to the Open context, the deferred …

cloudstorage: fix a bug causing context cancelled errors and stuck sink

---

go.mod
go.sum
pkg/sink/codec/avro/avro.go
pkg/sink/codec/avro/avro_test.go
pkg/sink/codec/avro/confluent_schema_registry.go
pkg/sink/codec/avro/confluent_schema_registry_test.go
pkg/sink/codec/avro/glue_schema_registry.go
pkg/sink/codec/simple/marshaller.go

Issue Number: close #11994
The `goavro` treats string literal "null" as null in the past. This is a bug of `goavro` and is fixed in v2.14.0. https://github.com/linkedin/goavro/issues/280
This PR upgrades the `goavro` dependency and outputs the correct type.
**Before**
```json
{
"type": "record",
"name": "test",
"fields":
[
{
"type": [
"null",
"string"
],
"default": "null",
"name": "field"
}
]
}
```
**After**
```json
{
"type": "record",
"name": "test",
"fields":
[
{
"type": [
"string",
"null"
],
"default": "null",
"name": "field"
}
]
}
```
- Unit test
```release-note
According to the Avro documentation (1.11), when a default value is specified for a record field whose type is a union, the type of the default value must match the first element of the union. 
```

codec(ticdc): fix incorrect encoding default "null" in Avro protocol 
